### ISSUE TITLE
Improve clarity Travis CI reports

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#1088]
I am wondering if we can make our Travis CI build reports easier to digest for our users. Some ideas:
- one (complicated) option would be to parse the Travis CI reports somehow, and post more human-readable comments directly to the GitHub pull request, with instructions to the submitter on what's wrong and how to fix it. There are bots like http://documentup.com/arturadib/botio that could be used for this, and it looks like RSpec can output JSON that would be easier to parse (http://jing.io/t/programmatically-execute-rspec-and-capture-result.html), but obviously it would be quite some work to set up.
- a quick change would be to improve the error messages. I think it might help to change currently test descriptions like "independent style university-of-helsinki-faculty-of-theology has no unused macros" to "independent style university-of-helsinki-faculty-of-theology has unused macros" (see e.g. https://travis-ci.org/citation-style-language/styles/builds/34003431). @inukshuk, do you think this is acceptable, or is that totally against RSpec standards?

**Comment by rmzelle** [comment]
Just to keep track of other GitHub bots, Facebook also released one: https://github.com/facebook/mention-bot

**Comment by bwiernik** [comment]
@adam3smith How do you feel about our current feedback?

**Comment by adam3smith** [comment]
We're doing pretty well I think. I'd close this
