### ISSUE TITLE
Springer styles in different languages

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/styles#1122]
There are German journals published by Springer which are at the moment treated as English journals. Sometimes there is also a link to a localized (German) Endnote style. (Moreover, there are the multilingual journals, but let us ignore them for the moment...). Can we just change the header information and maybe insert the "(German)" in the label? Or how are depending styles working exactly?

For a concrete example we can take the journal <a href="https://github.com/citation-style-language/styles/blob/master/dependent/informatik-spektrum.csl">Informatik-Spektrum</a> which is published in German only: "Publikationssprache dieser Zeitschrift ist deutsch." see <a href="http://www.springer.com/computer/journal/287?detailsPage=pltci_570163">Autorenhinweise</a>. Thus, in the end we want to have the same as Springer Basic style but with e.g. (Münch u. Smelser 1992) and In: / (Hrsg) / Aufl. / S / Gesehen / Dissertation / et al.

**Comment by rmzelle** [comment]
(see also #1526)
