### ISSUE TITLE
[RFC] Releases and packaging

### ISSUE THREAD

**Issue by till** [citation-style-language/styles#1226]
Would you guys be up for tagging releases of this repository? :)

Also, in order to _distribute_ these styles, we could contribute packaging if you guys would want that. I was thinking about using something like [fpm](https://github.com/jordansissel/fpm) and maybe adding the tooling to your travis-ci integration so releases are distributed when a tag is created or _unstable_ when something is merged into master?

**Comment by fh** [comment]
@rmzelle You dont need to have/add any servers. All bits are already there - you create the package using travis, and if there is a new tag, travis uploads the package to github, where it can be found under "releases".

The documentation is available at http://docs.travis-ci.com/user/deployment/releases/ - the only two bits needed from the CSL maintainers is 
* an encrypted github token to upload the files (see documentation link above) and
* start tagging releases 

Everything else can be crafted by me, @till or anyone else.

**Comment by dstillman** [comment]
I'm still not clear on the point of this. I don't think anyone involved with CSL updates is going to manually tag releases, since individual CSL updates happen all the time. There's no such thing as a "release".

So all that leaves is having a ZIP file instead of a git checkout, but if that's going to be on GitHub or Amazon S3 anyway, that's still an external dependency that could intermittently fail, and if you're concerned about that you should just use a clone on your own servers like Zotero and Mendeley do. I don't see much value in adding time to the build process every time there's a change to build a ZIP file with thousands of files.

**Comment by rmzelle** [comment]
@till, @fh, you know there is https://github.com/citation-style-language/styles-distribution/archive/master.zip, right? (you can find the link at https://github.com/citation-style-language/styles-distribution )

**Comment by till** [comment]
@rmzelle yeah, but mirror'ing github is _harder_ than mirroring an APT repository. In general, I try to avoid external dependencies and since we are on Ubuntu we already have the infrastructure to mirror external APT repositories.

That's why I suggested this.

But anyway, we can also maintain this in a local fork if it's not interesting to anyone else.

**Comment by rmzelle** [comment]
So I think that the conclusion is that we'd be open to incorporate a light-weight workflow to automatically create a package for the contents of https://github.com/citation-style-language/styles-distribution (and presumably https://github.com/citation-style-language/locales/ as well) on a per-commit or daily schedule, assuming it doesn't significantly increase the time it takes for commits to the "styles" repo to be pushed to "styles-distribution".

But as @dstillman explains, it makes no sense for us to tag commits. Also, the zip file of the repo contents is about 7 Mb right now. We've had over 640 commits to https://github.com/citation-style-language/styles-distribution in less than a year, which already amounts to 4.5 Gb if we would have pushed every commit as a release. I can't imagine GitHub being very enthusiastic about such a storage requirement.

**Comment by dstillman** [comment]
> In general, I try to avoid external dependencies

Then just do a periodic ```git pull``` on your deployment server and treat that as a dumb file hierarchy. Then there's no external dependency at build time.

I can't think of any possible benefit to having this repo cloned as an APT repo (which seems to be what you're suggesting), but if you want that you should do that yourself.
