### ISSUE TITLE
SBL: volume wrongly included in non-first citations of journal articles

### ISSUE THREAD

**Issue by usethe4ce** [citation-style-language/styles#1333]
In SBL, when a journal article is cited after the first occurrence, the journal volume is inserted where it shouldn't be. For example:

<sup>1</sup> John Smith, "Stuff," *Journal of Stuff* 42 (2014): 1-20.
<sup>2</sup> James Jones, "More Stuff," *Journal of Stuff* 42 (2014): 21-30.
<sup>3</sup> Smith, "Stuff," 42.
<sup>4</sup> Jones, "More Stuff," 42:29-30.

Seems to have resulted from the change a few days ago.

**Comment by adam3smith** [comment]
yes, I'm aware of this, thanks. Hope to have a fix by the end of the weekend.

**Comment by adam3smith** [comment]
fixed in https://github.com/citation-style-language/styles/commit/1057cc62de03f7a769caa33e0ac187090d7e0524
