### ISSUE TITLE
Offer tool for style reindenting/escaping/reordering

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#1388]
We probably can make it easier for users to contribute properly formatted styles. Currently I manually run https://github.com/citation-style-language/utilities/blob/master/csl-reindenting-and-info-reordering.py every once in a while, but it would be preferable if styles are reformatted by the contributors before they enter the repository. It would be nice to have a website where users can paste in their style, and have it reindented, the `<info/>` section reordered, and some unicode characters escaped. It could help users select the right style ID and "self" link as well.

We might be able to do this entirely in JavaScript, but I'm not aware of any good XML parsing libraries, and it might not be straight-forward to exactly duplicate the pretty printing from Python's lxml library. Maybe it's easiest to run the existing Python script on a server. [OpenShift](https://www.openshift.com/) has a free tier that comes with Python support, so we might want to explore that.

If we can hook it up to our [CSL validator](http://validator.citationstyles.org/), we could also give users the option to validate their style according to our repository rules (via our [stricter CSL schema](https://github.com/citation-style-language/schema/blob/master/csl-repository.rnc)).

**Comment by zuphilip** [comment]
That would IMO make most sense if integrated in the CLS validator. Otherwise I fear the workflow is not optimal: create csl style in one place, copy and paste to the reindenter, copy and paste to the validator, copy and paste to github.

**Comment by rmzelle** [comment]
Yeah, I agree. The biggest hurdle is implementing this client-side in JavaScript or server-side in Python/Ruby, though, so we can start with a separate tool, and integrate it later.

**Comment by rmzelle** [comment]
This is now available at http://rintze.zelle.me/style-formatter/. I mean to migrate it to a subdomain of citationstyles.org, e.g. "http://formatter.citationstyles.org", and move the repo to the CSL account, so I'll leave this open for now.

**Comment by zuphilip** [comment]
Thanks for the update on this. The style formatter for CSL looks really helpful.

**Comment by rmzelle** [comment]
(I also posted an update about this at http://xbiblio-devel.2463403.n2.nabble.com/CSL-style-formatter-tt7579386.html )

**Comment by adam3smith** [comment]
now available at http://formatter.citationstyles.org/, so this is all done. We can think about how to incorporate it into the contributing instructions, but I think that's all that's left to do.

**Comment by rmzelle** [comment]
> We can think about how to incorporate it into the contributing instructions, but I think that's all that's left to do.

I already link to it at https://github.com/citation-style-language/styles/wiki/Style-Requirements#11---xml-indentation

**Comment by adam3smith** [comment]
oh great. Yeah--as you know I'm all for keeping these concise, no need to sing all the benefits of the tool.
