### ISSUE TITLE
elsevier-harvard sorts citations by descending date issued

### ISSUE THREAD

**Issue by murfit** [citation-style-language/styles#1454]
I believe there is a bug in the style
http://www.zotero.org/styles/elsevier-harvard
On line 208, the file specifies that citations should be sorted in
*descending* order of date issued. I think it should be ascending
instead.

**Comment by adam3smith** [comment]
this was changed in
https://github.com/citation-style-language/styles/pull/1452
@rmzelle @karnesky -- I'm not seeing the rationale for this change. Quick look at sample articles suggests this should be ascending in bibliographies (descending in text).

**Comment by rmzelle** [comment]
> I'm not seeing the rationale for this change

Well, it seemed like descending in their guidelines.

**Comment by adam3smith** [comment]
but at least the part you cite refers to in text citation groups, not the bibliography?

**Comment by rmzelle** [comment]
Uhm, oops, I missed that. Feel free to roll back.

**Comment by murfit** [comment]
I agree that the text

>   Citations may be made directly (or parenthetically). Groups of references should be listed first alphabetically, then chronologically." 

may lead to this interpretation if considered together with

>   Examples: 'as demonstrated (Allan, 2000a, 2000b, 1999; Allan and Jones, 1999). Kramer et al. (2010) have recently shown ....' 

I just can't believe this is really intended. In papers I have seen styles with sorting or without, back never reverse-chronologically.

**Comment by adam3smith** [comment]
citation styles go both way, though more commonly ascending in the bibliography. Question is what the relevant Elsevier Harvard journals do.  Looking quickly it seems like ascending, though in Biological Conservations, there are very few papers by the same author group, so it's hard to tell.

**Comment by adam3smith** [comment]
oh, you're referring to in-text, though in line 208? That seems rather unambiguous from the instructions. The example is clearly descending. Note it's the secondary condition, so it won't apply all that often. Most of the time, alphabetical order settles this.

**Comment by murfit** [comment]
Maybe you are right, it just seems nonsensical to me, but OK.

To be sure, I just sent a question to Elsevier Customer Service, and will report back. I asked about NeuroImage because that's the important case for me, but the instructions are identical to those of Biological Conservation, and probably for all Elsevier journals using Harvard style.

**Comment by murfit** [comment]
I found a counter-example:

![snap22](https://cloud.githubusercontent.com/assets/1738353/6657386/a7807f8e-cb4a-11e4-935a-d3c3496975b3.png)

Both "Kamitani and Tong" and "Haynes and Rees" are sorted by increasing date. This is from Cichy, Chen, Haynes, NeuroImage 54 (2011) 2297–2307, doi:10.1016/j.neuroimage.2010.09.044. Of course, this could still have simply slipped through the copy-editing process.

**Comment by karnesky** [comment]
I believe the bug submitter received editorial advice on this.

The style directions are almost identical for citations vs. bibliography:
Citations: "Groups of references should be listed first alphabetically, then chronologically." 
Bibliography: "References should be arranged first alphabetically and then further sorted chronologically if necessary."
Elsevier doesn't specifically define chronological direction in either case and does not give an example for the bibliography.  So I agree that they could have been more clear in their requirements.

However, I see no justification for having citations sorted one way and the bibliography sorted the other.

Counter-examples are unconvincing to me unless the instructions for authors or editorial advice for those journals is explicit on the issue: some editors just don't care about secondary sort keys, so  may be unlikely to fix them.

I'll check on what the elsevier-supplied BST does shortly...

**Comment by karnesky** [comment]
Well, to add oil to this fire: the BST file sorts *ascending* in the bibliography (and in citations if \bibotions{sort} is enabled). I see no way for the publisher-provided BST to sort citations descending as given in the example. So: this isn'st too helpful in resolving the issue.

I'm fine either way.

**Comment by murfit** [comment]
Well, it appears I was mistaken. I received an answer from Elsevier / NeuroImage:

> This is to inform you that you may arrange the group of references chronologically starting from the most current up to the oldest.

Using a "may" here shows that they really have a knack keeping things a bit ambiguous, but the main message is clear: They actually want reverse-chronological order in grouped citations.

I still don't understand why someone would want this – in my experience, those parts of a paper where citations come in groups, namely literature review, normally function like story-telling: this guy did this, and then this guy did this, which isn't helped by reverse-chronological order – but whatever. Apologies.
