### ISSUE TITLE
default-locale overwrites own locale in Word

### ISSUE THREAD

**Issue by MexXxo** [citation-style-language/styles#1458]
The default-locale at the MISQ Citation style overruled my locale and all my citations in the MISQ Style were in english. I removed the default-locale and my citations changed to my locale. 
I would recommend to remove the default-locale of this style, otherwise it seems to be only usable if you use english.

Cheers 
MexXxo

**Comment by adam3smith** [comment]
that's by design. I don't believe the journal accepts submissions in languages other than English.

**Comment by MexXxo** [comment]
but the citation style is also used by others that do support other languages (no talking about journals)

At least it would be nice to have a hint for this style... 

I don't know how many universities using this a the recommend citation style but at least one :)

**Comment by adam3smith** [comment]
sorry, I don't think we'll want to take the default locale out. 
The specific purpose of that is to allow people to use generic styles in their own language but get the right language for journals and other publications with a fixed language. 
Depending on your reference manager, it may offer you to override default locales or not, but we'll keep them in.
