### ISSUE TITLE
Inconsistent page numbering format in CMS full-note

### ISSUE THREAD

**Issue by usethe4ce** [citation-style-language/styles#1475]
For CMS full-note (similarly, SBL and others), the final page number in a page range is abbreviated differently for the initial full citation using the entire article versus there or subsequently when specific pages are specified. For example:

<sup>1</sup> John Smith, "Stuff," <i>Journal of Stuff</i> 1 (2015): 123-45.
<sup>2</sup> Smith, "Stuff," 129-131.

Surely the inconsistency in two-digit vs. three-digit formats cannot be right.

**Comment by adam3smith** [comment]
When reporting issues here, remember to always specify the reference manager you're using. CSL is used by almost 30 different products now, not all interpreting styles in the same way.

I'm assuming this refers to citeproc-js. There, we currently don't apply the page-range-format (in this case the shortened page numbers required by CMoS) to locators, i.e. specific page ranges for citations. I know we've talked about this in the past, but I don't know why we didn't implement this. @fbennett @rmzelle ?

**Comment by rmzelle** [comment]
We had some discussion at http://xbiblio-devel.2463403.n2.nabble.com/page-range-format-for-locators-tt7578609.html

The 1.0.1 spec already seems compatible with applying "page-range-format" to locators with the label "page": "page-range-format - Activates expansion or collapsing of page ranges", although it wouldn't hurt to make this explicit.

**Comment by adam3smith** [comment]
yeah, I say we clarify the specs "Activates expansion or collapsing of page ranges for ```page``` and ```locator="page"``` and ask citeprocs to fix this. Everyone seemed to think it was a good idea.

**Comment by rmzelle** [comment]
Do we already have a ticket? If not, please create one in "documentation".

**Comment by adam3smith** [comment]
closing this since we have a proper ticket.
