### ISSUE TITLE
PNAS inline citations should be "ref. 1", not "Reference 1"

### ISSUE THREAD

**Issue by and3k** [citation-style-language/styles#1535]
Hi everyone!

What I get: `… according to Reference 1 something …`
What it should be `… according to ref. 1 something …`

I’m using up-to-date pandoc with pandoc-citeproc. Not sure if this is CSL issue or processor issue.

I couldn’t find the correct switch to modify this behaviour in the CSL. Happy to submit patch if somebody can tell me the correct switch.

Thanks!
Bela

**Comment by adam3smith** [comment]
sorry, I'm confused: what the style does (and what I'm seeing in PNAS), is ```... Here is an important citation (1) ... ```
The word "Reference" does not appear in the citation style, nor do I see ```ref.```  in PNAS. Maybe using an actual example rather than a stylized one would help to clarify.

**Comment by rmzelle** [comment]
How exactly are you inserting the citations in the text?

**Comment by and3k** [comment]
Sorry, I’m talking about *inline* citations (not sure if this is the right word), not bracket citations.

inline:
Markdown: `… according to @ref1 something …`
What I get: `… according to Reference 1 something …`
What it should be `… according to ref. 1 something …`

brackets (which works correctly):
Markdown: `… according to [@ref1] something …`
What I get: `… according to (1) something …`

Thanks!

**Comment by and3k** [comment]
Random example from PNAS: http://www.pnas.org/content/107/1/270.full, Figure 2: `[…] (data from ref. 10). […]`

**Comment by adam3smith** [comment]
That's not a concept CSL actually supports. pandoc is just improvising, you'd have to ask them if that's changeable. It's not in the style. 
I'll note, though, that these are still in parentheses in the actual journal example, so couldn't you just use a bracketed citation, along the lines of ```[data from @ref1]```

**Comment by and3k** [comment]
OK. Thanks. I "fixed" it with sed for now directly in my output.

There are also cases, where the citations in not in brackets at all, and just in the normal flow text, …

**Comment by rmzelle** [comment]
I assume you've seen http://pandoc.org/README.html#citations ?

**Comment by and3k** [comment]
Yes, but I didn’t see an option to change it to what I want…?

**Comment by adam3smith** [comment]
yes, the concept of what you call  "inline citation" is something that pandoc takes from bibtex (i.e. ```\citet```), it simply doesn't exist in CSL, so when people do use it in pandoc, it makes an educated guess, which I'd assume makes it hard to customize, but you'll have to see what they say. 
Same is true for author-date citation styles.

**Comment by xujiaze13** [comment]
use `citealp` as `… according to ref. \citealp{} something …`
