### ISSUE TITLE
ACM SIGCHI formats changed a bunch

### ISSUE THREAD

**Issue by wbt** [citation-style-language/styles#1539]
acm-sigchi-proceedings.csl needs some updating after the latest updates to style guidelines.  The guidelines are published for Word [here](http://cscw.acm.org/2016/submit/sigchi-word-proceedings.zip).

The CSCW deadline, for which many people might be using this format, is May 22. Might anybody who's a CSL master be able to update the format to reflect the new guidelines?

Thanks much!

**Comment by rmzelle** [comment]
I would suggest you to contact the authors of the style (listed in https://github.com/citation-style-language/styles/blob/master/acm-sigchi-proceedings.csl), but the style hasn't seen any real changes since at least 2010, so I don't know if you would have any luck with that.

**Comment by adam3smith** [comment]
no, this is important for me to take it. I'll get it done by the end of the weekend the latest.

**Comment by wbt** [comment]
Thanks much!  Any updates?

**Comment by adam3smith** [comment]
Should be ready today

**Comment by adam3smith** [comment]
up now. details tomorrow.

On Sat, May 16, 2015 at 1:51 PM, Sebastian Karcher <
karcher@u.northwestern.edu> wrote:

> Should be ready today
>
> Sent from my phone
> On May 16, 2015 1:41 PM, "wbt" <notifications@github.com> wrote:
>
>> Thanks much! Any updates?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/citation-style-language/styles/issues/1539#issuecomment-102664994>
>> .
>>
>


-- 
Sebastian Karcher, PhD
Department of Political Science
Northwestern University

**Comment by wbt** [comment]
Thanks!
