### ISSUE TITLE
Pflügers Archiv - European Journal of Physiology

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/styles#1578]
Currently assigned to Springer Basic (brackets), but should be reassigned to Springer Basic (brackets, alphabetical). In which list should this exactly be changed?

reference: https://forums.zotero.org/discussion/49691/style-error-pfluegers-archiv-european-journal-of-physiology/

**Comment by Jmuccigr** [comment]
Took a shot at updating this myself. See pull request [1581](https://github.com/citation-style-language/styles/pull/1581).
