### ISSUE TITLE
Bundesgesundheitsblatt

### ISSUE THREAD

**Issue by sjPlot** [citation-style-language/styles#1583]
The style `bundesgesundheitsblatt-gesundheitsforschung-gesundheitsschutz.csl` is derived from `springer-basic-brackets-no-et-al-alphabetical.csl`, ordering references in author's alphabetical order. However, [the guidelines for authors](http://static.springer.com/sgw/documents/820898/application/pdf/Leitfaden_Bundesgesundheitsblatt.pdf) indicate that references in the text should be ordered numerical, starting with 1 (thus, in order of appearance).

I would assume that the correct citation style for Bundesgesundheitsblatt would be `springer-basic-brackets-no-et-al.csl`.

**Comment by zuphilip** [comment]
It is written that 
<blockquote>bis sechs Autoren alle auflisten, ab sieben Autoren nur die ersten drei und „et al.“)</blockquote>
i.e. it should be the `springer-basic-bracket.cls`.

Actually, we have that already in a current pull request https://github.com/citation-style-language/styles/pull/1570/files#r31868984 , but it is good to check that again.

**Comment by sjPlot** [comment]
Ok, thanks for clarification. So this issue can be closed?

**Comment by POBrien333** [comment]
@rmzelle 
This can be closed now?
Bundesgesundheitsblatt is a dependent of springer-fachzeitschriften-medizin-psychologie since the last update, so the discussion here is obsolete.

**Comment by adam3smith** [comment]
yes, thanks
