### ISSUE TITLE
Stem cells and development, issue with listing the references

### ISSUE THREAD

**Issue by krikja** [citation-style-language/styles#1591]
When I use the Stem cells and development style the references should be listed numerically in the text but instead they are listed alphabetically in the reference list, thus not starting the reference count at [1] in the text. 

Has anyone else experienced this? And do you have any suggestions on how to change it?

Bw Rós

**Comment by rmzelle** [comment]
@krikja, sorry for taking so long! Must have snowed under in my inbox. Let us know if you experience any more issues with the style.
