### ISSUE TITLE
Chicago 16 author-date omits conference name for proceedings papers

### ISSUE THREAD

**Issue by jamiebullock** [citation-style-language/styles#1609]
I'm using Chicago 16 author-date with Papers 3 in Word, and bibliography entries corresponding to conference papers have the conference name omitted.

For example:

APA 6th:

> Bullock, J., Beattie, D., & Turner, J. (2011). Integra Live: a new graphical user interface for live electronic music  (pp. 1–6). Presented at the International Conference on New Interfaces for Musical Expression.

Chicago 16:

> Bullock, Jamie, Daniel Beattie, and Jerome Turner. 2011. “Integra Live: a New Graphical User Interface for Live Electronic Music.” In, 1–6.

**Comment by adam3smith** [comment]
CSL distinguishes between papers in published conference proceedings (```paper-conference```) and papers given at conferences or similar occasions, but not published (```speech```). According to the Chicago Manual, papers published in proceedings should be treated just like chapters in edited books--in other words, you'd not include the conference name, just the proceedings title, which the style does. If the proceedings title doesn't get mapped (to ```container-title```) or isn't included in the item type, you'll have to talk to Papers about this.
