### ISSUE TITLE
 Zeitschrift für Erziehungswissenschaft (Springer, German)

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/styles#1614]
I need some help of you on this issue https://forums.zotero.org/discussion/50373?page=1#Item_3

**Comment by rmzelle** [comment]
Sorry, but what is the issue here, exactly?

**Comment by zuphilip** [comment]
The journal is a using a Springer style in German. There seems to be some small errors, see points 1) - 4) from zurpher's list. It would be possible a) to change the general Springer style, b) to create a special German Springer style, c) to create a special style for this journal. How can we decide here what is best possible?

**Comment by adam3smith** [comment]
sorry for the late reply. Of those issues, 2) is the only problematic one:
1,5,6 aren't possible, 3 is a user preference, 4 is probably wrong in the parent style anyway, and 7 can be solved by adding a term for xml:lang="de" in the parent style.
Given that, I'd fudge 2) and also solve that with a term (including the colon) for xml:lang="de" in the parent style.

**Comment by zuphilip** [comment]
Thank you. I checked again and 4 is not wrong at least in English: 

<blockquote>Slifka, M.K., & Whitton, J.L. (2000). Clinical implications of dysregulated cytokine production.
Journal of Molecular Medicine, 78, 74–80 (2000). doi:10.1007/s001090000086.</blockquote>

http://www.springer.com/cda/content/document/cda_downloaddocument/Key_Style_Points_1.0.pdf

I agree that we can change 2, 7 within the terms definition: https://forums.zotero.org/discussion/50373/zeitschrift-fuer-erziehungswissenschaft-german-zfe/#Comment_228442

**Comment by adam3smith** [comment]
WRT 4 -- in both the English and the German version this should be 
Meyer, S., & Meuller, T.   but S. Meyer & T. Mueller -- that's also the way regular APA does this and what ZfE has in its guide. The comma isn't in front of the ampersand but after the initial (think of it as "der Meyer, Stefan, und der Mueller, Thomas."). Editors of book chapters are in the 2nd form, i.e. with name-as-sort-order="never"

**Comment by zuphilip** [comment]
Okay, so we can change that comma for editors (not name-as-sort-order) in the general Springer style(s). Right? (Sorry, I think you tried to explain me a similiar issue some time before and I seem to forget about this comma before the ampersand.)

**Comment by zuphilip** [comment]
Actually the comma here look alright. I just tested some cases.
