### ISSUE TITLE
Including styles with inline-references (instead of bibliography) for publication lists

### ISSUE THREAD

**Issue by reagle** [citation-style-language/styles#1615]
I'm aware of two styles that can be used in CVs and other publication lists, [my own](http://reagle.org/joseph/2003/cv/apa-cv.csl) (based on APA) and [Julien's](https://github.com/jtanguy/julien.jhome.fr/blob/master/assets/csl/jcsl.csl) (based on Chicago). Would these be welcome in the main repository?

**Comment by rmzelle** [comment]
We already have an APA version: https://github.com/citation-style-language/styles/blob/master/apa-cv.csl

**Comment by rmzelle** [comment]
(so I guess the answer is yes; but I'll leave it to @adam3smith on whether he wishes to accept another CMoS variant, since we have a lot of them, and it's quite a bit of work to keep them all in sync)

**Comment by reagle** [comment]
Ah, right. I forgot that because I'd been using my own version since the default apa-cv.csl causes pandoc to choke with an error. `pandoc-citeproc: ParseError {errorContexts = [], errorMessage = "Failed reading: takeWhile1", errorPosition = 47:1}`

I'll close this issue and open a bug on the repo's version.

**Comment by adam3smith** [comment]
FWIW, I'd rather not have a Chicago version, too. I figured having one
would be useful, that's why we picked APA.

On Tue, Jul 7, 2015 at 4:31 PM, Joseph Reagle <notifications@github.com>
wrote:

> Ah, right. I forgot that because I'd been using my own version since the
> default apa-cv.csl causes pandoc to choke with an error. pandoc-citeproc:
> ParseError {errorContexts = [], errorMessage = "Failed reading:
> takeWhile1", errorPosition = 47:1}
>
> I'll close this issue and open a bug on the repo's version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/issues/1615#issuecomment-119348352>
> .
>



-- 
Sebastian Karcher, PhD
Department of Political Science
Northwestern University

**Comment by reagle** [comment]
Okay, I opened a new issue #1619 for why I have difficulty using the existing apa-cv.csl .
