### ISSUE TITLE
apa-cv.csl not working with pandoc-citeproc

### ISSUE THREAD

**Issue by reagle** [citation-style-language/styles#1619]
`apa-cv.csl` generates parentheticals followed by references (standard format, not useful for CVs) with the following test files.

If you download the [test zip](http://reagle.org/joseph/2015/rtc/test.zip) you will see the following files:

```
apa-cv.csl  reviews-2.md  reviews.html  reviews.md  reviews.yaml
```

You can check that apa-cv.csl is the same as in [your repo](https://github.com/citation-style-language/styles/blob/master/apa-cv.csl). Then run it via pandoc:

```
> pandoc -s -w html -o reviews.html --csl=./apa-cv.csl --bibliography=reviews.yaml reviews-2.md
```

and confirm that review.html is not in the CV format. It works on a different file I have, so maybe I'm confusing myself somehow...?

**Comment by rmzelle** [comment]
Looks like the main difference between regular APA and the CV-variant is the sort order in the bibliography: https://www.diffchecker.com/1h9dneu5

You can see how this is supposed to work at https://api.zotero.org/groups/4211/collections/A6BP5MVZ/items/top?format=bib&style=https://raw.githubusercontent.com/rmzelle/styles/master/apa-cv.csl. If you get different results with pandoc, it seems to be a problem with the latter.

**Comment by reagle** [comment]
I also filed an issue there asking to see if folks can replicate.

**Comment by reagle** [comment]
Yes, and I'm not asking for a different cite order, but a style which expands citations fully where they are invoked and without a post-bibliography, such as this [one](http://reagle.org/joseph/2003/cv/apa-cv.csl) which I use to generate my [cv](http://reagle.org/joseph/2003/cv/cv.html).

**Comment by rmzelle** [comment]
Yeah, I agree that such a full-note style without a bibliography makes more sense than the current CV variant we have. @adam3smith, thoughts?

**Comment by rmzelle** [comment]
Actually, I was thinking about the situation with the Zotero word processor plugins, where it's a bit convoluted to create a bibliography without citing items.

In general, though, a bibliography should be much more convenient, since you get your style output in a list, and you can benefit from bibliography-specific formatting options.

**Comment by reagle** [comment]
To give you a sense of what I'm doing, here's the markdown (with the citation keys) and here's the result. It'd be nice to have a version of APA in the repo that permits this.

http://reagle.org/joseph/2003/cv/cv.md

http://reagle.org/joseph/2003/cv/cv.html

**Comment by rmzelle** [comment]
Couldn't that be achieved with https://api.zotero.org/groups/4211/collections/A6BP5MVZ/items/top?format=bib&style=https://raw.githubusercontent.com/rmzelle/styles/master/apa-cv.csl ?

**Comment by adam3smith** [comment]
I'd also want to see what e.g. Mendeley does with a citation style without
a bibliography. Or is the idea to just have citation and bibliography be
the same?

On Tue, Jul 14, 2015 at 8:32 AM, Rintze M. Zelle <notifications@github.com>
wrote:

> Couldn't that be achieved with
> https://api.zotero.org/groups/4211/collections/A6BP5MVZ/items/top?format=bib&style=https://raw.githubusercontent.com/rmzelle/styles/master/apa-cv.csl
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/issues/1619#issuecomment-121238199>
> .
>



-- 
Sebastian Karcher, PhD
Department of Political Science
Northwestern University

**Comment by reagle** [comment]
@rmzelle It doesn't work with pandoc as I would expect -- I no nothing of Zotero and Mendeley. See the pandoc command at the start of this issue.

**Comment by rmzelle** [comment]
Yeah, as I said above, it seems like there is an issue with pandoc.

**Comment by reagle** [comment]
@rmzelle I'm confused. My concern has nothing to do with sort order. I want *no* bibliography at the end of the document but for each citation to be expanded where it occurs -- like LaTeX's \fullcite. Please look at my [cv](http://reagle.org/joseph/2003/cv/cv.html): I have expanded citations integrated in with other text, and no bibliography at the end.

**Comment by rmzelle** [comment]
Right. So what you seem to want is a full-note style like https://github.com/citation-style-language/styles/blob/master/chicago-fullnote-bibliography.csl, where each in-text citation is a full reference (making the bibliography optional).

The apa-cv.csl in our repo is merely modified so that it generates a bibliography where items are sorted descending by date. In-text citations are generated as they are in regular APA style.

**Comment by reagle** [comment]
Yes, and if we go back to #1615, such styles exist and so my query was if they would be welcomed into the repository?

**Comment by rmzelle** [comment]
Probably not, unless there are official style guides describing such variants.

**Comment by adam3smith** [comment]
sorry, I was out -- I could see modifying apa-cv so that in-text citations are the same as the bibliography. Since presumably no one uses the in-text citations in their regular function, why not accommodate this for pandoc and similar users?
I'm disinclined, though, to allow other CV styles.

**Comment by rmzelle** [comment]
Seems like the best solution.

**Comment by reagle** [comment]
On 07/21/2015 09:18 AM, Sebastian Karcher wrote:
> sorry, I was out -- I could see modifying apa-cv so that in-text
> citations are the same as the bibliography. Since presumably no one
> uses the in-text citations in their regular function, why not
> accommodate this for pandoc and similar users? I'm disinclined,
> though, to allow other CV styles.

That would be welcome. I'd still have to go in and delete the bibliography that pandoc generated. Or, I'd have to maintain a fork of your version in the repo, but that's probably preferable to maintaining my own version which no one else is likely to find.

**Comment by adam3smith** [comment]
pull request welcome. Otherwise it'll take me a couple of weeks.

On Tue, Jul 21, 2015 at 8:27 AM, Joseph Reagle <notifications@github.com>
wrote:

> On 07/21/2015 09:18 AM, Sebastian Karcher wrote:
> > sorry, I was out -- I could see modifying apa-cv so that in-text
> > citations are the same as the bibliography. Since presumably no one
> > uses the in-text citations in their regular function, why not
> > accommodate this for pandoc and similar users? I'm disinclined,
> > though, to allow other CV styles.
>
> That would be welcome. I'd still have to go in and delete the bibliography
> that pandoc generated. Or, I'd have to maintain a fork of your version in
> the repo, but that's probably preferable to maintaining my own version
> which no one else is likely to find.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/issues/1619#issuecomment-123303626>
> .
>



-- 
Sebastian Karcher, PhD
Department of Political Science
Northwestern University

**Comment by reagle** [comment]
Just wanted to check in on this as I just created a new version from the latest apa.csl with a bug fix. Essentially, all you have to do is delete the citation element, and then rename the bibliography tags to citation tags.

**Comment by reagle** [comment]
Just wanted to check in on this...?

**Comment by adam3smith** [comment]
Relevant PR has been merged
