### ISSUE TITLE
Covering reprint editions and modern editions with original-* variables

### ISSUE THREAD

**Issue by adunning** [citation-style-language/styles#1649]
The current implementation of `original-date`, `original-publisher`, and `original-publisher-place` in the Chicago note styles assumes that it will be used to indicate an unrevised reprint; but these can also be used to provide the original publication information of a modern edition. This will provide:

> Dain, Alphonse. _Les manuscrits_. 3rd ed. 1949. Reprint, Paris: Belles lettres, 1975.

This is not a reprint, but a corrected edition by the original publisher. I want to provide the original date because it's important for the reader to know that this is a classic work of scholarship rather than something new.

Chicago is vague on this, but I _think_ (cf. the Emerson example below) that the best way of handling this would be to place the information on the original edition before `edition` (without printing the word 'reprint'); and to follow the present behaviour if the `edition` variable is not present and `original-date` (etc.) is provided. One can have a reprint of a second edition, but I doubt whether anyone would be citing it as such, and further one can still put something like 'reprint edition' under `edition`.

For reference, these are the examples given in [CMoS ¶14.119](http://www.chicagomanualofstyle.org/16/ch14/ch14_sec119.html) for the notes:

> 22. Ernest Gowers, _The Complete Plain Words_, 3rd ed. (London: H.M. Stationery Office, 1986; Harmondsworth, UK: Penguin Books, 1987), 26. Citations refer to the Penguin edition.
> 
> 23. Jacques Barzun, _Simple and Direct: A Rhetoric for Writers_, rev. ed. (1985; repr., Chicago: University of Chicago Press, 1994), 152–53.

And for the bibliography:

> Bernhardt, Peter. _The Rose’s Kiss: A Natural History of Flowers_. Chicago: University of Chicago Press, 2002. First published 1999 by Island Press.
> 
> Emerson, Ralph Waldo. _Nature_. 1836. Facsimile of the first edition, with an introduction by Jaroslav Pelikan. Boston: Beacon, 1985.
> 
> Fitzgerald, F. Scott. _The Great Gatsby_. New York: Scribner, 1925. Reprinted with preface and notes by Matthew J. Bruccoli. New York: Collier Books, 1992. Page references are to the 1992 edition.
> 
> National Reconnaissance Office. _The KH-4B Camera System_. Washington, DC: National Photographic Interpretation Center, 1967. Now declassified and also available online, http://www.fas.org/irp/imint/docs/kh-4_camera_system.htm.
> 
> Schweitzer, Albert. _J. S. Bach_. Translated by Ernest Newman. 2 vols. 1911. Reprint, New York: Dover, 1966.

Compare MHRA (11.2.2):

> H. Munro Chadwick and N. Kershaw Chadwick, _The Growth of Literature,_ 3 vols (Cambridge: Cambridge University Press, 1932–40; repr. 1986), i, p. xiii.
> 
> José Amador de los Ríos, _Historia crítica de la literatura española_, 7 vols (Madrid: the author, 1861–65; repr. Madrid: Gredos, 1969), vi (1865), 44–54.

**Comment by adam3smith** [comment]
I'm OK with that.

**Comment by adunning** [comment]
I haven't yet got to this, but will. Just to confirm, then, we're saying that this is the best interpretation of CMoS?

> Dain, Alphonse. *Les manuscrits*. 3rd ed. 1949. Paris: Belles lettres, 1975.

It looks a bit strange to have the year floating on its own in the middle, but I'm not sure what would be better (that could be achieved through CSL).

**Comment by nickbart1980** [comment]
A bit strange indeed. What’s wrong with the following?<blockquote>Dain, Alphonse. <i>Les manuscrits.</i> 3rd ed. Paris: Belles lettres, 1975. First published 1949.</blockquote>or<blockquote>Dain, Alphonse. <i>Les manuscrits.</i> 3rd ed. Paris: Belles lettres, 1975. First published Place: Publisher, 1949.</blockquote>or even, including “original-title”<blockquote>Dain, Alphonse. <i>Les manuscrits.</i> 3rd ed. Paris: Belles lettres, 1975. First published as <i>Original Title.</i> Place: Publisher, 1949.</blockquote>

**Comment by adunning** [comment]
Thanks, Nick; good thought. This would limit its use to books that had in fact been published, since it's making a bit of a statement to say that a work in manuscript was 'published'. Personally, I don't use original-date with critical editions, but could this be too restrictive or verbose for others?

**Comment by adam3smith** [comment]
I like the first published. Given the type of detail the manual suggests adding to these depending on the circumstances, we're never going to get it quite right. 
If we're concerned, though, one thought would be to wrap "First published (as)" in an if statement testing for original-publisher. I'd be happy with that, too.

**Comment by adunning** [comment]
Testing for `original-publisher` doesn't seem necessary to me. Right now, in the note style, no indication of status is given at all: do we want to change this?

Right now, we get:

> Alphonse Dain, *Les manuscrits*, 3rd ed. (1949; Paris: Belles lettres, 1975).

> Jean Leclercq, *The Love of Learning and the Desire for God: A Study of Monastic Culture*, trans. Catharine Misrahi, 3rd ed. (Paris: Cerf, 1957; New York: Fordham University Press, 1982).

> James E.G. Zetzel, Latin Textual Criticism in Antiquity (Salem, NH: Ayer, 1981; New York: Arno Press, 1981).

Changing this would instead give:

> Alphonse Dain, *Les manuscrits*, 3rd ed. (Paris: Belles lettres, 1975; first published 1949).

> Jean Leclercq, *The Love of Learning and the Desire for God: A Study of Monastic Culture*, trans. Catharine Misrahi, 3rd ed. (New York: Fordham University Press, 1982; first published as *L'amour des lettres et le désir de Dieu: Initiation aux auteurs monastiques du Moyen Âge*, Paris: Cerf, 1957).

> James E.G. Zetzel, *Latin Textual Criticism in Antiquity* (New York: Arno Press, 1981; repr., Salem, NH: Ayer, 1981).

These would correspond to the following bibliography styles, for reference:

> Dain, Alphonse. *Les manuscrits*. 3rd ed. Paris: Belles lettres, 1975. First published 1949.

> Leclercq, Jean. *The Love of Learning and the Desire for God: A Study of Monastic Culture*. Translated by Catharine Misrahi. 3rd ed. New York: Fordham University Press, 1982. First published as *L'amour des lettres et le désir de Dieu: Initiation aux auteurs monastiques du Moyen Âge*. Paris: Cerf, 1957.

> Zetzel, James E.G. *Latin Textual Criticism in Antiquity*. New York: Arno Press, 1981. Reprint, Salem, NH: Ayer, 1981.

One side effect of using the edition information to determine whether a work is a reprint is that it wouldn't be possible to render either of the note examples from CMoS (22/23 above); this is what one would get from CSL:

> 22. Ernest Gowers, *The Complete Plain Words*, 3rd ed. (Harmondsworth, UK: Penguin Books, 1987; first published London: H.M. Stationery Office, 1986), 26.

> 23. Jacques Barzun, *Simple and Direct: A Rhetoric for Writers*, rev. ed. (Chicago: University of Chicago Press, 1994; first published 1985), 152–53.

Given our limitations, does this seem acceptable, or is it possible to do any better?

**Comment by adunning** [comment]
Just noticed that there's also an example of a translated title in CMoS ¶14.109:

> Furet, François. *Le passé d’une illusion*. Paris: Éditions Robert Laffont, 1995. Translated by Deborah Furet as *The Passing of an Illusion* (Chicago: University of Chicago Press, 1999).

*or*

> Furet, François. *The Passing of an Illusion*. Translated by Deborah Furet. Chicago: University of Chicago Press, 1999. Originally published as *Le passé d’une illusion* (Paris: Éditions Robert Laffont, 1995).

They don't have anything to say about the note version of this. This causes me to wonder whether this is how they would handle `original-title`:

> 26. Jean Leclercq, *The Love of Learning and the Desire for God: A Study of Monastic Culture*, trans. Catharine Misrahi, 3rd ed. (New York: Fordham University Press, 1982), originally published as *L'amour des lettres et le désir de Dieu: Initiation aux auteurs monastiques du Moyen Âge* (Paris: Cerf, 1957), 27.

> 27. J.K. Rowling, *Harry Potter and the Sorcerer’s Stone* (New York: Scholastic, 1998), first published as *Harry Potter and the Philsopher’s Stone* (London: Bloomsbury, 1997), 102.

> Leclercq, Jean. *The Love of Learning and the Desire for God: A Study of Monastic Culture*. Translated by Catharine Misrahi. 3rd ed. New York: Fordham University Press, 1982. Originally published as *L'amour des lettres et le désir de Dieu: Initiation aux auteurs monastiques du Moyen Âge* (Paris: Cerf, 1957).

> Rowling, J.K. *Harry Potter and the Sorcerer’s Stone*. New York: Scholastic, 1998. First published as *Harry Potter and the Philsopher’s Stone* (London: Bloomsbury, 1997).

Do we want to make a distinction between 'first published' and 'originally published' depending on whether there is a translator present? (I would tend to stick with 'first published' for everything.)

**Comment by adam3smith** [comment]
I think that should work, including the added info in the notes. 
I'm not so sure about the original-title, though: as 14.109 says, this is an unusual way to cite a translated work (normally you just cite the translation or the original). What I'm concerned about is, once reference managers are actually offering this as a field and people fill it out (or we populate it automatically), they'll get incorrect CMoS citations.

**Comment by adunning** [comment]
Shall I leave out original-title for now, then, or is there a safer way to support it?

**Comment by adam3smith** [comment]
yeah, let's leave original-title alone for now.
