### ISSUE TITLE
in case more then 3 authors, apa-tr shows all authors.

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [citation-style-language/styles#1654]
When I add reference for an article with more then 3 authors in paragraph zotero adds it in the bibliography with all authors. I think there is an error. Because it shoult be added like (Ayhan vd., 2015).

**Comment by adam3smith** [comment]
The APA manual says to list up to 5 authors on the first citation of an item. They style is correct. (Please do check relevant style guides before reporting errors here. If you're not sure about something, use the Zotero forums to ask).
