### ISSUE TITLE
MHRA Author Date style error (modern-humanities-research-association-author-date.csl)

### ISSUE THREAD

**Issue by davepwsmith** [citation-style-language/styles#1672]
**Which citation style are you using?**
modern-humanities-research-association-author-date.csl; this more than likely will apply to all MHRA styles.

**Give examples of incorrect formatting of citations or the bibliography**
Thwaites, John A. 1937a. ‘Paul Klee and the Object’, Parnassus, 9: 8–11 <http://dx.doi.org/10.2307/771865>
———. 1937b. ‘Paul Klee and the Object: Second Part’, Parnassus, 9: 7–9, 33–34 <http://dx.doi.org/10.2307/771892>

**What should these citations or bibliographic entries look like?**
Thwaites, John A. 1937a. ‘Paul Klee and the Object’, Parnassus, 9.6: 8–11 <http://dx.doi.org/10.2307/771865>
———. 1937b. ‘Paul Klee and the Object: Second Part’, Parnassus, 9.7: 7–9, 33–34 <http://dx.doi.org/10.2307/771892>

**Describe the problem in more detail**
Where journals fail to sequentially paginate their issues, a journal part or issue number is necessary. I can only imagine that this will be very difficult to fix, because it will be impossible (?) to tell when the issue number should be used or dropped from the metadata provided.

From p. 68 of the MHRA style guide, Third Edition:
Normally it will not be necessary to cite the month or season of publication or the part number of an issue of a journal, unless the part numbers are individually paginated, in which case the information should be given. 
Lionel Trilling, ‘In Mansfield Park’, Encounter, 3.3 (September 1954), 9–19.
José Luis Pardo, ‘Filosofía y clausura de la modernidad’, Revista de Occidente, 66 (November 1986), 35–47.
E. Iukina, ‘Dostoinstvo cheloveka’, Novyi mir, 1984, no. 12, 245–48.

**Relevant metadata / BibLaTeX entries**
````
@article{thwaites1937,
  title = {Paul Klee and the Object},
  volume = {9},
  issn = {15436314},
  doi = {10.2307/771865},
  timestamp = {2015-08-21 18:42:47},
  eprinttype = {jstor},
  eprint = {771865?origin=crossref},
  number = {6},
  journaltitle = {Parnassus},
  author = {Thwaites, John A.},
  date = {1937-11},
  pages = {8--11},
  langid = {english}
}

@article{thwaites1937a,
  title = {Paul Klee and the Object: Second Part},
  volume = {9},
  issn = {15436314},
  doi = {10.2307/771892},
  shorttitle = {Paul Klee and the Object},
  timestamp = {2015-08-21 18:43:22},
  eprinttype = {jstor},
  eprint = {771892?origin=crossref},
  number = {7},
  journaltitle = {Parnassus},
  author = {Thwaites, John A.},
  date = {1937-12},
  pages = {7--9, 33--34},
  langid = {english}
}
````

**Comment by adam3smith** [comment]
We're considering this. It's a recurring issue with styles that insist on this annoying rule and there is no reasonably easy solution. We'll likely put the issue number in, but that means the (much more common) continuously paginated volumes are going to also included. There is no way to automate this correctly both ways.

(Btw. we automatically get style error reports from Mendeley, so reporting them once is enough. We prefer you go through them, so in case something is Mendeley-specific it's already there for their support to look at).

**Comment by adam3smith** [comment]
OK, just pushed the fixes for both MHRA styles. Should make it into Mendeley within the next day or two.

**Comment by rmzelle** [comment]
> It's a recurring issue with styles that insist on this annoying rule and there is no reasonably easy solution.

Right. Automation would be possible if we had a database of either all non-continuously or all continuously paginated journals. If we then had a toggle in CSL for suppressing issue number for continuously paginated journals, it would be relatively straightforward to match journal titles and/or ISSNs of individual items against that database and produce correct output for styles that require this. But since creating this datbase would be a significant effort (something that style guides like MHRA conveniently ignore, which instead apparently presume that authors check this by hand for each cited article), @adam3smith's solution of staying on the safe side and just including some potentially redundant information is clearly the simplest.

**Comment by adam3smith** [comment]
(for what it's worth, MHRA in its newest edition is quite flexible on this:

> The month or season of publication or the part number of an issue 
of a journal may be omitted if the volume as a whole is continuously 
paginated; but it can be helpful to include this information, and in any 
case it must be given if the part numbers are paginated individually, as 
in these examples


The biggest issue is really APA, which unfortunately is also by far the style with the highest density of sticklers.

**Comment by zuphilip** [comment]
Could a similiar shift to an <i>optional/tolerated</i> showing of the issue numbers also in continuously paginated journals for APA be possible? If we ask <a href="https://twitter.com/APA_Style">them</a> nicely and explain what the consequences of not doing this are...

**Comment by adam3smith** [comment]
I think @bwiernik has been on that for quite a while; I'm not getting my hopes up...

**Comment by bwiernik** [comment]
I don't see it changing any time soon. A while back, we found a partial list of by-issue paginated journals. That would be a good starting place for building support.
