### ISSUE TITLE
elsevier-harvard removes in-text page references

### ISSUE THREAD

**Issue by murfit** [citation-style-language/styles#1706]
I'm using `elsevier-harvard.cls` with pandoc and pandoc-citeproc. When I make a citation like this

    [@Doe, p. 156]

it is rendered as "(Doe, 2007)", i.e. without the reference to the page. I am quite sure that this is not a bug of pandoc/citeproc, because if I use their standard style `chicago-author-date.csl`, the same code results in "(Doe, 2007, 156)".

Is this a bug, or a feature of `elsevier-harvard.cls`? If the latter, is there a way to enable in-text page references?

**Comment by adam3smith** [comment]
It's in the style: https://github.com/citation-style-language/styles/blob/master/elsevier-harvard.csl#L215
I added it about 2 years ago, so unless you're somehow using a very old version of the style, I'd guess it's a pandoc issue (just in case, though, your file extension is wrong: it's .csl, not .cls, though I'm guessing that's just a typo here)>

**Comment by murfit** [comment]
@adam3smith, you are right, I was still using a style from 2009, no idea why. Thanks for the quick help!
