### ISSUE TITLE
Bioresources

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#1716]
https://forums.zotero.org/discussion/37079/style-request-bioresources/#Item_2

I want to submit an article in Bioresources which is an online open access journals with an obvious topic :D
http://www.ncsu.edu/bioresources/
ISSN: 1930-2126

example of freely available article
http://www.ncsu.edu/bioresources/BioRes_09/BioRes_09_3_3755_Editorial_Finkbeiner_Indirect_Land_Use_Change_5597.pdf

Citations examples you required :

***
Campbell, J. L., & Pedersen, O. K. (2007). "The varieties of capitalism and hybrid success," *Comparative Political Studies* 40(3), 307–332.
Mares, I. (2001). *Firms and the welfare state: When, why, and how does social policy matter to employers?* In P. A. Hall & D. Soskice (Eds.), Varieties of capitalism. The institutional foundations of comparative advantage (pp. 184–213). New York: Oxford University Press.

**Comment by zuphilip** [comment]
The forum post indicated that it is the same style as the <a href="http://ascelibrary.org/journal/jwrmd5">J. Water Resources Planing and Management</a>. This journal is published by the American Society of Civil Engineers (ASCE) and <i>not</i> by Springer as mentioned further in forum post. There is already a style from this publisher https://www.zotero.org/styles/american-society-of-civil-engineers?source=1 which links to the <a href="http://ascelibrary.org/doi/abs/10.1061/9780784478998.ch17">style manual for books</a>. There is another <a href="http://ascelibrary.org/doi/book/10.1061/9780784479018">manual from them for journals</a> (pp. 29-32). However, I have the impression that is may be same style in the end.

I will should check that more carefully... or maybe you have some more insights...

However, this would mean that we just have to create an independent style. Moreover, we could add an independent style for <a href="http://ascelibrary.org/journals/all_journal_titles">all ASCE journals</a> (I counted 36 journals).

**Comment by zuphilip** [comment]
Let us concentrate here on the BioResources.
(We can continue about the ASCE journals itself in #1783.)

**Comment by zuphilip** [comment]
There are some slightly differences of the BioResources to the ASCE style. I mainly focused at the <a href="https://www.ncsu.edu/bioresources/BioRes_Article_Template_Styles.docx">Word 2010 article template for peer-reviewed articles</a>:

![bioresources-differences](https://cloud.githubusercontent.com/assets/5199995/11485587/57f314f4-97b4-11e5-80aa-2ecefba4cce8.jpg)

However, the references are not very consistent across different article templates and also inside some example articles. For example, I have also seen the ASCE formatting of editor term. Consequently, I will not change that, but I will
 * add the DOI whenever possible
 * change the `.` to `,` after the title
 * add `in: `

Pull request is coming in a minute...
