### ISSUE TITLE
Herpetologica

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#1718]
https://forums.zotero.org/discussion/37562/herpetologica/#Item_3

ISSN: 0018-0831.
http://www.hljournals.org/
Author instructions: http://www.herpetologistsleague.org/dox/HL-Instructions-for-Authors.pdf

I searched for similar styles and found similar but not exact matches.
in-text citations are:
(Campbell and Pedersen, 2007)
(Mares, 2001)
(Jones et al., 1990) No italics

For the literature cited section, The Rockefeller University Press scored 94% match for a journal article, the main difference being that the journal name is NOT in italics is for Herpetologica. See below.

Campbell, J.L., and O.K. Pedersen. 2007. The varieties of capitalism and hybrid success. Comparative Political Studies 40:307-332.

The Rockefeller University Press is 83% match for book, but doesn't include page numbers, and instead of city and state, only the country is used.

McInnis, M.D., and L.P. Nelson. 2011. Shaping the body politic: Art and political formation in early america. University of Virginia Press, USA.

For the literature cited, Ecology was 96% match, instead of the state, Herpetologica only using the country.

Mares, I. 2001. Firms and the welfare state: When, why, and how does social policy matter to employers? Pages 184–213 in P. A. Hall and D. Soskice, editors. Varieties of capitalism. The institutional foundations of comparative advantage. Oxford University Press, New York.

**Comment by pmelchor** [comment]
Update URL for author instructions:
http://herpetologistsleague.org/HL-Instructions-for-Authors.pdf

**Comment by rmzelle** [comment]
Covered by #2306.

**Comment by rmzelle** [comment]
Thanks again, @pmelchor!

**Comment by pmelchor** [comment]
My pleasure :-) Moving up the pending style request list now. I have already updated https://forums.zotero.org/discussion/comment/263882#Comment_263882 but do let me know if you think the "style X now available" reply should be different or include other info.

**Comment by adam3smith** [comment]
update message is great as is.
