### ISSUE TITLE
Journal of Sport and Health Science]

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#1720]
https://forums.zotero.org/discussion/37949/style-request-journal-of-sport-and-health-science/#Item_7

•Campbell JL, Pedersen OK. The varieties of capitalism and hybrid success. Comp Polit Stud, 2007;40:307-2.
•Mares I. Firms and the welfare state: when, why, and how does social policy matter to employers? In: Hall PA, Soskice D, editors. Varieties of capitalism. The institutional foundations of comparative advantage. New York: Oxford University Press, 2001.p.184–213.

The ISSN and EISSN of the journal are

ISSN:
2213-2961 (Electronic)
2095-2546 (Print)
2213-2961 (Linking)

A link to online style documentation of my journal: http://www.jshs.org.cn/EN/column/column290.shtml

A link to a freely available paper formatted with the style I'm requesting: http://www.sciencedirect.com/science/article/pii/S2095254614000271

Thanks in advance!

Kindly regards,

Carol

---

adamsmith Jun 29th 2014 

there should not actually be a comma between journal abbreviation and year, correct? Journal and book titles should be in italics and journal volume numbers in bold, right?

I know Elsevier likes to have DOIs included for all articles in many of the journals, even if they may not appear in the end. What's your preference there?

---

1 Correct. There is NO comma between journal abbreviation and year.

2 Yes, Journal and book titles are be in italics, and journal volume numbers are in bold.

3 Yes, please keep the DOIs
http://doi.org/...

**Comment by pmelchor** [comment]
Question: the template I have started from includes specific bibliography renderings for types that are not mentioned in the JSHS style guide (e.g. article-newspaper or legal_case). Which of the following do you recommend?

a) "Keep them. If there was a good match in the basic types it is likely that those other types would also have to be treated as in the template style if they are ever used".

b) "Get rid of them. Let's keep new styles as simple as possible".

c) Other?

Thanks!

**Comment by adam3smith** [comment]
definitely a)

**Comment by pmelchor** [comment]
Here's another multiple choice question. The template I started from is not great: lots of formatting in bibliography instead of in macros, lots of affixes that could be avoided with a few delimiters, etc. Which option do we go for?

a) "Quick and dirty" (fastest): just make as few changes as are necessary to obtain the desired output.

b) "The perfectionist" (slowest): improve and submit the template style first, then work on the new one.

c) "The middle ground": leave the template as is but make at least the most obvious improvements in the new style —besides the output-related tweaks—.

d) Other

I have been working in c) mode so far.

**Comment by adam3smith** [comment]
I generally do c), too. If there are obvious mistakes (rather than just inelegant or unstable code) in the original style I do fix&submit those, though.

**Comment by rmzelle** [comment]
c) and a). The problem with all these journal-specific independent CSL styles is just that it's too much code to review and touch up by hand. (we spent a little bit of effort trying to automatically fix some coding errors, but that's also a long road: https://github.com/citation-style-language/styles/wiki/Quality-Control#repairing-problematic-code-patterns)

Ideally we would spend most of our time improving a small set of template styles and making them very high quality, and then try to base new styles off of those. That would be easier to do if we had a way to automatically classify our existing CSL styles according to coding quality (although popular style guides like APA and Chicago and common styles used by large publishers usually already have good CSL styles). And it would be handy to have the ability to exclude 'low-quality' styles from http://editor.citationstyles.org/searchByExample/.

**Comment by pmelchor** [comment]
> And it would be handy to have the ability to exclude 'low-quality' styles from http://editor.citationstyles.org/searchByExample/.

Have you considered doing this the other way around? Identify and tag high quality styles —probably the ones you guys have played a big part in writing— and add a checkbox to searchByExample to "include certified styles only" (could be certified/verified/validated/premium/whatever).

**Comment by rmzelle** [comment]
Yeah, that could work too. (it would also be nice if we could build phylogenetic trees for our styles based on the (dis)similarity of their output, so that we can hand-pick some representative styles from each branch as templates; like https://en.wikipedia.org/wiki/Phylogenetic_tree#/media/File:Tree_of_life_SVG.svg)

**Comment by pmelchor** [comment]
Do you know whether link rel="template" has been used consistently? If it has, it should not be too hard (with some coding) to build a tree based on ancestry as a proxy for output similarity.

**Comment by adam3smith** [comment]
Some thoughs:
1) To the multiple-choice question above, another option would be d) to make sure you're starting with a high-quality style. This usually isn't hard to tell: mostly groups rather then affixes for spaces and punctuation, terms rather than hardcoded values, in short, what I wrote up [here](https://zoteromusings.wordpress.com/2013/10/28/writing-csl-features-and-best-practices/). This is easy to recognize.
2) The CSL Editor _does_ show "popular" styles in blue. We could change that to "High Quality CSL" and pick a list of 30 or so styles that span several genres. That shouldn't be hard.
3) I'm in the process of writing something with @zuphilip about citation styles and we do want to analyze CSL styles as a sort of "data set" so maybe something interesting will come of this. One cool thing is that the CSL Editor actually gives us a JSON file with a full set of style outputs generated from identical metadata, so we may be able to actually compare similarity. I have also been thinking about using "template" for a network analysis of styles, but I'm afraid there may be a fairly large number of orphan styles, i.e. styles without a template. Easy to check, though.

**Comment by pmelchor** [comment]
@adam3smith Will check 2) and think about 3), thanks! With relationship to 1):

@rmzelle One thing I would like to do if you think it would be useful —and once I have cut my teeth with a few more of the pending style requests— is to take http://docs.citationstyles.org/en/stable/primer.html and expand it into / complement it with a "style developer manual". My experience as a newbie is that there is great info around but it is a little disperse (as is to be expected in any growing project). I would like to: include sections like "How to choose a good template for your style" or "Useful CSL Tools"; consolidate the info on best practices and common pitfalls; add some more complex markup examples (e.g. good macros, etc.)...

**Comment by rmzelle** [comment]
> I have also been thinking about using "template" for a network analysis of styles, but I'm afraid there may be a fairly large number of orphan styles, i.e. styles without a template. Easy to check, though.

There are 1354 styles in the root directory of the repo with `rel="self"`, and 801 files with at least one `rel="template"` link (total hits here is 823 across 801 files). So just shy of 60% of styles have a template link.

> One thing I would like to do ... is to take http://docs.citationstyles.org/en/stable/primer.html and expand it into / complement it with a "style developer manual"

Yeah, I'm not sure if the primer is the best starting point, but you're definitely right that the documentation on editing CSL styles is currently lacking and too spread out, especially for people new to CSL. We e.g. have:

https://github.com/citation-style-language/styles/wiki/Requesting-Styles
https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md
http://citationstyles.org/styles/#Editing_Styles
https://github.com/citation-style-language/styles/wiki/Editing-Styles
https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step
https://github.com/citation-style-language/csl-editor/wiki/User-guide-for-the-CSL-Editor
https://github.com/citation-style-language/styles/wiki

and none of the pages is a very comprehensive good starting point for users who wish to know how to edit styles. There is definitely room to consolidate some of these and improve the organization.

**Comment by zuphilip** [comment]
> ... network analysis of styles ...

By analyzing the template links, I wouldn't expect rich graph structure, but some stars and isolated nodes maybe some very few edges between them. Besides the numbers from @rmzelle I can provide some numbers about the frequently used styles templates styles (top-5):
```
<link count="82" href="http://www.zotero.org/styles/elsevier-vancouver"/>
<link count="40" href="http://www.zotero.org/styles/vancouver"/>
<link count="39" href="http://www.zotero.org/styles/apa"/>
<link count="32" href="http://www.zotero.org/styles/american-medical-association"/>
<link count="22" href="http://www.zotero.org/styles/elsevier-harvard"/>
```
Analyzing the output of the same reference in different styles as @adam3smith suggested would be much more interesting to do. Actually, I started to think something similar for providing an alternative way to search for styles based on some structural questions (e.g. is the title coming before the year or afterwards?).

**Comment by adam3smith** [comment]
Right, one of the problems of a network based on templates is that there are (almost) no styles with multiple templates, so even the theoretically possible graph structure is quite limited and there can't be any bridges between clusters. Still, I'm curious about this.

**Comment by zuphilip** [comment]
I tried a little bit more about to explore the graph structure according to the template relation see https://gist.github.com/zuphilip/f5ccbebb9a2599fc9ee53fa2c98e7c14#gistcomment-1925910 (it looks more interesting than I expected)

**Comment by pmelchor** [comment]
Thanks! That looks promising (e.g. Search by example > Click on "see in graph" button for the style with highest match % > Visually identify the closest "high quality" CSL ancestor).

**Comment by rmzelle** [comment]
> I can provide some numbers about the frequently used styles templates styles (top-5)

@zuphilip, do you have the full list as well? How did you deal with multiple degrees of separation? (e.g. if style A and B both have style C as the template, and style C has style D as the template, I would expect a link count of 2 for C (A + B) and 3 for D (A + B + C))

**Comment by zuphilip** [comment]
Sure, here is the complete list with the corresponding XQuery call: https://gist.github.com/zuphilip/6aeee41ac8477282b4c00e9fa0c0eded .

Please note this analyses just the links as they are explicitly written in the styles themselves. I didn't calculate the [transitive closure](https://en.wikipedia.org/wiki/Transitive_closure) as you suggest in your comment above.

**Comment by rmzelle** [comment]
Great, thanks. By the way, Carles Pina from Mendeley once shared some usage statistics as well in 2013 (I think it counted which style was selected when a user clicked "Insert Citation" in their Word plugin; APA is their default, and they have bunch of standard installed styles). Their top ones were:

```
36.8% http://www.zotero.org/styles/apa
8.2% http://www.zotero.org/styles/ieee
7.4% http://www.zotero.org/styles/harvard1
5.1% http://www.zotero.org/styles/nature
4.0% http://www.zotero.org/styles/vancouver
2.1% http://www.zotero.org/styles/chicago-author-date
2.1% http://www.zotero.org/styles/american-medical-association
1.0% http://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas
0.9% http://www.zotero.org/styles/american-political-science-association
0.6% http://www.zotero.org/styles/american-sociological-association
0.6% http://www.zotero.org/styles/cell
0.5% http://www.zotero.org/styles/american-chemical-society
0.5% http://www.zotero.org/styles/plos-one
0.4% http://www.zotero.org/styles/acm-sigchi-proceedings
0.4% http://www.zotero.org/styles/chicago-fullnote-bibliography
0.4% http://www.zotero.org/styles/ecology
0.3% http://www.zotero.org/styles/ABNT
0.3% http://www.zotero.org/styles/modern-language-association
0.3% http://www.zotero.org/styles/angewandte-chemie
0.3% http://www.zotero.org/styles/modern-humanities-research-association
0.3% http://www.zotero.org/styles/elsevier-harvard
0.3% http://www.zotero.org/styles/pnas
0.3% http://www.zotero.org/styles/apsa
0.2% http://www.zotero.org/styles/journal-of-the-american-chemical-society
0.2% http://www.zotero.org/styles/science
0.2% http://www.zotero.org/styles/the-journal-of-neuroscience
0.2% http://www.zotero.org/styles/elsevier-with-titles
0.2% http://www.zotero.org/styles/acs-nano
0.2% http://www.zotero.org/styles/american-geophysical-union
0.2% http://www.zotero.org/styles/vancouver-superscript
0.2% http://www.zotero.org/styles/national-library-of-medicine
0.2% http://www.zotero.org/styles/unisa-harvard
0.2% http://www.zotero.org/styles/american-chemical-society-with-titles
0.2% http://www.zotero.org/styles/molecular-ecology
0.2% http://www.zotero.org/styles/royal-society-of-chemistry
```
