### ISSUE TITLE
The Journal of Modern History

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#1722]
https://forums.zotero.org/discussion/38095/style-error-the-journal-of-modern-history/#Item_3

Journal says it follows Chicago Manual and does for the most part, but no DOIs and no Publishers.

**Comment by zuphilip** [comment]
This journal is currently a [dependent style](http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fthe-journal-of-modern-history) of [Chicago Manual (note)](http://www.zotero.org/styles/chicago-note-bibliography) but I think it should first be corrected to Chicago Manual **full-note**. Or do I miss something here?

Howerver, the other differences, as you already pointed out, are:
 * no DOIs are used
 * publishers are not present (the style says "Note: publishers' names are included only in the initial source information for books under review.")

==> Therefore, we will need a new independent style started from CMoS full note style with these two changes. I will wait for @adam3smith's feedback and can then do the work.
