### ISSUE TITLE
Development Policy Review

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#1724]
https://forums.zotero.org/discussion/38333/style-request-development-policy-review/#Item_3
Thank you to anyone who can help with this!

Campbell, J.L. and Pedersen, O.K. (2007) 'The Varieties of Capitalism and Hybrid Success', *Comparative Political Studies* 40(3): 307–332. doi:10.1177/0010414006286542

Mares, I. (2001) 'Firms and the Welfare State: When, why, and how does social policy matter to employers?' In P.A. Hall and D. Soskice (eds), *Varieties of capitalism. The institutional foundations of comparative advantage*: 184–213. New York: Oxford University Press.

ISSN: 0950-6764, ESSN: 1467-7679

Author Guidelines:
http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-7679/homepage/ForAuthors.html

Example:
http://www.researchgate.net/publication/215806391_The_Millennium_Development_Goals_Key_Current_Issues_and_Challenges/file/d912f50b0496ce0417.pdf

**Comment by zuphilip** [comment]
I will try to adapt Harvard Cite Them Right 9th edition for this journal. Differences are:
 * inline citations
   * the `et-al` is not italics
   * locator should be seperated by a colon `:` and not label
   * et-al rule: 3/1
   * use ibid: TODO
 * bibliography
   * different authors are separated by `;`
   * title case for English
   * container-editors have initials first and then last name
   * journal-title and volume is seperated by a space
   * no pages for chapters
   * page format minimal (?)
   * seperators in newspaper-article are different
