### ISSUE TITLE
Automatically pull

### ISSUE THREAD

**Issue by ismayc** [citation-style-language/styles#1748]
Is there a way to automatically update the files in my csl folder at <https://github.com/ismayc/rticles/tree/master/inst/rmarkdown/templates/reed_thesis/skeleton/csl> with the contents of the styles folder updated here?  I'd like to make sure credit is given to the work here, but I'd also like to make sure that folks using my thesis template have the most up-to-date csl files.

**Comment by adam3smith** [comment]
Nothing we have, though I'm sure some type of webhook could do that with relative ease.

**Comment by rmzelle** [comment]
If you have no objections to incorporating the entire CSL style repository into your own, you can also set up a git submodule (see e.g. http://stackoverflow.com/questions/5252450/using-someone-elses-repo-as-a-git-submodule-on-github for documentation). Basically it's a pointer to a certain commit from another repository that you can update by hand.

You can see examples of this in the root directory of https://github.com/zotero/zotero, which has two submodules to style and translator repositories.

**Comment by rmzelle** [comment]
> incorporating the entire CSL style repository into your own

(this doesn't actually take up any space online, since it's just a pointer, but you would have to check out the entire submodule repo on your computer)

**Comment by ismayc** [comment]
Thanks!
