### ISSUE TITLE
HdM Stuttgart Style

### ISSUE THREAD

**Issue by jukoegel** [citation-style-language/styles#175]
Hey guys,
I've created a style for the Stuttgart Media University (HdM). Would be great if the cls could be added to the repository.
https://gist.github.com/2922655

Julian

**Comment by adam3smith** [comment]
@nachtdenker -- the document linked above is no longer available. Could you put it back up?

**Comment by rmzelle** [comment]
It's also possible nowadays to save a copy on GitHub by attaching a file to your comment: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/
