### ISSUE TITLE
ASCE journals

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/styles#1783]
Splitted from #1716:

The <a href="https://www.zotero.org/styles/american-society-of-civil-engineers?source=1">CSL style from the American Society of Civil Engineers</a> which links to the <a href="http://ascelibrary.org/doi/abs/10.1061/9780784478998.ch17">style manual for books</a>. There is another <a href="http://ascelibrary.org/doi/book/10.1061/9780784479018">manual from them for journals</a> (pp. 29-32). My impression is that this is actually describing the same style and we could add an independent style for <a href="http://ascelibrary.org/journals/all_journal_titles">all ASCE journals</a> (I counted 36 journals).

Maybe we should ask someone from ASCE or do you have any insights?

**Comment by adam3smith** [comment]
I agree this is the same citation style for books and journals, had a pretty close look. Makes sense to me to create one independent style, do checks on a couple of journals, then add them all as dependent.

**Comment by zuphilip** [comment]
There exists currently only one independent style and I haven't found any of the journals in the repository with my simple search: https://github.com/citation-style-language/styles/search?q=asce&type=Issues&utf8=%E2%9C%93

The author guides from the different journals are (always?) linked to the ASCE guidelines:
 * https://www.editorialmanager.com/jrnmteng/default.aspx
 * https://www.editorialmanager.com/jrnlaeng/default.aspx
 * https://www.editorialmanager.com/jrncpeng/default.aspx
 * https://www.editorialmanager.com/jrnwweng/default.aspx
 * https://www.editorialmanager.com/jrnteeng/default.aspx
 * https://www.editorialmanager.com/jrnbeeng/default.aspx
 * https://www.editorialmanager.com/jrneieng/default.aspx
 * https://www.editorialmanager.com/jrngteng/default.aspx
 * https://www.editorialmanager.com/jrnhzeng/default.aspx
 * https://www.editorialmanager.com/jrnnmeng/default.aspx

I don't think I have access to any of this journals. Do you have?

**Comment by adam3smith** [comment]
don't have access either, but I think we can assume the links are correct. I can poke around and see if any of these are easily available online tonight.

**Comment by zuphilip** [comment]
Okay I tested around a dozend OA-articles from different ASCE journals found by GoogleScholar. All of them seem to use THE reference style according to the one here. Thus, I think it is safe enough to assume that all of them are following the same citation style manual. I will try to prepare a commit for these journals as dependen styles (but this may take a while).

<i>Fun fact</i>: The CSL repo will contain over 8.000 styles afterwards!

**Comment by rmzelle** [comment]
Thanks both! (https://www.zotero.org/styles now reports 8024 styles!)
