### ISSUE TITLE
Style for Glossa

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/styles#1829]
It would be nice to provide a CSL style for the transformed journal <a href="http://glossa.ubiquitypress.com/">Glossa</a>, which is now a fair Open Access journal. The guidelines can be found <a href="http://glossa.ubiquitypress.com/about/submissions/#style-sheet">here</a> and they refer to <a href="http://www.eva.mpg.de/linguistics/past-research-resources/resources/generic-style-rules.html">The Generic Style Rules for Linguistics (version of December 2014)</a> with some adaptions.

**Comment by rmzelle** [comment]
Added in #2459.

**Comment by zuphilip** [comment]
Thank you very much @damnation333 !
