### ISSUE TITLE
New Style Request for The Journal of Water Sanitation and Hygiene for Development

### ISSUE THREAD

**Issue by jeccak** [citation-style-language/styles#1834]
If anyone could code up the style for the Journal of Water Sanitation and Hygiene for Development I would really appreciate it!  I can't find one that matches via Zotero.

Here's the journal site:  http://washdev.iwaponline.com/content/instructions-authors

**Comment by adam3smith** [comment]
we actually ask for style requests via the Zotero forums (where there is a higher chance that someone else finds them) and in a specified format that gets anyone developing started quickly:
https://github.com/citation-style-language/styles/wiki/Requesting-Styles

**Comment by matejovo** [comment]
http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fgeological-magazine

**Comment by damnation333** [comment]
@adam3smith 
this can be closed as the style has now been created: https://github.com/citation-style-language/styles/pull/2405

**Comment by rmzelle** [comment]
@jeccak, you can now find this style in the Zotero Style Repository at https://www.zotero.org/styles?q=id%3Ajournal-of-water-sanitation-and-hygiene-for-development.

**Comment by jeccak** [comment]
THANK YOU!!!!
