### ISSUE TITLE
o-bib

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/styles#1835]
The Open Access library journal <a href="https://www.o-bib.de/">o-bib</a> will use a standard style beginning in the next year:

" Ab Heft 1/2016 wird kein eigener Zitierstil mehr zugrunde gelegt, sondern der Chicago-Stil (deutsch, mit Fußnoten) verwendet."

Source: Südwest-Info: Mitteilungsblatt des VDB-Regionalverbands Südwest Nr. 28 (2015), S. 21. http://www.vdb-online.org/landesverbaende/sw/sw-info/

**Comment by zuphilip** [comment]
You can assign me here. I will do that next year, maybe after the first issue in the new format is published.

**Comment by rmzelle** [comment]
Looks like I can only assign issues to people with push access. But noted that you'd like to take this :).
