### ISSUE TITLE
biological-journal-of-the-linnean-society.csl error with books with multiple editors

### ISSUE THREAD

**Issue by ms609** [citation-style-language/styles#1842]
There's a minor bug in this style: "In:" is repeated in multi-editor books.  Example:

Verrecchia EP. 2000. Fungi and sediments. In: Riding R,,  In: Awramik SM, eds. Microbial sediments. Springer-Verlag, Berlin, 68–75.

should read

Verrecchia EP. 2000. Fungi and sediments. In: Riding R, Awramik SM, eds. Microbial sediments. Springer-Verlag, Berlin, 68–75.

(See http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1095-8339/homepage/ForAuthors.html )

I'm afraid I can't work out how to propose an edit to the file.

**Comment by ms609** [comment]
In addition, the title of the book [ Microbial sediments in the above example] should be italicized, but is not.

**Comment by rmzelle** [comment]
Yeah, that wasn't coded very well. Should be better now: https://github.com/citation-style-language/styles/commit/5c2263d5bc04bba9d11349970d1b84f578204f6e

**Comment by rmzelle** [comment]
I'll close this issue, but feel free to mention any other problems you encounter with this style here.

**Comment by ms609** [comment]
Many thanks for this!
