### ISSUE TITLE
Error in ferdinand-porsche-fern-fachhochschule.csl

### ISSUE THREAD

**Issue by christian-focke-mail-fernfh-ac-at** [citation-style-language/styles#1846]
In the bibliography, the year is printed "(, yyyy)" instead of "(yyyy)". This has to be due to one of the modifications Sebastian Karcher proposed to me during his review yesterday. Unfortunately, I am not a CSL expert myself, so all the modifications he proposed made sense to me and I implemented them all right away. -- Can anybody help with this issue?

Kind regards, Christian Focke

**Comment by rmzelle** [comment]
You can fix this by clicking the pencil/edit icon at https://github.com/citation-style-language/styles/blob/master/ferdinand-porsche-fern-fachhochschule.csl, and changing

```xml
  <macro name="year-date">
    <choose>
      <if variable="issued">
        <date variable="issued" prefix=", ">
          <date-part name="year"/>
        </date>
      </if>
      <else>
        <text term="no date" form="short" prefix=", "/>
      </else>
    </choose>
  </macro>
```

into

```xml
  <macro name="year-date">
    <choose>
      <if variable="issued">
        <date variable="issued">
          <date-part name="year"/>
        </date>
      </if>
      <else>
        <text term="no date" form="short"/>
      </else>
    </choose>
  </macro>
```

(remove the ` prefix=", "` twice)

also, change

```xml
      <group delimiter=", ">
        <group>
          <text macro="author-short"/>
          <text macro="year-date"/>
        </group>
        <group>
          <label suffix=" " variable="locator" form="short"/>
          <text variable="locator"/>
        </group>
      </group>
```

into

```xml
      <group delimiter=", ">
        <text macro="author-short"/>
        <text macro="year-date"/>
        <group>
          <label suffix=" " variable="locator" form="short"/>
          <text variable="locator"/>
        </group>
      </group>
```

(remove one of the groups)

**Comment by rmzelle** [comment]
In general, coding styles becomes much easier if all macros give output without any separating punctuation at the start or end (like ", " in this case). Then you only have to get these delimiters right when you call the macros.

**Comment by christian-focke-mail-fernfh-ac-at** [comment]
Thanks! (I would have seen the error myself if I hat used the visual CSL editor ...)

**Comment by rmzelle** [comment]
Glad to help!

**Comment by christian-focke-mail-fernfh-ac-at** [comment]
Sorry to say so, but the error is still there ...

**Comment by rmzelle** [comment]
> Sorry to say so, but the error is still there ...

How did you determine that? Are you using Zotero? The preview in the Zotero Style Repository (at https://www.zotero.org/styles?q=ferdinand ) doesn't seem to have updated, even though the style there /is/ up-to-date, and in my local testing the fix should have worked.
