### ISSUE TITLE
Created new style: Acta Ophthalmologica

### ISSUE THREAD

**Issue by eldulli** [citation-style-language/styles#187]
Hi,

I have created a new style: Acta Ophtalmologica: https://gist.github.com/3007415

I followed the instructions in https://github.com/citation-style-language/styles/wiki/Submitting-Styles

It is based upon APSA.

These are the author guidelines for the journal:
http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291755-3768/homepage/ForAuthors.html

Best regards,
Troels

**Comment by CorradoSoprano** [comment]
Hi.....How do i download the acta opthalmologica citation style......Please guide me stepwise as iam not good with computers...thank you

**Comment by rmzelle** [comment]
@CorradoSoprano, you should be able to right-click the style title at https://www.zotero.org/styles?q=acta-ophthalmologica and save it to disk.

**Comment by CorradoSoprano** [comment]
@rmzelle.....Thank you for your reply......Is it possible to import this link to ENDNOTE reference style manager...?

**Comment by adam3smith** [comment]
no. CSL styles don't work with Endnote. A list of all software using CSL can be found at http://citationstyles.org/

**Comment by CorradoSoprano** [comment]
@adam3smith  Thank you.:) I just know how to use Endnote..i'll try to learn the CSL style now..
