### ISSUE TITLE
Journal of Cachexia, Sarcopenia and Muscle

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/styles#1887]
The journal moved from Springer to Wiley:

http://onlinelibrary.wiley.com/journal/10.1007/13539.2190-6009/homepage/ForAuthors.html

 Is the reference style still `springer-vancouver-brackets`?

**Comment by matejovo** [comment]
There are some changes...
**`springer-vancouver-brackets:`**
Slifka MK, Whitton JL (2000) Clinical implications of dysregulated cytokine production. J Mol Med 78:74–80. doi: 10.1007/s001090000086
**requested:** (no pp. year at the end)
Slifka MK, Whitton JL. Clinical implications of dysregulated cytokine production. J Mol Med. 2000; doi:10.1007/s001090000086

**Comment by adam3smith** [comment]
I'm not sure what "article by DOI" means, but I'd not cite without the page number. But yeah, the citation style has changed entirely. We're basically looking at Vancouver (brackets) now, maybe a slight variant for online sources, but print sources look identical.

**Comment by POBrien333** [comment]
solved in https://github.com/citation-style-language/styles/pull/2822

**Comment by rmzelle** [comment]
Thanks, @POBrien333!
