### ISSUE TITLE
New Style Request for Biologia

### ISSUE THREAD

**Issue by matejovo** [citation-style-language/styles#1912]
[http://www.degruyter.com/view/j/biolog](http://www.degruyter.com/view/j/biolog)
Instructions for Authors online: http://www.degruyter.com/view/supplement/s13369563_Instructions_for_Authors.pdf

**Comment by adam3smith** [comment]
https://github.com/citation-style-language/styles/wiki/Requesting-Styles

We'd need more information and we'd want this via the Zotero forums, please.
