### ISSUE TITLE
Clarify RSpec error for license requirements

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#1955]
@inukshuk, https://travis-ci.org/citation-style-language/styles/builds/115852877 is rather unclear (the problem was an extra line break in the license text string, see https://github.com/citation-style-language/styles/pull/1949#discussion-diff-56002828)

To output the comparison between the expected string and the actual string, I'd like to use something like:

```
    it "must have a <rights> element" do
      expect(style.info).to have_rights
    end

    it "must have the correct Creative Commons BY-SA license URL" do
      if style.has_rights?
       expect(style.info.rights[:license]).to eq(CSL::Schema.default_license)
     end
    end
    
    it "must have the correct Creative Commons BY-SA license text" do
      if style.has_rights?
        expect(style.info.rights.text).to eq(CSL::Schema.default_rights_string)
      end
    end
```

in https://github.com/citation-style-language/styles/blob/master/spec/styles_spec.rb, but this currently fails with `undefined method `has_rights?'`, since there is no "has_rights" property, and I don't know how to test for the existence of a `<rights/>` element. Can I fix this in RSpec or does this require changes to csl-ruby?

**Comment by inukshuk** [comment]
You can do `style.info.has_rights?`

We could add a delegate to the style node [here](https://github.com/citation-style-language/styles/blob/master/spec/styles_spec.rb) so that the shortcut `style.has_rights?` works as well, but technically the rights element is a child of info.

(If the style has no info element at all, `style.info.has_rights?` would fail, but the 'has info' spec would fail too.)

**Comment by rmzelle** [comment]
Ah, that works. Is there a way to see which fields exist for "style" and "style.info"? I've looked at the csl-ruby source code, but I got a little lost there.

**Comment by inukshuk** [comment]
I think the best approach would be a combination of the [API docs](http://www.rubydoc.info/gems/csl/1.4.3/CSL/Style), the source code (especially the spec files), and experimenting in IRB (just load a given style and you have a style object to experiment with).

The thing to look out for in the source code is `attr_struct` and `attr_children`; the former is for CSL attributes, the latter for CSL child nodes -- these helpers generate all sorts of convenience methods, default values etc. to make life easier for the cite processor. With most nodes you should be able to access attributes using `[]` syntax and child nodes using `.` notation (but you can also look at all children using `.children`) or navigate using '>', e.g.: `style.macros['author'] > 'names' > 'name'` this would navigate to the 'name' node inside the 'names' node in the 'author' macro.

**Comment by rmzelle** [comment]
Great, thanks.
