### ISSUE TITLE
resuscitation.csl

### ISSUE THREAD

**Issue by Phil54520** [citation-style-language/styles#1961]
This is the updated resuscitation CSL file because the older one was dependent on elsevier style which is slightly different

**Comment by Phil54520** [comment]
<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" class="in-text" version="1.0" demote-non-dropping-particle="sort-only" page-range-format="minimal" default-locale="en-GB">
  <info>
    <title>British Journal of Anaesthesia</title>
    <title-short>BJA</title-short>
    <id>http://www.zotero.org/styles/british-journal-of-anaesthesia</id>
    <link href="http://www.zotero.org/styles/british-journal-of-anaesthesia" rel="self"/>
    <link href="http://www.zotero.org/styles/vancouver" rel="template"/>
    <link href="http://www.oxfordjournals.org/our_journals/bjaint/for_authors/index.html" rel="documentation"/>
    <author>
      <name>Charles Parnot</name>
      <uri>http://twitter.com/cparnot</uri>
      <email>charles.parnot@gmail.com</email>
    </author>
    <category citation-format="numeric"/>
    <category field="medicine"/>
    <issn>0007-0912</issn>
    <eissn>1471-6771</eissn>
    <summary>Same as Vancouver, but cites in superscript with citation numbers space-separated, and only 3 first authors listed before at al.</summary>
    <updated>2012-09-27T22:06:38+00:00</updated>
    <rights license="http://creativecommons.org/licenses/by-sa/3.0/">This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 License</rights>
  </info>
  <locale xml:lang="en">
    <terms>
      <term name="retrieved">available</term>
      <term name="section" form="short">sect.</term>
    </terms>
  </locale>
  <macro name="author">
    <names variable="author">
      <name sort-separator=" " initialize-with="" name-as-sort-order="all" delimiter=", " delimiter-precedes-last="always"/>
      <label form="long" prefix=", "/>
      <substitute>
        <names variable="editor"/>
      </substitute>
    </names>
  </macro>
  <macro name="editor">
    <group delimiter=": ">
      <choose>
        <if type="chapter paper-conference" match="any">
          <text term="in" text-case="capitalize-first"/>
        </if>
      </choose>
      <names variable="editor" suffix=".">
        <name sort-separator=" " initialize-with="" name-as-sort-order="all" delimiter=", " delimiter-precedes-last="always"/>
        <label form="long" prefix=", "/>
      </names>
    </group>
  </macro>
  <macro name="publisher">
    <group delimiter=": " suffix=";">
      <choose>
        <if type="thesis">
          <text variable="publisher-place" prefix="[" suffix="]"/>
        </if>
        <else>
          <text variable="publisher-place"/>
        </else>
      </choose>
      <text variable="publisher"/>
    </group>
  </macro>
  <macro name="access">
    <choose>
      <if variable="URL">
        <group delimiter=": ">
          <group delimiter=" ">
            <text term="retrieved" text-case="capitalize-first"/>
            <text term="from"/>
          </group>
          <text variable="URL"/>
        </group>
      </if>
    </choose>
  </macro>
  <macro name="accessed-date">
    <choose>
      <if variable="URL">
        <group prefix="[" suffix="]" delimiter=" ">
          <text term="cited"/>
          <date variable="accessed">
            <date-part name="year"/>
            <date-part name="month" prefix=" " form="short" strip-periods="true"/>
            <date-part name="day" prefix=" "/>
          </date>
        </group>
      </if>
    </choose>
  </macro>
  <macro name="container-title">
    <choose>
      <if type="article-journal article-magazine chapter paper-conference article-newspaper" match="any">
        <group delimiter=" ">
          <text variable="container-title" form="short" strip-periods="true" font-style="italic"/>
          <choose>
            <if variable="URL">
              <text term="internet" prefix="[" suffix="]" text-case="capitalize-first"/>
            </if>
          </choose>
        </group>
        <text macro="edition" prefix=" "/>
      </if>
      
      <else-if type="bill legislation" match="any">
        <group delimiter=", ">
          <group delimiter=". ">
            <text variable="container-title" form="short"/>
            <group delimiter=" ">
              <text term="section" form="short" text-case="capitalize-first"/>
              <text variable="section"/>
            </group>
          </group>
          <text variable="number"/>
        </group>
      </else-if>
      <else>
        <text variable="container-title" suffix="." form="short"/>
      </else>
    </choose>
  </macro>
  <macro name="title">
    <text variable="title"/>
    <choose>
      <if type="article-journal article-magazine chapter paper-conference article-newspaper" match="none">
        <choose>
          <if variable="URL">
            <text term="internet" prefix=" [" suffix="]" text-case="capitalize-first"/>
          </if>
        </choose>
        <text macro="edition" prefix=". "/>
      </if>
    </choose>
    <choose>
      <if type="thesis">
        <text variable="genre" prefix=" [" suffix="]"/>
      </if>
    </choose>
  </macro>
  <macro name="edition">
    <choose>
      <if is-numeric="edition">
        <group delimiter=" ">
          <number variable="edition" form="ordinal"/>
          <text term="edition" form="short"/>
        </group>
      </if>
      <else>
        <text variable="edition" suffix="."/>
      </else>
    </choose>
  </macro>
  <macro name="date">
    <choose>
      <if type="article-journal article-magazine article-newspaper" match="any">
        <group suffix=";" delimiter=" ">
          <date variable="issued">
            <date-part name="year"/>
          </date>
          <text macro="accessed-date"/>
        </group>
      </if>
      <else-if type="bill legislation" match="any">
        <group delimiter=", ">
          <date variable="issued" delimiter=" ">
            <date-part name="month" form="short" strip-periods="true"/>
            <date-part name="day"/>
          </date>
          <date variable="issued">
            <date-part name="year"/>
          </date>
        </group>
      </else-if>
      <else-if type="report">
        <date variable="issued" delimiter=" ">
          <date-part name="year"/>
          <date-part name="month" form="short" strip-periods="true"/>
        </date>
      </else-if>
      <else>
        <group suffix=".">
          <date variable="issued">
            <date-part name="year"/>
          </date>
          <text macro="accessed-date" prefix=" "/>
        </group>
      </else>
    </choose>
  </macro>
  <macro name="pages">
    <choose>
      <if type="article-journal article-magazine article-newspaper" match="any">
        <text variable="page" prefix=": "/>
      </if>
      <else>
        <text variable="page" prefix=" p. "/>
      </else>
    </choose>
  </macro>
  <macro name="journal-location">
    <choose>
      <if type="article-journal article-magazine" match="any">
        <text variable="volume" font-weight="bold"/>
      </if>
    </choose>
  </macro>
  <macro name="report-details">
    <choose>
      <if type="report">
        <text variable="number" prefix="Report No.: "/>
      </if>
    </choose>
  </macro>
  <citation collapse="citation-number">
    <sort>
      <key variable="citation-number"/>
    </sort>
    <layout delimiter=" " vertical-align="sup">
      <text variable="citation-number"/>
    </layout>
  </citation>
  <bibliography et-al-min="7" et-al-use-first="3" second-field-align="flush">
    <layout>
      <text variable="citation-number" suffix=". "/>
      <group delimiter=". " suffix=". ">
        <text macro="author"/>
        <text macro="title"/>
      </group>
      <group delimiter=" " suffix=" ">
        <text macro="editor"/>
        <text macro="container-title"/>
        <text macro="publisher"/>
        <group>
          <text macro="date"/>
          <text macro="journal-location" prefix=" "/>
          <text macro="pages"/>
        </group>
      </group>
      <text macro="report-details" suffix=". "/>
      <text macro="access"/>
    </layout>
  </bibliography>
</style>

**Comment by POBrien333** [comment]
fixed in https://github.com/citation-style-language/styles/pull/2823

**Comment by rmzelle** [comment]
@Phil54520, it looks like you never actually submitted your style, but this should now be fixed. Thanks!
