### ISSUE TITLE
Modern Humanities Research Association csl error in pandoc

### ISSUE THREAD

**Issue by colcord** [citation-style-language/styles#1969]
Hi, I've been troubleshooting a formatting question in pandoc. I downloaded the latest MHRA csl yesterday to see if that would help. It now crashes pandoc-citeproc. I kept the MHRA csl that I downloaded on 17 Jan which works fine.

pandoc-citeproc: ParseError {errorContexts = [], errorMessage = "Failed reading: takeWhile1", errorPosition = 51:5}
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1

[the pandoc discussion](https://groups.google.com/d/msg/pandoc-discuss/IBf4wGbbFhk/rawUvL42BAAJ).

I get the above error even with Nick's MWE which I quote below:

Thanks in advance

~~~
pandoc -s -F pandoc-citeproc -t markdown-citations-markdown_in_html_blocks << EOT

Blah [@cit, 34-45].

Blah [@cit2, 56-67].

Blah [@cit, 67-78].

Blah [@cit2, 78-89].

---
csl: modern-humanities-research-association.csl

references:
- id: cit
  type: book
  author:
  - family: Lastname
    given: Firstname
  issued:
  - year: '2016'
  title: Long title; that could be abbrev
  title-short: Abbrev
  publisher: Fictional
  publisher-place: London
  language: en-en

- id: cit2
  type: book
  author:
  - family: Surname
    given: Firstname
  issued:
  - year: '2016'
  title: Another long title; that could be short
  publisher: Fictional
  publisher-place: London
  language: en-en
...
EOT
~~~

**Comment by adam3smith** [comment]
It looks like @nickbart1980 solved it over there. 
For future reference: we're happy to take reports of style errors (i.e. wrong formatting and the like here), but if pandoc or any processor throws an error with one of our styles, it's always their bug (or, as in this case, a user error with an unclear error message): all styles on the repository are validated automatically and so by definition work with a properly specified processor.

**Comment by colcord** [comment]
Thanks. Sorry about that. As Nick said, I was overly hasty in filing a bug
report here. Frank

On 21 March 2016 at 11:48, Sebastian Karcher <notifications@github.com>
wrote:

> It looks like @nickbart1980 <https://github.com/nickbart1980> solved it
> over there.
> For future reference: we're happy to take reports of style errors (i.e.
> wrong formatting and the like here), but if pandoc or any processor throws
> an error with one of our styles, it's always their bug (or, as in this
> case, a user error with an unclear error message): all styles on the
> repository are validated automatically and so by definition work with a
> properly specified processor.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/issues/1969#issuecomment-199238064>
>



-- 
frank@colcord.net, cell: +447763116793, skype: colcord,
if you ever get no response, please send to: fcolcord@gmail.com
