### ISSUE TITLE
Jorunal of Nuclear Medicine

### ISSUE THREAD

**Issue by sumatrabali** [citation-style-language/styles#1982]
I'm using Journal of Nuclear Medicine csl. However, the format in the references is not correct, there should be no DOI information at the end. And the inline citations are incorrect as well. Instead of "1" in superscript format, it should be "(1)".

I tried to change the style by clicking on "Edit the style" on this site: **http://editor.citationstyles.org/about/**
However, nothing happens, the link doesn´t work. Can anyone please help to correct the style of this journal or give some instructions how I can change it?

Thank you

**Comment by adam3smith** [comment]
The style currently just links to the AMA style, which is what the [journal's instructions](http://interactive.snm.org/docs/jnm_infoauth.pdf) say. If you want to edit it, edit that style in the editor instead (and give it a new name under info).

We'll fix this eventually, but might take a little.

**Comment by sumatrabali** [comment]
Thank you for the prompt reply. I tried to change the style hundret times but the link "edit the style" doesn´t work! I would be very grateful if someone could fix the problem as I have to submit the manuscript in 3 days.

**Comment by adam3smith** [comment]
did you understand that you'd need to edit the style "American Medical Association", not the Journal of Nuclear Medicine style?

**Comment by sumatrabali** [comment]
Now I got it! Thank you so much! I could change the style in include it into zotero!

**Comment by adam3smith** [comment]
Great. I'm leaving the issue open so we remember to actually fix the JONM style.

**Comment by rmzelle** [comment]
(this is now fixed)
