### ISSUE TITLE
ACM SIG should include DOI

### ISSUE THREAD

**Issue by GeorgLink** [citation-style-language/styles#1996]
The [ACM SIG template](http://www.acm.org/publications/article-templates/proceedings-template.html/)  (Jan. 23, 2015) requires DOIs to be included.

Example:

> [1]   Bowman, M., Debray, S. K., and Peterson, L. L. 1993. Reasoning about naming systems. _ACM Trans. Program. Lang. Syst_. 15, 5 (Nov. 1993), 795-825. DOI= http://doi.acm.org/10.1145/161468.16147. 

These CSL need to be updated:
ACM SIG Proceedings ("et al." for 15+ authors) (2014-09-06 22:02:33)
ACM SIG Proceedings ("et al." for 3+ authors) (2014-09-06 22:02:33)

PS: sorry for posting it in the wrong place first: https://github.com/citation-style-language/csl-editor/issues/194

**Comment by adam3smith** [comment]
(confirmed here too ;))

**Comment by rmzelle** [comment]
(fixed)

**Comment by GeorgLink** [comment]
Thanks! I'll give it a try next time I have to use the format.
