### ISSUE TITLE
APA style support for `working paper`

### ISSUE THREAD

**Issue by darrenleeweber** [citation-style-language/styles#2003]
Does the [APA style](http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fapa) support a "working paper"?

There is documentation on this at http://citesource.trincoll.edu/apa/apaworkingpaper.pdf

This is an example from that documentation:
```
Imberman, S., Kugler, A.D., & Sacerdote, B. (2009). Katrina’s children: evidence on the structure 
of peer effects from hurricane evacuees (Working Paper No. 15291). Retrieved from 
National Bureau of Economic Research website: http://www.nber.org/papers/w15291
```

**Comment by adam3smith** [comment]
working papers are treated as reports in CSL. That works nicely for APA, which tells us to do just that on p. 206 of the manual. The guide above is incorrect, by the way. The title should be in italics. It should also probably include publisher (NBER) and place (Washington, DC).

Beyond that, we ask that people approach their reference manager of choice for support. We're too small to provide customer support for the hundreds of thousands of users of the various projects using CSL.

**Comment by darrenleeweber** [comment]
FYI, this issue was created as a prelude to possible work on creating a new PR on this repo.

**Comment by rmzelle** [comment]
> Where do we go for clarification on whether a style supports a document type and whether a modification or new style could be submitted to this repo?

CSL currently doesn't specify what document types go well with what CSL item types, but most CSL repository styles are based around the document type mappings used by Zotero (http://aurimasv.github.io/z2csl/typeMap.xml) and Mendeley (http://support.mendeley.com/customer/portal/articles/364144-csl-type-mapping).

We welcome styles for published style guides and journals, but try hard to limit the number of (often arbitrary) variants for a give style. See https://github.com/citation-style-language/styles/wiki/Criteria-for-Accepting-Styles for more details. We accept modifications if they improve the style.

**Comment by adam3smith** [comment]
So, in line with that, the best way to see if a style works for an item type is to test out the style and see if it works. If it doesn't, it may require fixing/updating. For the big styles (MLA, Chicago, APA, Vancouver) you should always look at the original manual. Online distillations are frequently wrong. I

Also, at a minimum for Zotero and Mendeley (and ideally for all larger and/or commercial products), we really prefer people to report any issues there first. Many times, the problem is with the mapping, the CSL processor involved, etc. -- much easier to start there and if it turns out it's a CSL issue, then either take it upstream from there (or ask them to). 

If you do want to contribute directly (which is very much welcome), a good way to start would be working on new styles or confirmed errors (check for the "style errors" and "style requests" labels among open issues) rather than starting with something like APA, which has gotten a lot of attention from both CSL and APA style experts.

**Comment by darrenleeweber** [comment]
@rmzelle - thanks for the tips about doc-type mappings to CSL fields, that's SO what I need right now, i.e.
  - document type mappings used by Zotero (http://aurimasv.github.io/z2csl/typeMap.xml) and
  - Mendeley (http://support.mendeley.com/customer/portal/articles/364144-csl-type-mapping)

So now I'm curious about whether there are any open-source ruby projects to support these mappings (looks like a simple hash data structure).  Perhaps more importantly, whether there are any formal schema to define these mappings and whether library catalog systems and/or publishing houses conform to any such schema?  (A json-schema for doc-types like book, article, etc. is what I'm considering.)

**Comment by rmzelle** [comment]
It's currently up to the individual reference managers to maintain their own mapping, and I'm not aware of any that rely on a schema. The Zotero mapping is generated with https://github.com/aurimasv/z2csl.

**Comment by adam3smith** [comment]
citeproc-JS uses a format we call citeproc-JSON or sometimes CSL JSON. I don't believe there is a schema, but it's used almost verbatim by Datacite in their API and a similar version is used by CrossRef.

As for ruby -- there is citeproc-rubyhttps://github.com/inukshuk/citeproc-ruby, though I'm not sure what "supports these mappings" exactly means.

**Comment by darrenleeweber** [comment]
Perfect, thanks!  We are using citeproc-ruby.  We are looking at expanding support for more doc-types, so the Zotero example [1,2] of mapping UI label -> doc-type field -> CSL field is perfect and it looks like the JSON-SCHEMA [3] is a useful validator for the citation data generated by any similar mapping into CSL.

[1] https://github.com/aurimasv/z2csl
[2] http://aurimasv.github.io/z2csl/typeMap.xml
[3] https://github.com/citation-style-language/schema#csl-json-schema

**Comment by rmzelle** [comment]
> citeproc-JS uses a format we call citeproc-JSON or sometimes CSL JSON. I don't believe there is a schema, but it's used almost verbatim by Datacite in their API and a similar version is used by CrossRef.

Yeah, but that doesn't prescribe which item types may have which metadata fields, which I think is what @darrenleeweber is after.

**Comment by darrenleeweber** [comment]
True, the consistency of metadata fields seems to be a problem.  The Zotero and Mendeley examples are possibly inconsistent?  For example, compare the CSL fields used in
 - http://aurimasv.github.io/z2csl/typeMap.xml#map-report vs.
 - http://support.mendeley.com/customer/portal/articles/364144-csl-type-mapping (Working Paper at the bottom of the page)

That inconsistency (e.g. DOI vs URL) might be OK.  I'm curious if there is a schema document that specifies the required and optional fields for a CSL "report".  For example, if we have a JSON API that receives any old JSON payload, how do we validate that the data will map into a CSL item type?  If say the JSON payload has a field label like 'type' with a value of 'report', can the rest of that JSON payload be validated using json-schema for a CSL 'report' document?

In the CSL documentation (and possibly schema), how do we find/identify all the item types and all the fields that belong to any particular CSL item type?  For example, how do you start to build the CSL item type column at the top of this page: http://aurimasv.github.io/z2csl/typeMap.xml#map-report ?

**Comment by rmzelle** [comment]
> In the CSL documentation (and possibly schema), how do we find/identify all the item types and all the fields that belong to any particular CSL item type?

You can't. CSL defines its a set of item types and a set of fields, but as I said above, CSL doesn't specify which fields go with which item types.

**Comment by darrenleeweber** [comment]
So, when Zotero creates the mapping, are they also creating a CSL definition for each of the items that map into CSL fields?  We are trying to work with `apa.csl`, `mla.csl` and `chicago-author-date.csl`, without creating custom CSL, unless it seems necessary.

**Comment by rmzelle** [comment]
> does Zotero create a report.csl

You might be misunderstanding how things work. A ".csl" file is always a CSL citation style, which typically supports a variety of item types (CSL styles for journals typically support at minimum books, chapters, and journal articles, while CSL styles for popular style guides like APA are coded to support a much wider range of item types). You would never create a ".csl" file for a single item type.

**Comment by rmzelle** [comment]
> So, when Zotero creates the mapping, are they also creating a CSL definition for each of the CLS items and it's CSL fields?

Zotero has a set of Zotero item types and Zotero fields. An internal schema describes which Zotero item types have which Zotero fields. When rendering citations and bibliographies, Zotero maps these Zotero item types and Zotero fields onto their CSL equivalents, following the mapping I linked to.

Once the metadata has been transformed from the Zotero data model to the CSL data model, the latter is fed to Zotero's CSL processor (the open source citeproc-js), which renders it according to the selected CSL style.

Does that clarify things a little?

**Comment by adam3smith** [comment]
As a bit of additional context, both Zotero and Mendeley are somewhat locked into their data model; Zotero even more than Mendeley, but it's also closer to getting out of that. 
So, for example, neither supports the dataset item type that CSL has, though both know they should. Zotero doesn't have a DOI for anything but journal articles, though they obviously know they should. etc.

**Comment by adam3smith** [comment]
also -- you're aware of the xbiblio listserv? That's really the best place for more fundamental questions like these. All (or at least most) citeproc developers as well as the key reference manager stakeholders are present there, in addition to other people active on CSL. You're more likely to get additional input from people with experience actually implementing citeprocs there.

**Comment by darrenleeweber** [comment]
Ah, so I need to understand the set of CSL item types and the set of CSL item fields and how each `.csl` handles them.  Like, how does `apa.csl` handle the CSL item type for `report`?  When I read the `apa.csl`, that question is not very easy to answer.

**Comment by adam3smith** [comment]
that actually won't work well. CSL is designed to rely heavily on fallbacks, i.e. either items are cited independent of item type (that's actually the case for author in APA -- the conditional for report only kicks in in a `substitute` condition) or they're caught by an `<else>` or and `<if>` with `match="none"` condition. The whole point is that you don't necessarily have to think through every item type one-by-one, especially for well-written styles. The way CSL styles are written, it is impossible to reverse engineer required fields. 
To give another example, many styles call the publisher and publisher-place variable for every item type, but in fact display incorrectly where those variables are present for journal articles, for example. So they rely on restrictions imposed on the input data. That, too, is by design (though problematic in this particular example, but that's a different story).

**Comment by adam3smith** [comment]
(You'll really be better of writing up what you actually have in mind as an endproduct and sending it to xbiblio)

**Comment by darrenleeweber** [comment]
Thanks so much for very helpful commentary on this issue.  I may enough to see my way through this now.  It's not as simple as I first imagined, but so long as the authors of the `.csl` do it well (according to specs), it solves a lot of headaches.  The trick for us is simply in mapping our doc-types and doc-fields into reasonable CSL doc-types and doc-fields.  Although this may not be simple, once it's done we benefit from CSL formatting.  I can only imagine the process (politics) involved in defining the CSL types and variables.

**Comment by rmzelle** [comment]
(our mailing list is at https://lists.sourceforge.net/lists/listinfo/xbiblio-devel )

**Comment by juliakate** [comment]
you don't have to follow certain guides. It's the 21st century. Everything is automated. If you want to use APA style, just search the internet for [APA citation generator,](http://www.researchomatic.com/apa-citation-generator/) you would get plenty of tools to get the job done. It's easy, fast and accurate.
