### ISSUE TITLE
apa.csl has no space after parentheses holding translator.

### ISSUE THREAD

**Issue by reagle** [citation-style-language/styles#2019]
Using the current apa.csl I am missing a space after the closing parenthesis: "...Trans.)ZEIT Wissen, ...". I can apparently remedy this by adding a space after the suffix in the `<macro name="secondary-contributors">`.

```
  <macro name="secondary-contributors">
    <choose>
      <if type="article-journal chapter paper-conference entry-dictionary entry-encyclopedia" match="none">
        <group delimiter=", " prefix=" (" suffix=") ">
          <names variable="container-author" delimiter=", ">
            <name and="symbol" initialize-with=". " delimiter=", "/>
            <label form="short" prefix=", " text-case="title"/>
          </names>
          <names variable="editor translator" delimiter=", ">
            <name and="symbol" initialize-with=". " delimiter=", "/>
            <label form="short" prefix=", " text-case="title"/>
          </names>
        </group>
      </if>
    </choose>
  </macro>
```

**Comment by rmzelle** [comment]
Yeah, something is wrong there.

@adam3smith, see https://github.com/citation-style-language/styles/blob/caef31625397da134c0db63893970f30f3b41308/apa.csl#L61 and https://github.com/citation-style-language/styles/blob/caef31625397da134c0db63893970f30f3b41308/apa.csl#L521. Can you check in the APA manual whether this needs to be a space?

**Comment by reagle** [comment]
@rmzelle, I'm not familiar with the manual or what you are asking @adam3smith to check, but presently you can find a [copy of the manual as a PDF](https://www.hse.ru/data/2013/12/06/1336424472/APA%20Manual%206th%20Edition%20(1).pdf).

**Comment by adam3smith** [comment]
sorry, somehow I didn't seen this. I do have a copy of the manual (though I'm glad someone put it up!), thanks. Looking now.

**Comment by adam3smith** [comment]
Fixed in the main version. Will push it out to the other versions asap. I'm using a comma and space now, which seemed more in line with APA. Since this is an exceedingly rare situation (it only occurs with items that have a container-title and a secondary contributor, but aren't a website, blog, chapter, or conference paper), there's no clear guidance in the manual.

**Comment by reagle** [comment]
Thanks!

**Comment by rmzelle** [comment]
Thanks both!

@reagle, it's probably clear now, but my question was what the delimiter should be (space, comma-space, or something else).
