### ISSUE TITLE
Regional University  Citation Style

### ISSUE THREAD

**Issue by Neucir** [citation-style-language/styles#2058]

**Comment by adam3smith** [comment]
Not clear what you're trying to do here. Could you explain?

**Comment by Neucir** [comment]
Hello
I have created a citation style for my university, and i want to find him in the mendeley search tool.

The style has been uploaded to the site(my account) but i dont know how to proceed.

Thanks.

**Comment by rmzelle** [comment]
@Neucir, we have instructions for contributing styles here: https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md

Let us know if you need more help than that.

**Comment by rmzelle** [comment]
Covered by #2060.
