### ISSUE TITLE
Citation Style Language “if then”

### ISSUE THREAD

**Issue by autumnrustle** [citation-style-language/styles#2092]
try to modificate csl style (Specification) fore Zotero. I don't know how to do next: if I have more then 4 authors, I need to insert one text.

How can I do it? I try next, but it is not work...
```
<else-if type="chapter paper-conference" match="any">
<choose>
    <if variable="name" et-al-min="4">
        <text value="ONE TEXT"/>
    </if>
</choose>
</else-if>
```

**Comment by rmzelle** [comment]
Can you give an example of what you're trying to achieve? What would the actual reference look like?

**Comment by autumnrustle** [comment]
@rmzelle It turned out it was a mistake in the standard...

But the problem was interesting

**Comment by rmzelle** [comment]
Okay. I'll close this, then.
