### ISSUE TITLE
Update universidade-estadual-do-oeste-do-parana-programa-institucional-de-bolsas-de-iniciacao-cientifica

### ISSUE THREAD

**Issue by Neucir** [citation-style-language/styles#2158]
Hello

I have a newer version of this csl style, how do i update the archive in zotero style repository?

thanks.

**Comment by rmzelle** [comment]
@Neucir, we have instructions on updating existing styles at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style

**Comment by rmzelle** [comment]
(coverered by #2159)
