### ISSUE TITLE
New style for imstat package for Statisticians

### ISSUE THREAD

**Issue by Bo-Ning** [citation-style-language/styles#2174]
If anyone could code up the style for imstat style for statistics community, I would really appreciate it!

Here's the citation style link: http://www.e-publications.org/ims/support/ims-instructions.html

**Comment by rmzelle** [comment]
Feel free to leave this issue open, but you can increase your chances of someone helping you by posting your style request to the Zotero forums, and by providing an example of the style format, as described at https://github.com/citation-style-language/styles/wiki/Requesting-Styles.

**Comment by POBrien333** [comment]
@Bo-Ning 
I've created a style for the IMS publishing house and will create dependents for the individual journals, too: https://github.com/citation-style-language/styles/pull/2824

**Comment by bwiernik** [comment]
This can be closed
