### ISSUE TITLE
Discovery Medicine

### ISSUE THREAD

**Issue by dancindoc** [citation-style-language/styles#2181]
New style request

The "Information for Authors" document can be found at
http://www.discoverymedicine.com/about/information-for-authors-of-discovery-medicine/ . The document contains information on the preparation of a manuscript including how to cite and list references. 
EndNote output style for Discovery Medicine at ftp://support.isiresearchsoft.com/pub/pc/styles/endnote4/Discovery%20Medicine.ens or the Reference Manager output style at ftp://support.isiresearchsoft.com/RefMan/Styles/Discovery%20Medicine.os . In the software settings, please use "Abbreviations 2" for abbreviating journal names in the reference list.

> Reference and Citation
> 
> Reference list:
> 
> An article is followed by generally no more than 75 references. A full citation of a reference includes all authors in the format of PubMed listing (see the example below) (if there are more than 20 authors, abbreviate the list as “first 20 authors, et al.”), article title, the journal’s name (PubMed abbreviations, in italic), volume number (issue number in parentheses), page numbers, and year of publication.
> 
> References are listed according to the alphabetical order of the last name of the first author and publishing year (older year first if the same author but different years). If there are multiple references with the same first author and same publishing year, please add a letter after the year to differentiate the references (such as 2004a, 2004b, 2004c, etc.).
> 
> Examples of references and the order of references in the reference list:
> 
> Boisvert WA. A leukocyte homologue of the IL-8 receptor CXCR-2 mediates the accumulation of macrophages in atherosclerotic lesions of LDL receptor-deficient mice. J Clin Invest 101(2):353-363, 2005.
> Boisvert WA, Santiago R, Curtiss LK, Terkeltaub RA. A leukocyte homologue of the IL-8 receptor CXCR-2 mediates the accumulation of macrophages in atherosclerotic lesions of LDL receptor-deficient mice. J Clin Invest 101(2):353-363, 1998.
> Boisvert WA, Santiago R, Curtiss LK, Terkeltaub RA. A leukocyte homologue of the IL-8 receptor CXCR-2 mediates the accumulation of macrophages in atherosclerotic lesions of LDL receptor-deficient mice. J Clin Invest 101(2):353-363, 2003a.
> Boisvert WA, Santiago R, Curtiss LK, Terkeltaub RA. A leukocyte homologue of the IL-8 receptor CXCR-2 mediates the accumulation of macrophages in atherosclerotic lesions of LDL receptor-deficient mice. J Clin Invest 101(2):353-363, 2003b.
> 
> For bibliography software EndNote or Reference Manager users, if your version of the program does not come with the reference output style for Discovery Medicine already installed, you may click here to download it for EndNote and click here to download it for Reference Manager.
> 
> Examples of reference citations in the article text:
> 
> A reference is cited in the article text as “First Author’s Last Name et al., year” (in parentheses) in the following format:
> (Doe, 2009), if there’s only one author
> (Doe and Doe, 2009), if there are two authors
> (Doe et al., 2009), if there are three or more authors
> (Doe, 2009; Doe et al., 2009), if two or more references are cited at the same time (the sequence of the references cited could be based on relevance)
>

**Comment by rmzelle** [comment]
Thanks. In general, you'll have better luck following the instructions at https://github.com/citation-style-language/styles/wiki/Requesting-Styles (see especially point 3, which makes it much easier for us to quickly check whether there is an existing CSL style that is close to what you need).

**Comment by damnation333** [comment]
@rmzelle this could be closed as we've merged it into the repo: https://github.com/citation-style-language/styles/pull/2399

**Comment by rmzelle** [comment]
@dancindoc, you can now find this style in our CSL repository here, and also e.g. in the Zotero Style Repository (https://www.zotero.org/styles?q=id%3Adiscovery-medicine).
