### ISSUE TITLE
Priority: CSL Style Editor is dependent on Flash Player (fully depreciated in Chrome 53)

### ISSUE THREAD

**Issue by dsifford** [citation-style-language/styles#2193]
Hi there,

I hope this is being posted in the correct location.

I noticed that, in order to download custom CSL after using the CSL style editor, the user must have Flash Player installed.

![image](https://cloud.githubusercontent.com/assets/5240018/18152235/667e1c1c-6fc2-11e6-99dd-27fd25b4d67f.png)

Chrome 53 completely blocks Flash Player due to several security reasons. The other browsers are not far behind. Adobe is actively trying to kill flash as well.

Consider removing this dependency in the near future.

Thanks so much 😄

**Comment by adam3smith** [comment]
Closing as duplicate: https://github.com/citation-style-language/csl-editor/issues/179
(though the save to disk button does work in Chrome 53. Flash is not actually entirely disabled, see https://chrome.googleblog.com/2016/08/flash-and-chrome.html)

**Comment by dsifford** [comment]
@adam3smith ah, sorry about that. Didn't see that one.

Of note, I meant Chrome 54.

![image](https://cloud.githubusercontent.com/assets/5240018/18153900/60d1a340-6fce-11e6-9b46-a027dc78ec8e.png)

I can confirm that the save button _does not_ work with Chrome 54.
