### ISSUE TITLE
Update DOI display from latest Crossref guidelines?

### ISSUE THREAD

**Issue by adunning** [citation-style-language/styles#2197]
The [Crossref DOI display guidelines](http://www.crossref.org/02publishers/doi_display_guidelines.html) were recently updated: the format `doi:10.NNNN/doisuffix` is now discouraged, recommending instead that all DOIs be displayed with a resolver, e.g. `https://doi.org/10.NNNN/doisuffix`. There are many styles, of course, that use either the old format or the longer resolver address; it will probably be some time before they are updated, but in the meantime, I am finding that editors (at least the ones who want to include DOIs at all) prefer the newer guidelines.

As this is a purely technical matter, I think it would be sane to assume that the latest Crossref guidelines should overrule older style guides, but this is obviously open to discussion.

**Comment by adam3smith** [comment]
as you know, we're doing that for APA and there, in spite of clear statements by APA itself, we're getting a ton of complaints -- so I'd be quite hesitant to do it with Chicago Manual, where we wouldn't be able to point to similar statements by the editors. Which other styles do you have in mind?

**Comment by adunning** [comment]
Interesting that has happened with APA; not what I would have expected, and given that it's probably best not to change it for Chicago for now. What about the case of e.g. MHRA, which still uses the old `http://dx.doi.org/` resolver? I can't imagine anyone would complain about that being shortened.

**Comment by adam3smith** [comment]
> I can't imagine anyone would complain about that being shortened.

you need to widen your imagination -- it happens all the time -- but that one I'm willing to fight. We should use doi.org/ as a resolver across the board. Do we use dx.doi.org anywhere but in MHRA?
I'd gladly take a PR for this -- I'm super busy right now.

**Comment by rmzelle** [comment]
> Do we use dx.doi.org anywhere but in MHRA?

In quite a few styles (search for "dx.doi"):

```
/Users/rintzezelle/Documents/CSL/styles/advances-in-alzheimers-disease.csl
59: <text variable="DOI" prefix="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/american-journal-of-plant-sciences.csl
106: <text variable="DOI" prefix="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/american-society-of-civil-engineers.csl
8: <link href="http://dx.doi.org/10.1061/9780784478998.ch17" rel="documentation"/>
9: <link href="http://dx.doi.org/10.1061/9780784479018.ch05" rel="documentation"/>
/Users/rintzezelle/Documents/CSL/styles/association-for-computing-machinery.csl
100: <text variable="DOI" prefix=" DOI:http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/colombian-journal-of-anesthesiology.csl
24: <text variable="DOI" prefix="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/el-profesional-de-la-informacion.csl
114: <text value="http://dx.doi.org/" font-style="italic"/>
/Users/rintzezelle/Documents/CSL/styles/french1.csl
75: <text value="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/french2.csl
75: <text value="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/french3.csl
92: <text value="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/french4.csl
80: <text value="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/institut-national-de-sante-publique-du-quebec-napp.csl
85: <text value="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/journal-of-genetic-engineering-and-biotechnology.csl
25: <text variable="DOI" prefix="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/modern-humanities-research-association-author-date.csl
263: <text variable="DOI" prefix=" &lt;http://dx.doi.org/" suffix="&gt;"/>
/Users/rintzezelle/Documents/CSL/styles/modern-humanities-research-association.csl
413: <text variable="DOI" prefix=" &lt;http://dx.doi.org/" suffix="&gt;"/>
/Users/rintzezelle/Documents/CSL/styles/national-institute-of-health-research.csl
23: <text variable="DOI" prefix="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/psychiatric-clinics-of-north-america.csl
25: <text variable="DOI" prefix="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/radiopaedia.csl
405: <text variable="DOI" prefix="&lt;a href=&quot;http://dx.doi.org/" suffix="&quot; target=&quot;_blank&quot;&gt;"/>
/Users/rintzezelle/Documents/CSL/styles/revista-virtual-de-quimica.csl
151: <text variable="DOI" prefix="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/revue-archeologique-du-centre-de-la-france.csl
131: <text value="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/technische-universitat-dresden-betriebswirtschaftslehre-logistik-author-date.csl
61: <text variable="DOI" prefix="&lt;https://dx.doi.org/" suffix="&gt;"/>
/Users/rintzezelle/Documents/CSL/styles/technische-universitat-dresden-historische-musikwissenschaft-note.csl
415: <text value="http://dx.doi.org/"/>
/Users/rintzezelle/Documents/CSL/styles/water-alternatives.csl
346: <text variable="DOI" prefix="www.dx.doi.org/"/>
```

The last one even uses "www.dx.doi.org/", which surprisingly works. I don't see any reasons not to switch all these to "http://doi.org". CrossRef doesn't have any guidelines on pushing "https" over "http"?

**Comment by adam3smith** [comment]
no guidance of https over http, no. Agree on replacing this across the board.

**Comment by mfenner** [comment]
No official statement from Crossref or DataCite for using "https://doi.org" over "http://doi.org", but like everyone else on the net we are moving to "https" as default. @afandian, any comment from you regarding this?

**Comment by afandian** [comment]
Using HTTPS is best practice, and we generally prefer the `doi.org` resolver. All DOIs that I'm producing (e.g. those in Event Data) are `https://doi.org`. We recently collaborated with Wikimedia to convert all of their DOIs to HTTPS. 

Sorry there's no official Crossref guidance.

**Comment by rmzelle** [comment]
> Sorry there's no official Crossref guidance.

@afandian, it would be great if you could put a statement at http://www.crossref.org/02publishers/doi_display_guidelines.html recommending HTTPS for its general benefits concerning privacy and security, just so we have something official to point to. Once that's up we'd be happy to convert all styles to use "https". I also noticed a typo in the sentence: "We also recommend that the formerly used the “DX” in the http://dx.doi.org be dropped." (the "the" in "formerly used the 'DX'" should be deleted)

And while I have your attention, do you happen to know if NCBI PubMed has already been contacted about their use of non-hyperlinked DOIs in their abstracts? See e.g. http://www.ncbi.nlm.nih.gov/pubmed/21131518, which still uses the plain text "doi: 10.1128/AEM.02132-10". It's one of my pet peeves.

**Comment by afandian** [comment]
Thanks for pointing those things out @rmzelle . I'll see what I can do.

**Comment by afandian** [comment]
We've now published something on this: http://blog.crossref.org/2016/09/new-crossref-doi-display-guidelines.html

**Comment by adunning** [comment]
Thanks, Joe, for doing that!

I think that the new guidelines are definitive enough that they can be said
to override the old advice still repeated in style guides such as Chicago,
should anyone complain. Do you suppose it would be sufficient if this were
applied across the board, with an explanatory forum post linking to this?

**Comment by rmzelle** [comment]
> Do you suppose it would be sufficient if this were
> applied across the board, with an explanatory forum post linking to this?

Yes, I'll update the existing CSL styles to use HTTPS DOI links.

**Comment by adunning** [comment]
Brilliant; thanks! Happy to provide support if anyone does see it as being
in violation of the style guides, but I don't think it will be a problem as
long as it is made clear that the doi: style was also from Crossref, and
not academic editors.

**Comment by adam3smith** [comment]
no, those are different issues: 
Rintze is just referring to updating the existing linked DOIs to https. 
I am, unfortunately, not convinced that we should move ahead with switching otherwise labeled DOIs over to linked ones, even if it's the right thing to do for citation styles:
For one, I just don't have the patience to deal with yet another user group complaining about this. Between Zotero and Mendeley I have had to point this out for APA at least 50 times.
Beyond that (which applies to Chicago, MLA, MHRA, NLM), it's less clear-cut for journal styles, since most journals requiring DOIs in submitted citations do post-processing anyway and use them to create linked citations of some type. Changing the structure here may actually mess with their workflows.

**Comment by adunning** [comment]
Right, I see. You know best!

**Comment by rmzelle** [comment]
> Rintze is just referring to updating the existing linked DOIs to https.

Right. We just made this change in the CSL styles repo for all existing styles that used "http://doi.org". Thanks all!
