### ISSUE TITLE
When will the next stable release be available? 

### ISSUE THREAD

**Issue by bartsch-dev** [citation-style-language/styles#2221]
The last stable version was in 13-Sep-2013 ([according to MavenCentral](http://search.maven.org/#search|ga|1|citationstyles)). 
When can I expect another stable release or do I have to use the snapshots (for both, styles and locales)?

**Comment by rmzelle** [comment]
@michel-kraemer, thoughts?

@bartsch-dev, just as background, the MavenCentral versions were put up by Michel who created http://michel-kraemer.github.io/citeproc-java/. See http://xbiblio-devel.2463403.n2.nabble.com/Styles-and-locales-as-Java-jar-in-Maven-Central-td7578700.html as well. We (the maintainers of the GitHub CSL styles repo) don't really touch it, and we assume that most developers will just use the latest version in the "master" branch. But maybe Michel can update the MavenCentral versions (or snapshots).

**Comment by michel-kraemer** [comment]
The "stable" version is indeed 1.0. The version number corresponds to the CSL specification 1.0. The current version of the spec is 1.0.1. New styles are added continuously to this repo here. I have set up an automated process that updates the snapshot 1.0.1 every time a new style is added or edited.

The whole idea was to use the same version number for the spec and the styles published to Maven central. I know this is not optimal and possibly confusing. Any idea how improve this is appreciated.

**Comment by rmzelle** [comment]
@michel-kraemer, it looks like the snapshots haven't updated in a while:

http://mavensearch.io/repo/org.citationstyles/styles (19 Sep 2015)
http://mavensearch.io/repo/org.citationstyles/locales (17 Sep 2015)

**Comment by michel-kraemer** [comment]
Yes, they have been updated. This is the correct site:
https://oss.sonatype.org/content/repositories/snapshots/org/citationstyles/styles/

mavensearch.io is probably not up to date. I don't know how often they update their cache.

**Comment by rmzelle** [comment]
@michel-kraemer, okay, thanks.

@bartsch-dev, so, in short, the "stable" release is extremely outdated and shouldn't be used. The CSL style repository has a fairly extensive set of tests to make sure that pull requests are only merged when everything checks out, so breaking changes in the snapshots should be extremely rare.

**Comment by bartsch-dev** [comment]
This works for me! Thanks.

What you could do is to release a monthly build with the date as a suffix or something like that (but for me it isn't necessary).

**Comment by rmzelle** [comment]
> What you could do is to release a monthly build with the date as a suffix or something like that (but for me it isn't necessary).

Yeah, that would be fine with us.

**Comment by koppor** [comment]
I also like the idea with a date suffix. This would ease packaging at linux distributions such as debian.

**Comment by koppor** [comment]
Can a hint be given, how the `pom.xml` is generated? I don't find a `pom.xml` here in this repo, but one is available at https://oss.sonatype.org/content/repositories/snapshots/org/citationstyles/styles/1.0.1-SNAPSHOT/styles-1.0.1-20161006.003041-731.pom

Side comment: The `<developerConnection>` in that pom seems to be outdated.

**Comment by michel-kraemer** [comment]
> it seems the date suffixes are in place now

This has always been the case. I haven't changed anything.

> Can a hint be given, how the pom.xml is generated?

Look at the following file. It contains the instructions to generate the pom.
https://github.com/michel-kraemer/styles/blob/gradle/build.gradle

> The &lt;developerConnection> in that pom seems to be outdated.

I needed a place where I could store the `build.gradle` file. That's why I created this repo.

The jars in the Maven repository were originally supposed to be used by citeproc-java [1] and applications using citeproc-java.

Hope this helps!

Michel

[1] http://michel-kraemer.github.io/citeproc-java/
