### ISSUE TITLE
Style for Journal of Evolution and Health

### ISSUE THREAD

**Issue by Noora99** [citation-style-language/styles#2222]
Journal of Evolution and Health uses style:
Freedman SB, Adler M, Seshadri R, Powell EC. Oral ondansetron for gastroenteritis in a pediatric emergency department. N Engl J Med. 2006 Apr 20;354(16):1698-705. PubMed PMID: 16625009.

It is similar to Physiology & Behavior citation style but instead of point after number in text uses brackets around number and instead of PMID uses doi.

**Comment by rmzelle** [comment]
(instructions to authors at http://jevohealth.com/journal/policies.html#formatting)

**Comment by rmzelle** [comment]
Style has been added to the repository (https://github.com/citation-style-language/styles/pull/2770).
