### ISSUE TITLE
Submit style to Zotero

### ISSUE THREAD

**Issue by simtyrell** [citation-style-language/styles#2224]
Hello,

Sorry I'm a novice. I have submitted a new style and it has gone through and been approved. What is my next step to adding it to the Zotero style library? Thank you

**Comment by simtyrell** [comment]
Hello,

Sorry I'm a novice. I have submitted a new style and it has gone through and been approved. What is my  next step to adding it to the Zotero style library?  Thank you

**Comment by adam3smith** [comment]
(refers to: https://github.com/citation-style-language/styles/pull/2223 )
They style has passed automated checks. We'll now review it manually, possibly make requests for further adjustments. When it's accepted (Merged in github terms) it will automatically appear in Zotero's style repository.
