### ISSUE TITLE
Incorrect or incomplete "renamed-styles.json"

### ISSUE THREAD

**Issue by Lavapuncher** [citation-style-language/styles#2229]
Hello,
I've just noticed, that there's most likely an error in the "renamed-styles.json".
In line 3 it says that the file has been renamed to "mammal-research".

https://github.com/citation-style-language/styles/blob/master/renamed-styles.json#L3

But such a file doesn't exist. Is it just a typo from "mammal-review":
https://github.com/citation-style-language/styles/blob/master/mammal-review.csl

or does the style no longer exist at all?

Thanks!

**Comment by rmzelle** [comment]
Thanks for keeping an eye out, but this seems to be correct.

There is a style "mammal-research" in the "dependent" subdirectory: https://github.com/citation-style-language/styles/blob/master/dependent/mammal-research.csl

And http://link.springer.com/journal/13364 shows that the title of this journal has been changed from "Acta Theriologica" to "Mammal Research".
