### ISSUE TITLE
Style Request: Reviews of Environmental Contamination and Toxicology

### ISSUE THREAD

**Issue by syta99** [citation-style-language/styles#2238]
http://www.springer.com/series/398

**Comment by adam3smith** [comment]
https://github.com/citation-style-language/styles/wiki/Requesting-Styles
(FWIW, I much prefer style requests on the Zotero forums. I don't really look at them here).

**Comment by syta99** [comment]
adam3smith Thank you for your help.

**Comment by rmzelle** [comment]
Added now: https://github.com/citation-style-language/styles/commit/b9e693443f20e80af2f040d0dc72d7efbccaf896
