### ISSUE TITLE
org.citationstyles / locales not updated in maven repository ?

### ISSUE THREAD

**Issue by gduh** [citation-style-language/styles#2280]
Hi, 

I use maven repository to retrieve org.citationstyles / locales (and styles) but some files are not updated since a long time ago if I compare them with https://github.com/citation-style-language/locales/blob/master/locales-fr-FR.xml

So the result after using citeproc-java (and locales-1.0.jar) the result is not correct. 

How can I get the last version ?

**Comment by rmzelle** [comment]
We don't maintain the Maven repositories ourselves, but I think you can use https://oss.sonatype.org/content/repositories/snapshots/org/citationstyles/styles/ and https://oss.sonatype.org/content/repositories/snapshots/org/citationstyles/locales/. See https://github.com/citation-style-language/styles/issues/2221#issuecomment-246447880 for more details.

**Comment by rmzelle** [comment]
(if you have any further questions, it's probably handier if you ask them in the issue I linked to above)
