### ISSUE TITLE
Update distribution-updater with new Travis webhook verification

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#2304]
https://github.com/citation-style-language/styles-distribution doesn't pull styles anymore, since about 2 weeks back. @rmzelle is this Sylvester's code or someone else's?

**Comment by rmzelle** [comment]
Dan's.

@dstillman, @inukshuk, does either of you have time to take a look at https://github.com/citation-style-language/distribution-updater? I'm pretty sure it's the same issue we ran into with @citation-style-language/sheldon (see https://github.com/citation-style-language/Sheldon/pull/7), namely that Travis changed its authentication method on 11/1: https://blog.travis-ci.com/2016-08-31-webhook-delivery-changes

**Comment by inukshuk** [comment]
Yes, this is likely the same cause. The [new verification method](https://docs.travis-ci.com/user/notifications/#Verifying-Webhook-requests) involves checking a SHA1 digest of the request's payload. @dstillman I can probably take a stab at it sometime later this week if you want.

**Comment by dstillman** [comment]
@inukshuk, that'd be great. I've put in a less-restrictive check for the moment.

**Comment by rmzelle** [comment]
@inukshuk, @dstillman, should I keep this issue about updating the webhook verification open?

**Comment by bwiernik** [comment]
I think we can close this? @adamsmith @retorquere

**Comment by retorquere** [comment]
We're not doing anything with Travis anymore.
