### ISSUE TITLE
Journal of Vacuum Science & Technology has moved

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#2317]
journal-of-vacuum-science-and-technology-b-microelectronics-and-nanometer-structures
journal-of-vacuum-science-and-technology-a-vacuum-surfaces-and-films
seem to have moved from IEEE to AIP, including their citation styles. Need to check which style exactly they're using now and switch.

**Comment by damnation333** [comment]
@adam3smith 
This could be closed as it's been dealt with? https://github.com/citation-style-language/journals/pull/17

**Comment by rmzelle** [comment]
@damnation333, yup. Thanks.
