### ISSUE TITLE
Cell Styles vs. Elsevier generic

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#2319]
At some point we switched all the cell styles over to Elsevier format. @rmzelle do you remember why we/Carles did this? Was this ever discussed? Can we switch those back?

**Example:**

Current Biology: http://www.cell.com/current-biology/authors
Example from author guidelines:
1. Holmes, S., and Watson, J. (1993). Identification of the function of the moriarty gene product. Curr. Biol. 3, 121–129.

Cell (numeric)
1. Einstein, A. (1905). On the electrodynamics of moving bodies. Ann. Phys. 17, 1–26.

Current Biology (Elsevier Vancouver):
[1] Einstein A. On the electrodynamics of moving bodies. Ann Phys 1905;17:1–26. doi:10.1088/0143-0807/27/4/007.

**Comment by rmzelle** [comment]
See https://github.com/citation-style-language/utilities/commit/ed5689ba93d4788a37a5bf61412d231919f375b4#commitcomment-13460634. Re-reading Carles comment on that commit, it seems to me that
we'd probably would want to add all 'non-standard' journals to the
skip list.

**Comment by adam3smith** [comment]
Closed by https://github.com/citation-style-language/styles/pull/2350
