### ISSUE TITLE
Correctly deal with entry-dictionary/entry-encyclopedia in Chicago styles

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#2346]
Follow-up of https://github.com/citation-style-language/styles/pull/1822, where @adunning proposed a fix.

**Comment by adam3smith** [comment]
(leaving this closed & going to review adunning's fix shortly)

**Comment by rmzelle** [comment]
Ah, right, his new PR: https://github.com/citation-style-language/styles/pull/3857
