### ISSUE TITLE
"In Press" suddenly added to journal articles in Restoration Ecology CSL

### ISSUE THREAD

**Issue by Caitydid** [citation-style-language/styles#2357]
As of the most recent update to the Restoration Ecology CSL, many journal entries seem to be getting "In Press" added to them. As I didn't make any changes recently, I'm not sure what's happened. And I can't figure out how to implement the fix I found in the CSL code because it won't let me edit it even when I'm logged in (which is probably because I can't figure out how to get to a branch instead of the master, even though I'm sure I've done it before).

**Comment by adam3smith** [comment]
thanks, should be fixed. 
Github will automatically create a branch when you edit using the pencil icon on https://github.com/citation-style-language/styles/blob/master/restoration-ecology.csl

**Comment by rmzelle** [comment]
No real changes to this style were made since you first submitted it in June, so either you changed how you use it (e.g. by citing fewer items with locators), or there was a change in your reference manager software.

**Comment by adam3smith** [comment]
(the code was definitely incorrect, though, so it's possible that a citeproc fix would have broken the style).

**Comment by rmzelle** [comment]
@Caitydid, are you using Zotero, Mendeley, or something else?
