### ISSUE TITLE
For 'et al.' in Persian, replace "و دیگران" with "و همکاران"

### ISSUE THREAD

**Issue by hamedheydari** [citation-style-language/styles#2474]
It would be great if for 'et al.' in Persian, replace "و دیگران" with "و همکاران"
I have no idea where to ask this.

**Comment by bwiernik** [comment]
CSL files are maintained here:
https://github.com/citation-style-language/locales

You could submit an issue or even better a pull request fixing it.

**Comment by hamedheydari** [comment]
Thanks
