### ISSUE TITLE
Author disambiguation in taxon.csl

### ISSUE THREAD

**Issue by damnation333** [citation-style-language/styles#2509]
I've been emailed regarding this style and can't figure out how to get it right:
**problem**: Following up on this: I've been using the style in Mendeley and notice that in the in-text citations 1) there appears to be some disambiguation of author surnames going on, which we don't do (some are appearing with initials or full names rather than just surname; I have a suspicion that it is somehow not dealing well with minor variants of the same name). 2) Some (but not all) citations include multiple author names (our usual format for 3+ authors is of course "1st author & al."). Perhaps this has something to do with the vagaries of my own database, but I haven't seen this behaviour in the few other styles that I have used so far. Do you think a fix will be on the cards?

Guidelines:
If several articles by the same author[s] in the same year are
cited, add letters to the year (e.g., 2006a). This applies also to articles
by the same first author but two or more various co-authors that
have to be cited with “& al.” in the text.

Relevant code in https://github.com/citation-style-language/styles/blob/master/taxon.csl 
citation et-al-min="6" et-al-use-first="1" et-al-subsequent-min="3" et-al-subsequent-use-first="1" disambiguate-add-year-suffix="true" disambiguate-add-names="true" disambiguate-add-givenname="true" collapse="year" givenname-disambiguation-rule="primary-name"

Thanks.

**Comment by adam3smith** [comment]
1) is indeed an issue of inconsistent name entry in Mendeley. I'd assume adding the initial for first authors is otherwise correct
2) we'd want to delete disambiguate-add-names="true"

**Comment by damnation333** [comment]
thanks! Now I got it.
I also had to change the et-al-min settings. The example citation I was using had 5 authors only... Silly me.
PR made for changes: https://github.com/citation-style-language/styles/pull/2510
