### ISSUE TITLE
Improve style naming

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#2512]
As followup of https://github.com/citation-style-language/styles/pull/2490#issuecomment-280091164 and https://github.com/citation-style-language/styles/commit/04d2e46bacd6c5ad80a3d18f1fec86e3bba9288f#commitcomment-20913664, I'd like to propose some changes:

* I'd like to change titles like "Elsevier Vancouver" to "Elsevier - Vancouver". This would extend to all (mostly publisher-wide) styles that have "Vancouver" and "Harvard" variants. Since this generally only involves adding a hyphen (and a space), this wouldn't affect IDs.
* I'd like to change over all the "Harvard - [university name]" styles to "University name - Harvard". I'd like to update the IDs to reflect this change as well. We might get a few complaints here during the switch, but I think it's still a better solution long-term. (maybe we should ask Mendeley if they support style redirection via renamed-styles.json, since I think they're rather popular in UK universities, which have most of these styles)

(we could switch to "University name (Harvard)" as well, which we already use for a few styles, but maybe we should make an distinction between labels like "Harvard", "Vancouver", and "APA", and more basic labels like "numeric" and "author-date" (I think we should keep placing the latter between parentheses)).

**Comment by rmzelle** [comment]
@adam3smith, let me know if you agree with this. We could do the Harvard styles in two stages (titles first, then style IDs), and wait to see what the response is after each change.

**Comment by adam3smith** [comment]
I'm fine with the renaming patterns and agree keeping Harvard/Vancouver etc. out of parentheses.
My concern apart from whether Mendeley et al handle the renaming gracefully would be universities who either link directly to styles or list them with their current name. I have no sense if that's common at all, so no idea if this is a non-issue or a major issue, though.

**Comment by rmzelle** [comment]
Also, if you agree, I'd like to change the title of "Taylor & Francis - American Psychological Association" to "Taylor & Francis - APA". More consistent with the other styles:

https://www.zotero.org/styles?q=-%20american
https://www.zotero.org/styles?q=-%20apa

**Comment by bwiernik** [comment]
(I have never heard any psychologist refer to the style by its full name.)

**Comment by adam3smith** [comment]
definitely OK with the T&F rename

**Comment by rmzelle** [comment]
> definitely OK with the T&F rename

Mind if I change the style ID as well? As far as I can tell the style has no dependents, so impact should be limited: http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Ftaylor-and-francis-american-psychological-association (compare to the bottom of the page at http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fapa)

**Comment by rmzelle** [comment]
> As far as I can tell the style has no dependents

(further investigation shows that this style is a dependent itself :P)

**Comment by rmzelle** [comment]
Added a short mention of these naming conventions to the style requirements: https://github.com/citation-style-language/styles/wiki/Style-Requirements/_compare/d21d9967ab0db82487798ea1edb70f69c50e09d4...2e5560ecd454486f2af6481b44024d5b5e5bb073

Closing this issue.
