### ISSUE TITLE
What ISSN to use for a Special Issue style?

### ISSUE THREAD

**Issue by sjdv1982** [citation-style-language/styles#2516]
I have created a new style for the Nucleic Acid Research (NAR) Web server issue, a yearly issue of NAR with ~90 articles per year. I created the style by adapting the existing NAR style (for non-web server issues).
 
The pull request is here:
https://github.com/citation-style-language/styles/pull/2515

However, the automatic check fails with the following message:
**The CSL Style Repository may not contain any (non-excepted) duplicate ISSNs**

Obviously, the NAR web server issue has the same ISSN as NAR itself.
What to do?

**Comment by bwiernik** [comment]
You can keep the discussion of this issue with your pull request. Please post this information in the thread there.

**Comment by rmzelle** [comment]
> However, the automatic check fails with the following message:
> The CSL Style Repository may not contain any (non-excepted) duplicate ISSNs
> 
> Obviously, the NAR web server issue has the same ISSN as NAR itself.
> What to do?

We have a check that prohibits multiple styles from having the same ISSN(s). The purpose of that check is to prevent us to accidentally accepting multiple styles for the same journal under (slightly) different names. In rare cases, like this one, we do wish to have more than one CSL style per journal, and in that case we can add the ISSN(s) of that journal to a list of exceptions.
