### ISSUE TITLE
MIS Quarterly missing space after book title

### ISSUE THREAD

**Issue by GeorgLink** [citation-style-language/styles#2537]
MIS Quarterly.csl has no space (or comma) after a book title when followed by editor names or the series.

Examples:
![image](https://cloud.githubusercontent.com/assets/8862021/23375953/e5ef173e-fcef-11e6-8207-2680fdd9603f.png)
![image](https://cloud.githubusercontent.com/assets/8862021/23375885/9cda9c58-fcef-11e6-9eb0-f4f5bdecf8aa.png)
![image](https://cloud.githubusercontent.com/assets/8862021/23375896/a75b4c36-fcef-11e6-9a35-8776768ad81f.png)

I use Zotero Standalone and Word 2016.

**Comment by rmzelle** [comment]
Should be better now: https://github.com/citation-style-language/styles/commit/329c32e6b48b4e75590f1609661ed1fc3e38f4ca

You can update the style from the Zotero Style Repository, or just wait until 24 h until Zotero auto-updates its styles.

**Comment by GeorgLink** [comment]
@rmzelle thanks for the quick fix!
