### ISSUE TITLE
And with dash

### ISSUE THREAD

**Issue by Chimborasso** [citation-style-language/styles#2605]
Hello,

is there a way to separate two authors using dash ( - ) instead of symbol (&) or text (and)?

Thanks!

**Comment by rmzelle** [comment]
Can you give an example of what the actual reference should look like?

**Comment by adam3smith** [comment]
But the general answer is that
1. You can set a delimiter between all authors using `delimiter=" - "` and note setting the `and` attribute at all. I suspect that's what you're looking for here. Most existing examples of this use a slash, e.g. 
https://github.com/citation-style-language/styles/blob/master/archiv-fur-die-civilistische-praxis.csl#L86 
2. You can replace the `text` version of `and` with any term you want, including a dash, though that would affect the entire citation style. You cannot have "and" in one place and dash in another.
3. You cannot currently replace the symbol (&) for and, though we're considering that.
