### ISSUE TITLE
apa nonapersand custom text

### ISSUE THREAD

**Issue by pa0** [citation-style-language/styles#2615]
After define: <term name="and">i</term> (for polish version of APA) I have "and" between multiple authors. Is there any way to suppress using "i" instead "and"?

**Comment by rmzelle** [comment]
It's not entirely clear to me what you're describing (feel free to write in Polish if that's easier for you).

When used in Polish, our APA style should already be using "i" in name lists. What program are you using our style with?

**Comment by pa0** [comment]
I use Rmarkdown ⇢ pandoc ⇢ tex ⇢ pdf in RStudio.
Probably pandoc work in english and didn't brother with my "\usepackage{polski}"

I had checked locales-pl-PL (made some corrections) and will try to tell pandoc use it :-)

I am think that with CSL everything is ok - sorry for disturbing You.

**Comment by rmzelle** [comment]
Yes, our APA style isn't fixed to any particular locale, and should translate freely (although it may have some issues in languages other than English).

Feel free to report back here, but I'll close this for now.
