### ISSUE TITLE
Problem with cite-group-delimiter ?

### ISSUE THREAD

**Issue by ARMetcalf** [citation-style-language/styles#2642]
Here's one style affected:  styles/aerosol-science-and-technology.csl

I've also tried writing/editing my own csl files where I want use this.

From the spec:
cite-group-delimiter
Activates cite grouping and specifies the delimiter for cites within a cite group. Defaults to “, ”. E.g. with delimiter on cs:layout in cs:citation set to “; ”, collapse set to “year”, and cite-group-delimiter set to “,”, citations look like “(Doe 1999,2001; Jones 2000)”.

But what I get using the above style is: 
(Utada et al. 2007b; 2007a; Cramer et al. 2004)
(Abate and Weitz 2009; Chu et al. 2007b; Utada et al. 2007a; 2005)

Any ideas to fix this?

**Comment by adam3smith** [comment]
This isn't, by definition, a CSL error, but an implementation error. What software are you using?

**Comment by ARMetcalf** [comment]
I'm using Papers3's Citations feature in Word 2016.  I submitted a ticket to them too, but their development is slow these days.  Just thought I would check on who's to blame so it hopefully gets fixed soon.

Thanks.

**Comment by adam3smith** [comment]
errors in how valid CSL styles are implemented are always in the reference manager (and/or the citation processor it uses. Papers has their own citation processor, so this is entirely on them).
FWIW, this is working correctly in Zotero/citeproc-js
