### ISSUE TITLE
Journal of chemical information and modeling

### ISSUE THREAD

**Issue by ilsacripante** [citation-style-language/styles#2647]
Dear maintainers,
the style of references for JCIM has two mistakes:
1. the issue numbers must be removed from the references
2. books should show publishers and publication cities
All the best

**Comment by adam3smith** [comment]
Books do show publisher and publishing location in JCIM (check the [preview](https://www.zotero.org/styles?q=id%3Ajournal-of-chemical-information-and-modeling) on Zotero, e.g.)-- that must be something wrong in your data or a problem with your reference manager. 

The issue numbers need to be present for journals that start with page one for each new issue. As we have no way of telling that, we include them.
