### ISSUE TITLE
apa.csl ignoring post-weblog as needing access time

### ISSUE THREAD

**Issue by reagle** [citation-style-language/styles#2648]
apa.csl only specifies an accessed date (e.g., " Retrieved January 1, 2015, from ") for `webpage` types. `post-weblog` should have it too. And what about including it for any source that has a URL? At the least, it should be:

```
<if type="post-weblog webpage" match="any">
```

**Comment by adam3smith** [comment]
I agree on post-weblog, but we're purposefully not including it for all URLs, since as per APA you're only supposed to add it when the source is likely to change (I'd have to check on the exact wording, but that's the gist of it).

**Comment by reagle** [comment]
Okay, now in pull request #2650.

**Comment by reagle** [comment]
now merged
