### ISSUE TITLE
Conjunction Errors in MLA 8

### ISSUE THREAD

**Issue by Elbar914** [citation-style-language/styles#2695]
**What We're Solving For:**

Conjunctions such as "I'll " are incorrect when citation is generated in MLA 8 on EasyBib.com and other citation generator services. 

Titles are formatted in title case which capitalizes every word in the title except for a list of conjunctions. It looks like certain words containing apostrophes are being capitalized incorrectly, it looks like words with more than one letter after the apostrophe are such as "I'll" and "I've" are being capitalized as "I'Ll" and "I'Ve" but words like "I'm" and "Don't" are unaffected. I don't know if this is a flaw in the language itself or some other part of the system but either way it can't be corrected in the CSL itself. The title case attribute could be removed from the title variable but that would cause far more issues than it would fix.

**Detailed User Acceptance Criteria**:

Current Output:
Wallace, David Foster. A Supposedly Fun Thing I`Ll Never Do Again.

Expected Output:
Wallace, David Foster. A Supposedly Fun Thing I'll Never Do Again.

**Question**:

Do you have any ideas on how this can be remedied, or even if it can?

**Comment by rmzelle** [comment]
@fbennett, thoughts? Our MLA 8 style uses title-cased titles: https://www.zotero.org/styles/modern-language-association-8th-edition?source=1

**Comment by fbennett** [comment]
It works fine here. Perhaps the services are using another citation processor, or an outdated version of `citeproc-js`?

(The error example shows a back-tick instead of an apostrophe. It tested with that as well, and the processor renders the string with correct capitalization [with a back-tick]. Perhaps it's worth double-checking the input though?)

**Comment by adam3smith** [comment]
Yeah, I also cannot replicate this. Closing. 
(In any case, this is definitely a processor issue, not a CSL issue, so should be moved to that respective repository -- though if you're using citeproc-js, as per fbennett and my testing, this is not an issue in the current version of the processor).

**Comment by rmzelle** [comment]
@Elbar914, if you're affiliated with EasyBib.com, it would help if you could find out the version number of the CSL processor software used (presumably still citeproc-js), and have them update to the latest version if they aren't up to date.
