### ISSUE TITLE
MLA 8th Edition should abbreviate "University" to "U" and "University Press" to "UP"

### ISSUE THREAD

**Issue by JonathanReeve** [citation-style-language/styles#2700]

**Comment by adam3smith** [comment]
sorry, CSL isn't able to provide that level of abbreviation handling. There may be plugins for individual reference managers (e.g. abbreviation filter for Zotero) that can help here, but we're not going to address this any time soon.

**Comment by rmzelle** [comment]
We could change `<text variable="publisher"/>` to `<text variable="publisher" form="short"/>`. With that, an abbreviated publisher name would be used if available (see also http://docs.citationstyles.org/en/stable/specification.html#text.), but it would be up to the reference manager to either offer its users a dedicated "abbreviated publisher name" field for manual entry, or to automatically abbreviate the full publisher name according to the MLA rules. We're not aware of any that do either, though, so this is mostly a theoretical exercise right now.

I don't think CSL styles themselves should attempt to offer automatic abbreviation, and it's unlikely we'll ever add support for this.

(if you only ever use MLA, you can of course just store the abbreviated publisher names in the standard publisher field of your reference manager)

@adam3smith, by the way, do you what's up with our current set of MLA styles? Normally we would shift "modern-language-association.csl" to the latest 8th edition and keep the old style as "modern-language-association-7th-edition.csl", right? Currently we have a style named "modern-language-association-8th-edition.csl", and "modern-language-association.csl" is still 7th edition.

**Comment by adam3smith** [comment]
Yes, I did that on purpose to ease in the transition and to make sure MLA 8 got a bit of testing before we ship it as the default style. 
I think we're pretty much ready for the shift as you describe, though I'd like to give MLA 8 one more look before. In particular, it's not quite clear what to do about DOIs (there's a Zotero thread on that).
