### ISSUE TITLE
Style error: American Journal of Hypertension 

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#2705]
Instructions for authors here: https://academic.oup.com/ajh/pages/general_instructions#FormatofManuscripts
they refer to both Vancouver and AMA, but the style, in particular for books and chapters, follows neither exactly. Journal articles look like AMA

**Comment by rmzelle** [comment]
(this is currently a dependent style: https://github.com/citation-style-language/styles/blob/master/dependent/american-journal-of-hypertension.csl)

@damnation333, feel free to take this if you're interested :).

**Comment by damnation333** [comment]
Cool. Hadn't seen this one. Will add it to the list.
