### ISSUE TITLE
Update MLA from 7th to 8th edition

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#2763]
Per https://github.com/citation-style-language/styles/issues/2700#issuecomment-304764851, we currently have "modern-language-association-8th-edition.csl" (8th edition) and "modern-language-association.csl" (7th edition). Eventually we should rename "modern-language-association-8th-edition.csl" to "modern-language-association.csl" (and set up a redirect in renamed-styles.json for this), and "modern-language-association.csl" to  "modern-language-association-7th-edition.csl".

@adam3smith indicated in the thread above that we still need to double-check the DOI behavior in the 8th edition. See also https://forums.zotero.org/discussion/comment/261399/#Comment_261399

**Comment by rmzelle** [comment]
@adam3smith, I don't know if this sufficiently answers your question

> I'm not quite sure what to do about the DOIs -- nowhere in the manual (that I could find) does it say that all references retrieved online should have a DOI, even if there's a print equivalent. Very few of the examples in the manual do have a DOI, although (presumably) pretty much any article anyone uses today is retrieved online (or do you know anyone who consults paper journals in the library stacks?).

but https://style.mla.org/2016/08/11/page-range-and-doi/ says:

> The location of an online work is typically indicated by a URL or DOI, **one of which should be included** [emphasis mine]. If the work is paginated and forms part of a larger work, such as an anthology or periodical, you may provide the page range in addition to the URL or DOI.

In addition, https://style.mla.org/2016/11/02/urls-some-practical-advice/ says:

> The new MLA Handbook recommends including URLs in works-cited-list entries for online works, but it also notes their drawbacks: they can cause clutter, become obsolete, and have limited use in a print work. URLs may also be inaccessible when the pages to which they refer are behind a paywall. Although **writers can avoid these problems by following the handbook’s recommendation to use permalinks and DOIs when such information is available** [emphasis mine], URLs are often the only option.
> 
> **Basic Rule of Thumb**
> The MLA Handbook encourages writers to list the URL that they see in their browsers unless the source identifies a DOI or permalink associated with it.

So MLA appears to advocate the use of DOIs quite heavily.

**Comment by rmzelle** [comment]
(there is also https://style.mla.org/ask-a-question/, but it appears that they are quite picky about which questions they actually answer)

**Comment by adam3smith** [comment]
yeah, that's great. I'll add the DOI across the board then asap and we can switch. Will do as PRs
