### ISSUE TITLE
Possible to add line breaks in a citation?

### ISSUE THREAD

**Issue by NateWr** [citation-style-language/styles#2831]
I'd like to create a CSL style for the [RIS file format](https://en.wikipedia.org/wiki/RIS_(file_format)), so that I can use our citeproc-php integration to generate the downloadable file. 

The RIS format requires a line break between each piece of data in the citation. Is there any way to indicate a line break in `<layout>`?

I've tried using `\n` with no luck:

```xml
    <layout>
      <text value="TY - "/>
      <text macro="type"/>
      <names variable="author" prefix="\nAU - ">
        <name delimiter="\nAU - "/>
      </names>
      <text value="\nPY - "/>
      <date variable="issued">
        <date-part name="year" form="long" suffix="/"/>
        <date-part name="month" form="numeric-leading-zeros" suffix="/"/>
        <date-part name="day" form="numeric-leading-zeros"/>
      </date>
      <text value="\nY2 - "/>
      <date variable="accessed">
        <date-part name="year" form="long" suffix="/"/>
        <date-part name="month" form="numeric-leading-zeros" suffix="/"/>
        <date-part name="day" form="numeric-leading-zeros"/>
      </date>
      <text value="\nTI - "/>
      <text variable="title"/>
      <text value="\nJF - "/>
      <text variable="container-title"/>
      <text value="\nDO - "/>
      <text variable="DOI"/>
      <text value="\nUR - "/>
      <text variable="URL"/>
      <text value="\nER - "/>
    </layout>
```

**Comment by adam3smith** [comment]
My first recommendation would be -- don't: E.g. Zotero exports RIS using in a fairly complex javascript file and CSL is just not powerful enough to get good metadata export. It'd be so much better to actually have the ability to use a programming language to get this right. (To be clear -- I do expect you'll be able to get something out of this and it'll likely be valid RIS; I just wouldn't expect it to be a good/comprehensive export).

Second, if you must, what will work depends on your citeproc. E.g. citeproc-js simply removes linebreaks even if they are coded into CSL. There, the only way to get a linebreak is with the `display` attribute which wouldn't work, e.g., for the way you handle authors. 

Third, *if* this will work, it will work with XML-encoded entities, i.e.
Carriage return: `&#xD;`
Line feed: `&#xA;`

**Comment by NateWr** [comment]
Thanks for the response and the tips on the XML-encoded entities. I understand I'm pushing CSL a bit beyond what it's intended to do. 

We're implementing a CSL integration for rendering a journal article's citation in various formats (we do journal publishing), so we have a limited subset of needs for the export data. But I'll take the hint and roll a custom solution if the line-break entities don't work.

Cheers. :+1:

**Comment by rmzelle** [comment]
I'm aware of a few standalone converters between CSL JSON and BibTeX (https://github.com/larsgw/citation.js and https://github.com/fiduswriter/biblatex-csl-converter), but not between CSL JSON to RIS.

(other than that, like @adam3smith said, CSL wasn't designed for bibliographic format conversion (other than from CSL JSON to formatted references), and you'll probably run into some limitations)

**Comment by adam3smith** [comment]
Glad that was helpful. Closing here
