### ISSUE TITLE
Smithsonian Institution Scholarly Press Styles: author-date, note, botanics

### ISSUE THREAD

**Issue by POBrien333** [citation-style-language/styles#2867]
Via https://forums.zotero.org/discussion/59189/style-request-smithsonian-institution-scholarly-press

3 styles: https://scholarlypress.si.edu/resources/guidelinesforms/

- [x] author date: https://github.com/citation-style-language/styles/pull/2866 (03.08.2017)
- [x] botanics: https://github.com/citation-style-language/styles/pull/2882 (12.08.2017)
- [x] note - work started: https://github.com/citation-style-language/styles/pull/2885 (24.04.2018)

**Comment by rmzelle** [comment]
Cheers 🎆 🌟 🎈

**Comment by POBrien333** [comment]
Waheeee!!
