### ISSUE TITLE
Update Journal of General Virology

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#2874]
I got the following request via citationstyles.org:

> The Journal of General Virology have changed their citation format, but CSL has still the old version. Can it be updated please.
> http://www.microbiologyresearch.org/authors/information-for-authors#references

Looks like 6 journals by the Microbiology Society use the same style.

@POBrien333, could you take a look?

**Comment by POBrien333** [comment]
Sure, will do. :)

**Comment by POBrien333** [comment]
Just made the style here: https://github.com/citation-style-language/styles/pull/2877
Who emailed you? They could link to the CSL repo from their website. They do that for Endnote...

**Comment by rmzelle** [comment]
Covered by https://github.com/citation-style-language/styles/pull/2878. Thanks!

> Who emailed you?

An academic researcher. Didn't see a link to e.g. the editorial board of the journal.
