### ISSUE TITLE
Brain, Behavior and Evolution wrong style

### ISSUE THREAD

**Issue by egisholt** [citation-style-language/styles#2905]
Sorry I am new here, I was trying to format my Bibliography according to the journal and the csl style is completely different. I have been trying to edit the style but I can´t sort the Bibliography alphabetically instead of appereance. Checking the editor I saw that it refers to this http://www.karger.com/Journal/Guidelines/254338#11

But that corresponds to the Guidelines of Acta Cytologica journal instead of Brain, Behavior and Evolution.

I am not sure how to change that.

Thanks for any help

**Comment by rmzelle** [comment]
Continued in #2906.
