### ISSUE TITLE
Wrong Brain, behavior and evolution.csl style

### ISSUE THREAD

**Issue by egisholt** [citation-style-language/styles#2906]
Sorry I am new here, I was trying to format my Bibliography according to the journal and the csl style is completely different. I have been trying to edit the style but I can´t sort the Bibliography alphabetically instead of appereance. Checking the editor I saw that it refers to this http://www.karger.com/Journal/Guidelines/254338#11

But that corresponds to the Guidelines of Acta Cytologica journal instead of Brain, Behavior and Evolution.

I am not sure how to change that.

Thanks for any help

**Comment by adam3smith** [comment]
Generally we prefer if you report errors to & through your reference manager. Which are you using?

**Comment by egisholt** [comment]
Hi I am sorry I just found your page. I use Mendeley

Thanks

**Comment by adam3smith** [comment]
You should be able to use the style "Karger journals" which looks correct to me while we fix this.

**Comment by egisholt** [comment]
Hello Sebastian

Thanks for all your help. Unfortunately Karger journals style is still different than the one that they require in Brain,Behavior and Evolution. I have modified it using the editor in Mendeley but I can´t find were to change the order of the Bibliography. Karger Journals sorts references by appearance while Brain, Behavior and Evolution sorts bibliography by alphabetical order. 

https://www.karger.com/Journal/Guidelines/223831#06 <https://www.karger.com/Journal/Guidelines/223831#06>

I am sorry that the publishers use different styles

Hope you can help me otherwise I have to do it manually

Thank you

Eduardo

**Comment by adam3smith** [comment]
How quickly do you need this?

**Comment by egisholt** [comment]
I just need this to submit the paper, but don't worry otherwise I can do it manually 

Thanks for all the help

Eduardo Garza Gisholt

**Comment by rmzelle** [comment]
We now have a corrected style for Brain, Behavior and Evolution. Sorry for the wait, and thanks to @POBrien333 for doing the work!
