### ISSUE TITLE
citing software packages and datasets

### ISSUE THREAD

**Issue by xgirouxb** [citation-style-language/styles#2940]
Science as a whole is facing a reproducibility crisis, and the most unified response to this is a big push towards open science practices within the scientific community. In addition, developing software for analysis in different fields is hard work represents some of the most advanced heavy lifting done in many disciplines, yet it is seldom accounted for in traditional impact metrics.

To address these issues, there is an increased (and perfectly reasonable) expectation that researchers properly cite software packages (especially package version, url), computer programs and a datasets used. This has become a regular part of a researcher's referencing workflow across many disciplines, and at present, it is hacky regardless of the citation software used because it is not yet implemented in CSL (please correct me if I'm wrong). Consequently I find myself writing out about 5-10% of my bibliography manually because software doesn't fit the strict molds of journal article citations, and I haven't found an any satisfactory workarounds (I'm open to suggestions).

Is there a plan to eventually integrate this functionality into CSL?

**Comment by rmzelle** [comment]
It's on the radar.

CSL already has a "dataset" item type (although e.g. Zotero still needs to add it as an item type: https://github.com/citation-style-language/zotero-bits/issues/22), and the next CSL version will most likely have a "software" item type as well (https://github.com/citation-style-language/zotero-bits/issues/69).

**Comment by adam3smith** [comment]
In the meantime, I would suggest citing software using any item type that broadly fits -- even "book" works fairly well if you add "version" and "DOI" -- Zotero's computer program item already does the former. I'm closing this since we have the zotero-bits tickets.

**Comment by xgirouxb** [comment]
Thanks for the quick reply and the suggestions, it's great to see that there are active efforts to implement this feature. I assumed the core of this discussion would be in the CSL repository so my searches didn't extend to zotero, good to know that is a good resource to track changes and current dev work for CSL. Apologies for duplicating the issue.

**Comment by adam3smith** [comment]
no worries -- it's a historical relic that it's on Zotero and we just don't have the time to re-organize it properly. Technically the right place would be here.
