### ISSUE TITLE
Create sodertorns-hogskola-harvard.csl #2947

### ISSUE THREAD

**Issue by Ca7w3as3l** [citation-style-language/styles#2953]
Hi
Sorry for being impatient. I am new to this process. My submission has been sitting for a couple of days. I have intended to have this style added to the database for our students to access. Do I have to do anything else to expedite the process.
Thanks,
Kurt

**Comment by rmzelle** [comment]
Hi @Ca7w3as3l,

Sorry for the wait. I just responded to you in your most recent pull request. Note that the CSL repository is maintained by just two volunteers, so sometimes it takes a while before we have time to respond.
