### ISSUE TITLE
Natureza and Conservacao

### ISSUE THREAD

**Issue by JulianaTrajano** [citation-style-language/styles#3000]
This journal "Natureza and Conservacao" has changed its title to "Perspectives in Ecology and Conservation" (https://www.journals.elsevier.com/perspectives-in-ecology-and-conservation/). The reference style itself has not changed, but the Style Title must be changed to Perspectives in Ecology and Conservation.

**Comment by rmzelle** [comment]
Thanks for reporting! This is now fixed.
