### ISSUE TITLE
American Journal of Emergency Medicine style not showing up

### ISSUE THREAD

**Issue by primary332** [citation-style-language/styles#3025]
No option to choose AJEM is given despite Mendeley and Elevisier listing this as a supported style.

**Comment by adam3smith** [comment]
Use the style "Elsevier Vancouver" which the journal follows. We rely on Elsevier to give us up-to-date lists on which journals follow these generic styles. I think they're working on giving us an updated one, hopefully with AJEM on it; the list has thousands of journals, we cannot do this manually.
