### ISSUE TITLE
Taylor & Francis journal style requests

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#3039]
We had a user request via the CSL website for:

International Journal of Polymeric Materials and Polymeric Biomaterials
http://www.tandfonline.com/action/authorSubmission?show=instructions&journalCode=gpom20

and

Materials Technology
http://www.tandfonline.com/action/authorSubmission?show=instructions&journalCode=ymte20#References

(this one seems to use standard https://www.zotero.org/styles/taylor-and-francis-national-library-of-medicine?source=1 )

@POBrien333? If it saves you some time I can prepare a full style request for the first journal.

**Comment by rmzelle** [comment]
(and I can generate the second journal style via the "journals" repo)

**Comment by POBrien333** [comment]
I'll make the independent style for the first one. Great if you can add the 2nd one for the automatic generation. :)

**Comment by rmzelle** [comment]
Thanks @POBrien333!
