### ISSUE TITLE
In MLA8, the source field is not being included unless a URL or DOI is present

### ISSUE THREAD

**Issue by lightman76** [citation-style-language/styles#3123]
I created PR #3122 related to this, but adam3smith recommended setting up a discussion for this

The `container2-location` macro is only displaying the `source` when a `URL` or `DOI` is present.  I think this should always be shown.

I might be running into this problem due to confusion in what CSL variables are for what purposes.  I'm using the `source` field as the variable for a database name (Gale, Ebsco, etc) in my CSL integration.  I based this off of the description of the `source` field at http://docs.citationstyles.org/en/1.0.1/specification.html#standard-variables but perhaps I misunderstood the situations in which that should be used.  Should I be using `archive` for these instead?  The documentation makes the `archive` fields appear to be more about physical items/locations.

**Comment by adam3smith** [comment]
No, that's correct, but why would items retrieved from EBSCO or Gale not have a URL? They clearly do and we expect that to be present to identify them as the actual source of the text (as opposed to e.g. a library catalog, which per the specs is also captured in `source`)

**Comment by lightman76** [comment]
I guess that's true.  

The case I was thinking of was where a user uploads a PDF to my system that they retrieved from a database.  They might remember it's from Gale, but not have the URL available when they do this.  I found it a little surprising that Gale didn't show up in the citation unless there was a URL/DOI.  

I concede that this is probably a rare edge case though.  Most of the time they use our tools for capturing PDFs which automatically records the URL.
