### ISSUE TITLE
csl styles with pandoc don't work without internet connection

### ISSUE THREAD

**Issue by lsaravia** [citation-style-language/styles#3131]
I am trying to use some new styles I donwloaded from the repository but when I am offline the following error appears:

pandoc-citeproc: Error parsing XML file journal-of-ecology.csl: FailedConnectionException2 "www.zotero.org" 80 False getAddrInfo: does not exist (Temporary failure in name resolution)

I think this is a problem with new styles that reference other styles on the web, so how can I make these styles internet independent?

**Comment by adam3smith** [comment]
What's the exact command you're using?

**Comment by rmzelle** [comment]
> I think this is a problem with new styles that reference other styles on the web, so how can I make these styles internet independent?

This seems more of a question for the [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc) GitHub repo. I found a related discussion at https://github.com/jgm/pandoc-citeproc/issues/30, but it doesn't look like the issue ever got resolved there.

**Comment by lsaravia** [comment]
The command is:

`pandoc CriticalGF.md -o CriticalGF.pdf -H margins.sty --bibliography CriticalGF.bib --csl=journal-of-ecology.csl --latex-engine=xelatex `

I thought about leaving a question at the pandoc-citeproc but it is not a problem about pandoc because if I use another csl style (an old one) it works. 

This one I downloaded yesterday from the zootero repository does not work:
[journal-of-ecology.csl.zip](https://github.com/citation-style-language/styles/files/1501540/journal-of-ecology.csl.zip)

And this one does I have since dic 2016 works

[global-change-biology.csl.zip](https://github.com/citation-style-language/styles/files/1501547/global-change-biology.csl.zip)

**Comment by rmzelle** [comment]
The "Global Change Biology" style is a so-called "independent" CSL style, which means that it defines its own style format and isn't dependent on another style.

The "Journal of Ecology" style is a "dependent" CSL style, which means that it re-uses a citation format from a different style (in this case, that of independent CSL style https://github.com/citation-style-language/styles/blob/master/apa-old-doi-prefix.csl). It appears that pandoc-citeproc can't handle "dependent" styles when there is no internet connection.
