### ISSUE TITLE
Install your Edited Style with Zotero

### ISSUE THREAD

**Issue by LiangMa2017** [citation-style-language/styles#3249]
Hi, I am trying to Install an Edited Style with Zotero by following https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step. But it can not be added in the repository for using in MS word.

**Comment by adam3smith** [comment]
could you post this to forums.zotero.org with more details (what are you trying, what error message are you getting, etc.)

**Comment by LiangMa2017** [comment]
Thank you. I choose to "manage style" -> choose "Cell" -> "Style Editor" -> "save as" to my PC "C:\Users\liangma1\Documents\zotero_style\1-cell.csl" -> go back to  Cite pane in the Zotero preferences. Click on the “+” sign below the list of installed styles. In the file selection dialogue that opens, navigate to the .csl file you just created and open it. But the new style didn't show up. I tried several times, it's not working. Maybe we can put the new style to Zotero styles install folder, but I didn't find where it is.

**Comment by adam3smith** [comment]
sorry, I wasn't clear on this: This really is not the right place for this question. This is a Zotero question and you should take it to forums.zotero.org

**Comment by LiangMa2017** [comment]
All right. Thank you for your reply.

Best,
Liang

**Comment by rmzelle** [comment]
> I choose to "manage style" -> choose "Cell" -> "Style Editor" -> "save as" to my PC "C:\Users\liangma1\Documents\zotero_style\1-cell.csl" -> go back to Cite pane in the Zotero preferences. Click on the “+” sign below the list of installed styles. In the file selection dialogue that opens, navigate to the .csl file you just created and open it. But the new style didn't show up. I tried several times, it's not working. Maybe we can put the new style to Zotero styles install folder, but I didn't find where it is.

No, don't bother trying to put the style by hand in the Zotero styles folder. It shouldn't make a difference, if it works at all. Installing the style via the Zotero preferences is the way to go.

In general, there are two things that could be causing problems:

* You haven't modified the style ID and title. See https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step#change_the_style_title_and_id for details on how to do this.
* The style isn't valid CSL. You can check this at http://validator.citationstyles.org/. 

If you copy and paste your style at https://gist.github.com/ and give us the link, we'll take a quick look at the style code for you.

**Comment by LiangMa2017** [comment]
Thank you for your suggestions.

Basically, I just revised 'cell' style but just show the first author at
line 60 (see attached). I have tried to add to my style repository but
failed and no error occurred. It works if I add styles by using 'Get
additional style' in your repository (see snapshot below).
<citation et-al-min="3" et-al-use-first="1"
disambiguate-add-year-suffix="true" collapse="year">
[image: Inline image 1]

Best,
Liang

**Comment by rmzelle** [comment]
(you can't email attachments or embedded images on GitHub)

**Comment by LiangMa2017** [comment]
Thanks. I just show I add styles from zotero window 'cite' -> 'get
additional styles'.

**Comment by rmzelle** [comment]
@LiangMa2017, yes, but we'd like to see a copy of your style. Sharing it via https://gist.github.com/ is the easiest way.

**Comment by LiangMa2017** [comment]
Thanks, here is the link:
https://gist.github.com/LiangMa2017/048ffc4009c70401b1ed653d5621e4c5

Best,
Liang

**Comment by rmzelle** [comment]
Great, thanks. So, what you need to do is change

```xml
    <title>Cell</title>
    <id>http://www.zotero.org/styles/cell</id>
```

to something like

```xml
    <title>Cell - custom</title>
    <id>http://www.zotero.org/styles/cell-custom</id>
```

That way Zotero won't confuse your style with the original Cell style.

**Comment by LiangMa2017** [comment]
Thank you so much. That is the reason I cannot add! I need to change the
title to avoid the conflict with 'Cell''.

Cheers,
Liang

**Comment by LiangMa2017** [comment]
Hello Zotero community,
I'd like to use the style of "Molecular Psychiatry", but it is not updated.
For example, your current format is

Paper 1,2



1             Hook PW, McClymont SA, Cannon GH, Law WD, Morton AJ, Goff LA *et
al.* Single-Cell RNA-Seq of Mouse Dopaminergic Neurons Informs Candidate
Gene Selection for Sporadic Parkinson Disease. *Am J Hum Genet* 2018; *102*:
427–446.

2             Zhou F, Li X, Wang W, Zhu P, Zhou J, He W *et al.* Tracing
haematopoietic stem cell formation at single-cell resolution. *Nature*
2016; *533*: 487.

The Molecular Psychiatry format is


Paper [1, 2]

 1.            Anderson CA, Boucher G, Lees CW, Franke A, D'Amato M, Taylor
KD et al. Meta-analysis identifies 29 additional ulcerative colitis risk
loci, increasing the number of confirmed associations to 47*.* Nat Genet.
2011; 43: 246-252.

2.            Buenrostro J, Wu B, Chang H, Greenleaf W. ATAC-seq: A Method
for Assaying Chromatin Accessibility Genome-Wide*.* Curr Protoc Mol Biol.
2015; 109: 21.29.21-21.29.29.


Your format script is as below, could you help me update it?

---------------------

<?xml version="1.0" encoding="utf-8"?>

<style xmlns="http://purl.org/net/xbiblio/csl" class="in-text"
version="1.0" demote-non-dropping-particle="sort-only"
page-range-format="minimal" default-locale="en-GB">

  <info>

    <title>Molecular Psychiatry 20180211</title>

    <id>http://www.zotero.org/styles/molecular-psychiatry-letters-modified
</id>

    <link href="http://www.zotero.org/styles/molecular-psychiatry-letters"
rel="self"/>

    <link href="
http://mts-mp.nature.com/cgi-bin/main.plex?form_type=display_auth_instructions#style"
rel="documentation"/>

    <author>

      <name>Michael Berkowitz</name>

      <email>mberkowi@gmu.edu</email>

    </author>

    <contributor>

      <name>Sean Takats</name>

      <email>stakats@gmu.edu</email>

    </contributor>

    <contributor>

      <name>Sebastian Karcher</name>

    </contributor>

    <contributor>

      <name>Daniel Stjepanovic</name>

      <email>daniel.stjepanovic@gmail.com</email>

    </contributor>

    <category citation-format="numeric"/>

    <category field="medicine"/>

    <issn>1359-4184</issn>

    <eissn>1476-5578</eissn>

    <summary>Vancouver style w/o titles for use in Letters to the Editor to
the Nature journal Molecular Psychiatry</summary>

    <updated>2015-01-01T17:31:53+00:00</updated>

    <rights license="http://creativecommons.org/licenses/by-sa/3.0/">This
work is licensed under a Creative Commons Attribution-ShareAlike 3.0
License</rights>

  </info>

  <macro name="author">

    <names variable="author" suffix=". ">

      <name sort-separator=" " initialize-with="" name-as-sort-order="all"
delimiter=", " delimiter-precedes-last="always"
delimiter-precedes-et-al="never"/>

      <et-al font-style="italic"/>

      <label form="long" prefix=", "/>

      <substitute>

        <names variable="editor"/>

      </substitute>

    </names>

  </macro>

  <macro name="editor">

    <names variable="editor" suffix=". ">

      <name sort-separator=" " initialize-with="" name-as-sort-order="all"
delimiter=", " delimiter-precedes-last="always"/>

      <label form="long" prefix=", "/>

    </names>

  </macro>

  <macro name="publisher">

    <choose>

      <if type="thesis">

        <text variable="publisher-place" prefix="[" suffix="]: "/>

      </if>

      <else>

        <text variable="publisher-place" suffix=": "/>

      </else>

    </choose>

    <text variable="publisher" suffix="; "/>

    <group suffix=". ">

      <date variable="issued">

        <date-part name="year"/>

      </date>

      <text macro="accessed-date" prefix=" "/>

    </group>

  </macro>

  <macro name="access">

    <group>

      <text value="Available from: "/>

      <text variable="URL"/>

    </group>

  </macro>

  <macro name="accessed-date">

    <choose>

      <if variable="URL">

        <group prefix="[" suffix="]" delimiter=" ">

          <text term="cited"/>

          <date variable="accessed">

            <date-part name="year"/>

            <date-part name="month" prefix=" " form="short"
strip-periods="true"/>

            <date-part name="day" prefix=" "/>

          </date>

        </group>

      </if>

    </choose>

  </macro>

  <macro name="journal-title">

    <choose>

      <if type="article-journal article-magazine" match="any">

        <group suffix=" ">

          <text variable="container-title" form="short"
strip-periods="true" font-style="italic"/>

          <choose>

            <if variable="URL">

              <text term="internet" prefix=" [" suffix="]"
text-case="capitalize-first"/>

            </if>

          </choose>

        </group>

      </if>

      <else>

        <text variable="container-title" suffix=". " form="short"
font-style="italic"/>

      </else>

    </choose>

  </macro>

  <macro name="title">

    <group delimiter=" ">

      <choose>

        <if type="book">

          <text variable="title" font-style="italic"/>

        </if>

        <else-if type="article-journal" match="none">

          <text variable="title"/>

        </else-if>

      </choose>

      <choose>

        <if type="article-journal article-magazine" match="none">

          <choose>

            <if variable="URL">

              <text term="internet" prefix="[" suffix="]"
text-case="capitalize-first"/>

            </if>

          </choose>

        </if>

      </choose>

      <choose>

        <if type="thesis">

          <text variable="genre" prefix="[" suffix="]"/>

        </if>

      </choose>

    </group>

  </macro>

  <macro name="edition">

    <choose>

      <if is-numeric="edition">

        <group delimiter=" ">

          <number variable="edition" form="ordinal"/>

          <text term="edition" form="short"/>

        </group>

      </if>

      <else>

        <text variable="edition" suffix="."/>

      </else>

    </choose>

  </macro>

  <citation collapse="citation-number">

    <sort>

      <key variable="citation-number"/>

    </sort>

    <layout delimiter="," prefix="[" suffix="]">

      <text variable="citation-number"/>

    </layout>

  </citation>

  <bibliography et-al-min="7" et-al-use-first="6"
second-field-align="flush">

    <layout>

      <text variable="citation-number" form="long" suffix=". "/>

      <text macro="author"/>

      <text macro="title" suffix=". "/>

      <choose>

        <if type="bill book graphic legal_case legislation motion_picture
report song thesis" match="any">

          <group prefix=" " delimiter=" ">

            <text macro="edition"/>

            <text macro="publisher"/>

            <text variable="number-of-pages" suffix=" p."/>

          </group>

        </if>

        <else-if type="chapter paper-conference" match="any">

          <group prefix=" " suffix=". ">

            <text term="in" suffix=": " text-case="capitalize-first"/>

            <text macro="editor"/>

            <text variable="container-title"/>

          </group>

          <text macro="publisher" prefix=" "/>

          <text variable="page" prefix=" p. " suffix="."/>

        </else-if>

        <else>

          <text macro="journal-title"/>

          <group suffix=";">

            <date variable="issued">

              <date-part name="year"/>

            </date>

            <text macro="accessed-date" prefix=" "/>

          </group>

          <group suffix=". " delimiter=": " prefix=" ">

            <text variable="volume" font-weight="bold"/>

            <text variable="page"/>

          </group>

        </else>

      </choose>

      <text macro="access"/>

    </layout>

  </bibliography>

</style>

---------------------

Thank you,
Liang

**Comment by adam3smith** [comment]
Sorry, I don't quite understand -- do you have a corrected copy of the style and you want us to add it to repository? If so, see here: https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md

If you're just reporting an error in the style (which is great, too), please do so on the Zotero forums at forums.zotero.org

**Comment by LiangMa2017** [comment]
Thank you, I've submitted the discussion at  forums.zotero.org
