### ISSUE TITLE
AMA journal title abbreviation

### ISSUE THREAD

**Issue by amandastevens** [citation-style-language/styles#3255]
The full title of the journal is included in the citation for the AMA style, but in AMA style an abbreviated journal title should be used instead of the full title.

**Comment by adam3smith** [comment]
we'd need more details -- generally the style uses abbreviated journal titles (see https://github.com/citation-style-language/styles/blob/master/american-medical-association.csl#L221 ) so this is most likely an issue with the reference manager you're using. Probably better to start with their support, although if you tell us we may be able to help here, too.

**Comment by johnbarneson1** [comment]
Hi Adam,
I originally noticed the issue and reported it to Amanda. We are running Open Journal Systems (OJS). It's an open source academic journal system written in php. CSL is rendered by a plugin which uses the cite-proc-php library - https://github.com/seboettg/citeproc-php

You can see it here (or on any article in this journal) in the 'How to Cite' block:
https://pubs.lib.umn.edu/index.php/innovations/article/view/933

I'm new to CSL but am happy to provide you with any information. I'm not sure where to start but am familiar enough with php/xml to try to help solve this. Any advice on where to start and what to look for is greatly appreciated.

I will start by digging into the plugin code and finding out how it renders and abbreviated title.

Thanks,
John

**Comment by adam3smith** [comment]
Could you post sample JSON here? Are you sure container-title-short is specified there? I'd assume citeproc-php doesn't automatically abbreviate journal titles, it needs this specified.

**Comment by johnbarneson1** [comment]
I don't have the ability to see the json (the site is hosted at PKP). The plugin uses the api to get the json and renders behind the scenes.

I have found where the OJS plugin is pulling the abbreviated name from. I will forward this on to OJS/PKP.

**Comment by adam3smith** [comment]
Yeah, sorry, can't help further with that, but the style is definitely correct. The data also appears to mess up the DOI (i.e. store it including the URL resolver) which leads to the weird  doi:https://doi.org/10.24926/iip.v8i4.933.
