### ISSUE TITLE
Requested Style: Bulletin of the American Schools of Oriental Research 

### ISSUE THREAD

**Issue by chrismckinny** [citation-style-language/styles#3269]
I am interested in using a style that does not appear in the Zotero CSL repository - BASOR. The biggest problem is the fact that the bibliography is supposed to have the author(s) by themselves on a line and then the year on the line followed by a blank space and then the entry. The closest style that I can find is "American Antiquity" - but the spacing is not quite right and the publisher and location are inverted.

Link to publishing style: http://www.asor.org/wp-content/uploads/2017/04/BASORContributorInstructions.pdf

Link to paper published in BASOR: https://www.academia.edu/18335231/Late_Bronze_Age_Cultic_Activity_in_Ancient_Canaan_A_View_from_Tel_Burna 

In-text citation: 
(Campbell and Peterson 2007)
(Mares 2001)

Bibliography:
Campbell, J. L., and Pedersen, O. K. 
2007 The varieties of capitalism and hybrid success. _Comparative Political Studies_ 40(3): 307–332. https://doi.org/10.1177/0010414006286542
Mares, I. 
2001 Firms and the welfare state: When, why, and how does social policy matter to employers? Pp. 184–213 in _Varieties of capitalism. The institutional foundations of comparative advantage_, eds P. A. Hall & D. Soskice. New York: Oxford University Press.

(note - if possible the citation should be spaced as in the link above; also in the bibliography two authors are separated by a ", and" but more than two authors are separated by a ";" with the final author having "; and" )

**Comment by adam3smith** [comment]
Check again https://github.com/citation-style-language/styles/wiki/Requesting-Styles 
we need the exact two references given there, i.e. the Mares and the Peterson & Campbell, formatted for the style you're requesting

**Comment by chrismckinny** [comment]
My mistake - will fix this.

Chris

**Comment by chrismckinny** [comment]
Updated

**Comment by chrismckinny** [comment]
Thanks so much for your work on this! 

However, I do see several issues with the format related to journal articles.

The journal name should not be abbreviated or shortened. 
The volume number should not be in italics.
The punctuation following the volume number should be a ":" not a ","

Thus the current version (below):
Hisakata, R.; Nishida, S.; and Johnston, A.
2016 An adaptable metric shapes perceptual space. Curr Biol 26, 1911–1915.

Should be the following:
Hisakata, R.; Nishida, S.; and Johnston, A.
2016 An adaptable metric shapes perceptual space. Current Biology 26: 1911–1915.

Also - I am not sure if this is possible or not - but foreign language is particularly important for this style. If possible it would helpful to add a parenthesis at the end when the language is not English. For example:

Hisakata, R.; Nishida, S.; and Johnston, A.
2016 An adaptable metric shapes perceptual space. Current Biology 26: 1911–1915 (French).
