### ISSUE TITLE
Style Request: Anthropologie et sociétés

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#3278]
Requested via citationstyles.org contact form (Wed, Jan 17, 2018 at 7:43 PM):

- Website : https://www.anthropologie-societes.ant.ulaval.ca/
- Online style documentation : https://www.anthropologie-societes.ant.ulaval.ca/sites/anthropologie-societes.ant.ulaval.ca/files/antsoc_normes_editoriales_2014.pdf.
- ISSN 0702-8997 (cf NNL catalgue : https://www.ncbi.nlm.nih.gov/nlmcatalog/101087095)
- Link to a freely available paper formatted with the style > https://www.erudit.org/fr/revues/as/2016-v40-n2-as02669/1037509ar/

> In-text citation:
> (Campbell et Pedersen 2007)
> (Mares 2001)
> 
> Bibliography:
> CAMPBELL J. L. et O. K. PEDERSEN, 2007, « The varieties of capitalism and hybrid success », _Comparative Political Studies_, 40, 3 : 307–332.
> MARES I., 2001, « Firms and the welfare state: When, why, and how does social policy matter to employers? » : 184–213, _in_ P. A. Hall et D. Soskice (dir.), _Varieties of capitalism_. _The institutional foundations of comparative advantage_. New York, Oxford University Press.

**Comment by POBrien333** [comment]
Thanks. Will take care of it :)

**Comment by rmzelle** [comment]
@POBrien333, bump :)

(got pinged by the requestor)
