### ISSUE TITLE
Style Request: Baghdad Science Journal

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#3312]
Title of Journal: Baghdad Science Journal
(P) ISSN:2078-8665
(E) ISSN:2411-7986
URL address for guideline for author: http://www.csw-journal.org/myfile/Guidelines%20for%20Authors%20Baghdad%20Science%20Journal%20E.pdf
Journal language: English
The Journal URL : http://www.csw-journal.org
The issue URL: http://www.csw-journal.org/show-issues.php
Our journal index in:
Road: http://road.issn.org/issn_search?afs:query=Baghdad%20%20Science%20Journal%20&afs:ip=MONIP#.WdyFw7eXfIU
DOAJ: https://doaj.org/toc/2411-7986?source=%7B"query"%3A%7B"filtered"%3A%7B"filter"%3A%7B"bool"%3A%7B"must"%3A%5B%7B"term"%3A%7B"index.issn.exact"%3A"2411-7986"%7D%7D%2C%7B"term"%3A%7B"_type"%3A"article"%7D%7D%5D%7D%7D%2C"query"%3A%7B"match_all"%3A%7B%7D%7D%7D%7D%2C"from"%3A0%2C"size"%3A100%7D
Scopus: http://suggestor.step.scopus.com/progressTracker/index.cfm?trackingID=2679EF0F82748E74

Requested via http://citationstyles.org/contact/#/contact-form

The requestor, the editor-in-chief of the journal, also wrote:

> In the Baghdad Science Journal we used the Imperial College London - Vancouver.
Please, kindly vist the following link: http://www.csw-journal.org/myfile/Guidelines%20for%20Authors%20Baghdad%20Science%20Journal%20E.pdf

So we might be able to just create a dependent style to https://github.com/citation-style-language/styles/blob/master/vancouver-imperial-college-london.csl.

**Comment by POBrien333** [comment]
Grand. I'll look into it :)

**Comment by POBrien333** [comment]
Hi,
Just had a look and there is a bunch of smaller differences between what he wants and what Imperial Vancouver is. 
Could you go back to him and ask him what he wants? I can make a custom style no problem, but it kind of doesn't make sense if he says they're using the Imperial Vancouver style.

**Comment by POBrien333** [comment]
@rmzelle 
Any news on this one?

**Comment by rmzelle** [comment]
> Just had a look and there is a bunch of smaller differences between what he wants and what Imperial Vancouver is.
> Could you go back to him and ask him what he wants? I can make a custom style no problem, but it kind of doesn't make sense if he says they're using the Imperial Vancouver style.

@POBrien333, sorry I didn't get back to you any sooner. What did you end up doing? Should we still contact the journal editor?

**Comment by POBrien333** [comment]
I've just made the style based on their guidelines now. That's what they outline. Their fault if it's wrong.

**Comment by rmzelle** [comment]
Works for me :). Just pinged the requestor, so I'll let you know if we get feedback.
