### ISSUE TITLE
[style request] Biblio 3W

### ISSUE THREAD

**Issue by albertovalzgris** [citation-style-language/styles#3379]
Hi all,

I'm contributing with an article to be published in this journal, currently learning my way through markdown and pandoc exports. I have been browsing the repository and can't find anything matching, yet it would be great to have a suitable .csl instead of hand editing things in the final .doc file in order to match their requirements.

Not sure whether a style request is the correct procedure in this case, so please correct me if I'm wrong. I'd be more than happy to contribute although my coding literacy is close to zero..let's see.

Title of Journal: Biblio 3W. Revista Bibliográfica de Geografía y Ciencias Sociales
ISSN: 1138-9796. 
Depósito Legal: B. 21.742-98
URL address for guideline for author: http://www.ub.edu/geocrit/nrm-b3w.htm
Journal language: English
The Journal URL : http://www.ub.edu/geocrit/bw-22.htm

Cheers!

**Comment by adam3smith** [comment]
See here: https://github.com/citation-style-language/styles/wiki/Requesting-Styles

**Comment by rmzelle** [comment]
@POBrien333, can you add this request to your list?

**Comment by rmzelle** [comment]
@albertovalzgris, we just added a style for Biblio 3W to the repository (courtesy of @POBrien333).

**Comment by albertovalzgris** [comment]
wow, thank you @rmzelle and @POBrien333! 🙏

**Comment by POBrien333** [comment]
@albertovalzgris 
You can always buy me a coffee via https://www.ko-fi.com/damnation333 to show your appreciation ;)
