### ISSUE TITLE
Style verified but not marged (pull request closed)

### ISSUE THREAD

**Issue by mrusiniak** [citation-style-language/styles#3403]
Dear all,

I have submitted the new style:
https://github.com/citation-style-language/styles/pull/3387#pullrequestreview-107608889

However it is not merged and it is closed so I cannot do anything. Please help me on this :)

**Comment by bwiernik** [comment]
The pull request was closed automatically when you deleted the branch. Make a new pull request from the branch.

**Comment by mrusiniak** [comment]
my branch is hanging for a while after completing all automatic tests. Can someone who has rights can merge it to the trunk?

**Comment by POBrien333** [comment]
@adam3smith and @rmzelle 
Any chance we can get this PR reviewed to close this issue? https://github.com/citation-style-language/styles/pull/3387#pullrequestreview-107608889

**Comment by rmzelle** [comment]
Done.

**Comment by POBrien333** [comment]
Ace :)
