### ISSUE TITLE
Style verified but not additional action over 1 month

### ISSUE THREAD

**Issue by cnnsbs** [citation-style-language/styles#3493]
Dear all,

I had submitted the new style 1 month ago. :
#3411 (review)

However, there are no other actions since the bot had reviewed it. 
Is there anything else I need to do to pass?

**Comment by rmzelle** [comment]
Sorry, there are only two (volunteer) maintainers of the style repository, and both of us have been too busy lately to keep on top of all incoming requests. We'll try to take a look soon.
