### ISSUE TITLE
APA output currently generates two part surnames incorrectly

### ISSUE THREAD

**Issue by ryan-p-randall** [citation-style-language/styles#3494]
According to the [APA Style Blog](http://blog.apastyle.org/apastyle/2017/05/whats-in-a-name-two-part-surnames-in-apa-style.html), two part surnames should be cited with the particle before the surname. For instance, Simone de Beauvoir should be `de Beauvoir, S.` and T.A. van Dijk should be `van Dijk, T.A.`.  

The current apa.csl file generates `Beauvoir, S. de.` or `Dijk, T.A. van.` instead.

Thank you for considering a fix for this behavior. I appreciate all the work this team does and am new enough to using these tools that I don't know how to edit csl files myself.

**Comment by rmzelle** [comment]
With Zotero and apa.csl, I get:

>de Jong-Gubbels, P., van den Berg, M. A., Steensma, H. Y., van Dijken, J. P., & Pronk, J. T. (1997). The Saccharomyces cerevisiae acetyl-coenzyme A synthetase encoded by the ACS1 gene, but not the ACS2-encoded enzyme, is subject to glucose catabolite inactivation. FEMS Microbiology Letters, 153(1), 75–81. https://doi.org/10.1111/j.1574-6968.1997.tb10466.x

What software are you using, and how exactly are your names stored in your software? (with Zotero, you would store these names as "de Jong-Gubbels" as last name, and "Patricia" as given name)

**Comment by rmzelle** [comment]
Yes, the pandoc-citeproc repo is probably a better place for this request, as the APA CSL style correctly handles these name particles. See e.g. https://github.com/jgm/pandoc-citeproc/issues/266 and https://github.com/jgm/pandoc-citeproc/issues/95, which seem related to this issue.
