### ISSUE TITLE
Turabian 9th Edition

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#3496]
Has apparently just come out and is updated to conform to Chicago 17th. Would be good to update the style -- maybe just base it on CMoS and adjust as needed. 

If someone with a track record of submitting styles wants to take this on, we can buy you a copy of the manual.

**Comment by rmzelle** [comment]
https://www.amazon.com/Manual-Writers-Research-Papers-Dissertations/dp/022643057X

Looks like it was published on April 16, 2018.

**Comment by rmzelle** [comment]
We also have an author-date version of Turabian, last updated in 2013, that is just labeled `Turabian Style (author-date)` and which is dependent on chicago-author-date (which is now at the 17th edition).

**Comment by BasdeWinter** [comment]
Any progress on this?

**Comment by J-SHarper** [comment]
Any news here?

**Comment by adam3smith** [comment]
Depends on the definition of news/progress. I've bought the manual...

**Comment by icornelius** [comment]
Could we just create a dependent csl for Turabian notes and bibliography, parallel to the one that already exists for Turabian author-date? How close is the alignment between Turabian 9 and CMoS 17?

**Comment by hadleyonfire** [comment]
Is it possible to convert an Endnote style for use in Zotero? They updated to the 9th edition of Turabian back in 2018. https://endnote.com/style_download/turabian-9th-footnote/

**Comment by denismaier** [comment]
No, there's no way to convert an Endnote style to CSL.

**Comment by J-SHarper** [comment]
Any update here? This has been under discussion for over a year.

**Comment by orangecuse44** [comment]
Bump de bump de bump.

**Comment by icornelius** [comment]
I reiterate my suggestion of [8 Sept 2019](https://github.com/citation-style-language/styles/issues/3496#issuecomment-529253747). Turabian9 states that it conforms to CMoS17. If that self-description is accurate, we should just create a dependent csl for Turabian notes and bibliography, parallel to the one that already exists for Turabian author-date.

**Comment by denismaier** [comment]
If Turabian really is identical to CMoS17, that would be the easiest option. To verify I've set up a [testing repository](https://github.com/denismaier/csl-turabian9-fullnote) using [jest-csl](https://github.com/cormacrelf/jest-csl). 

I will see if I can look into this, but help with setting up the tests and the test corpus wouldn't hurt either. 

So, if someone wants to move this forward: I suggest we use the examples from the [citation quick guide](https://www.chicagomanualofstyle.org/turabian/turabian-notes-and-bibliography-citation-quick-guide.html). The first step would be to create items in this [Zotero Group](https://www.zotero.org/groups/2487389/turabian9-fullnote-testdata). From there we'll create the corpus.json files. Then, we'd have to populate `turabian9-fullnote.tests.yaml` with the test.

As I've said, I'll look into this. But it would really help if someone had time to add items to the Zotero group.

**Comment by petersractsfw** [comment]
It's similar, but not exactly identical. I can't enumerate all the differences but one important one is the bibliography. If I create a Bibliography using the CMOS17 style, it does not include the blank line between entries required by Turabian.

It may be better to update the existing Turabian 8th edition style than to adapt the CMOS17.

**Comment by denismaier** [comment]
> If I create a Bibliography using the CMOS17 style, it does not include the blank line between entries required by Turabian.

That's trivial to change and therefore not so important. I think, the more important question is how each reference is rendered.
By the way, one approach can be to set up the tests and a testing library, and then run the tests on both styles, CMoS 17 and Turabian 8. That way we'll see which style is the better fit, or the better starting point for Turabian 8.

**Comment by icornelius** [comment]
Thanks, Denis. I've begun populating the zotero test group.

**Comment by denismaier** [comment]
Great, thanks. I've updated test repo and will assemble some tests tomorrow.

**Comment by denismaier** [comment]
I've just created a few test cases for bibliographic entries: 12 pass, 13 failed.
But: Some of those that fail are actually also wrong for CMoS17, the rules are the same for these. So, if we fix that for Chicago, it will also work here.

**Comment by POBrien333** [comment]
I have made an initial draft of the style, but due to the lack of information and the manual I only made two relatively minor changes. Do test it out and let us know what's missing.

**Comment by adam3smith** [comment]
Thanks -- it's been on my list and I have the manual here, so can check.
