### ISSUE TITLE
Style for Preprints

### ISSUE THREAD

**Issue by St0cc0** [citation-style-language/styles#3585]
Is there some way to create a style for citations of preprint articles? I have had a look around but not seen anything, it would be good if there were a type such as preprint.

**Comment by rmzelle** [comment]
Are you asking with a specific style guide in mind?

It's my understanding that in general, preprints can be saved and cited as a regular journal article. (@adam3smith, correct me if I'm wrong here)

**Comment by bwiernik** [comment]
In some recent discussion, @adam3smith suggested using `article` rather than `article-journal` or `report` for preprints. This seems like a good idea to me: https://forums.zotero.org/discussion/comment/311905#Comment_311905

**Comment by St0cc0** [comment]
Hi, thanks, I should have been clearer from the beginning. I am in the process of modifying a style guide and I would like to make a unique reference style just for preprints, that would be different to how articles/reports are displayed. Judging by the discussion @bwiernik linked to this is not currently possible.

**Comment by bwiernik** [comment]
In terms of CSL, I would recommend item type `article` for preprints.

**Comment by adam3smith** [comment]
Closing this as it's not style specific -- we can add a ticket on the schema repo on preprints
