### ISSUE TITLE
Cleaning up and simplifying APA

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/styles#3591]
I want to clean up and fix some parts of the APA styles and add support for the various types of creators. 

I have a few questions about creator role labels:
1. Is there a way to suppress creator role labels if all of the creators have the same role? For example, when citing musical scores and recordings, APA doesn't require labeling the composer unless there are also creators with other roles, such as librettist, lyricist, or performer.
1. APA generally doesn't require illustrators to be labeled as such. Is there a way to suppress the illustrator label other than to define custom locale terms?

**Comment by adam3smith** [comment]
The answers for these are both that you'd have to test for the creator types, so for
1. You'd have to test for the other creators (though they don't exist in CSL, so not sure how you'd do that anyway?) and for 
2. You'd simply not set a label for `names variable="illustrator"`
