### ISSUE TITLE
Question about gender and <number>

### ISSUE THREAD

**Issue by customcommander** [citation-style-language/styles#3627]
Hi,

As far as I can tell you cannot have a `gender` attribute on a `<number>` rendering element. This style does not validate against the schema for example:

```xml
<style class="note" version="1.0" xmlns="http://purl.org/net/xbiblio/csl">
  <info>
    <id/>
    <title/>
    <updated>2008-10-29T21:01:24+00:00</updated>
  </info>
  <citation>
    <layout>
      <number variable="volume" gender="masculine" form="ordinal" />
    </layout>
  </citation>
</style>
```

Does this mean that CSL processors should always be looking for neuter variant of ordinal terms and fallback to "ordinal"?

If this style was using [locales-fr-FR.xml](https://github.com/citation-style-language/locales/blob/master/locales-fr-FR.xml) for localisation and `volume` was set to `1`, would the expected output be: `1ᵉ`?

Here's the relevant bit from the locale file:

```xml
<!-- ORDINALS -->
<term name="ordinal">ᵉ</term>
<term name="ordinal-01" gender-form="feminine" match="whole-number">ʳᵉ</term>
<term name="ordinal-01" gender-form="masculine" match="whole-number">ᵉʳ</term>
```

Many thanks

**Comment by customcommander** [comment]
I also conducted a search across all styles (at [styles-distribution@71783e2](https://github.com/citation-style-language/styles-distribution/tree/71783e215af89793240bb1677ab753843be4eaa9)) to see how `<number>` is used. I haven't found a single occurrence using gender-specific ordinals.

Cf. attached search report
[number.txt](https://github.com/citation-style-language/styles/files/2234913/number.txt)

**Comment by rmzelle** [comment]
In CSL, locale specific settings (such as gender assignments) are set in the CSL locale files, and/or in the optional `<locale/>` section within the styles themselves. In your example above, you would assign a gender to the volume term as:

```xml
<style class="note" version="1.0" xmlns="http://purl.org/net/xbiblio/csl">
  <info>
    <id/>
    <title/>
    <updated>2008-10-29T21:01:24+00:00</updated>
  </info>
  <locale>
    <terms>
      <term name="volume" gender="masculine">translation of the volume term</term>
    </terms>
  </locale>
  <citation>
    <layout>
      <number variable="volume" form="ordinal" />
    </layout>
  </citation>
</style>
```

**Comment by customcommander** [comment]
I see. Ok makes more sense now. Thanks for the clarification ;)
