### ISSUE TITLE
Future Science group vs journals (dependent)

### ISSUE THREAD

**Issue by POBrien333** [citation-style-language/styles#3643]
Just realised that we have these on our repository:

future-science-group
and
future-science-journals (depedent on ...-group)

Do we need this dependent?

**Comment by POBrien333** [comment]
@rmzelle & @adam3smith, what do you think? Was this on purpose or just an oversight?

**Comment by POBrien333** [comment]
I guess it's not ideal if the bot closes issues before anybody had a chance to look into it, no?

**Comment by rmzelle** [comment]
Removed the style.
