### ISSUE TITLE
use "et al." not "u. a." for HMD

### ISSUE THREAD

**Issue by GeorgLink** [citation-style-language/styles#3685]
The style `HMD Praxis der Wirtschaftsinformatik (German)` currently uses for intext citations `u. a.` to eclipse extra authors but should use `et al.` according to the author guidelines (section: Zietierung im Text): 

https://www.springer.com/computer/journal/40702?detailsPage=pltci_2456704

Screenshot from author guidelines:
![image](https://user-images.githubusercontent.com/8862021/45453670-11d89380-b6a7-11e8-9393-ba06565779c8.png)

**Comment by rmzelle** [comment]
@POBrien333, mind taking a look?

**Comment by POBrien333** [comment]
@GeorgLink 
thanks for pointing out the issue.
I've suggest a fix in #3693.
Could you test out the style by downloading it here? https://github.com/citation-style-language/styles/raw/34951950fac0e4b1c60da2d6b10d9bb3e7105b71/springer-basic-author-date.csl (right click and save as)

**Comment by GeorgLink** [comment]
Thanks @POBrien333! The change works as expected.
