### ISSUE TITLE
Journal of Neurophysiology update

### ISSUE THREAD

**Issue by apstchristensen** [citation-style-language/styles#3701]
Hi, I copy edit [the _Journal of Neurophysiology_](https://www.physiology.org/journal/jn) for [the American Physiological Society (APS)](http://www.the-aps.org/). I probably worked on your manuscript in at least some capacity if you had one accepted by the journal in the last few years. The style posted on here is not quite correct. I believe [this](https://github.com/citation-style-language/styles/blob/master/journal-of-neurophysiology.csl) is the one being used. Would someone help us reorder the in-text reference citations alphabetically first, chronologically second within that? Some of the punctuation in the existing style may also not be correct, and some of these citations can be abbreviated by not repeating in full when only different years need to be given.

The following are a variety of "perfect" in-text citations to help illustrate my request.

> (Grinvald and Hildesheim 2004; Tsytsarev et al. 2009, 2010)

> (Avillac et al. 2005; Cohen and Andersen 2002; Fetsch et al. 2007; Maier and Groh 2009; Pouget et al. 2002)

> (Landis et al. 2012; Morris 2012; Wadman 2013)

> (Bremmer et al. 2002a; Yang et al. 2011)

> (Danner et al. 2009, 2011, 2013)

> (Caballero et al. 2014a, 2014b)

> Logan and Irwin (2000) proposed separate control signals for eye and hand, whereas Boucher et al. (2007b) proposed...

For the bibliography, here are some fresh examples that show our style, minus DOIs and PMIDs that we pull from CrossRef and PubMed, respectively. I notice sometimes we get manuscripts where the years are placed elsewhere, and we also do not use journal print issue numbers or abbreviate the last page number.

> Eide L, McMurray CT. Culture of adult mouse neurons. _Biotechniques_ 38: 99–104, 2005.

> Landis SC, Amara SG, Asadullah K, Austin CP, Blumenstein R, Bradley EW, Crystal RG, Darnell RB, Ferrante RJ, Fillit H, Finkelstein R, Fisher M, Gendelman HE, Golub RM, Goudreau JL, Gross RA, Gubitz AK, Hesterlee SE, Howells DW, Huguenard J, Kelner K, Koroshetz W, Krainc D, Lazic SE, Levine MS, Macleod MR, McCall JM, Moxley RT 3rd, Narasimhan K, Noble LJ, Perrin S, Porter JD, Steward O, Unger E, Utz U, Silberberg SD. A call for transparent reporting to optimize the predictive value of preclinical research. _Nature_ 490: 187–191, 2012.

> Meyer T, Qi XL, Constantinidis C. Persistent discharges in the prefrontal cortex of monkeys naïve to working memory tasks. _Cereb Cortex_ 17, _Suppl_ 1: i70–i76, 2007.

> Mullins PG, McGonigle DJ, O’Gorman RL, Puts NA, Vidyasagar R, Evans CJ, Edden RA; Cardiff Symposium on MRS of GABA. Current practice in the use of MEGA-PRESS spectroscopy for the detection of GABA. _Neuroimage_ 86: 43–52, 2014.

> Pfrieger FW, Barres BA. Synaptic efficacy enhanced by glial cells in vitro. _Science_ 277: 1684–1687, 1997.

> Pierrot-Deseilligny E, Burke B. _The Circuitry of the Human Spinal Cord: Spinal and Corticospinal Mechanisms of Movement_. Cambridge, UK: Cambridge Univ. Press, 2012.

> Ringach DL. Peripheral guidance of cortical organization. In: _The New Visual Neurosciences_, edited by Werner JS and Chalupa LM. Cambridge, MA: MIT Press, 2013.

> Reutens DC, Berkovic SF, Macdonell RA, Bladin PF. Magnetic stimulation of the brain in generalized epilepsy: reversal of cortical hyperexcitability by anticonvulsants. _Ann Neurol_ 34: 351–355, 1993a.

> Reutens DC, Puce A, Berkovic SF. Cortical hyperexcitability in progressive myoclonus epilepsy: a study with transcranial magnetic stimulation. _Neurology_ 43: 186–192, 1993b.

> Rudomin P. Presynaptic selection of afferent inflow in the spinal cord. _J Physiol Paris_ 93: 329–347, 1999.

I registered just to post this humble request, but I've personally admired GitHub for years. If you have any questions or I can be of further assistance regarding this change, please contact me! Thanks, all.

Travis

**Comment by rmzelle** [comment]
@apstchristensen, thanks for contacting us. @POBrien333, mind taking a look?

> I registered just to post this humble request, but I've personally admired GitHub for years.

Yes, we're big fans of GitHub as well. (and just to clarify: none of us, Citation Style Language project members, work for GitHub. We just use the GitHub website as our development platform, like most open source projects do nowadays.)

**Comment by POBrien333** [comment]
Hi @apstchristensen 

sorry I missed this one.
Style fix submitted: https://github.com/citation-style-language/styles/pull/3847

Test: (Campbell and Pedersen 2007; Isaacson 2011; Miller 2000, 2005; Papoulia and Chriazomenou 2013)
Other than that I did rework a few bits of the style to make it more robust, but I did not see any punctuation mistakes. Is that 100% of users that used this CSL style to submit a manuscript?

Also note, there are actually a few mistakes in your guidelines. Specifically regarding chapters. Either pages are missing or they're shown as "p.1-29" without the space.

**Comment by rmzelle** [comment]
@apstchristensen, sorry for the long wait. @POBrien333 just made some corrections to the Journal of Neurophysiology CSL style.

I'll close this issue for now, but feel free to report any further issues with the style here.

**Comment by apstchristensen** [comment]
> sorry I missed this one.

No problem. This has been a short wait, all considered.


> Test: (Campbell and Pedersen 2007; Isaacson 2011; Miller 2000, 2005; Papoulia and Chriazomenou 2013)

Perfect!


> Other than that I did rework a few bits of the style to make it more robust, but I did not see any punctuation mistakes. Is that 100% of users that used this CSL style to submit a manuscript?

Authors submit manuscripts using a variety of CSL styles, some from other publishers that don't match our requirements, as well as manual typing. Having the CSL style for the journal corrected is a massive help.


> Also note, there are actually a few mistakes in your guidelines. Specifically regarding chapters. Either pages are missing or they're shown as "p.1-29" without the space.

I'm not aware of this, but indeed there should be a space there. Here is an example from our style guide:
Frick WF, Puechmaille SJ, Willis CK. White-nose syndrome in bats. In: _Bats in the Anthropocene: Conservation of Bats in a Changing World_. New York: Springer, 2016, p. 245–262. https://doi.org/10.1007/978-3-319-25220-9_9.

Note that this is general American Physiological Society (APS) style rather than specific to _Journal of Neurophysiology_. When it comes to the bibliography section, it is identical in _JNP_ except the list is not numbered (because references are cited in the text by author name and year). Books with chapters should have page numbers and even chapter numbers if available, and there should be a space before the number or range.

Thanks so much, @POBrien333, and to @rmzelle I do know that no one here works for GitHub, which makes your commitment all the more special and appreciated. I was previously expressing my general, long-time admiration for this site, which has only risen.

**Comment by rmzelle** [comment]
You're welcome! Thanks @POBrien333 for helping out with this!

**Comment by POBrien333** [comment]
@apstchristensen 
You're welcome. :)
I've set up a "Ko-Fi" page, if you want to buy me a coffee ;) https://www.ko-fi.com/damnation333
