### ISSUE TITLE
Help change Author's Initials After the Last Name 

### ISSUE THREAD

**Issue by miramire** [citation-style-language/styles#3706]
Hello, I appreciate your help with initializing author's name initials after the last name. 
https://github.com/citation-style-language/styles/blob/master/comision-economica-para-america-latina-y-el-caribe.csl

Thank you very much
Mirian

**Comment by adam3smith** [comment]
sorry you never got an answer on this, but I also don't understand the question -- what are you trying to do in which style?

**Comment by miramire** [comment]
Thank you very much Sebastián. We are trying to change the code of our style (we have it in both English<https://www.zotero.org/styles?q=economic%20comm> and Spanish<https://www.zotero.org/styles?q=cepal>)  in order to change the author information display.

The idea would be to get the reference similar to what the APA style in author display, displaying the  Last name, initial of first name(s) of the author field.
Example: Smith, A., & Jackson, B. S.

At this moment the code of our style displays the full author information.

Do you think you can help us with the coding or recommend some sources in order to make some testing in our code file?

Thank you very much,
Mirian Ramirez
ECLAC Library

**Comment by adam3smith** [comment]
Those are the only two changes? I can make those for you

**Comment by miramire** [comment]
Thank you so much, Sebastian. Yes, Those would be the changes.

**Comment by adam3smith** [comment]
This is now fixed

**Comment by miramire** [comment]
Thank you so much, Sebastian for all your help and support
