### ISSUE TITLE
TravisBuddy

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#3722]
I came across https://www.travisbuddy.com/, which [appears](https://github.com/search?o=desc&q=travis+bot&s=stars&type=Repositories) to be the most popular GitHub/Travis-CI bot.

It seems a bit more advanced than our current https://github.com/citation-style-language/Sheldon tool, as it can leave comments directly in the pull request with Travis build summaries. See https://github.com/bluzi/travis-buddy, as well as https://github.com/bluzi/travis-buddy-jasmine-tests/pull/2#issuecomment-426155983 for a real example. I find the regular Travis build webpages rather intimidating to newcomers, so this seems like it would be a big improvement.

**Comment by adam3smith** [comment]
Given @retorquere 's current work and our limited success with this, I'm going to close it.

**Comment by retorquere** [comment]
I did look at Travis buddy, but it's

* test-framework specific, and rspec wasn't yet supported, so we'd have to add that
* delivering the rendered items didn't seem to fit the way it works.

So all in all it didn't seem to me to be worth going that route.
