### ISSUE TITLE
redundant comma in APA style

### ISSUE THREAD

**Issue by annakuglerin** [citation-style-language/styles#3747]
If an article has two authors there is a redundant comma after the first name, e.g. 

> Huber, **_A.,_** & Mayer, H. (2018). blabla

**Comment by adam3smith** [comment]
No, that's correct, see e.g. https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/reference_list_author_authors.html

The logic here is that the first name is grammatically similar to an apposition and thus enclosed in commas.
