### ISSUE TITLE
Style Error: peerj.csl no periods after name initials

### ISSUE THREAD

**Issue by Nkirc** [citation-style-language/styles#3779]
Hello,

Thank you for maintaining all these citation styles. Could you update the .csl for _PeerJ_? The current .csl iteration has the reference citations looking like this:

> Hisakata R., Nishida S., Johnston A. 2016. An adaptable metric shapes perceptual space. Current Biology 26:1911–1915. DOI: 10.1016/j.cub.2016.05.047.

However, the PeerJ website is now presenting the reference citations without a period after the authors' initials like this:

> Smith JL, Jones P, Wang X. 2004. Investigating ecological destruction in the Amazon. Journal of the Amazon Rainforest 112:368-374 DOI: 10.1234/amazon.15886.

More _PeerJ_ citation info can be found here: [https://peerj.com/about/author-instructions/](url)

Here are two examples of recent PeerJ papers using the lack of periods: [https://peerj.com/articles/5783/](url) and [https://peerj.com/articles/4095/](url)

**Comment by adam3smith** [comment]
Thanks - fixed.
