### ISSUE TITLE
SBL page number

### ISSUE THREAD

**Issue by rudolfbyker** [citation-style-language/styles#3795]
It should be possible to include a specific page number in the SBL "bibliography". For example, on p.46 of the SBL handbook:

![img_1535](https://user-images.githubusercontent.com/10025342/48847215-aa774800-eda9-11e8-8260-0f3a5ddc8b7d.jpg)

Currently the page number only appears in "citation".

**Comment by adam3smith** [comment]
This is a misunderstanding: All the examples with individual page numbers are not for the bibliography, but only for notes, and those can be specified via your reference managers word processor integration.

**Comment by rudolfbyker** [comment]
OK, what do you mean by "notes"? I'm not using this through a reference manager. I'm writing an app using a PHP implementation of CiteProc.

**Comment by adam3smith** [comment]
Notes is what you put in a footnote in SBL style. Page numbers for individual citations can be added to those notes using the `locator` variable in CSL styles (and they are included in the SBL style). In your app, you'd need to find a way to allow for authors to specify these and pass them on to the citeproc. I would recommend looking at some of the existing reference managers and their word integration

**Comment by rudolfbyker** [comment]
Thanks for the tip. I was not aware of the locator variable. I'll try it
soon.

**Comment by rudolfbyker** [comment]
I read the entire CSL 1.0.1 Specification, and it says very little about locators and how to use them. I still did not manage to get them working.

As I already said, I'm using PHP CiteProc. Looking at their examples, they only use "page", and never "locator". See https://github.com/seboettg/citeproc-php/tree/master/example

Their example is for a journal article, using elsevier style:
```json
  {
    "DOI": "10.1016/j.jhydrol.2008.05.025",
    "ISSN": "0022-1694",
    "author": [
      {
        "family": "Cole",
        "given": "Steven J.",
        "id": "steven.j"
      },
      {
        "family": "Moore",
        "given": "Robert",
        "id": "moore.r"
      }
    ],
    "container-title": "Journal of Hydrology",
    "id": "ITEM-3",
    "issue": "3-4",
    "issued": {
      "date-parts": [
        [
          2008
        ]
      ]
    },
    "page": "159-181",
    "title": "Hydrological modelling using raingauge- and radar-based estimators of areal rainfall",
    "type": "article-journal",
    "url": "http://www.sciencedirect.com/science/article/pii/S0022169408002394",
    "volume": "358"
  }
```

Using the following code ...

```php
$dataString = file_get_contents("data.json");
$style = StyleSheet::loadStyleSheet("elsevier-vancouver");
$citeProc = new CiteProc($style, "en-US");
$data = json_decode($dataString);
$bibliography = $citeProc->render($data, "bibliography");
```

... results in this:

```
Cole SJ, Moore R. Hydrological modelling using raingauge- and radar-based estimators of areal rainfall. Journal of Hydrology 2008;358:159-81. https://doi.org/10.1016/j.jhydrol.2008.05.025.
```

Page numbers `159-81` are there as expected.

Changing from `elsevier-vancouver` to `society-of-biblical-literature-fullnote-bibliography` results in this:

```
Cole, Steven J., and Robert Moore. “Hydrological Modelling Using Raingauge- and Radar-Based Estimators of Areal Rainfall”. Journal of Hydrology 358.3-4 (2008): 159-81.
```

The page numbers are still there as expected.

If I now change the type to "book", which is what my users will use most of the time, the page number disappears:

```
Cole, Steven J., and Robert Moore. Hydrological Modelling Using Raingauge- and Radar-Based Estimators of Areal Rainfall. Journal of Hydrology. Vol. 358, 2008.
```

Using "locator" instead of "page" also does nothing.

**Comment by rudolfbyker** [comment]
To be clear, the same happens with 
```php
$bibliography = $citeProc->render($data, "citation");
```

Since CiteProc only has options for "citation" and "bibliography", while SBL speaks of "notes" and "bibliography", I'm assuming "citation" === "notes".

**Comment by adam3smith** [comment]
Right, so locators are only relevant for "citation" you'd only see them working there. How (and whether) citeproc-php expects to receive locator information is a question for that project -- it's not something that the CSL specifications prescribe, so you'd want to ask there.
