### ISSUE TITLE
How to add date of visite at the end of citation like  [Online November 7, 2002]

### ISSUE THREAD

**Issue by EhoumanEvans** [citation-style-language/styles#3819]
My name is Ehouman Evans, I am a phd Student at Nangui Abrogoua University.
Please I need a help in editing csl reference with Mendeley Reference editor. I would like to submit a paper to EcoHealth (https://www.springer.com/public+health/journal/10393?print_view=true&detailsPage=pltci_1060699). It is said to write the reference as in the exemple : Skelly C, Weinstein P (2003) Pathogen survival trajectories: an eco- environmental approach to
the modelling of human Campylobacteriosis ecology. Environmental Health Perspectives
111:19–28; DOI: 10.1289/ehp.5312 [Online November 7, 2002]

I re-edited an APA form and I successfully removed different element however, I don't know how to add the date of viste like this **[Online November 7, 2002]**. 
Thank you for your help and I look forward to hearing from you soon.

**Comment by bwiernik** [comment]
This is the `accessed` variable.

**Comment by EhoumanEvans** [comment]
Thank you very much. I resolved the issue. Kind of you
