### ISSUE TITLE
citation style re-edition_Error  404

### ISSUE THREAD

**Issue by EhoumanEvans** [citation-style-language/styles#3852]
Dear, 
When trying to edit a citation style that I have personally modified, It is impossible to make changes.
I always appear the following message : 
"Cannot fetch style: https://csl.mendeley.com/styles/18459701/apa-3  (Error: 404)

Please select a different style to edit."
Then
"Couldn't fetch page: error"

What is it due to and how could I re-edit my citation style or avoid such issue.

Kind regards, 

Evans, E.

**Comment by adam3smith** [comment]
I'm afraid we can't help with that. The version of the editor at Mendeley.com is run by Mendeley. Contact their support.

**Comment by afnbabfA** [comment]
I have the same problem, could you help me, please?
