### ISSUE TITLE
A problem in american-geophysical-union.csl 

### ISSUE THREAD

**Issue by zhangrite** [citation-style-language/styles#3866]
Hi. I use this style through Mendeley. I find for the reference with the first author named "Zhang", there always a display problem (please see the following reference and the attached capture). Other names are OK. If I turn the name "Zhang" to other names such as "Zhan", the display turns right. How to fix this? Thank you.
![capture](https://user-images.githubusercontent.com/29829877/50893313-eb9fe600-1443-11e9-8371-03e888e0673f.PNG)

Zhang, C. C., Shi, B., Gu, K., Liu, S. P., Wu, J. H., Zhang, S., et al. (2018). Vertically Distributed Sensing of Deformation Using Fiber Optic Sensing. Geophysical Research Letters. https://doi.org/10.1029/2018GL080428

**Comment by rmzelle** [comment]
See https://www.zotero.org/support/kb/given_name_disambiguation for an explanation of why this happens. 

Are you citing any other items that have "Zhang" as the first author? I'm not sure if the style is adding the initial to distinguish C. C. Zhang from S. Zhang in your cited item, or a first-author Zhang in another item.

(see also https://github.com/citation-style-language/styles/blob/fa6831a7062cb23473bea8ba41ffa277a9e4e511/american-geophysical-union.csl#L663, http://docs.citationstyles.org/en/1.0.1/specification.html#disambiguation, and https://publications.agu.org/agu-grammar-and-style-guide/; the latter says "In-text references should always include the first initials (even when year of publication is different) to avoid ambiguity.")

**Comment by zhangrite** [comment]
I got it. Thank you for your detailed reply.
