### ISSUE TITLE
apa.csl author disambiguation

### ISSUE THREAD

**Issue by kenjmatthews** [citation-style-language/styles#3873]
I have two authors with the same surname. 
Cheung, M W.-L
Cheung, S. F.

In-text citations only add initials to M W.-L. citations. In APA, however, initials should be added to each author. I corrected this by changing the rule to "all-names." I'm not a csl expert so I don't know if my change will introduce new issues, but I'm not seeing any in my document.

**Comment by adam3smith** [comment]
No, the rule definitely needs to be primary, i.e. only first authors receive initials, for APA. `all-names` also adds initials for authors listed in 2nd, 3rd, etc. position, which is incorrect for APA.

If only one of two identical (first author) names receives initials in the text with the current APA style,  that's a bug in the reference manager you're using, so best to report to their forum/their support.
