### ISSUE TITLE
New Style: Science Advances

### ISSUE THREAD

**Issue by psychelzh** [citation-style-language/styles#3881]
Based on [the instructions](http://advances.sciencemag.org/content/information-authors) of this journal, it is a little different from the style of **Science**. Specifically,

> **Science Advances** uses a complete citation format that includes all authors, full titles of journal articles, the journal abbreviation, the volume, the first and last page, and the year of publication. The absolute formatting (what is bold and what is italic) is less important than having a complete citation for each journal article cited.

>The abbreviations for journal names are taken from the Bibliographic Guide for Editors and Authors (BGEA) or Serial Sources for the BIOSIS Data Base *(BIOSIS), a more recent publication. When in doubt, provide the journal’s complete name. Spell out cities that are listed after a journal name: *Acta Zool. (Stockholm). Do not use op. cit., ibid., 3-m dashes, en dashes, or et al. (in place of the complete list of authors’ names). For author names with Jr. or 2nd, etc. see example number 4 in the Journals section.

>In references to books or chapters in books, publisher names are given in shortened form. “Press” is usually dropped. Exceptions: Academic Press (“Academic” is an adjective), Cold Spring Harbor Laboratory Press, National Academies Press, University Park Press, CRC Press, MIT Press, and Cambridge Univ. Press (for university presses, to distinguish them from the university itself). Only one publisher city is needed. A few world-renowned cities (for example, Amsterdam, London, Philadelphia, Chicago, New York, Baltimore) can be listed without state or country; less well-known cities and those with names that could be confused take state abbreviations (Cambridge alone for the city in the U.K., but Cambridge, MA). Inclusive page numbers or a chapter number must be given when specific articles are referred to within an edited volume.

**Comment by bwiernik** [comment]
Based on the description you are giving, the existing submission style for Science (which has titles and which is what the existing Science Advances style points to) fits all these requirements to the degree possible by CSL (e.g., CSL can't do things like drop "Press" or country names if they are supplied, but my understanding of Science's policies is that they aren't too concerned about that).

https://www.zotero.org/styles/science

**Comment by psychelzh** [comment]
I do not know if I am correct. I think seemingly **Science** and **Science Advances** both requires to include all authors, just like:

> I. Friso-van den Bos, E. H. Kroesbergen, J. E. H. Van Luit, I. Xenidou-Dervou, L. M. Jonkman, M. Van der Schoot, E. C. D. M. Van Lieshout, Longitudinal development of number line estimation and mathematics performance in primary school children. J. Exp. Child Psychol. 134, 12–29 (2015).

But currently, they are both like this:

> I. Friso-van den Bos et al., Longitudinal development of number line estimation and mathematics performance in primary school children. J. Exp. Child Psychol. 134, 12–29 (2015).

**Comment by bwiernik** [comment]
Ah, so the issue with the style you are raising is et al. The style is currently set to use et al when there are six or more authors. The guidelines for Science (which Science Advances just copies—they use the same style) say to not use “et al”, but in the example citations, they do in fact use et al for examples with six or more authors. 

As far as I know, there has never been a complaint about this from the Science publication office, and at some point et al is certainly necessary (it is not uncommon for articles with 1000s of authors to be cited in Science journals), so my recommendation is to leave the style as it currently is, considering that it follows the examples given by the journal.

**Comment by rmzelle** [comment]
No strong feeling either way. I checked a few recent articles to see what ends up in print:

https://doi.org/10.1126/sciadv.aav4020 (Science Advances; doesn't use et al. even for items with over 15 authors)

https://doi.org/10.1126/science.aap8586 (Science; big differences between HTML and PDF versions, both use et al., but PDF is much more aggressive, and doesn't even show titles for most items)
