### ISSUE TITLE
Style Request: Chemical Engineering Progress

### ISSUE THREAD

**Issue by qwertyuser1983** [citation-style-language/styles#3900]
Reference
https://www.aiche.org/file/6530/download?token=obL_5H_q

In-text citation:
[1]
[2]

Bibliography:
1. 	**Campbell, J. L., and O. K. Pedersen**, "The varieties of capitalism and hybrid success. Comparative Political Studies", 40(3), 307–332. https://doi.org/10.1177/0010414006286542 (2007).
2. 	**Mares, I.**, "Firms and the welfare state: When, why, and how does social policy matter to employers?" In **P. A. Hall & D. Soskice eds.**, "Varieties of capitalism. The institutional foundations of comparative advantage" pp. 184–213. New York: Oxford University Press (2001).

I am not sure the in text citation and the 2nd reference is correct.

Should be indented. Don't know how to make it in GitHub. 

I may be wrong in representing the Campbell Mares example. 

The search gave the highest similarities to Cambridge University Press (numeric)

**Comment by adam3smith** [comment]
@qwertyuser1983 the samples you provide aren't terribly close to the style you're requesting -- e.g. missing quotation marks, bolded volumes, periods instead of commas, etc. Could you please revisit those -- the samples only save us time if they're accurate.

**Comment by qwertyuser1983** [comment]
> @qwertyuser1983 the samples you provide aren't terribly close to the style you're requesting -- e.g. missing quotation marks, bolded volumes, periods instead of commas, etc. Could you please revisit those -- the samples only save us time if they're accurate.

Thanks for the catch, sorry for late reply. 

I have updated the samples.

Renan

**Comment by POBrien333** [comment]
Thanks for sending in the request. I've put it on the todo list. Will take a bit of time though. Quite a bunch of requests outstanding and my job search is currently priority number 1. :)

**Comment by rmzelle** [comment]
> my job search is currently priority number 1.

Good luck!

**Comment by rmzelle** [comment]
@qwertyuser1983, I just added a CSL style for this journal to the repository (prepared by @POBrien333).

**Comment by qwertyuser1983** [comment]
Ahh, sorry for late reply. 

I have checked just now, and they work perfectly. 

Many thanks! ;)

Renan
