### ISSUE TITLE
Upload to ZOTERO new style for TGM diploma thesis

### ISSUE THREAD

**Issue by gschachinger** [citation-style-language/styles#3921]
Dear all,
would you be so kind to upload this new citation-style from our organisation TGM  to ZOTERO online style list to be used by our students for their diploma thesis (an all other interested people), because we do not know how to do it.
Thank you very much for your help.

KR gschachinger

[tgm_katigel_diplomarbeit_vereinfachte-zitierregel-nach-onorm.zip](https://github.com/citation-style-language/styles/files/2848183/tgm_katigel_diplomarbeit_vereinfachte-zitierregel-nach-onorm.zip)

**Comment by adam3smith** [comment]
Superseded by https://github.com/citation-style-language/styles/pull/3924
