### ISSUE TITLE
Retrieved <date> missing in american-sociological-association.csl

### ISSUE THREAD

**Issue by jaySf** [citation-style-language/styles#3923]
First of all thank you for taking care of all the `*.csl`s!

I'm using [your latest ASA style](https://github.com/citation-style-language/styles/blob/master/american-sociological-association.csl) (_asa.csl_). According to ASA style guide a website should be cited

> The University of Chicago Press. 2019. "Chicago-Style Citation Quick Guide." Retrieved February 10, 2019 (https://www.chicagomanualofstyle.org/tools_citationguide.html).

however with _asa.csl_ the result is just:

> The University of Chicago Press. 2019. "Chicago-Style Citation Quick Guide."  

This is how the `*.bib`-file looks:

```
@misc{the_university_of_chicago_press_chicago-style_2019,
	title = {Chicago-{Style} {Citation} {Quick} {Guide}.},
	url = {https://www.chicagomanualofstyle.org},
	abstract = {Find it. Write it. Cite it. The Chicago Manual of Style Online is the venerable, time-tested guide to style, usage, and grammar in an accessible online format. ¶ It is the indispensable reference for writers, editors, proofreaders, indexers, copywriters, designers, and publishers, informing the editorial canon with sound, definitive advice. ¶ Over 1.5 million copies sold!},
	language = {en},
	urldate = {2019-02-10},
	author = {{The University of Chicago Press}},
	month = feb,
	year = {2019},
	file = {Snapshot:C\:\\Users\\jay\\Zotero\\storage\\GDVNXDRS\\tools_citationguide.html:text/html}
}
```
I'm using R with Rmarkdown, specify `csl: "../R/tex/asa.csl"` in the YAML header, and add `<div id="refs"></div>` at the end after references header.

Since Rmarkdown uses [Chicago author-date format for citations and references](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_styles) by default and at least the link appears in the references if no explicit `*.csl` is specified, the issue might be related to the _asa.csl_.

`sessioninfo()` yields:

```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.2  backports_1.1.3 rprojroot_1.3-2 htmltools_0.3.6 tools_3.5.2    
 [6] yaml_2.2.0      Rcpp_1.0.0      rmarkdown_1.8   knitr_1.21      xfun_0.4       
[11] digest_0.6.18   evaluate_0.12  

> rmarkdown::pandoc_version()
[1] ‘1.19.2.1’

# MiKTeX 2.9
```

It would be great if you could look into this issue, thanks!

**Comment by adam3smith** [comment]
The ASA CSL style (though note that the file name is american-sociological-association.csl , not asa.csl) will print the retrieved date and URL for webpages and blogposts. The problem here is almost certainly the translation (by pandoc) of bibtex to CSL JSON, the input format used for CSL styles. I assume `@misc` isn't translated into `webpage` but into something more generic (since bibtex is from the mid 80s, there is no item type for webpages). If you're able to use biblatex instead (and `@online` there) that would likely work. Similarly, using CSL JSON directly would work if you're e.g.getting the data from Zotero.

**Comment by jaySf** [comment]
Thanks for your prompt answer! I use biblatex now to be a little bit better up to date - works perfectely!
