### ISSUE TITLE
Style Request: [Materials Energy Today] - CSL

### ISSUE THREAD

**Issue by d1xenotime** [citation-style-language/styles#3931]
Hello everyone I am new to GitHub and I hope I am at the right place. 

I am a Mendeley user. I am working on a paper to publish in "Materials Today Energy [https://www.elsevier.com/journals/materials-today-energy/2468-6069/guide-for-authors](url)". I spent 3 days figuring out the Visual CSL Editor with no luck. 

I looked at the main page https://github.com/citation-style-language/styles which landed me here. Following some of the instruction, I ended up visiting https://www.zotero.org/styles which has the Style but... When loaded on the "Visual CSL Editor" - redirected via Mendeley, I was unable to open up the CSL code... 

May someone tell me what I am doing wrong? Would anyone know if there is a CSL version or equivalent for Materials Today Energy style?

Thank you very much

**Comment by adam3smith** [comment]
"Materials Today Energy" uses a standard Elsevier style that's called "Elsevier (numeric, with titles)". You should be able to find that in Mendeley (as well as the visual editor if you need to make changes to it).

I don't know why you can't find the style in Mendeley proper -- it should be available there, too, but that's a question for Mendeley support.

**Comment by d1xenotime** [comment]
Hello Adam, thank you so much for the quick response. I did not expect such a quick reply. 

I will give the "Elsevier (numeric, with titles)" style a try. I can see it when doing the search. I did not know they were related. I will give it a go! Cheers.  

I am very inexperience in CSL editor.
