### ISSUE TITLE
Update brain.csl style

### ISSUE THREAD

**Issue by alapo** [citation-style-language/styles#3949]
Brain (brain.csl) has updated their template since the last release. The letters following the year should now be italicized. Additionally only the letter should be highlighted. I have added a photo below of the current csl document (left) and what it should be (right)

![img](https://i.imgur.com/VFTtafY.png)

Below I have uploaded the template which was emailed to me by the editor recently.
[Brain_template.docx](https://github.com/citation-style-language/styles/files/2894345/Brain_template.docx)

**Comment by rmzelle** [comment]
@alapo, thanks for reporting. @POBrien333 has made the change.
