### ISSUE TITLE
DOI format for Springer Styles

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#3956]
https://forums.zotero.org/discussion/76159/style-error-climate-dynamics#latest reports that at least one journal is using the modern (https://doi.org/) DOI format. I think we can safely switch this across all Springer parent styles.

**Comment by bwiernik** [comment]
The LNCS Springer style should also apparently have DOIs https://forums.zotero.org/discussion/76224/springer-lncs-web-sources-including-doi
