### ISSUE TITLE
Chemosphere is not need the author in the main text

### ISSUE THREAD

**Issue by tetrar124** [citation-style-language/styles#3959]
Dear contributors,

Chemosphere does not need the author in the main text, but this csl file has an author region.
Would you please change it?

It is difficult for me to understand writing method for this csl.

**Comment by adam3smith** [comment]
Sorry, I'm not quite sure what you're requesting. The ]Chemosphere author guidelines](https://www.elsevier.com/journals/chemosphere/0045-6535/guide-for-authors), while specifying that no specific citation style is required, do list an author-date style, which is what CSL has for the journal. If you want a different citation style, given the journal's policy, you can just pick any other style.

**Comment by tetrar124** [comment]
I checked 5 papers on Chemosphere, two papers are only years, and the other papers are mixing year and author.
I will change it manually.
