### ISSUE TITLE
Chinese Std GB/T 7714-2015 has updated, but there is still GB/T 2005

### ISSUE THREAD

**Issue by Eternal-Br** [citation-style-language/styles#3970]
Chinese journals has updated the styles,who can help us update the GB/T 7714-2005 to GB/T 7714-2015?
Thanks so much! 
And this link can be a reference for GB/T 2015 : https://github.com/CTeX-org/gbt7714-bibtex-style

**Comment by jinlin82** [comment]
I need GB/T 7714-2015 csl file, too.
I am very appreciated if there is an update of GB/T 7714-2005.
Thanks so much!
