### ISSUE TITLE
Vancouver style with three author

### ISSUE THREAD

**Issue by WeiCSong** [citation-style-language/styles#3980]
Hi all, i'm writing script for british journal of oral and maxillofacial surgery. The journal requires vancouver style with three authors at most. However, i found only Vancouver style with 6 authors at most in mendely. Which style shall i install? Thank you!

**Comment by rmzelle** [comment]
Hi, sorry for the slow response. You can request a custom style for this journal by following the instructions at https://github.com/citation-style-language/styles/wiki/Requesting-Styles#requesting-a-new-style.
