### ISSUE TITLE
Style dev assist: tests with watch

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/styles#3994]
Something like this might already exist, but here goes.

I've finally gotten around to rewriting the citeproc-js test runner in Node.js. (It's been a long time coming, I know.) Looking at the work on APA at #3602, I'm thinking that some small changes to the script might help lighten development for complex styles.

The idea would be to set up a separate area in the citeproc-js repo for style folders, and add two options to the script:
* **-S** to instruct the script to run tests from a particular style's folder, and
* **-w** to instruct the script to watch for changes in a style file being edited.

Script would then poll for changes to the style, and rerun the tests when change is detected, to provide alerts of collateral changes that a given change might have, without keyboard/mouse back-and-forth. Kind of Zotero Style Editor on steroids/NTZ.

I've used manually run processor test fixtures here for a style project recently, and it worked quite well. Watch monitoring would lighten the process further.

Thoughts? Rotten tomatoes?

**Comment by bwiernik** [comment]
This would be really cool. I would love to set up all of the tests for APA style.

**Comment by fbennett** [comment]
Here you go: https://github.com/Juris-M/citeproc-js/#citeproc-js

**Comment by adam3smith** [comment]
@rmzelle not sure if we can apply Stalebot to PRs only?

**Comment by rmzelle** [comment]
> @rmzelle not sure if we can apply Stalebot to PRs only?

We could: https://github.com/probot/stale/commit/26a21235d26cd48706b561608757e5c703d409f7#diff-04c6e90faac2675aa89e2176d2eec7d8R32

**Comment by adam3smith** [comment]
What do you think? I don't mind issues staying open for a long time, especially something like this. It's the PRs where the bot really helps.
