### ISSUE TITLE
Make it clear where to discuss a style

### ISSUE THREAD

**Issue by jameshowison** [citation-style-language/styles#40]
At the moment the general advice seems to be, "In the Zotero Styles Forums".  That's fine as far as it goes, but there is a lot of noise there and noI think it would be great if every style file on http://zotero.org/styles or https://github.com/citation-style-language/styles had a link to a specific (sub)-forum to discuss it.  Maybe a tracker system so that previous discussions can be referenced?  Hmmm, maybe this is really a request to the Zotero forums, but one placed I looked for this was in the metadata of a CSL style.

**Comment by rmzelle** [comment]
FWIW, Mendeley has introduced a form to report style problems: http://support.mendeley.com/customer/portal/articles/1392513-i-would-like-to-report-an-incorrect-citation-style-in-mendeley-

(@adam3smith deals the reports that come in from there)

**Comment by adam3smith** [comment]
that's working very well, btw. About 1-2/month on average, about 2/3 of them actual style errors.
