### ISSUE TITLE
C# PROBLEM TO SAVE DATA IN THE TABLE

### ISSUE THREAD

**Issue by anasssssssss** [citation-style-language/styles#4006]
I need urgent help in the visual studio 2015: I build windows application using C# to build database and I want insert data to the local table. the problem is: when (after run the project) I add record to DataGridView and save it, I see the inserted data in DataGridView, but when I exit all the data lost in the local table (not saved)????

Same problem when I build Access table, I used the following code for it:

private void button1_Click(object sender, EventArgs e)
        {
            OleDbConnection Con = new OleDbConnection("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=|DataDirectory|student.accdb");
            Con.Open();
            try
            {
                OleDbCommand Com = new OleDbCommand("Insert into student(ID,first_name,last_name) values(@ID,@first_name,@last_name)", Con);
                Com.Parameters.AddWithValue("@ID", textBox1.Text);
                Com.Parameters.AddWithValue("@first_name", textBox2.Text);
                Com.Parameters.AddWithValue("@last_name", textBox3.Text);

                Com.ExecuteNonQuery();
                studentBindingSource.EndEdit();
                studentTableAdapter.Update(this.studentDataSet.student);
                          MessageBox.Show("Registration successfull");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                studentBindingSource.ResetBindings(false);
            }
            Con.Close();
        }

**Comment by adam3smith** [comment]
I'm pretty sure you're in the wrong place. Check the repository content. If I'm wrong and this is, in fact, related to the citation style language, you'd have to provide more background.
