### ISSUE TITLE
New style for the Faculty of biology and medicine at Lausanne University (UNIL)

### ISSUE THREAD

**Issue by alerac** [citation-style-language/styles#4031]
Hello,

I tried to update the thread on my pull request to get more info about the eligibility of our style. I open a new issue with the thread referenced here.

Please let me know if it is not the right way to do so.

Best,

Alex

-----------------------------------------------------------------------------------------------------

Hello,

Do you think there is a chance that our vancouver style for the students of the faculty of Biology and Medicine at the Lausanne University (UNIL) would be accepted into the Zotero repository ?

The CSL style did pass all the automated checks last week but I was wondering if maybe I had to make other corrections. Or if you consider this style would not be eligible ?

Many thanks for all your work.

Alex

_Originally posted by @alerac in https://github.com/citation-style-language/styles/pull/3952#issuecomment-470148487_

**Comment by adam3smith** [comment]
The style is now merged.
