### ISSUE TITLE
harvard-university-of-sunderland.csl - could you please remove it?

### ISSUE THREAD

**Issue by DRmarkp** [citation-style-language/styles#4058]
harvard-university-of-sunderland.csl **- I'm not setting out to offend anyone, but could you please remove this style?**

- I am Dr Mark R Proctor at the University of Sunderland (UK) and there is currently an issue with our students thinking that the above online style has been created 'officially' by the University of Sunderland in the UK.

- The issue is that the style is actually a mixture of styles. e.g. even looking at the preview - you can see one type of reference has full-stops both sides of the brackets surrounding the year which makes this reference type inconsistent with the other ones in the preview. And I found a lot of other issues with it when I looked at the style years ago, which is why I created another style for PhD students at the University of Sunderland.

-  My style has been working reasonably well for PhD students at https://goo.gl/Mi7MUV which could be uploaded instead. This version took me a several weeks of my time to modify so it works for a range of styles. 

- The style I created (by modifying another style) is based on the 9th Edition of Cite Them Right, it was created using the Mendeley editor, and the style can be used to create a decent representation of the Harvard type of style shown at https://www.citethemrightonline.com/ . However, it is not compliant with the style standards and gives a warning when introducing it into Zotero which is why I have not uploaded it so far. Please let me know if it would be advisable or even possible to upload this instead? I will be happy to have my name associated with it.

**Comment by adam3smith** [comment]
Happy to try to resolve this, yes. Two options:
1. If you want to use your style, if you could add it following these instructions: https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md, we can help you with the validation

2. Alternatively, we have a well-developed style for Cite Them Right (10th edition) https://www.zotero.org/styles?q=id%3Aharvard-cite-them-right . If Sunderland simply follows that style, we could swap the current style with a link to the existing Cite Them Right style. 

Both options would work for us; you're probably a better judge of what will work best for your students.

**Comment by DRmarkp** [comment]
Oh, Thank you very much. I will check out your style and add my own if it is significantly different. 
Will you still look into removing the other style I identified in this discussion thread?

**Comment by adam3smith** [comment]
Unless this takes very long, replacing the style is easier than removing it, so I'd prefer to do that -- the end result would still be that the current version of it is no longer accessible, though.

**Comment by DRmarkp** [comment]
OK,
Thank you. I'll look into replacing the style with the one I and the
students use.
Thank you.
Mark

**Comment by adam3smith** [comment]
@DRmarkp did you get a chance to compare your style to our Cite Them Right? As you note above, this issue is currently causing confusion among your students and I'd love to see it resolved.

**Comment by rmzelle** [comment]
@DRmarkp, since https://library.sunderland.ac.uk/find-resources/referencing/ just points to the Cite Them Right website, one of my fellow volunteers changed harvard-university-of-sunderland.csl to use the same citation format as our harvard-cite-them-right CSL style (it's now just an alias pointing to the latter style).

**Comment by DRmarkp** [comment]
Wonderful.
Many thanks.
Mark
