### ISSUE TITLE
modern-humanities-research-association.csl

### ISSUE THREAD

**Issue by MartinPaulEve** [citation-style-language/styles#4062]
I think this might be a recurrence of https://github.com/citation-style-language/styles/issues/1672 but currently modern-humanities-research-association.csl is not appending issue after volume for some reason (i.e. it gives "27" rather than "27.1").

The same metadata fed into modern-humanities-research-association-author-date.csl is producing the volume.issue format.

**Comment by MartinPaulEve** [comment]
HI @adam3smith -- just to check here -- you removed my conditional for issue, which means that if there is no issue specified, it will render the "." without a trailing issue number, I believe...?

**Comment by adam3smith** [comment]
No -- the delimiter only gets placed _between_ the two items in the group, i.e. won't show up if either is absent. That's why there's no need for the conditional.

**Comment by MartinPaulEve** [comment]
Apologies - my bad!

**Comment by adam3smith** [comment]
Nothing to apologize for -- thanks for the PR.
