### ISSUE TITLE
Film References in mhra style are Incorrect

### ISSUE THREAD

**Issue by MHRAuser** [citation-style-language/styles#4085]
Hi there, 

I've noticed for a long time that the film citations in MHRA are incorrect. I have zero coding experience and no time nor desire to learn. I thought I would be able to just report the error to Mendeley support and they'd get it fixed, but they directed me here. I just want to get these film citations to come out correctly without having to manually edit each citation. Can anyone help me out?

The layout should be: _Film Title_, dir. by Director's Name (Distributor Name, Date) [format].

Instead I get: Director's Name, _Film Title_ (Distributor Name, Date).

What do I have to do to get this fixed?

Thanks.

**Comment by POBrien333** [comment]
@MHRAuser 
Hi,
I don´t have access to the guidelines. Could you quote the section from the MHRA guidelines here?
Thanks

**Comment by MHRAuser** [comment]
For films, the reference should include, as a minimum, title, director,
distributor, date, e.g.:
_The Grapes of Wrath_, dir. by John Ford (20th Century Fox, 1940).
Names of artists may be given after that of the director. First names may
be omitted if not deemed necessary. If a video reference is available, it
should be added at the end.
