### ISSUE TITLE
Citation Problem With Collab

### ISSUE THREAD

**Issue by getmohanraj95** [citation-style-language/styles#4097]
Hi Team
 
         I have Problem multi site with collaborate and Author same year. below details

Actual result:
===========
​Gil, 2018, Health Care Cost Institute​ 

Excepted result:
=============
​Gil, 2018, Health Care Cost Institute​ 2018

My Cite Code is
=============
<citation et-al-min="3" et-al-use-first="1" disambiguate="true" disambiguate-add-year-suffix="true" collapse=**"year-suffix-ranged"** cite-group-delimiter=", ">

Year-suffix-range option must here, if i set year working fine but same time range affected. so please help how i resolve this.

Thanks
mohan

**Comment by adam3smith** [comment]
Sorry, we'd need to see a whole style. I'm also not sure what "Collaborate" refers to?

**Comment by biosainik** [comment]
@getmohanraj95 please place your comment clearly.

**Comment by POBrien333** [comment]
@getmohanraj95 
Pinging you here in case you didn´t see the reply.
