### ISSUE TITLE
din-1505-2-alphanumeric  empty brackets

### ISSUE THREAD

**Issue by bjuergens** [citation-style-language/styles#4121]
"din-1505-2-alphanumeric" is broken. The brackets are always empty. 

### example
![grafik](https://user-images.githubusercontent.com/4362465/58472525-b8d26200-8146-11e9-9770-f1795b65abd5.png)

When I use an other CSL (iso690-author-date-en in this case) for the same document it looks fine: 

![grafik](https://user-images.githubusercontent.com/4362465/58471904-48771100-8145-11e9-955e-c39cfd18bbd1.png)

### reproducing the example

    cd example
    wget https://www.zotero.org/styles/din-1505-2-alphanumeric
    wget https://www.zotero.org/styles/iso690-author-date-en
    pandoc --bibliography=file.bib  --csl=din-1505-2-alphanumeric file.md -o out1.html
    pandoc --bibliography=file.bib  --csl=iso690-author-date-en file.md -o out2.html

`example/file.md`: 
```
# Content

paper 1: [@small]

paper 2: [@big]

# References
```

`example/file.bib`: 

```
%  a sample bibliography file
%

@article{small,
author = {Freely, I.P.},
title = {A small paper},
journal = {The journal of small papers},
year = 1997,
volume = {-1},
note = {to appear},
}

@article{big,
author = {Jass, Hugh},
title = {A big paper},
journal = {The journal of big papers},
year = 7991,
volume = {MCMXCVII},
}
```

pandoc-version: 

```
pandoc --version
pandoc 2.2
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.7.0.2
Default user data directory: /home/bjoern/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by adam3smith** [comment]
Sorry, overlooked this, but the style is fine.
`<text variable="citation-label"/>`  (which the style uses) is simply not defined in the citation data. citeproc-js defines `citation-label` automatically. I think for citeproc-pandoc it actually makes more sense to have it be user defined, which makes it more flexible.
