### ISSUE TITLE
Event issues

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/styles#4126]
Ran across some weird output with apa.csl today.

For this item:
Wang, Y., et al. (2019, October). Mobile sensor markers: Theoretically oriented? Data-driven? Replicable? In D. S. Ones (Chair), Measuring psychological variables using mobile sensing technologies: Modeling Big Data and implications for research and designing intelligent support for wellbeing and productivity at work. Symposium presented at the Technology, Mind and Society Conference, Washington, DC.

I had forgotten to enter the meeting name, so this output was produced:
Wang, Y., et al. (2019, October). Mobile sensor markers: Theoretically oriented? Data-driven? Replicable? In D. S. Ones (Chair), Measuring psychological variables using mobile sensing technologies: Modeling Big Data and implications for research and designing intelligent support for wellbeing and productivity at work. Symposium presented at the Washington, DC. Washington, DC.

Two issues:
1. "Symposium presented at the Washington, DC" isn't grammatical and should just be "Symposium presented at Washington, DC". Non-English locales don't have an article in the `presented-at` term, but I don't think it's a good idea to change English term now. Is there anything to be done here or do we just ignore this unusual case? I suppose the main reason you would have a `speech` item without `event` would be for something like "Invited lecture presented at the Department of Psychology…", so keeping "the" for those cases would probably be fine. 

1. Washington, DC is printed twice. This occurs because Zotero maps Place to both `event-place` and `publisher-place`. The style tests for `event` in the publisher macro to suppress the second printing. I could add a similar test to `event` macro, but I wonder if it would just be better to wait for Zotero to fix its field mapping in Zotero 5.1?

**Comment by bwiernik** [comment]
@adam3smith Any thoughts on these two questions?

**Comment by POBrien333** [comment]
I just noticed that issue 2 is still an issue. Is this incorrect/duplicated fieldmapping for event-place something we should ask to get fixed?

**Comment by bwiernik** [comment]
Yeah let's raise it to Dan and the Zotero folks now that they have begun updating field mappings
