### ISSUE TITLE
Please clarify extend of "derived work" of CC-BY-SA license

### ISSUE THREAD

**Issue by nhnb** [citation-style-language/styles#4129]
Hi,

please clarify the extend of which "derived work" of the CC-BY-SA applies to users of CSL. It is obvious that all modifications to .csl-files are subjected to CC-BY-SA.

But I am not sure about the following situations:

- May a CC-BY-SA .csl file be used to generate citations in a report of publications, without the publicationlist.pdf - report being subjected to CC-BY-SA?

- May a software product for managing publications include CC-BY-SA .csl files in its own zip file (with giving proper attribute on its own About-page and allowing its users to modify the .csl files) without the complete software.zip being subjected to CC-BY-SA?

Thank you
Hendrik

**Comment by rmzelle** [comment]
>     * May a CC-BY-SA .csl file be used to generate citations in a report of publications, without the publicationlist.pdf - report being subjected to CC-BY-SA?

We make no license claim to any output generated with CSL styles. We're only concerned about the code within the CSL styles themselves.

>     * May a software product for managing publications include CC-BY-SA .csl files in its own zip file (with giving proper attribute on its own About-page and allowing its users to modify the .csl files) without the complete software.zip being subjected to CC-BY-SA?

Yes.

**Comment by nhnb** [comment]
Thank you
