### ISSUE TITLE
PLOS style references include publisher for journal articles

### ISSUE THREAD

**Issue by dhimmel** [citation-style-language/styles#4140]
[PLOS Computational Biology](https://journals.plos.org/ploscompbiol/s/submission-guidelines#loc-references) (and PLOS) show an example journal article reference of:

> 1. Hou WR, Hou YL, Wu GF, Song Y, Su XL, Sun B, et al. cDNA, genomic sequence cloning and overexpression of ribosomal protein gene L9 (rpL9) of the giant panda (Ailuropoda melanoleuca). Genet Mol Res. 2011;10: 1576-1588.
>
> 2. Devaraju P, Gulati R, Antony PT, Mithun CB, Negi VS. Susceptibility to SLE in South Indian Tamils may be influenced by genetic selection pressure on TLR2 and TLR9 genes. Mol Immunol. 2014 Nov 22. pii: S0161-5890(14)00313-7. doi: 10.1016/j.molimm.2014.11.005.

Note that publisher information is not included (at least when `container-title` is known). However, we find [here](https://greenelab.github.io/meta-review/v/040638d25b9a45ad3d060afc9689a17f4c3a3045/#ref-12sHvZy1a) that the publisher is included (in this case "Oxford University Press"):

> 4. Khare R, Good BM, Leaman R, Su AI, Lu Z. Crowdsourcing in biomedicine: challenges and opportunities. Brief Bioinform. Oxford University Press; 2016;17: 23–32. doi:10.1093/bib/bbv021

The CSL for this item is:

```json
  {
    "source": "PubMed",
    "accessed": {
      "date-parts": [
        [
          2019,
          4,
          4
        ]
      ]
    },
    "id": "12sHvZy1a",
    "title": "Crowdsourcing in biomedicine: challenges and opportunities",
    "author": [
      {
        "family": "Khare",
        "given": "Ritu"
      },
      {
        "family": "Good",
        "given": "Benjamin M"
      },
      {
        "family": "Leaman",
        "given": "Robert"
      },
      {
        "family": "Su",
        "given": "Andrew I"
      },
      {
        "family": "Lu",
        "given": "Zhiyong"
      }
    ],
    "container-title-short": "Brief Bioinform",
    "container-title": "Briefings in bioinformatics",
    "publisher": "Oxford University Press",
    "ISSN": "1467-5463",
    "issued": {
      "date-parts": [
        [
          2016,
          1
        ]
      ]
    },
    "page": "23-32",
    "volume": "17",
    "issue": "1",
    "PMID": "25888696",
    "PMCID": "PMC4719068",
    "DOI": "10.1093/bib/bbv021",
    "type": "article-journal",
    "URL": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4719068/",
    "note": "This CSL JSON Item was automatically generated by Manubot v0.2.3 using citation-by-identifier.\nstandard_id: pmcid:PMC4719068"
  },
```

Is it possible for the following to be conditional, in a way that would omit showing publisher when type is `article-journal` and `container-title` is available:

https://github.com/citation-style-language/styles/blob/76e2ff8e518bd8623b48e31e1c70ff4ffb66217b/plos.csl#L305

**Comment by bwiernik** [comment]
I wouldn’t pay any attention to that example. Journal articles in PLOS journals don’t generally, if ever, include publishers. There is no reason for the inconsistency in the examples here. 

Note that `container-title` is the title of the journal, so the conditional you propose would always be true.

**Comment by adam3smith** [comment]
@bwiernik -- I don't understand (or maybe you're misreading the issue -- the example with publisher is not from PLOS but from our style for PLOS). 
It's not uncommon for journal article metadata to include the publisher (pubmed, CrossRef). In some countries (such as Brazil) it's even included in the citation. The problem is that our styles have assumed for a very long time the Zotero data model which doesn't have a publisher for journal articles and so we're getting this.

I'd add a much more general publisher conditional that removes it entirely from journal, magazine, and newspaper articles (at a minimum)

**Comment by bwiernik** [comment]
Yes, that’s right. Sorry—I misread the issue as quoting example citations.

**Comment by dhimmel** [comment]
Cleaning up old GitHub notification emails. Thanks @POBrien333 for resolving this in https://github.com/citation-style-language/styles/pull/4191. 

Noting that we've encountered some additional issues with the PLOS CSL style, described at https://github.com/citation-style-language/styles/issues/4138 and https://github.com/greenelab/meta-review/pull/241#issuecomment-501252429. Some of the issues like including `[Preprint]` after the preprint repository name are likely not possible given the current types supported by CSL Data Items.

Ideally journals would produce the styles themselves and use it as the reference implementation of how the styles should behave. But until then, thanks to volunteers like @POBrien333 and @adam3smith for doing the hard work!
