### ISSUE TITLE
Do CSLs have any required / validated fields? 

### ISSUE THREAD

**Issue by coryschires** [citation-style-language/styles#4153]
I am working on an automated citation parsing tool. As such, I would like to flag citations which are missing critical fields (e.g. `issued` or `title`). This way, I would know these citations likely need additional, manual attention before being considered to be complete / correct / accurate.

This leads to my question:

> Are any fields (e.g. `year` or `title`) required by the CSL-JSON spec?

Looking around, I think the answer is "no" as most tooling (e.g. Citeproc.js) allows seemingly integral fields to be blank.

But I figured I'd ask the experts in order to get a definitive answer.

Thanks for your help!

**Comment by adam3smith** [comment]
no, there are no required fields in the spec or in practice. E.g. letters often don't have a title and there are lots of works without a defined publication date/year.

Not on a spec level, but as a general rule, if your CSL JSON does have neither creator, title, and date, a fair number of citation styles will not output anything (in which case citeproc-js e.g. prints an error messages)

**Comment by adam3smith** [comment]
Re: citation parsing -- you're familiar with http://anystyles.io ? That project was written by the citeproc-ruby author.

**Comment by coryschires** [comment]
@adam3smith Thanks for the quick response! 

Yep. I'm actually using AnyStyle (as well as several other tools). I can confirm it works pretty well and is very easy to implement. Thanks for the tip!
