### ISSUE TITLE
Structural breakage in many styles (cs:substitute + cs:choose)

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/styles#4178]
While working through a CSL-M style bug with @denismaier, we traced the fault to use of `cs:choose` immediately under `cs:substitute`, without and enclosing `cs:group`. The style concerned was based on a style from the CSL repository, do I did a check for similar structures, and was alarmed to find that the structure, which can easily break formatting in ways that are difficult to debug when used, is quite common. A bare `cs:choose` element occurs under `cs:substitute` in 397 styles, and a condition node (`cs:if`, `cs:else-if`, or `cs:else`) contains multiple ungrouped elements (which is particularly bad) in 127 styles.

One of the ways that the latter of these structures will break formatting in `citeproc-js` is to grab the first-rendered element as the content of `display="block"`, and dump out the remaining elements in another context. In any case, the context is not properly closed in the processor, so all sorts of strange and wonderful things can happen. It's a bundle of styles that need attention, but they should really be fixed. The quick-and-dirty method that will work in most cases is just to add a `cs:group` wrapper around any `cs:choose` that occurs immediately under a `cs:substitute` element.

Here is the script I used for the audit. To run it, copy the code into the top of the styles repo, do `npm i xmldom` and `npm i xpath`, and run with `node ./NAME-OF-SCRIPT-FILE.js`.

```javascript
var fs = require("fs");
const dom = require('xmldom').DOMParser
const xpath = require("xpath");

console.log("#Styles with bare choose elements in cs:substitute");

var count = 0;
var noGroupList = [];
var countMultiElement = 0;
var multiElementList = [];

for (var fn of fs.readdirSync(".")) {
    if (fn.slice(-4) !== ".csl") {
        continue;
    }
    var xml = fs.readFileSync(fn).toString();
    xml = xml.replace("xmlns=\"http://purl.org/net/xbiblio/csl\"", "");
    var doc = new dom().parseFromString(xml)
    var nodes = xpath.select("//substitute/choose", doc);
    if (nodes.length > 0) {
        var hasGroup = false;
        var hasMultipleElements = false;
        for (var node of nodes) {
            var groups = xpath.select(".//group", node);
            if (groups.length > 0) {
                hasGroup = true;
            } else {
                var ifs = xpath.select(".//if", node);
                for (var ifNode of ifs) {
                    if (xpath.select("./*", ifNode).length > 1) {
                        hasMultipleElements = true;
                    }
                }
                var elseifs = xpath.select(".//else-if", node);
                for (var elseifNode of elseifs) {
                    if (xpath.select("./*", elseifNode).length > 1) {
                        hasMultipleElements = true;
                    }
                }
                var elses = xpath.select(".//else", node);
                for (var elseNode of elses) {
                    if (xpath.select("./*", elseNode).length > 1) {
                        hasMultipleElements = true;
                    }
                }
            }
        }
        if (!hasGroup) {
            noGroupList.push(fn);
            count++;
            if (hasMultipleElements) {
                multiElementList.push(fn);
                countMultiElement++;
            }
        }
    }
}

console.log("\n## Styles with bare cs:choose: "+count);
console.log("- " + noGroupList.join("\n- "));

console.log("\n## Styles with multiple elements under if, else-if, or else: "+countMultiElement);
console.log("- " + multiElementList.join("\n- "));
```

**Comment by fbennett** [comment]
I see now why this is so common across styles. The [Visual Editor](https://editor.citationstyles.org/visualEditor/) offers `cs:choose` as one of the options under `cs:substitute`. That option should be removed.
![visual-editor-tree](https://user-images.githubusercontent.com/75338/60762752-acc0b500-a0a1-11e9-886b-fc4befea6fab.png)

**Comment by bwiernik** [comment]
There isn't anything in the spec prohibiting this. Including `choose` elements under `substitute` is used (and is really necessary) extensively in `apa.csl` (e.g., https://github.com/citation-style-language/styles/blob/0f9b6e915dd01f25e0e0efb3fe8e585f22fb3aa0/apa.csl#L268). I'm not sure how to avoid this.

**Comment by fbennett** [comment]
There isn't a problem with the conditionals themselves. I was concerned about the lack of a `cs:group` wrapper around them. But ...

Ah, complexity. I just love it when my alarmed reactions turn out to be unfounded. That profound feeling of embarrassment and lack of self-worth and abject abasement. Priceless. It seems I have misunderstood something pretty basic, and that there is a good reason why there have been no error reports over this. The pattern that I was reacting to is shown in a 2012 [example](https://github.com/citation-style-language/schema/issues/104#issuecomment-9293253) posted by Charles Parnot. [brief interlude to allow the reader to click through and read the example]

I was reading unwrapped sequential in a condition, like this ...
```xml
<text variable="publisher"/>
<text macro="title"/>
````
... as intending to render both elements. But that is not what it means, is it. The style is just providing an alternative list of substitute elements, depending on the type. In the immortal words of Alan Partridge: "Aha."

I'll close this, and the associated pull request. Please return to your normally scheduled programming.

**Comment by bwiernik** [comment]
Your humor always amuses me @fbennett

**Comment by fbennett** [comment]
It's the only way I can cope.
