### ISSUE TITLE
Human Molecular Genetics/Nucleic Acids Research CSL does not include spaces between the comma after the author's last name and the initials

### ISSUE THREAD

**Issue by guhanrv** [citation-style-language/styles#4220]
Example:

Khor,B., Gardet,A. and Xavier,R.J. (2011) Genetics and pathogenesis of inflammatory bowel disease. Nature, 474, 307–317.

This is duplicated in https://editor.citationstyles.org/ and thus in Paperpile, etc. The sort separator needs another space.

**Comment by POBrien333** [comment]
Hi @guhanrv 
Why do you think this is an issue?
The guidelines say:
Schmitt,E., Panvert,M., Blanquet,S. and Mechulam,Y. (1995) Transition state stabilisation by the 'high' motif of class I aminoacyl-tRNA synthetases: the case of Escherichia coli methionyl-tRNA synthetase. Nucleic Acids Res., 23, 4793-4798. 

In publications they have: (note they as the editors remove the title as described in their guidelines)
63 Maskell,D.J., Szabo,M.J., Deadman,M.E. and Moxon,E.R. (1992) Mol.Microbiol., 6, 3051–3063.

**Comment by guhanrv** [comment]
Just clicked on the latest issue of HMG, picked the top article (Occupational exposure to gases/fumes and mineral dust affect DNA methylation levels of genes regulating expression), and scrolled down to the references. The top reference:

Iversen, M. and Dahl, R. (2000) Working in swine- confinement buildings causes an accelerated decline in FEV1: a 7-yr follow-up of Danish farmers. Eur. Respir. J., 16, 404–408.

Perhaps Nucleic Acids Research and Human Molecular Genetics have diverged in their style? I see spaces between the commas after last names and the initials, and additionally also see the titles of the Articles.

**Comment by POBrien333** [comment]
Great. Thanks for checking that.
I found another style, database.csl, which matches the style of HMG. I just submitted a fix for an issue with the style as it was not 100% correct.
Database is also a OUP journal like HMG.

**Comment by rmzelle** [comment]
Database and HMG have just been updated, courtesy of @POBrien333: https://github.com/citation-style-language/styles/pull/4227

**Comment by POBrien333** [comment]
@rmzelle Can we close this issue? :)
