### ISSUE TITLE
American Sociological Association Tabs on first line not second

### ISSUE THREAD

**Issue by tcratius** [citation-style-language/styles#4297]
APA referencing style CSL not formatting reference list to match standards expected of APA Reference Guide 6th edition using Biblatex reference format. Styles tried with same effect:
american-physiological-society.csl, apa-5th-edition.csl, apa.csl.
 
RStudio Version
$mode
[1] "desktop"

$version
[1] ‘1.2.1335’

PDF Rmarkdown
![apa-no-tab](https://user-images.githubusercontent.com/21984574/64601573-84866700-d400-11e9-8a72-c9db56df3374.jpg)

rticles::elsevier_article
![apa-tabbed-1st-line](https://user-images.githubusercontent.com/21984574/64601816-fd85be80-d400-11e9-8d64-834c71d5df4e.jpg)

**Comment by rmzelle** [comment]
This appears to be an issue specific to pandoc which is used by RStudio. See https://github.com/rstudio/rticles/issues/45 and specifically https://github.com/crsh/papaja/issues/37#issuecomment-104185288 for more background and a possible solution.
