### ISSUE TITLE
Requst style: Hapres-Vancouver of Jouneral of Acoustics (JoA)

### ISSUE THREAD

**Issue by QianchengKao** [citation-style-language/styles#4308]
https://joa.hapres.com/JOA_GuideforAuthors.aspx

ISSN is currently unavailable.

In-text citation:
as discussed by xxx [2]
as discussed elsewhere [2,3]

Bibliography:
**Journal articles:**
1.
Halpern SD, Ubel PA, Caplan AL. Solid-organ transplantation in HIV-infected patients. N Engl J Med. 2002 Jul 25;347(4):284-7. doi: 10.1056/NEJMsb020632
2.
Rose ME, Huerbin MB, Melick J, Marion DW, Palmer AM, Schiding JK, et al. Regulation of interstitial excitatory amino acid concentrations after cortical contusion injury. Brain Res. 2002;935(1-2):40-6. doi: 10.1016/S0006-8993(02)02445-9

**Books and book chapters:**

3.
Murray PR, Rosenthal KS, Kobayashi GS, Pfaller MA. Medical microbiology. 4th ed. St. Louis (US): Mosby; 2002.

4.
Meltzer PS, Kallioniemi A, Trent JM. Chromosome alterations in human solid tumors. In: Vogelstein B, Kinzler KW, editors. The genetic basis of human cancer. New York (US): McGraw-Hill; 2002. p. 93-113.

**Proceedings:**

5.
Christensen S, Oppacher F. An analysis of Koza’s computational effort statistic for genetic programming. In: Foster JA, Lutton E, Miller J, Ryan C, Tettamanzi AG, editors. Genetic programming. EuroGP 2002: Proceedings of the 5th European Conference on Genetic Programming; 2002 Apr 3-5; Kinsdale, Ireland. Berlin (Germany): Springer; 2002. p. 182-91.

**Reports, dissertations, and patents:**

6.
Yen GG (Oklahoma State University, School of Electrical and Computer Engineering, Stillwater, OK, US). Health monitoring on vibration signatures. Final report. Arlington (VA, US): Air Force Office of Scientific Research (US), Air Force Research Laboratory; 2002 Feb. Report No.: AFRLSRBLTR020123. Contract No.: F496209810049.

7.
Borkowski MM. Infant sleep and feeding: a telephone survey of Hispanic Americans [dissertation]. Mount Pleasant (MI, US): Central Michigan University; 2002.

8.
Pagedas AC, inventor; Ancel Surgical R&D Inc., assignee. Flexible endoscopic grasping and cutting device and positioning tool assembly. United States patent US 20020103498. 2002 Aug 1.

**Websites and personal communications:**

9.
The Mouse Tumor Biology Database. Available from: http://tumor.informatics.jax.org/mtbwi/index.do. Accessed 2013 May 20.

10.
Harris, Pat (National Information Standards Organization, Bethesda, MD, US). ISO standards on bibliographic references to be revised. Message to/Conversation with: Karen Patrias (Public Services Division, National Library of Medicine, Bethesda, MD, US). 2005 Jul 07.

**Comment by POBrien333** [comment]
This looks just like http://www.zotero.org/styles/vancouver-brackets-no-et-al
Can you confirm?
I'll then make a dependent style to help future authors to find the correct style.
