### ISSUE TITLE
CSE style author first name & last name

### ISSUE THREAD

**Issue by jeffge2017** [citation-style-language/styles#4326]
Hi, 

For Council of Science Editors citation style, the author's names should be "Lastname F."  There's no comma between the last name and first name and first name should be in uppercase initial. 

Here's an example:

Wrong format:

Rueegger, Niels. 2017. Artificial tree hollow creation for cavity-using wildlife – Trialling an alternative method to that of nest boxes. Forest Ecology and Management. 405:404–412. doi:10.1016/j.foreco.2017.09.062.

Correct format:

Rueegger N. 2017. Artificial tree hollow creation for cavity-using wildlife – Trialling an alternative method to that of nest boxes. Forest Ecology and Management. 405:404–412. doi:10.1016/j.foreco.2017.09.062.

I wonder if you could update the codes?  Thanks.

Best,

Jeff

**Comment by POBrien333** [comment]
Hi @jeffge2017 
CSE does this correctly.
Test output:
Hancké B, Rhodes M, Thatcher M, editors. 2007. Beyond varieties of capitalism: Conflict, contradiction, and complementarities in the European economy. Oxford and New York, NY: Oxford University Press.

How are you producing your citations? Please make sure that the author name is entered correctly in Zotero in the two fields for first and last name.

**Comment by adam3smith** [comment]
You're welcome to follow up with further questions, but as the style is correct, closing the ticket
