### ISSUE TITLE
Keeping APA 6th edition styles

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/styles#4362]
Which of the APA 6th edition styles do we want to keep around? Just the main one? @rmzelle could you check what dependent styles use the various APA variants?

**Comment by adam3smith** [comment]
Unless I'm missing something this is a full list:
apa-5th-edition
apa-old-doi-prefix
apa-old-doi-prefix
apa-old-doi-prefix
apa-old-doi-prefix
apa-old-doi-prefix
apa-no-doi-no-issue
apa-old-doi-prefix
apa-no-doi-no-issue


Here's what I'd do:
1. Keep the regular 6th edition one
2. Add 6th edition to the title of the old-doi and no-doi-no-issue variants 
3. Convert all other APA styles to 7th edition with no 6th edition version.

**Comment by bwiernik** [comment]
Okay great. What I was wondering about was if any dependent styles used, for example, apa-no-ampersand that we would need to maintain in their current state.

**Comment by bwiernik** [comment]
Do I need to to change the `independent-parent` tags in the dependent styles using old-doi-prefix and no-doi-no-issue, or is that handled by renamed-styles.json?

**Comment by rmzelle** [comment]
> What I was wondering about was if any dependent styles used, for example, apa-no-ampersand that we would need to maintain in their current state.

To see whether a given style has dependents, you can use the visual editor (see e.g. the "Dependent Styles" listing for apa.csl at https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fapa), or just search a local copy of the repository with your text tool of choice (grep, text editor, etc.).

In general, I think it's fine to automatically update all dependents to the latest version of APA. It's what we typically do for updates to major style guides, and many journals that specify the use of APA don't specify a specific style guide version.

> Do I need to to change the `independent-parent` tags in the dependent styles using old-doi-prefix and no-doi-no-issue, or is that handled by renamed-styles.json?

"renamed-styles.json" is totally passive and not part of any continuous integration (although CI does check it for consistency). It's just there for downstream clients like Zotero who wish to offer their users an automated upgrade path for styles that are deleted or change their ID.

**Comment by bwiernik** [comment]
Got it, thanks.
