### ISSUE TITLE
Trying to create new style of Vancouver "Erro 0 while trying to save style"

### ISSUE THREAD

**Issue by jystatistics** [citation-style-language/styles#4418]
Hi,

I'm trying create my csl file based on Vancouver format for incite citation. 

After I changed the incite citation and try to save as save as, then there is an error message like this:

"Error0 while trying to save style"

I don't know why I cannot save this style in CSL editor.

Could you help on this?

I captured the error message here. 

Thank you.

<img width="1292" alt="Screen Shot 2019-11-21 at 9 15 55 AM" src="https://user-images.githubusercontent.com/39386861/69360710-e3a5fa80-0c3f-11ea-8465-a28f1674ba25.png">

**Comment by adam3smith** [comment]
There appears to be a bug with the Mendeley version of the editor. Our own hosted version at editor.citationstyles.org should be fine, so I'd recommend using that and reporting your issues to Mendeley

**Comment by jystatistics** [comment]
Thank you for your help! @adam3smith 

It is working from editor.citationstyles.org
