### ISSUE TITLE
IEEE style should have DOI

### ISSUE THREAD

**Issue by jronallo** [citation-style-language/styles#4446]
According to the IEEE Reference Guide a DOI should be included when available. The current ieee.csl and ieee-with-url.csl styles not include the DOI from what I can tell.

https://ieeeauthorcenter.ieee.org/wp-content/uploads/IEEE-Reference-Guide.pdf

You can reach that PDF from this page:
https://journals.ieeeauthorcenter.ieee.org/your-role-in-article-production/ieee-editorial-style-manual/

Anything I can do to help correct this? Would you accept a pull request which included this change?

**Comment by POBrien333** [comment]
@rmzelle and @adam3smith 
Guidelines are from 11.12.2018 and for example for article-journal state:
M. M. Chiampi and L. L. Zilberti, “Induction of electric field in human bodies moving near MRI: An efficient BEM computational procedure,”IEEE Trans.Biomed. Eng., vol. 58, no. 10, pp. 2787–2793, Oct. 2011, doi:10.1109/TBME.2011.2158315.

Shall I prepare a PR?

**Comment by adam3smith** [comment]
Yes, we'd take a PR from either of you for all IEEE and IEEE with URL

**Comment by rmzelle** [comment]
Thanks all! (@jronallo, also thanks for the documentation links. I updated those in our styles too)
