### ISSUE TITLE
Title only style for citations in prose?

### ISSUE THREAD

**Issue by reagle** [citation-style-language/styles#4464]
Is there a style that could be used in online journalistic/popular writing where there's no bibliography and the citations are (hypertextual) work titles? For example:

> Penny wrote about this a few years ago ("[Life-hacks of the poor and aimless](https://thebaffler.com/latest/laurie-penny-self-care)").

**Comment by POBrien333** [comment]
Try this. Right click, save as, install in Z via double click or menu: https://gist.githubusercontent.com/POBrien333/1ed595a02d5ea2b788055d92953f9fb6/raw/e737c35dd0daf10db5e2848a363d92aca8e8a29a/in-text-title.csl

**Comment by reagle** [comment]
@POBrien333, thank you for that, but I use pandoc in which that doesn't work -- all the citations disappear. I'm also assuming this means no such style presently exists? (It's hard to search/comprehend them all.)

**Comment by adam3smith** [comment]
There's definitely no such style, no. I'm surprised the above style doesn't work to give you the title in the text (it really should, also in pandoc) but hyperlinking isn't possible with CSL at all, so arguably the mos timportant part of this can't be done.

**Comment by reagle** [comment]
Sorry, it is working, but I didn't notice them because it wasn't what I was expecting; I fixed that with

```      <text variable="title" prefix='("' suffix='")' text-case="title"/>
```

@adam3smith is the inability to link issue #145?

**Comment by POBrien333** [comment]
Can't see what you posted there.

**Comment by adam3smith** [comment]
Yes, that's the one.

**Comment by reagle** [comment]
Okay, well thanks for the help, I'll close this and keep an eye on 145.
