### ISSUE TITLE
Adopt Code of Conduct / Diversity Statement

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#4471]
I think it would behoove us to adopt a Code of Conduct and/or Diversity Statement, as part of open source best practices. Some options:

1. [Contributor Covenant](https://www.contributor-covenant.org/)
2. [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/)
3. [Project Jupyter Code of Conduct](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md)

If anybody knows of other templates that would be a good fit for us, or has an opinion about the options above, please chime in.

**Comment by adam3smith** [comment]
+1 -- I like standardization and would tend towards option 1 - also seems like a good balance of comprehensive & short. (I do like the "be respectful about how others spend their time" part in the Jupyter one, but I think we'll be fine without it.

**Comment by rmzelle** [comment]
Done (via https://github.com/citation-style-language/.github/pull/1)
