### ISSUE TITLE
APA 7th Edition

### ISSUE THREAD

**Issue by saridor63** [citation-style-language/styles#4501]
Hi,
Cant find the correct updated file for the new APA 7th ed CSL (eg should not display place of publication). May I ask that you direct me to it? or perhaps I should wait for an update?
Thanx!
Shelly

**Comment by adam3smith** [comment]
The standard apa.csl style is 7th edition

**Comment by saridor63** [comment]
Thank you Sebastian.
However, using the standard apa.csl style in our Discovery system (Primo<https://haifa-primo.hosted.exlibrisgroup.com/primo-explore/search?tab=default_tab&sortby=rank&vid=HAU&lang=en_US>), it will produce a citation with the publishers location.
The APA 7th edition states that it should no longer be included: https://apastyle.apa.org/instructional-aids/reference-guide.pdf

Will there be an update to apa.csl?

BR,
Shelly


[cid:image001.gif@01D092CE.DC2D50E0]<http://lib.haifa.ac.il/>
Shelly Shen-Aridor
Reference Librarian
Library Information Systems Team
Younes and Soraya Nazarian Library<http://lib.haifa.ac.il/index.php/en/> | University of Haifa<http://www.haifa.ac.il/index.php/en/>
199 Aba-Hushi Ave. Mount Carmel, Haifa, Israel
Phone: 972-4-8249509 | Mobile: 972-52-2976321
Email: saridor@univ.haifa.ac.il<mailto:saridor@univ.haifa.ac.il>

**Comment by rmzelle** [comment]
> Will there be an update to apa.csl?

We updated apa.csl in this style repository on January 1st to APA 7th edition (see https://twitter.com/csl_styles/status/1212463420802514955).

Assuming you're running Primo EV, https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/050Other_Configuration/Managing_Citation_Styles_for_Primo_VE#Adding_a_Citation_Style has documentation on how to upload our updated style. The same page also says:

> Because Primo VE downloads new styles from the repository prior to each release, some of the newer styles may not be available until Primo VE's next release.

So you could also wait until the next Primo VE update.

**Comment by rmzelle** [comment]
This is the documentation for regular Primo, which also uses CSL styles: https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Back_Office_Guide/110Additional_Primo_Features/Managing_Citation_Styles

**Comment by rmzelle** [comment]
(and feel free to keep responding here, but I assume this answers your question)

**Comment by saridor63** [comment]
Hi,
Thanx. This indeed is the correct documentation according to which I have configured our Primo. CSL has been working great for us.
However, although the APA style have changed their guidelines so the place of publication should no longer be part of the citation in our Primo it still appears, I was hoping there is a new updated CSL file.
The following is a citation using the apa.csl from our Primo:
  Nash, D. (2007). David Nash. London: Thames & Hudson.

The correct citation according to APA 7th edition is:
  Nash, D. (2007). David Nash. Thames & Hudson.

I would greatly appreciate any help.

Thanks and Best Regards,
Shelly

[cid:image001.gif@01D092CE.DC2D50E0]<http://lib.haifa.ac.il/>
Shelly Shen-Aridor
Reference Librarian
Library Information Systems Team
Younes and Soraya Nazarian Library<http://lib.haifa.ac.il/index.php/en/> | University of Haifa<http://www.haifa.ac.il/index.php/en/>
199 Aba-Hushi Ave. Mount Carmel, Haifa, Israel
Phone: 972-4-8249509 | Mobile: 972-52-2976321
Email: saridor@univ.haifa.ac.il<mailto:saridor@univ.haifa.ac.il>

**Comment by adam3smith** [comment]
We really do understand the new APA rules and the APA 7th edition style provided in CSL does not include the place of publication. You can check out the preview on https://www.zotero.org/styles?q=APA for example.
If it's still showing in your Primo instance than either your local copy of the APA style hasn't been updated or the metadata is incorrectly mapped (e.g. with Publisher: Place in the publisher field). Our style is updated and correct, so you really do need to find a solution on the Primo end.
