### ISSUE TITLE
bibtex.csl editor and translator fields question

### ISSUE THREAD

**Issue by sergesd** [citation-style-language/styles#4537]
When I pass editor or translator fields to the bibtex style a word "Editor" or "Translator" is added, for example:
editor={Haley, DEditor}
instead of:
editor={Haley, D}

Please help me to understand where the problem can be.

**Comment by rmzelle** [comment]
Can you tell us about your software environment? Pandoc?

**Comment by sergesd** [comment]
I’m using citeproc-js via demo.html page from the demo folder. Just added editor field to the first Item in the example and downloaded bibtex.csl for testing.

**Comment by adam3smith** [comment]
this is now fixed (note that the ability of CSL to generate completely accurate bibtex is limited, so do use that style with caution)
