### ISSUE TITLE
Issue with Hebrew conjunctions when multiple contributors exist

### ISSUE THREAD

**Issue by nilinatan** [citation-style-language/styles#4583]
Hi 

We are opening this case on behalf of the Israeli academic institutions that are using Ex Libirs Primo discovery system, which allow users to use citations  based on CSL. 

Following issues have been reported with missing the right hebrew conjunction among multiple contributers:

- american-sociological-association.csl display "and" instead of the Hebrew character "ו" 
  before the last contributor 
  
![image](https://user-images.githubusercontent.com/16845055/75450634-dfdcef00-5977-11ea-89da-b5416891c595.png)

Similar issues appear with additional citation styles : chicago-author-date.csl , turabian-fullnote-bibliography 

In MLA we can report that we see "et al" instead of the hebrew translation "אחר"  
as shown below:

![image](https://user-images.githubusercontent.com/16845055/75450880-46faa380-5978-11ea-9714-50fce420dce1.png)

We'd appreciate your feedback and help in resolving these issues affecting all our Primo Israeli academic institutions.

Best Regards
Nili Natan
Product Manager of Discovery & Delivery 
nili.natan@exlibrisgroup.com
www.exlibrisgroup.com

**Comment by adam3smith** [comment]
CSL styles take a locale variable that's not based on the language of the source, but on the language specified for the bibliography. E.g. if I'm writing in English, all my et als, ands, editors, etc. are going to be in English, even for Hebrew, German, French, Chinese, etc. sources.

It looks like your implementation of CSL defaults to English. You could change this to Hebrew (we don't know how you've implemented CSL, so can't help much with that) and you'd get ו and אחר
for all items.

**Comment by nilinatan** [comment]
Hi 
Thank you for you comment, we do provide the locale information- passing he-IL when recognizing Hebrew records and we still get back from the in the response  the conjunctions  & and et-al instead of the Hebrew ones. we are using the  citeproc  API , can you recommend on a way to debug this outside of our application to see if there are  issues in the conjunctions handling on non-Latin languages

Any input will help us with improving the use of CSL for our Israeli customers 
All the best 
Nili

**Comment by adam3smith** [comment]
this isn't an issue with CSL in general -- e.g. I get correct conjunctions when passing the he-IL locale to Zotero -- so you'll really need to take this up with your citeproc implementation. The first step for debugging would be to figure out the exact stack you're using for Primo's CSL implementation. There are e.g. at least half a dozen different citeprocs and "citeproc API" isn't something that I recognize/know about under that label.
