### ISSUE TITLE
urldate or access date do not appear for online sources

### ISSUE THREAD

**Issue by northern-arizona** [citation-style-language/styles#4585]
I am using this style to convert markdown to an odt (using a reference-doc file).

My bib file looks like this:

```
@Online{ edwards1758,
    author = {Jonathan Edwards},
    title = {An Unpublished Essay on the Trinity},
    url = {Online: https://ccel.org/ccel/edwards/trinity/trinity},
    urldate = {24 January 2020},
    date = {24 January 2020},
}

```

FOOTNOTE:

>      Jonathan Edwards, “An Unpublished Essay on the Trinity,” n.d., Online: https://ccel.org/ccel/edwards/trinity/trinity.

This is what my footnote looks like (Notice, it should have (Cited on 24 January 2020), but that information does not appear. Can you help me get the urldate to appear in the footnote and bibliography entries?

**Comment by adam3smith** [comment]
You say "this style" but you don't actually tell us which one you're using. 
Also, the exact software set-up is relevant here. I'm not clear on how you're actually converting. Using pandoc or something else?

**Comment by northern-arizona** [comment]
My conversion command is:

`pandoc` --bibliography=bib.bib --csl=society-of-biblical-literature-fullnote-bibliography.csl --reference-doc=ref.odt --standalone thesis.md -o thesis.odt

**Comment by POBrien333** [comment]
Hi,

I don't think the SBL style is supposed to add the accessed date:

SBLHS **discourages** including the date the student last accessed the page (see 6.1.6).7.  R.  Timothy  McLay,  “The  Goal  of  Teaching  Biblical  and  Religious  Studies  in  the Context of an Undergraduate Education,” SBL Forum, **6 October 2006**, http://www.sbl-site .org/publications/article.aspx?articleId=581.

The date in bold is the issued date and will be produced correctly by the style.
