### ISSUE TITLE
Build failure with 'https' URLs for zotero.org & creativecommons.org

### ISSUE THREAD

**Issue by florisvdh** [citation-style-language/styles#4594]
Since some time, we are preparing an update of `research-institute-for-nature-and-forest.csl` .

In commit 66d5cb3d, I updated most `http://` links to `https://` links. However, in some cases this led to an error in [the build](https://travis-ci.com/florisvdh/styles/builds/151689618). I would suggest to allow (the more secure) `https://` variants in the checks.

It went wrong here:

```
1) research-institute-for-nature-and-forest: style ID must be of the form "http://www.zotero.org/styles/" + style file name (without ".csl" extension, e.g. "http://www.zotero.org/styles/apa")
     Failure/Error: expect(style.id).to eq("http://www.zotero.org/styles/#{basename}")
     
       expected: "http://www.zotero.org/styles/research-institute-for-nature-and-forest"
            got: "https://www.zotero.org/styles/research-institute-for-nature-and-forest"
     
       (compared using ==)
     Shared Example Group: "style" called from ./spec/styles_spec.rb:216
     # ./spec/styles_spec.rb:185:in `block (2 levels) in <top (required)>'
                                                                                
  2) research-institute-for-nature-and-forest: must have the correct Creative Commons BY-SA license URL
     Failure/Error: expect(style.info.rights[:license]).to eq(CSL_LICENSE_URL)
     
       expected: "http://creativecommons.org/licenses/by-sa/3.0/"
            got: "https://creativecommons.org/licenses/by-sa/3.0/"
     
       (compared using ==)
     Shared Example Group: "style" called from ./spec/styles_spec.rb:216
     # ./spec/styles_spec.rb:200:in `block (2 levels) in <top (required)>'
```

However the https:// variants do work:

- https://www.zotero.org/styles/research-institute-for-nature-and-forest
- https://creativecommons.org/licenses/by-sa/3.0/

Adding @ThierryO since he suggested this improvement of our csl file.

**Comment by adam3smith** [comment]
Thanks! I don't think we'll do this, though:
Since both zotero.org and creativecommons.org enforce https, there is (almost) no practical difference and it's hugely preferable to a) have the links all uniform and b) not update a massive number of existing styles for essentially cosmetic purposes, making their timestamps uninformative.

(And specifically for style ids, those are used by several tools as identifiers, not just locators, so changing them actually may create real issues)

**Comment by rmzelle** [comment]
Yes, sorry. We're big fans of HTTPS, but there are practical reasons (which @adam3smith is already alluding to) why we can't easily upgrade these type of links.

**Comment by florisvdh** [comment]
Thanks @adam3smith @rmzelle for clarifying your reasons. Will adjust this!
