### ISSUE TITLE
Issues I found with the COPPE-ABNT style.

### ISSUE THREAD

**Issue by AraujoH** [citation-style-language/styles#4647]
Hi, 

I have found some issues with the style **_universidade-federal-do-rio-de-janeiro-instituto-alberto-luiz-coimbra-de-pos-graduacao-e-pesquisa-de-engenharia-abnt.csl_** that I'd like to make known. I'm not sure if it's important to say but I'm using this citation style through Mendeley's MS-Word plug-in. I also feel like saying maybe these issues may have to do more with Mendeley than the citation itself. In this case, I apologize. But here are a list of things I found that got my attention for being out of what I expected:

1. I noticed that if I have "Notes" that I wrote about an article/book section/any-other-publication, these notes will be part of the "Bibliography" of my text. I don't think this is supposed to happen.

2.  Sometimes, even after I delete all references to a certain publication in my text, the citation will keep occurring in the "Bibliography".

3. So far, by using this style, I have noticed that author's names will show up in parenthesis no matter what. According to ABNT, whenever the author's name(s) is(are) part of the sentence, it(they) should appear without parenthesis. For example: 

SMITH, J. (2010) claims A is not equal B. 

When the reference to an author is indirect, then the entire citation comes inside parenthesis. E.g.:

It is claimed that A is not equal B (SMITH, J., 2010). 

Thank you for your time.

**Comment by adam3smith** [comment]
1. Is an issue with the style -- several of the ABNT styles include notes to accommodate information that doesn't fit in other fields. I'm trying to push back on this as much as possible, but for styles associated with particular organizations, they often insist. Have you tried any of the other ABNT options?

2. Is a Mendeley issue. My guess is that you have a "hidden" reference left in the text. You may be able to find that by showing field codes in Word (alt+f9 or alt+fn+f9)

3. Is also independent of the style. I believe the Mendeley Word add-on allows you to just print the year for a citation and you can then write the authors in the text.

**Comment by p3palazzo** [comment]
@AraujoH: for 3. The ABNT-UFPR style does just what you expect, but I find it annoying. @adam3smith 's solution is better.

**Comment by fgnievinski** [comment]
About issue #3, in Zotero and probably in Mendeley, you're expected to manually edit the default parentheses to put them around just the year.

**Comment by POBrien333** [comment]
Re 3.
Mendeley, just like Zotero let's you suppress the author and then you can just manually write it in the next.
See: 
![Screenshot 2020-06-09 12 22 12](https://user-images.githubusercontent.com/954979/84136761-0963e700-aa4c-11ea-8405-fa73a5e79ea9.png)
