### ISSUE TITLE
Journals following ICMJE recommendations should be based on the Vancouver style

### ISSUE THREAD

**Issue by hubgit** [citation-style-language/styles#4722]
If I understand correctly, the journals [listed as "following the ICMJE recommendations"](http://www.icmje.org/journals-following-the-icmje-recommendations/) are following the [ICMJE guidelines for references](http://www.icmje.org/recommendations/browse/manuscript-preparation/preparing-for-submission.html#g), which means they're using the [NLM reference style](https://www.nlm.nih.gov/bsd/uniform_requirements.html) as described in [Citing Medicine](https://www.ncbi.nlm.nih.gov/books/NBK7256/).

The [National Library of Medicine citation style ](https://csl.mendeley.com/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fnational-library-of-medicine) is the same as the [Vancouver citation style](https://csl.mendeley.com/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fvancouver), so the styles for all the listed journals should have `http://www.zotero.org/styles/vancouver` as their `link (independent-parent)`.

**Comment by hubgit** [comment]
I raise this because of a user report that the CSL style for [Osteoarthritis and Cartilage](https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fosteoarthritis-and-cartilage) is currently based on AMA, but according to the [author guidelines](https://www.elsevier.com/journals/osteoarthritis-and-cartilage/1063-4584/guide-for-authors#1.9.11) it follows the ICMJE guidelines and is included in the ICMJE list.

**Comment by POBrien333** [comment]
vancouver.csl still is not 100% correct.

**Comment by adam3smith** [comment]
It's certainly possible that individual journals are misclassified, but ICMJE recommendations are applied in a wide variety of ways (including with respect to et al.) and we cannot, unfortunately, just link them to one of the Vancouver styles.
