### ISSUE TITLE
Mendeley not updating new element edited in csl editor

### ISSUE THREAD

**Issue by Alvinarnardu** [citation-style-language/styles#4758]
I have edited my csl code to include: justification `</citation> <bibliography hanging-indent="true"  align="justified" >` however when i install the new csl file is not updating the element it reverts back. 
I want references to appear as below : 
![Capture](https://user-images.githubusercontent.com/64644294/80809371-d3685300-8bc1-11ea-9dee-497c74ae54d1.PNG)
But it reverts back to below 
![Capture](https://user-images.githubusercontent.com/64644294/80810011-30b0d400-8bc3-11ea-819f-df4001d8b32e.PNG)

**Comment by rmzelle** [comment]
> `align="justified"`

The "align" attribute doesn't exist in CSL 1.0.1. Assuming you're working in Word, I believe you should be able to change the Word style applied the bibliography to be justified.

**Comment by Alvinarnardu** [comment]
Thank you. I hope that in future csl that will be included as you noticed i am able to fix it in word however i want it to be automatic as i may have sevaral drafts.
Alvin
    On Sunday, May 3, 2020, 12:04:37 AM GMT+2, Rintze M. Zelle <notifications@github.com> wrote:  
 
 


Closed #4758.

**Comment by rmzelle** [comment]
> I hope that in future csl that will be included as you noticed i am able to fix it in word however i want it to be automatic as i may have sevaral drafts.

I'm not aware of any reference style guides specifying the use of justified or left-aligned, so we'll likely keep considering this outside of the scope of CSL.
