### ISSUE TITLE
ACS citation style in Mendeley wrong: remove DOI

### ISSUE THREAD

**Issue by vamendola** [citation-style-language/styles#4764]
Please see attached file
thank you
[mendeley.docx](https://github.com/citation-style-language/styles/files/4576210/mendeley.docx)

**Comment by adam3smith** [comment]
As per ACS's pubication office, DOIs are preferred; this is on purpose.

**Comment by vamendola** [comment]
Dear Sebastian
I copy and paste the recommendation just received from ACS Nano:

References

- Put reference titles in title case (Including words after hyphens)

 - Only include DOI information when citing journals only published online.

 - Remove issue numbers from references

 - Capitalize all cases of "in Situ" to read "In Situ" (See Ref 15)

 - Use correct journal abbreviations (CASSI) in references (See Ref 22, 23,
43, 45)


Therefore, as per ACS's journals editorial office, DOIs are preferred;

Are you planning to implement ACS Nano style without DOI, to comply with
journal requests?

Thanks a lot for your help
Vincenzo


Il giorno mar 5 mag 2020 alle ore 16:16 Sebastian Karcher <
notifications@github.com> ha scritto:
