### ISSUE TITLE
Quotation in title in Chicago Style 

### ISSUE THREAD

**Issue by smhmd** [citation-style-language/styles#4780]
I'm using R markdown with CSL file https://github.com/citation-style-language/styles/blob/master/chicago-fullnote-bibliography-with-ibid.csl

I have a bib entry from https://www.jstor.org/stable/42909473 as follows:
```bib
@article{devers_2011,
  title={"I know how to do the play now": A Part of Willy Loman in Synecdoche, New York},
  author={Devers, Rebecca},
  journal={The Arthur Miller Journal},
  volume={6},
  number={2},
  year={2011},
  publisher={The Arthur Miller Society}
}
```

When the citation is rendered, the quotes aren't handled properly:
![footnote](https://user-images.githubusercontent.com/46059092/81601501-80a94b00-93ba-11ea-826f-4988879ca622.png)
![works cited](https://user-images.githubusercontent.com/46059092/81601453-6d967b00-93ba-11ea-80c1-e8953efbf7d5.png)

Three closing quotation marks and a single opening one.

**Comment by adam3smith** [comment]
The styles (mostly) don't determine inner quote handling and CSL should do this correctly. Here's Zotero output for your cites:

![image](https://user-images.githubusercontent.com/128986/81605702-e1775a00-939f-11ea-8575-9fd8f5fa9915.png)

You'd want to test this with a fresh pandoc install (pandoc handles R-Markdown citations) and then report it at pandoc: https://github.com/jgm/pandoc

**Comment by smhmd** [comment]
https://sourceforge.net/p/xetex/bugs/172/
