### ISSUE TITLE
Editor for edited book apa.csl

### ISSUE THREAD

**Issue by katew1576672** [citation-style-language/styles#4781]
7th edition should display as: 
Editor, E. E. (Ed.). (Year of publication). Title of work: Capital letter also for subtitle. Publisher.

Instead seeing:
Merino, N. (2016). Immigration reform / Noël Merino, book editor. Farmington Hills, Mich: Greenhaven Press, a part of Gale, Cengage Learning.
Example in Primo VE https://sandbox02-na.primo.exlibrisgroup.com/discovery/fulldisplay?context=L&vid=01CACCL_CC:scc&search_scope=MyInst_and_CI&tab=Everything&docid=alma9975864105264

I see it is defined: 
      <term name="collection-editor" form="short">
	        <single>ed.</single>
	        <multiple>eds.</multiple>
	      </term>

And 
  
	        <names variable="editor" delimiter=", ">
	          <name name-as-sort-order="all" and="symbol" sort-separator=", " initialize-with=". " delimiter=", " delimiter-precedes-last="always"/>
	          <label form="short" prefix=" (" suffix=")" text-case="title"/>
	        </names>

Thanks!

**Comment by adam3smith** [comment]
The CSL APA style does this correctly (as the excerpts you point to show)

This is a data issue. You can see that Primo has "Immigration reform / Noël Merino, book editor." in the title metadata and I'm guessing that it doesn't correctly label Merino as an editor in the metadata. You'll have to talk to exlibris.

**Comment by katew1576672** [comment]
That helps, thank you!
