### ISSUE TITLE
Journal update to citation style-Estuaries and coasts

### ISSUE THREAD

**Issue by wryanjames** [citation-style-language/styles#4816]
There has been an update to the bibliography style in Estuaries and Coasts. They have switched (Jan 2020 is the earliest I could detect) from full first names to initials follow by a period. I wasn't able to find an updated style and thought this might be of interest given the style has not been updated since 2014. It seems to be a recent journal update. I have attached a pdf of author guidlines that includes the update citation style. I apologize because I would submit and edit myself, but I am not familiar with csl file formats 

[Estuaries_and_Coasts_IFA_Jan2020.pdf](https://github.com/citation-style-language/styles/files/4657641/Estuaries_and_Coasts_IFA_Jan2020.pdf)

**Comment by rmzelle** [comment]
@POBrien333, would you mind taking a look? See https://github.com/citation-style-language/styles/blob/master/dependent/estuaries-and-coasts.csl.

**Comment by POBrien333** [comment]
Hi @wryanjames 

Could you help me with checking some of the dependent styles of the parent style springer-humanities-author-date?
Could you check 3 or 4 of any of these journals and see if they also changed the style? Based on that we either then change the parent style or make an independent style for _Estuaries_.

thanks.

Agriculture and Human Values, American Journal of Potato Research, Archive for History of Exact Sciences, Argumentation, Bandung: Journal of the Global South, Business Research, Chinese Political Science Review, Contemporary Jewry, Continental Philosophy Review, Dialectical Anthropology, Estuaries and Coasts, Feminist Legal Studies, Food Ethics, Fudan Journal of the Humanities and Social Sciences, Functional Linguistics, Geoenvironmental Disasters, International Journal of Dharma Studies, International Journal of Disaster Risk Science, International Journal of Ethics Education, Journal of East Asian Linguistics, Journal of Quantitative Economics, Law and Critique, Lexicography, Lingua Sinica, Liverpool Law Review, Maritime Studies, Medicine, Health Care and Philosophy, Medicine Studies, Metascience, Minerva, Monash Bioethics Review, Multilingual Education, Natural Language & Linguistic Theory, Natural Language Semantics, Österreichische Zeitschrift für Soziologie (German), Paläontologische Zeitschrift, Pastoralism, Philosophy of Management, Proceedings of the Zoological Society, Qualitative Sociology, Res Publica, Review of Philosophy and Psychology, Review of Religious Research, Soziale Probleme (German), Studies in Philosophy and Education, Sugar Tech, The Journal of Chinese Sociology, The Journal of Comparative Germanic Linguistics, Zeitschrift für Politikwissenschaft, Zeitschrift für Vergleichende Politikwissenschaft (German)

**Comment by wryanjames** [comment]
Hey @POBrien333,

I checked a few and found mixed results, so I decided to go through the entire list and here's what I found outside of Estuaries and Coasts:

Appears to be same style as before
Agriculture and Human Values, Archive for History of Exact Sciences, Argumentation, Bandung: Journal of the Global South, Chinese Political Science Review, Contemporary Jewry, Continental Philosophy Review, Dialectical Anthropology, Feminist Legal Studies, Food Ethics, Fudan Journal of the Humanities and Social Sciences, Functional Linguistics, International Journal of Dharma Studies, International Journal of Ethics Education, Journal of East Asian Linguistics, Law and Critique, Lexicography, Lingua Sinica, Liverpool Law Review,  Maritime Studies, Medicine, Health Care and Philosophy, Medicine Studies, Metascience, Minerva, Multilingual Education, Natural Language & Linguistic Theory, Natural Language Semantics,  Österreichische Zeitschrift für Soziologie, Paläontologische Zeitschrift, Pastoralism, Philosophy of Management, Proceedings of the Zoological Society, Qualitative Sociology, Res Publica, Review of Philosophy and Psychology, Review of Religious Research, Soziale Probleme, Studies in Philosophy and Education, Sugar Tech, The Journal of Chinese Sociology, Zeitschrift für Politikwissenschaft, Zeitschrift für Vergleichende Politikwissenschaft

Changed (looks to be same changes as E and C at first glance)
American Journal of Potato Research - https://www.springer.com/journal/12230/submission-guidelines
Journal of Quantitative Economics - https://www.springer.com/journal/40953/submission-guidelines#Instructions%20for%20Authors_References

Appears to have changed different than E and C
Geoenvironmental Disasters (Only letters for first names but no period) - https://geoenvironmental-disasters.springeropen.com/submission-guidelines/preparing-your-manuscript/research-articles
International Journal of Disaster Risk Science - https://www.springer.com/journal/13753/submission-guidelines
Monash Bioethics Review - https://www.springer.com/journal/40592/submission-guidelines

The Journal of Comparative Germanic Linguistics - https://www.springer.com/journal/10828/submission-guidelines#Instructions%20for%20Authors_References

**Comment by POBrien333** [comment]
Wow. Thank you for your thorough work.
I did a sample check myself (I remember one of them was the potato one...), but must've hit exactly 3 journals that had changed their style. In that case, I'll make a separate new style and then will go from there.

**Comment by adam3smith** [comment]
This looks all done. Thanks belatedly
