### ISSUE TITLE
APA 7 Conferences/InProceedings incorrect

### ISSUE THREAD

**Issue by acircleda** [citation-style-language/styles#4825]
According to the APA 7th manual, papers/conferences should be listed as:

> Author, A. (Year, Month). Title [type of contribution]. Conference information.

However, using the APA 7 .csl and a .bib latex entry like the one below , it is rendered as 

> Author, A. (Year). *Title*. Conference information.

```
@Conference{1,
  author = {Anthony Schmidt and Joshua Rosenberg},
  title = {Becoming “tidyr” over time: Data visualization development in an online community of practice},
  year = {2020},
  month = {March},
  organization = {{University of Tennessee, Knoxville College of Education, Health, and Human Sciences Graduate Research Colloquium}},
  note = {Poster presentation},
  key = {1},
}
```

Is this an issue with the .CSL file, the .bib entry, or something in between the two?

**Comment by bwiernik** [comment]
Don't use .bib with CSL styles. BibTeX/BibLaTeX and CSL are not completely compatible, and converting between them is lossy. This is a key example. Instead, use CSL-JSON to store your data. If you are using RMarkdown/pandoc to generate your document, then provide a CSL .json file instead of a .bib file.

**Comment by acircleda** [comment]
Good to know. I am using RMarkdown. My .bib's are being generated from an Excel file via RefManageR. Do you know a package or function to get them into the .json format needed?

**Comment by bwiernik** [comment]
Are you using Zotero?

**Comment by acircleda** [comment]
I am not. I am using Google Sheets to R to `RefManageR` to generate the .bib, and then `vitae` to create the CV. When I type it out, it sounds like a complicated process.

**Comment by bwiernik** [comment]
I would recommend not using a spreadsheet to organize your references and instead using a reference manager, such as Zotero (which has the best support for CSL of the available programs). You can use the [rbbt](https://github.com/paleolimbot/rbbt) plugin for RStudio to conveniently connect your Zotero library to RMarkdown and automatically generate your CSL-JSON file at knit time. 

For the immediate situation, generate your .bib file and save it. Then, install Zotero and the BetterBibTeX plugin. Then import your .bib file using the Better BibLaTeX or Better BibTeX translator. Then export Better CSL-JSON. Other tools exist for translating between BibTeX and CSL JSON (e.g., citation.js), but BetterBibTeX has by far the best translation.

Also note that for this specific item, it should be CSL `speech`, not CSL `paper-conference`. `paper-conference` is for papers formally published in conference proceedings. Items only presented at the conference are `speech`.

**Comment by acircleda** [comment]
Thanks. I will reconsider my workflow for this project and try out both Zotero and `rbbt`.
