### ISSUE TITLE
proper use of `locale`, `macro`, and `citation`

### ISSUE THREAD

**Issue by icornelius** [citation-style-language/styles#4840]
`manchester-university-press.csl` is buggy. I would like to update it, but I have questions about contents and format of the csl file. If I compare with a recently updated file (e.g. `modern-humanities-research-association.csl`) I notice

1. `manchester-university-press.csl` lacks a `locale` element
2. `manchester-university-press.csl` does much of the formatting within the `citation` element, whereas `modern-humanities-research-association.csl` makes heavier use of macros.

[CSL documentation](https://docs.citationstyles.org/en/1.0.1/specification.html#macro) states 

> It is recommended to keep the contents of `cs:citation` and `cs:bibliography` compact and agnostic of item types (e.g. books, journal articles, etc.) by depending on macro calls.

From that statement, I understand that `manchester-university-press.csl` does not match current standards. I am looking for advice on how to approach revision. Should I start afresh with a compliant template (perhaps `modern-humanities-research-association.csl` itself)?

**Comment by rmzelle** [comment]
@icornelius, the things you’re highlighting aren’t wrong per se. E.g. a locale section is only necessary if the style needs to overwrite the default translations.

If your corrections are relatively minor, you’re probably best off just modifying the existing style.
