### ISSUE TITLE
Bug in CSL-style heart-rhythm.csl, et al behavior, 123/3 should be 7/3

### ISSUE THREAD

**Issue by milokes** [citation-style-language/styles#4845]
Et al rule for the journal should be 7/3 and the comments state that it been accordingly adjusted from 13/3 but in reality the old 13/3 rule persists (line 262: <bibliography et-al-min="13" et-al-use-first="3" second-field-align="flush">.

(this being one of the reasons for a recent manuscript returned, I was not able to correct the simple bug in Github)

**Comment by POBrien333** [comment]
I have submitted a fix as you can see. Thanks for reporting.
Btw, as you already know how to fix this, why did you not submit your own Pull Request? (just out of interest)

**Comment by rmzelle** [comment]
> I was not able to correct the simple bug in Github

We have instructions on editing styles via Github at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style. Let us know if any steps there are unclear.

**Comment by rmzelle** [comment]
(and this issue has now been fixed. Thanks!)
