### ISSUE TITLE
few csl files not working

### ISSUE THREAD

**Issue by Murgowt** [citation-style-language/styles#4851]
i am trying to get citation from doi  using the command:

```
curl -LH "Accept: text/x-bibliography; style= acta-paediatrica.csl " https://doi.org/10.1037/a0028240
```

But i a running into error with a few styles which give the error:

                            Could not find style in classpath: \/acta-paediatrica.csl

<details>
  <summary>Full Error</summary>
{"status":"error","message-type":"exception","message-version":"1.0.0","message":{"name":"class java.io.FileNotFoundException","description":"java.io.FileNotFoundException: Could not find style in classpath: \/acta-paediatrica.csl","message":"Could not find style in classpath: \/acta-paediatrica.csl","stack":["de.undercouch.citeproc.CSL.loadStyle(CSL.java:224)","de.undercouch.citeproc.CSL.<init>(CSL.java:173)","de.undercouch.citeproc.CSL.<init>(CSL.java:130)","de.undercouch.citeproc.CSL.<init>(CSL.java:94)","sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)","sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)","java.lang.reflect.Constructor.newInstance(Constructor.java:423)","clojure.lang.Reflector.invokeConstructor(Reflector.java:180)","cayenne.formats.citation$__GT_citation.invokeStatic(citation.clj:77)","cayenne.formats.citation$__GT_citation.doInvoke(citation.clj:71)","clojure.lang.RestFn.applyTo(RestFn.java:139)","clojure.core$apply.invokeStatic(core.clj:648)","clojure.core$apply.invoke(core.clj:641)","cayenne.api.transform$eval19358$fn__19359.invoke(transform.clj:67)","clojure.lang.MultiFn.invoke(MultiFn.java:233)","cayenne.api.v1.routes$work_transform_resource$fn__23539$fn__23543.invoke(routes.clj:270)","liberator.core$run_handler.invokeStatic(core.clj:190)","liberator.core$run_handler.invoke(core.clj:147)","liberator.core$handle_ok.invokeStatic(core.clj:244)","liberator.core$handle_ok.invoke(core.clj:244)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$multiple_representations_QMARK_.invokeStatic(core.clj:250)","liberator.core$multiple_representations_QMARK_.invoke(core.clj:250)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$put_to_existing_QMARK_.invokeStatic(core.clj:317)","liberator.core$put_to_existing_QMARK_.invoke(core.clj:317)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$post_to_existing_QMARK_.invokeStatic(core.clj:320)","liberator.core$post_to_existing_QMARK_.invoke(core.clj:320)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$method_patch_QMARK_.invokeStatic(core.clj:329)","liberator.core$method_patch_QMARK_.invoke(core.clj:329)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$method_delete_QMARK_.invokeStatic(core.clj:331)","liberator.core$method_delete_QMARK_.invoke(core.clj:331)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$if_modified_since_exists_QMARK_.invokeStatic(core.clj:351)","liberator.core$if_modified_since_exists_QMARK_.invoke(core.clj:351)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$if_none_match_exists_QMARK_.invokeStatic(core.clj:369)","liberator.core$if_none_match_exists_QMARK_.invoke(core.clj:369)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$if_unmodified_since_exists_QMARK_.invokeStatic(core.clj:389)","liberator.core$if_unmodified_since_exists_QMARK_.invoke(core.clj:389)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$if_match_exists_QMARK_.invokeStatic(core.clj:403)","liberator.core$if_match_exists_QMARK_.invoke(core.clj:403)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$exists_QMARK_.invokeStatic(core.clj:406)","liberator.core$exists_QMARK_.invoke(core.clj:406)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$processable_QMARK_.invokeStatic(core.clj:409)","liberator.core$processable_QMARK_.invoke(core.clj:409)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$encoding_available_QMARK_.invokeStatic(core.clj:413)","liberator.core$encoding_available_QMARK_.invoke(core.clj:413)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$accept_encoding_exists_QMARK_.invokeStatic(core.clj:428)","liberator.core$accept_encoding_exists_QMARK_.invoke(core.clj:428)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$accept_charset_exists_QMARK_.invokeStatic(core.clj:441)","liberator.core$accept_charset_exists_QMARK_.invoke(core.clj:441)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$accept_language_exists_QMARK_.invokeStatic(core.clj:455)","liberator.core$accept_language_exists_QMARK_.invoke(core.clj:455)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$media_type_available_QMARK_.invokeStatic(core.clj:465)","liberator.core$media_type_available_QMARK_.invoke(core.clj:465)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$accept_exists_QMARK_.invokeStatic(core.clj:468)","liberator.core$accept_exists_QMARK_.invoke(core.clj:468)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$is_options_QMARK_.invokeStatic(core.clj:485)","liberator.core$is_options_QMARK_.invoke(core.clj:485)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$valid_entity_length_QMARK_.invokeStatic(core.clj:488)","liberator.core$valid_entity_length_QMARK_.invoke(core.clj:488)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$known_content_type_QMARK_.invokeStatic(core.clj:491)","liberator.core$known_content_type_QMARK_.invoke(core.clj:491)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$valid_content_header_QMARK_.invokeStatic(core.clj:493)","liberator.core$valid_content_header_QMARK_.invoke(core.clj:493)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$allowed_QMARK_.invokeStatic(core.clj:496)","liberator.core$allowed_QMARK_.invoke(core.clj:496)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$authorized_QMARK_.invokeStatic(core.clj:499)","liberator.core$authorized_QMARK_.invoke(core.clj:499)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$malformed_QMARK_.invokeStatic(core.clj:502)","liberator.core$malformed_QMARK_.invoke(core.clj:502)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$method_allowed_QMARK_.invokeStatic(core.clj:505)","liberator.core$method_allowed_QMARK_.invoke(core.clj:505)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$uri_too_long_QMARK_.invokeStatic(core.clj:508)","liberator.core$uri_too_long_QMARK_.invoke(core.clj:508)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$known_method_QMARK_.invokeStatic(core.clj:511)","liberator.core$known_method_QMARK_.invoke(core.clj:511)","liberator.core$decide.invokeStatic(core.clj:103)","liberator.core$decide.invoke(core.clj:91)","liberator.core$service_available_QMARK_.invokeStatic(core.clj:514)","liberator.core$service_available_QMARK_.invoke(core.clj:514)","liberator.core$run_resource.invokeStatic(core.clj:599)","liberator.core$run_resource.invoke(core.clj:597)","cayenne.api.v1.routes$work_transform_resource$fn__23539.invoke(routes.clj:255)","compojure.response$eval22712$fn__22713.invoke(response.clj:47)","compojure.response$eval22634$fn__22635$G__22625__22642.invoke(response.clj:7)","compojure.core$wrap_response$fn__23304.invoke(core.clj:158)","compojure.core$wrap_route_middleware$fn__23288.invoke(core.clj:128)","compojure.core$wrap_route_info$fn__23293.invoke(core.clj:137)","compojure.core$wrap_route_matches$fn__23297.invoke(core.clj:146)","compojure.core$routing$fn__23312.invoke(core.clj:185)","clojure.core$some.invokeStatic(core.clj:2592)","clojure.core$some.invoke(core.clj:2583)","compojure.core$routing.invokeStatic(core.clj:185)","compojure.core$routing.doInvoke(core.clj:182)","clojure.lang.RestFn.applyTo(RestFn.java:139)","clojure.core$apply.invokeStatic(core.clj:648)","clojure.core$apply.invoke(core.clj:641)","compojure.core$routes$fn__23316.invoke(core.clj:192)","compojure.core$routing$fn__23312.invoke(core.clj:185)","clojure.core$some.invokeStatic(core.clj:2592)","clojure.core$some.invoke(core.clj:2583)","compojure.core$routing.invokeStatic(core.clj:185)","compojure.core$routing.doInvoke(core.clj:182)","clojure.lang.RestFn.applyTo(RestFn.java:139)","clojure.core$apply.invokeStatic(core.clj:648)","clojure.core$apply.invoke(core.clj:641)","compojure.core$routes$fn__23316.invoke(core.clj:192)","compojure.core$make_context$handler__23382.invoke(core.clj:285)","compojure.core$make_context$fn__23384.invoke(core.clj:293)","compojure.core$routing$fn__23312.invoke(core.clj:185)","clojure.core$some.invokeStatic(core.clj:2592)","clojure.core$some.invoke(core.clj:2583)","compojure.core$routing.invokeStatic(core.clj:185)","compojure.core$routing.doInvoke(core.clj:182)","clojure.lang.RestFn.applyTo(RestFn.java:139)","clojure.core$apply.invokeStatic(core.clj:648)","clojure.core$apply.invoke(core.clj:641)","compojure.core$routes$fn__23316.invoke(core.clj:192)","compojure.core$routing$fn__23312.invoke(core.clj:185)","clojure.core$some.invokeStatic(core.clj:2592)","clojure.core$some.invoke(core.clj:2583)","compojure.core$routing.invokeStatic(core.clj:185)","compojure.core$routing.doInvoke(core.clj:182)","clojure.lang.RestFn.applyTo(RestFn.java:139)","clojure.core$apply.invokeStatic(core.clj:648)","clojure.core$apply.invoke(core.clj:641)","compojure.core$routes$fn__23316.invoke(core.clj:192)","ring.middleware.logstash$wrap_logstash$fn__29143.invoke(logstash.clj:110)","ring.middleware.keyword_params$wrap_keyword_params$fn__30014.invoke(keyword_params.clj:36)","ring.middleware.nested_params$wrap_nested_params$fn__30062.invoke(nested_params.clj:89)","ring.middleware.params$wrap_params$fn__29978.invoke(params.clj:67)","cayenne.api.route$wrap_cors$fn__30605.invoke(route.clj:101)","metrics.ring.expose$expose_metrics_as_json$fn__29529.invoke(expose.clj:94)","metrics.ring.instrument$instrument$fn__29545$fn__29546.invoke(instrument.clj:44)","metrics.ring.instrument.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)","com.yammer.metrics.core.Timer.time(Timer.java:91)","metrics.ring.instrument$instrument$fn__29545.invoke(instrument.clj:43)","heartbeat.ring$wrap_heartbeat$fn__29231.invoke(ring.clj:18)","cayenne.api.conneg$wrap_accept$fn__21175.invoke(conneg.clj:53)","cayenne.api.route$wrap_exception_handler$fn__30610.invoke(route.clj:110)","cayenne.api.route$wrap_ignore_trailing_slash$fn__30618.invoke(route.clj:136)","org.httpkit.server.HttpHandler.run(RingHandler.java:91)","java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)","java.util.concurrent.FutureTask.run(FutureTask.java:266)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)","java.lang.Thread.run(Thread.java:745)"],"cause":null}}
</details>

**Comment by rmzelle** [comment]
You're trying to use Crossref's Citation Formatting Service? (https://www.crossref.org/labs/citation-formatting-service/)

On that page, they link to http://data.crossref.org/styles which shows all available CSL styles. It looks like they don't offer acta-paediatrica.csl, which was turned into an independent CSL style in 2018, so their style collection is likely out of date.

![image](https://user-images.githubusercontent.com/77951/83978856-4e670c80-a8d8-11ea-95f8-ee3325074c34.png)

You could ask them to update their CSL styles (https://github.com/CrossRef/rest-api-doc seems like the best place; just mention this issue to them).

**Comment by adam3smith** [comment]
Oddly this works via CrossCite: 
https://citation.crosscite.org/format?doi=10.1037/a0028240&style=acta-paediatrica&lang=en-US

which I thought was on the CN backend

**Comment by rmzelle** [comment]
@adam3smith, thanks for checking. Still doesn't look like something we can fix on our end.

**Comment by adam3smith** [comment]
yeah, absolutely this isn't our error. 
I mentioned this because CrossCite might be a helpful because it works on the same set of DOIs as DOI content negotiation and is, apparently, up to date.
