### ISSUE TITLE
Incorrect behavior for particles in Chicago Author Date?

### ISSUE THREAD

**Issue by coryschires** [citation-style-language/styles#4857]
## Problem
I recently noticed that the [Chicago Author Date CSL](https://github.com/citation-style-language/styles/blob/master/chicago-author-date.csl) does not handle non-dropping participle as I would expect.

## How to recreate
Given this CSL JSON:
```
csl = {
  "id": "12779",
  "type": "article-journal",
  "title":  "My example article",
  "container-title": "Global Issues",
  "container-title-short": "Global Issues",
  "publisher": "University of Testing",
  "author": [
    { "given"=>"Ludwig", "family"=>"van Beethoven" }
  ]
}
```

Using the [chicago-author-data CSL](https://github.com/citation-style-language/styles/blob/master/chicago-author-date.csl), this citation renders as:

> Beethoven, Ludwig van. n.d. “My Example Article.” Global Issues.

But I would expect the "van" to come before "Beethoven" as in:

> van Beethoven, Ludwig. n.d. “My Example Article.” Global Issues.

## Why is this happening?
As far as I can tell, the [chicago-author-data CSL](https://github.com/citation-style-language/styles/blob/master/chicago-author-date.csl) has `demote-non-dropping-particle` set incorrectly:

```
demote-non-dropping-particle="display-and-sort"  # Current behavior
demote-non-dropping-particle="sort-only"         # Correct behavior
```

## Or maybe I'm just wrong?
Or maybe the current behavior is correct and my expectation is wrong? Looking through the Chicago Manual of Style, I don't see any explicit guidelines about how to handle non-dropping participles (but maybe I'm not looking hard enough).

Here's what I did find:

<img width="446" alt="Screen_Shot_2020-06-09_at_6_11_31_PM" src="https://user-images.githubusercontent.com/104563/84209832-c0785680-aa7c-11ea-8c45-0468d7b9d1ec.png">

<img width="459" alt="Screen_Shot_2020-06-09_at_6_11_15_PM" src="https://user-images.githubusercontent.com/104563/84209862-d259f980-aa7c-11ea-8fea-ba365121549d.png">

Also, for what it's worth, the author who brought this issue to my attention definitely thinks the current behavior is incorrect (and I'm inclined to trust his judgement about how his own name ought to be formatted).

## Solution?
Of course, I could easily update the CSL file that I am using locally. But, before doing so, I wanted to post an issue to check if my perception is correct. Also, assuming I am correct, I would love to see the "official" CSL updated so my own version matches the version hosted in this repo.

**Comment by adam3smith** [comment]
This was actually changed a while ago based on feedback by @njbart : https://github.com/citation-style-language/styles/pull/1677
However, the exact example from the CSL specifications, Jean de La Fontaine, is currently treated incorrectly by the CSL style (Manual says La Fontaine, Jean de; output is Fontaine, Jean de La). 

It's clearly not possible to get both right. What I'm not clear on, though, is where Nick's assertion from the earlier thread that Keere, Pieter van den should be "van den Keere" in citations comes from. I don't see that anywhere and without that requirement, that could just be satisfied by using "Pieter van den" as a first name. 

So I'm currently inclined to set this back to "never" (it's definitely not "sort-only" -- Van Rensellaer is sorted under V, de Gaulle under D etc.), but will wait for others to chime in

(Tussenvoegsel, i.e. the dutch "van" have their own set of problems with capitalization and we're never going to get that right, I'm afraid)

**Comment by njbart** [comment]
My assertion comes from CMOS 16e, 8.10 = CMOS 17e, 8.10:

> **8.10 *Dutch names.*** In English usage, the particles *van*, *van den*, *ter*, and the like are lowercased when full names are given but usually capitalized when only the last name is used.

> Joannes van Keulen; Van Keulen  
Pieter van den Keere; Van den Keere  
Vincent van Gogh; Van Gogh  
Gerard ter Barch; Ter Barch

(Capitalisation is of course a different, as of yet, it seems, unsolved problem in CSL, but what this shows very clearly is what exact part is considered to be the last name [in a wider sense].)

In addition, a few other points:

- Ludwig van Beethoven is not a good example since in his case (a German name) "van" is a dropping particle (CMOS 16e, 8.8 = CMOS 17e, 8.8: "Ludwig van Beethoven; Beethoven").

- "La Fontaine, Jean de" is formatted correctly by Zotero using chicago-author-date if entered in Zotero's two-part name field as [La Fontaine] [Jean de].

**Comment by njbart** [comment]
@coryschires - Well, as I said, Zotero refuses to import it, and pandoc-citeproc is unable to process it. [citeproc-java](https://michel-kraemer.github.io/citeproc-java/), a command line tool based on citeproc-js, does not report an error but does not show any output either.

With the following modified CSL JSON, all three programs seem to work as expected:

```
[
  {
    "id": "12779",
    "type": "article-journal",
    "title": "My example article",
    "container-title": "Global Issues",
    "author": [
      {
        "given": "Robert",
        "family": "van Gulik"
      }
    ]
  }
]
```

Using this, as `test1.json`, to run

`citeproc-java bibliography -i test.json -s chicago-author-date.csl`

the output is

`Gulik, Robert van. n.d. “My Example Article.” Global Issues.`

However, if you protect the family part, like this

`"family": "\"van Gulik\""`

the output becomes

`van Gulik, Robert. n.d. “My Example Article.” Global Issues.`

… which seems to match what you’ve been expecting.

**Comment by njbart** [comment]
@coryschires - Depending on how you call citeproc-js you might also be able to set its `parse-names` flag globally to `false` (that’s what Zotero does, which fully parses names itself before forwarding CSL JSON data to citeproc-js). In this case you wouldn’t have to bother with wrapping names such as ”van Gulik” in extra quotes, but you’d have to make sure that all other names containing particles and suffixes in your CSL JSON data have been fully parsed.

**Comment by adam3smith** [comment]
Thanks again @njbart for chiming in. Given the above, we'll leave things as they are.

**Comment by coryschires** [comment]
Thanks everyone! Sorry for my delayed response.

The problem is still a little unclear to me, so I'd like to restart the issue (as I understand it). Hopefully, this will not only benefit me but also any other non-experts who stumble across this issue.

First, to restate the original problem:

```
Given the following CSL-JSON:
  [
    {
      "id": "12779",
      "type": "article-journal",
      "title": "My example article",
      "container-title": "Global Issues",
      "author": [
        { "given": "Robert", "family": "van Gulik" }
      ]
    }
  ]
When using citeproc-js to render the citation
chicago-author-date will produce: `Gulik, Robert van`
But the author expects `van Gulik, Robert`
```

We could fix this problem by changing `demote-non-dropping-particle` from `display-and-sort` to `never`. But, if I understand correctly, that would cause problems for Dutch and Arabic CMOS conventions. So, either way, we're stuck.

So, the solution, as recommended by @njbart, is to leave `demote-non-dropping-particle` set to `display-and-sort` and wrap the the `family` name in double quotes in order to achieve the desired behavior for Robert van Gulik (and other such cases). At least this way, one can achieve the desired result whereas if we changed to `never` Dutch and Arabic names would be broken without any way of being fixed.

Is that an accurate recap of the situation? (Again, sorry to belabor the discussion. Just trying to make sure I got it.)

**Comment by adam3smith** [comment]
Yes, that's accurate. The one amendment to this is [Nick's post](https://github.com/citation-style-language/styles/issues/4857#issuecomment-642587197) about setting the `parse-names` flag to false (and making sure all particles are entered in the CSL JSON as such), in which case ` { "given": "Robert", "family": "van Gulik" }` would already be rendered correctly.

If you're putting together your own CSL JSON, this seems like the cleaner approach to me.

**Comment by coryschires** [comment]
Thanks. That's helpful. Let me make sure I understand...

citeproc-js (and probably other citeproc tools) will, by default, attempt to parse the author name to infer less common name parts such as dropping particles, suffixes, etc. Alternatively, you can explicitly encode each name part as a separate key in the author's name field. [More info about how this works in citeproc-js](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#name-fields).

If I understand correctly, if I set `parse-names` to `false`, then I will not need to disambiguate using double quotes. But I would also need to be sure to explicitly encode each of the author's name parts (i.e. I cannot rely on citeproc-js to parse it for me).

Is that a correct understanding of the trade off?

**Comment by adam3smith** [comment]
yup, that's exactly right.
