### ISSUE TITLE
APA 7th Edition doesn't render all article journals in sentence case when a bibliography is created

### ISSUE THREAD

**Issue by OriginUnknown** [citation-style-language/styles#4864]
According to the [APA 7th Edition Reference Guide](https://apastyle.apa.org/instructional-aids/reference-guide.pdf), the **title of journal articles should appear in sentence case when a bibliography is generated**. However, when this citation style is used alongside article journals with the title written in title case and is then subsequently used as a reference in a Word document, the generated bibliography renders the title of such article journals in title case.

After investigating the issue, it turns out that the `text-case` property responsible for rendering the bibliography under this particular CSL isn't set at all (I.E. no value has been set for this property).

Using the [citation styles editor](https://editor.citationstyles.org/visualEditor/) to set the `text-case` property to `sentence` case, the amended CSL file was uploaded into Mendeley Desktop and tested against article journals with their titles written in title case. After generating the bibliography, the outcome rendered these article journals in the correct sentence case style, strongly suggesting that there's a fault with the initial APA 7th Edition CSL file.

I've taken the liberty of creating a [PR](https://github.com/citation-style-language/styles/pull/4865#issue-433802937) containing the fix for the APA 7th Edition CSL and have followed the [Guide to submitting CSL style](https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md) to ensure that the amended file is both validated and meets the citation style language criteria.

**Comment by adam3smith** [comment]
Thanks -- see my explanation for why we're not taking this in the pull request. (English) titles should be entered in sentence case in the first place and automated sentence case transformation doesn't work reliably enough.

**Comment by bwiernik** [comment]
This issue can probably be closed?

**Comment by OriginUnknown** [comment]
As I mentioned in the PR, thank you @adam3smith for the expedient response to my query regarding sentence casing. I just wanted to know if you guys have plans of deprecating the `sentence` value as an option for setting `text-case` on CSLs in future?
