### ISSUE TITLE
Conjunctions with Non-Latin languages

### ISSUE THREAD

**Issue by PrimoQA** [citation-style-language/styles#4873]
Hello, thank you very much for the great API.
We are facing some issue on different languages.
When working with Non-Latin languages such as Russian or Hebrew, conjunctions such as '&' or 'et. al.' are not being translated and displayed in English.
for example APA CSL style:

Мария Владимировна Певная, & Анна Александровна Кузьминчук (2014). ИСТОРИЯ АМЕРИКАНСКОГО ВОЛОНТЕРСТВА В СОЦИОЛОГИЧЕСКОМ РАКУРСЕ Sovremennye Issledovaniâ Socialʹnyh.

We've tried different language formats ( "heb", "he" or "he-IL" for hebrew) but still getting the same response.

Below is an example for parameters on the API request.
The CSLItemData object sent to the API for the language format "heb":

{"id":"-GEN-1as39vqkk5","type":"book","language":"heb","author":[{"family":"כתרי, רון","given":""}
,{"family":"מלצר, אפי","given":""}],"issued":{"date-parts":[[2008]]},"container-title":"מבט מל"מ : כתב עת לענייני מודיעין ובטחון מבית המרכז למורשת המודיעין","DOI":"","edition":"","ISBN":"","ISSN":"","issue":"52","keyword":"מבט מלמ (המרכז למורשת המודיעין)","note":"","number-of-pages":"","page":"","page-first":"","PMID":"","publisher":"המרכז למורשת המודיעין (מ.ל.מ) ע"ר","publisher-place":"","section":"","title":"גיליון 52","URL":"","volume":""}

Can you please assist in solving this?
Thanks in advance.

**Comment by bwiernik** [comment]
First, locales are defined using the two-letter or four-letter ISO forms (e.g., `he` or `fr-FR`). See the locale names here: https://github.com/citation-style-language/locales

Second, to be clear, localization is controlled by the **document** locale, not the cited item locale. So, if you want terms to be in Hebrew or Russian, you need to set the document to use the appropriate locale (and it will use the same locale regardless of the item language). The CSLm extension to CSL (see [here](https://citeproc-js.readthedocs.io/en/latest/csl-m/)) allows for multilingual bibliographies.

Third, the `&` between names currently cannot be localized. If the text-form `and` is used, that will be translated, but `&` is always used if `and="symbol"` is used. That will change in an upcoming version of CSL.

Both of your examples have only two authors. `et-al` should localize as needed based on the document locale.

**Comment by rmzelle** [comment]
And are you asking about the Primo API (https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/050Other_Configuration/Managing_Citation_Styles_for_Primo_VE, https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Back_Office_Guide/110Additional_Primo_Features/Managing_Citation_Styles)? The CSL project itself doesn't offer any API services.

**Comment by adam3smith** [comment]
Closing as this is really a question for Exlibris
