### ISSUE TITLE
Wiley VCH books

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/styles#4889]
The current style pretty much looks nothing like the author guidelines anymore: 
  - https://authorservices.wiley.com/author-resources/book-authors/prepare-your-manuscript/house-style.html#t
  - https://authorservices.wiley.com/asset/book-author-documents.html/House_Style_References_Examples.docx

Their example styles and BibTeX file just use the natbib `plainnat.bst` file. Perhaps we should just translate `plainnat` into CSL? And make this a dependent style? The publisher permits either author-date or numeric-brackets formats for the citations.

@POBrien333 if you have time? https://www.bibtex.com/s/bibliography-style-natbib-plainnat/

(I came across this because this is the only style that currently uses the undocumented `container` date variable which is slated for removal.)

**Comment by POBrien333** [comment]
Hi @bwiernik 
Just looked into this...

I am not sure how the plainnat style relates to this Wiley house style?
The wiley-vch-books.csl we have certainly needs edits (numeric >> author-date) and a few smaller amendments for the bibiliography, but the plainnat style you linked to is vastly different.

(Happy to also make that plainnat style, but not sure what exactly that is for)

**Comment by bwiernik** [comment]
The LaTeX template Wiley distributes just uses the plainnat citation style. The published books seem fairly inconsistent.

**Comment by POBrien333** [comment]
Ok, I see.
Happy to make that style. Any idea for a name for it?

**Comment by bwiernik** [comment]
I think BibTeX plainnat (numeric) and BibTeX plainnat (author-date) would work.

**Comment by adam3smith** [comment]
> BibTeX plainnat (numeric) and BibTeX plainnat (author-date) would work.

I'd like to find something better. Since we also have a style that tries to emulate actual bibtex (`bibtex.csl`) I'm worried that these will cause confusion. @rmzelle do you have any ideas?

**Comment by bwiernik** [comment]
Actually, since these are from the natbid package, how about "natbib - plainnat (numeric)"

**Comment by rmzelle** [comment]
> Since we are modeling of the natbib package implementation, how about "natbib - plainnat (numeric)"

Yes, I think that's the best option here. Per the readme at https://www.ctan.org/tex-archive/macros/latex/contrib/natbib:

> The standard .bst files (plain et al) and other numerical citation .bst files
are also understood, but they can produce only numerical citations.
Replacement .bst files
>
> * plainnat.bst
> * abbrvnat.bst
> * unsrtnat.bst
>
> are provided to produce the same formatting of the reference list as the
standard equivalent, but allowing both author-year and numerical citations.

So especially if we have an author-date variant, it seems to make more sense to name this style after natbib than after BibTeX.

**Comment by POBrien333** [comment]
@rmzelle 
Can this issue be closed?
