### ISSUE TITLE
medical-physics.csl may be incorrect and redundant

### ISSUE THREAD

**Issue by fedorov** [citation-style-language/styles#4901]
I used [`medical-physics.csl`](https://github.com/citation-style-language/styles/blob/master/medical-physics.csl) via [Paperpile](https://paperpile.com/) in Google Docs. 

I've been working on a revision of a manuscript to Medical Physics, addressing comments of the reviewer about missing DOIs/URLs for some of the references, and first I thought I would need to change the csl to add DOI/URL. However, that turned out to be far from trivial, and so I turned back to the [Medical Physics submission guidelines](https://aapm.onlinelibrary.wiley.com/hub/journal/24734209/about/author-guidelines#_4._PREPARING_YOUR), which state unambiguously that

> References should follow standard American Medical Association (AMA) Style.

I then was able to switch to AMA via [`american-medical-association.csl`](https://github.com/citation-style-language/styles/blob/master/american-medical-association.csl), and had my problem solved.

This led me to think that `medical-physics.csl` is not needed, and in fact creates confusion, since it omits URLs/DOIs that are often really critical.

`medical-physics.csl` was added in [this commit](https://github.com/citation-style-language/styles/commit/6fc73bf6b337ba082eedf3bd0753e409b7a63cd5#diff-097ec79ddd2c442e6ea508a21fd5ddca) on Sept 16, 2012.

But `american-medical-association.csl` was added back in Dec 18, 2010 as [`ama.csl`](https://github.com/citation-style-language/styles/commit/bdd98f5bb11ed56c045de993b5a9eaa04f8e7e22#diff-7476b4e3cad67f6c6608847ae5bb5885), and later renamed.

I believe `medical-physics.csl` should be removed, or should be replaced with the content of `american-medical-association.csl`.

**Comment by adam3smith** [comment]
(journal changed publisher & citation style recently; should indeed be AMA dependent)

**Comment by rmzelle** [comment]
@fedorov, thanks for reporting this. The Medical Physics CSL style has been made a dependent of AMA.
