### ISSUE TITLE
Alternative to renamed-styles/unstable ids? 

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/styles#4903]
I've been thinking about the problems with `renamed-styles` and potentially changing style IDs, and it occurred to me that maybe we could solve all of these problems using dependent styles? If a style ID were changed, rather than listing it in renamed styles, why not make a dependent style with the old id? These dependent styles could be stored in a specific legacy-id folder or similar?

**Comment by rmzelle** [comment]
Downstream CSL consumers would have to treat such styles specially, though. I.e., they wouldn't want these legacy-ID dependents to show up in their browsable collection, but they should make sure to resolve any requests to these styles (so they can't completely ignore them).

Not sure this approach is any cleaner than having renamed-styles.json.
