### ISSUE TITLE
Style Info Not Found

### ISSUE THREAD

**Issue by anritsupolii** [citation-style-language/styles#4917]
Our Style journal at [zotero](https://www.zotero.org/styles/politeknik-negeri-manado-jurnal-p3m) repository are **Searchable** through Mendeley Cite and Zotero (Web and Desktop) using keyword "jurnal".
But there is no **Style Info** in [csl.mendeley](https://csl.mendeley.com) and [citationstyles.org](https://editor.citationstyles.org). Help is needed on how to achieve this. Thanks

Regards.

**Comment by POBrien333** [comment]
(this relates to this style: https://github.com/citation-style-language/styles/blob/master/politeknik-negeri-manado-jurnal-p3m.csl )

**Comment by anritsupolii** [comment]
> The repository on citationstyles.org only gets updated every few months. That database is actually just mainly used for using styles as templates to develop other styles.
I see, our styles using IEEE Template.

> Mendeley uses the CSL repository we have here to include in their releases. WHEN they do their updates we cannot control. You'd need to speak to Elsevier about this issue. Completely not in our control.
Ok, will contact Elsevier later.
 
> The Zotero database is by far the one to look at for this. Any change we make here on the GitHub repository gets merged into that database within hours (certainly within 24h): https://www.zotero.org/styles?q=politeknik-negeri-manado-jurnal-p3m
Yes that's right, so far Zotero is directly conducting data acquisition. 
Thank you for your answer.

Regards.
