### ISSUE TITLE
Localize language descriptors in titles

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#4921]
I think it would be better to localize the language descriptors in titles to make styles less English-centric. E.g. change `<title>Tijdschrift voor Geneeskunde (Dutch)</title>` to `<title>Tijdschrift voor Geneeskunde (Nederlands)</title>`.

This can be done relatively easily since we already have all translations at https://github.com/citation-style-language/locales/blob/cbb45961b815594f35c36da7e78154feb5647823/locales.json#L49.

P.S. Used some regex for this (in Atom, with manual curation of some edge cases):

Find:
`Chinese([^\(]*\).*</title>)`

Replace:
`中文$1`

**Comment by rmzelle** [comment]
Still need to update some journals metadata as well: https://github.com/citation-style-language/journals/search?q=german (https://github.com/citation-style-language/journals/blob/7474b25a712fdac4954e072c7dbfbd13e6c7e9c6/springer/_journals.tab has "German" in the title field, and https://github.com/citation-style-language/journals/blob/7474b25a712fdac4954e072c7dbfbd13e6c7e9c6/springer-fachzeitschriften-medizin/_journals.tab has "German" in its LANGUAGE field.

**Comment by adam3smith** [comment]
I think this is all done @rmzelle ?

**Comment by adam3smith** [comment]
Closing
