### ISSUE TITLE
DOI link has extra 'dot' in URL

### ISSUE THREAD

**Issue by Gressling** [citation-style-language/styles#4971]
This applies for  ACS Nano american-chemical-society.csl where is a rendering error in DOI URL.

Example: 
(2) 	Gallant, S. I. Connectionist Expert Systems. Commun. ACM 1988, 31 (2), 152–169. https: //doi.org/10.1145/42372.42377.

opens the URL 'https: //dx.doi.org/10.1145/42372.42377.' which is invalid due to the extra dot. 
Should be: 'https: //dx.doi.org/10.1145/42372.42377', so the href of <a> is wrong?

**Comment by Gressling** [comment]
<img width="390" alt="URL error" src="https://user-images.githubusercontent.com/21124662/90340062-c139e580-dff5-11ea-946e-8597b4a552b4.png">

**Comment by adam3smith** [comment]
Which reference manager is this? While it's probably a bad rule, many citation styles include a period after the URL/linked DOI. 

The CSL styles don't say what the hyperlink would be, so including the period (as well as adding the unnecessary dx.) is something your reference manager appears to do -- you should contact them.

**Comment by Gressling** [comment]
It is paperpile. They said: _"This is not an issue per se, but an unfortunate consequence of ACS style guidelines which require a full stop to close bibliographic entries. 
I should also point out we don't generate our own styles but fetch them from online repository CSL - where users can browse 8,000+ styles and edit/customize them if necessary with their editing tool.

I'm afraid we don't have the necessary resources to troubleshoot style issues / customization; I did poke around the editor in the hopes of finding a simple solution (which is sometimes the case) but was unsuccesful so I have no suggestions to share."_

**Comment by adam3smith** [comment]
You can point them to this thread -- it really isn't our issue, the hyperlinking is done by Paperpile or the citation processor they're using; CSL styles do not even have the ability to specify hyperlinks.
 
E.g. in Zotero using the exact same CSL style and Google docs integration you get no hyperlinking:
![image](https://user-images.githubusercontent.com/128986/91178092-a8df6000-e6b2-11ea-96f2-70739d17e105.png)

and using HTML export you get correct hyperlinking:
![image](https://user-images.githubusercontent.com/128986/91178325-f9ef5400-e6b2-11ea-9776-a1715c780aef.png)

**Comment by agruber** [comment]
Google Docs automatically converts something the looks like a hyperlink to an actual hyperlink. I am afraid there is now way to tell Google Docs that it should not include the full stop when it automatically assigns the hyperlink.

**Comment by Gressling** [comment]
With manual copy/paste Google doc ommits the last '.', parses correctly. So for manual paste. Example:  https://doi.org/10.1021/acs.analchem.9b04884.    works

**Comment by adam3smith** [comment]
I thought this might be google docs, but the `dx.doi.org` in the hyperlink (vs. `doi.org` in the printed URL) suggests this is happening somewhere else. Google docs wouldn't change the actual link, I'm pretty sure.

**Comment by adam3smith** [comment]
I'm closing this since it's definitely not a CSL issue -- I does seem to me like Paperpile should be able to address this, but obviously they know best.
