### ISSUE TITLE
CSL file for Journal of Industrial microbiology and biotechnology

### ISSUE THREAD

**Issue by yogeshgupt** [citation-style-language/styles#4997]
Hi,

I am not able to find the CSL file for the Journal of Industrial microbiology and biotechnology (https://link.springer.com/journal/10295/volumes-and-issues/47-6)

I will be thankful if anyone can share the CSL file for this Journal.

Many thanks,
Yogesh

**Comment by adam3smith** [comment]
That's `Springer Basic (numeric, brackets)`
https://www.zotero.org/styles?q=id%3Aspringer-basic-brackets
