### ISSUE TITLE
Can't find uploaded style 

### ISSUE THREAD

**Issue by cappelluti** [citation-style-language/styles#5012]
Hi,
two days ago I correctly uploaded a new style language on Github: clinical-management-issues.csl  (https://github.com/citation-style-language/styles/pull/5008).
The submission has passed all automated tests. Now, do we have to wait a review of pull requests before find the style in Zotero repository?

Thank you,
Enzo

**Comment by adam3smith** [comment]
> Now, do we have to wait a review of pull requests before find the style in Zotero repository?

Yes, exactly, that's how essentially all projects on github work. There are some automated tests and then project maintainers manually review and request changes or merge.
