### ISSUE TITLE
Access date not appearing in Harvard 10th Edition citation style

### ISSUE THREAD

**Issue by ada59** [citation-style-language/styles#5094]
I am using the style Harvard-10th Edition in Mendeley Desktop. I would like the information contained in the “Date accessed” section in the Desktop to be shown at the end of the citation of all types of documents in the form (Accessed: year) or similar. Yet, I notice that when I try to edit the style to add the date accessed, the information only appears if contained in the “Year” section (i.e. when the date variable is set to be "issued" date).
Does this style not include access dates? I am unsure about whether this is the problem or if I might be doing something wrong in my manual edit on the CSL Editor.
The steps I have followed to try include the information are:

Macro: 
-access > Conditional > If DOI > Group > Date > variable: accessed
-access > Conditional > Else-If URL > Group > Date > variable: accessed

Thanks a lot in advance for the help.

**Comment by adam3smith** [comment]
I'd guess you just have this set incorrectly in Mendeley: Make sure under View --> Citation Styles --> More Styles you have "Include URLs and access data.." set to "All Document types". Or are you saying this also doesn't show in the preview in the CSL Editor?

**Comment by ada59** [comment]
Thank you for this super quick reply. I have double-checked the setting and "All Document types" is selected on my Mendeley. And yes, actually the example citations in the visual CSL editor appear in the format I want, with an accessed year different from the published. 
It is when I try to use the style with my refs (e.g. in a word document) when the issue appears. If my edit contains "accessed" in date variable, the formatted citation appears without the added "(Accessed: year)" at the end. If the edit contains "issued" in date variable, the citation includes the edit with the information in the "Year published" Mendeley section.

**Comment by ada59** [comment]
Oh, so I have figured it out, sorry for the trouble. It seems that the information is not picked up unless in the format dd/mm/yyyy in this section. All is solved, thanks a lot!
