### ISSUE TITLE
Add new input option to Mendeley interface

### ISSUE THREAD

**Issue by Soolia** [citation-style-language/styles#5129]
I'm trying to change my APA 7 style in Mendeley so that it will correctly reference a republished book. Looking for advice on how to make this happen - I found some elements to change in the CSL editor (publication history; original date), but these do not appear as input options when entering reference details in Mendeley. 

Any advice would be most helpful. Thanks!

**Comment by POBrien333** [comment]
@bwiernik could you have a look?

**Comment by adam3smith** [comment]
Sorry for not responding, but this isn't actually a style question, it's a Mendeley question. Mendeley doesn't have those fields.
In Mendeley Desktop, you can add these in a note like this:
![image](https://user-images.githubusercontent.com/128986/101513249-f8882580-3949-11eb-9aaf-f8a7bd7d070f.png)

I'm not quite sure what "publication history" refers to in the editor, but I suspect that'd be `references`

**Comment by bwiernik** [comment]
"publication-history" is the name of the macro. @Soolia There isn't any need to edit the APA style for republished books. It is already written to format them according to the manual. See, e.g., https://www.zotero.org/groups/2205533/test_items_library/collections/MR2N872S/items/QEIICTIX/collection

**Comment by POBrien333** [comment]
@adam3smith 
Can this issue be closed?
