### ISSUE TITLE
referencing style for the Aquatic Conservation: Marine And Freshwater Ecosystems

### ISSUE THREAD

**Issue by GSmith178** [citation-style-language/styles#5152]
Hi, 

The referencing style for the Aquatic Conservation: Marine And Freshwater Ecosystems switched to Harvard from 1st March 2020. Please can this be updated in Mendeley. Please can you confirm when actioned

Many thanks,
Georgie

**Comment by POBrien333** [comment]
Hi,

Thanks for reporting the issue.

"Harvard" is actually not one specific style, but just a way of citing in an author-date way. The current style already does this correctly. E.g: (Mares, 2001)

However, I see there is some minor discrepancies between the style outlined in their guidelines and the style we have on the repository and I will look into fixing those. We will post here when a new style is available. :)

**Comment by POBrien333** [comment]
@GSmith178 
The updated style has now been merged. It will be available for Zotero immediately, but Mendeley has a different release schedule. But you can download the style right now by right-clicking on this link, "Save as..." and download it. Install it according to the manufacturer's manuals.
https://raw.githubusercontent.com/POBrien333/styles/5ae065c3bbb7f49738ef623ce5e49305b2a57961/aquatic-conservation.csl
