### ISSUE TITLE
issue with health-and-human-rights-journal.csl #3537

### ISSUE THREAD

**Issue by lucianobottini** [citation-style-language/styles#5158]
This citation style is not adding more the one citation/source per reference and separates each citation in a new reference number. The style should be endnotes, with one endnote per sentence with all the citation.

https://cdn1.sph.harvard.edu/wp-content/uploads/sites/2469/2019/12/HHR-EDITORIAL-STYLE-GUIDE_2019-1.pdf, page 17: "The Center uses endnotes, not footnotes, for citations. Endnote numbers within the text should be placed at the end of the sentence, rather than within the sentence. Each sentence may include only one. Combine into this note all relevant reference material from the sentence.

Thank you

**Comment by POBrien333** [comment]
Hi.
Thanks for reporting the error. That was indeed not meant to be a numeric style, but a note one.
I have fixed a bunch of errors. Give it a test ride. Right click, save as..., install: https://raw.githubusercontent.com/citation-style-language/styles/5808c6cab55aca19d7ff0969bbbace9c24de91b8/health-and-human-rights-journal.csl
