### ISSUE TITLE
Test if suppress author was checked

### ISSUE THREAD

**Issue by jogrue** [citation-style-language/styles#5167]
Hi there,

Many applications (e.g., Zotero) have an option to suppress the author. I am currently working with a style that outputs my Zotero database keys (from BetterBibTex) in Word in a way that could easily be transferred to a Markdown/Pandoc file. Basically, a piece in my database might have the key `jogru-bugreport-2020`. It then becomes `[@jogru-bugreport-2020]` and it should become `[-@jogru-bugreport-2020]` if "Suppress author" was checked. However, this is not implemented, yet (this is the simple style https://github.com/retorquere/zotero-better-bibtex/blob/master/better-bibtex-citekeys.csl)

I was trying something like this:
```xml
  <macro name="noauthor">
    <choose>
      <if variable="suppress-authors">
        <text value="@" prefix="-"/>
      </if>
      <else>
        <text value="@"/>
      </else>
    </choose>
  </macro>
```

`"suppress-authors"` is how the Zotero key is named. I was also trying `"suppress-author"` (which citeproc-js mentions) and I checked if I could do it with `if variable="author"` but that also did not work. I was also thinking about names and substitutes, but I could not come up with anything. Actually, I have not found any information on how the suppressing is done. I reported it here, but we do not have any ideas right now: https://github.com/retorquere/zotero-better-bibtex/issues/1703

So my question is: Is there any way to test if the suppress author option was checked (and accordingly change the output of the style)?

Best,
Johann

**Comment by adam3smith** [comment]
Sorry we never answered this, but the answer is also just no, there's no way. Suppress author isn't a feature of CSL -- it's a way in which CSL support is implemented in several tools, and so CSL styles have no knowledge of it and no ability to address it. 
While better support for author-date citations is planned, I don't think we'll try to address this particular edge case.
