### ISSUE TITLE
Citations for scores are not formatted correctly in the Chicago style

### ISSUE THREAD

**Issue by abbales** [citation-style-language/styles#5177]
The citation formatting for scores, using the Chicago (author/date) and Chicago (notes/bibliographies) style is incorrect. The score title is quoted instead of italicized. 

Example 1: [Duke Ellington](https://onesearch.library.nd.edu/permalink/f/tgve9/ndu_aleph001532605)
  Ellington, Duke. 1995. “Duke Ellington”. Milwaukee, WI: H. Leonard.
  Ellington, Duke. “Duke Ellington.” Milwaukee, WI: H. Leonard, 1995.
Should be
  Ellington, Duke. 1995. _Duke Ellington_. Milwaukee, WI: H. Leonard.
  Ellington, Duke. _Duke Ellington_. Milwaukee, WI: H. Leonard, 1995.
[Record metadata](https://onesearch.library.nd.edu/primo-explore/fulldisplay?docid=ndu_aleph001532605&vid=NDU&search_scope=nd_campus&tab=nd_campus&lang=en_US&context=L&showPnx=true). The document type (score) is indicated in the record/display/type field.

Example 2: [Ring des Nibelungen. Rheingold](https://onesearch.library.nd.edu/permalink/f/1phik6l/ndu_aleph003319002)
  Wagner, Richard. 1900. “Ring Des Nibelungen. Rheingold.”
  Wagner, Richard. “Ring Des Nibelungen. Rheingold.,” 1900.
Should be
  Wagner, Richard. 1900. _Ring Des Nibelungen. Rheingold_.
  Wagner, Richard. _Ring Des Nibelungen. Rheingold_., 1900.
[Record Metadata](https://onesearch.library.nd.edu/primo-explore/fulldisplay?docid=ndu_aleph003319002&vid=NDU&search_scope=malc_blended&tab=onesearch&lang=en_US&context=L&showPnx=true). The document type (score) is indicated in the record/display/type field.

The context of the CSL use is the Primo Discovery System developed and hosted by Ex Libris. This instance is for the Hesburgh Libraries at the University of Notre Dame

**Comment by adam3smith** [comment]
Sorry for the very late reply. CSL currently doesn't have a score item type and scores should be mapped to `book` in which case this will come out correctly. That would need to get reported to Exlibris
