### ISSUE TITLE
Citation code for JFQA

### ISSUE THREAD

**Issue by dddd8288** [citation-style-language/styles#5204]
Hi,

Does anyone know if there is any CSL code for the JFQA citation style? If not, can anyone help me with one? I want to use that for Mendeley

**Comment by POBrien333** [comment]
Please follow this guide. But you can just add all the information here (please read carefully and double check). No need to open a thread on the Zotero forums, especially since you won't have an account for Zotero.
https://github.com/citation-style-language/styles/wiki/Requesting-Styles

**Comment by POBrien333** [comment]
superseeded by https://github.com/citation-style-language/styles/issues/5211
