### ISSUE TITLE
Style Request: [JFQA]

### ISSUE THREAD

**Issue by dddd8288** [citation-style-language/styles#5211]
https://jfqa.org/submissions/style-guide-for-accepted-and-conditionally-accepted-papers/

Fully list 3 or more authors on first citation; abbreviate to “et al.” for subsequent citations.

Enclose each citation year within parentheses; separate citations within parentheses by commas.
When a location (page) or equation within the work is referred to, place that within the parentheses as well.

Put citations inline, not in footnotes.
Citation examples:
• Madison, Hamilton, and Jefferson’s (MHJ) (1775), (1776) revolutionary system is the foundation of …
• (see Jones ((2001), p. 1453), ((2009), eq. 3), Rumplemeyer and Schrafft (1874)).
• (see, e.g., Smith, Miller, and Jones (1985), Strunk (1997), and Rosen and Chin (1982)).

Arrange references alphabetically at the end of the manuscript. Ensure that references for working and forthcoming papers are up to date.

Reference examples:
• Rosen, S. A., and L. H. Chin. “Sense and Sensibility.” In Literary Economics,  Vol. I, I. McHugh and J. L. Strauss, eds. Cambridge, MA: Ballinger (1982), 233–267.
• Smith, S.; D. Miller; and J. P. Jones. “Daily Dishwashing: The Case for Antibacterial Soap.” Journal of Hygiene, 9 (1985), 1–31.
• Strunk, W., Jr. “Does Punctuation Matter? Evidence from the Classroom.” Working Paper, University of Alberta (1997).

**Comment by POBrien333** [comment]
Hi,
Have a look at this guide. Please add the missing information outlined HERE. Please don't make a thread on the forums as stated as that will just duplicate things.
https://github.com/citation-style-language/styles/wiki/Requesting-Styles

**Comment by rmzelle** [comment]
@dddd8288, we just added a style for JFQA to the repository (kindly contributed by @POBrien333).
