### ISSUE TITLE
Failing builds report everything is fine

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#5275]
It seems that builds sometimes report everything is fine ("Your submission passed all our automated tests.") even when the test suite doesn't run properly.

See e.g. https://github.com/citation-style-language/styles/pull/5271#issuecomment-778919033 and build https://github.com/citation-style-language/styles/runs/1900561674

cc @adam3smith, @retorquere

**Comment by retorquere** [comment]
That's because of [this](https://github.com/citation-style-language/styles/blob/master/.github/workflows/sheldon.yaml#L63) -- `sheldon` report is always ran (in fact that `(failure() || success())` should just be `always()`), with the intent that is displays the success or fail of the CSL render -- it doesn't anticipate the tests themselves being a reason why the workflow fails.

I'm working on a way to make sheldon smarter about this.

**Comment by retorquere** [comment]
Do we want Sheldon to report back on this? Or just not report back a CSL render result?

**Comment by retorquere** [comment]
In the case of https://github.com/citation-style-language/styles/runs/1900561674 the failure was due to the missing `require 'yaml'`. I must admit my ruby skills have atrophied.

**Comment by adam3smith** [comment]
I think we can keep not rendering CSL for any falling build, even if the CSL itself is fine. In all hopes and expectations this should be rare.

**Comment by retorquere** [comment]
That's now the case. I'm passing the action state to sheldon, and if the action state is `failed`, but there are no failed examples in the spec result, sheldon will just stay silent.

**Comment by rmzelle** [comment]
> That's now the case. I'm passing the action state to sheldon, and if the action state is `failed`, but there are no failed examples in the spec result, sheldon will just stay silent.

https://github.com/citation-style-language/styles/pull/5278 now reports:

```
The workflow is not valid. .github/workflows/sheldon.yaml (Line: 64, Col: 12): Unrecognized function: 'success'. Located at position 2 within expression: (success() && 'success') || 'failure' 
```

**Comment by rmzelle** [comment]
Reverted https://github.com/citation-style-language/styles/commit/bdcae896b6067303a75ad5ef80e70911a2c58616 for now in https://github.com/citation-style-language/styles/commit/12ae0b18c24b77945976a280f0f07dc30876217e

**Comment by rmzelle** [comment]
@retorquere, https://github.com/citation-style-language/styles/commit/86347b7741001bc2dc41f2d04a07ccc0b608b2c4 doesn't seem to work. See e.g. https://github.com/citation-style-language/styles/runs/1924455532:

> Run bundle exec sheldon --token=$GITHUB_TOKEN --{{ job.status }} --verbose
invalid option: --{{

(are these changes testable via PR, or does it require commits directly to "master"?)

**Comment by retorquere** [comment]
They are, and I should be using it -- I will do that from here on out. I don't know how to set up a PR-against-a-PR (which is what would be needed to test them), but I can do all this on my own fork on master, submit PRs against my own master, and when that works, submit my master as a PR against styles.

I've pushed the fix on for now, but I will be making follow-up changes to my own fork.

**Comment by rmzelle** [comment]
(fix in https://github.com/citation-style-language/styles/commit/52f2621649c239e0fa03eaf65c34b034bc37ae08)
