### ISSUE TITLE
How can I convert an EndNote style (ens) into CSL style?  

### ISSUE THREAD

**Issue by giannakopoulosg** [citation-style-language/styles#5306]
Dear All,
My previous University used Endnote about 12 year ago. 
Now I want to convert the endnote style (ens) file into CSL becuse I want to import this style it into Mendeley.
I'm wondering if this it is possible to be done
Any ideas, suggestions and recommendations are more than welcome.

[Univ.Plymouth Harvard.zip](https://github.com/citation-style-language/styles/files/6091249/Univ.Plymouth.Harvard.zip)
[Univ.Plymouth Harvard.zip](https://github.com/citation-style-language/styles/files/6091251/Univ.Plymouth.Harvard.zip)

**Comment by rmzelle** [comment]
@giannakopoulosg, there are no automated tools I'm aware of for converting EndNote styles to CSL styles. If you know the desired citation format, you can look for styles with similar output with our "Search by example" tool (https://editor.citationstyles.org/searchByExample/), or, if a style guide is available, you can put in a style request (https://github.com/citation-style-language/styles/blob/master/REQUESTING.md#requesting-csl-styles).
