### ISSUE TITLE
font-style="italic" doesn't work for Chinese publication

### ISSUE THREAD

**Issue by redleafnew** [citation-style-language/styles#5323]
hi all,

I edited a csl file, and used  `font-style="italic"` for `<container-title>` , the code is 
`<text variable="container-title" suffix=". " font-style="italic"/>`,

and the English publication italicizes, however the Chinese publication remains unchanged.

the snapshot: 
<img width="620" alt="italic" src="https://user-images.githubusercontent.com/22135631/111126340-8f015e00-85ad-11eb-931d-79f947924537.png">

the gist: https://gist.github.com/redleafnew/1139eb32d6204ca4eebfd2e90dd75d18

an example item:https://gist.github.com/redleafnew/9b71ab6b5577bb32a7504ee0916d9939

Many thanks.

**Comment by POBrien333** [comment]
Duplication of: https://forums.zotero.org/discussion/88346/font-style-italic-doesnt-work-for-chinese-publication#latest

**Comment by redleafnew** [comment]
thanks @POBrien333, however, there is no solution.

**Comment by ocouch** [comment]
Have you checked this with the Zotero previewer? It will narrow it down as to whether it's just a problem with the word add-in, or a higher level issue.

![image](https://user-images.githubusercontent.com/43231870/113500189-62fb4c00-955f-11eb-805e-e446ce03640d.png)

**Comment by redleafnew** [comment]
> Have you checked this with the Zotero previewer? It will narrow it down as to whether it's just a problem with the word add-in, or a higher level issue.
> 
> ![image](https://user-images.githubusercontent.com/43231870/113500189-62fb4c00-955f-11eb-805e-e446ce03640d.png)

Thanks for your reply.

I tried it using Style Editor and Style Preview, the English publication title shows italic and Chinese one shows normal (non italic).
<img width="660" alt="Snipaste_2021-04-04_14-19-46" src="https://user-images.githubusercontent.com/22135631/113500489-e2355380-9550-11eb-832f-8e4d29404608.png">
![Uploading Snipaste_2021-04-04_14-21-46.png…]()

**Comment by ocouch** [comment]
Hmm, what if you try swapping "italic" for "oblique"

![image](https://user-images.githubusercontent.com/43231870/113501877-cdb28480-956b-11eb-816f-505f17e20f52.png)

Italic usually requires a special italic version of the font, whereas oblique just distorts the characters of the normal font. It may be a temporary workaround.

**Comment by redleafnew** [comment]
> Hmm, what if you try swapping "italic" for "oblique"
> 
> ![image](https://user-images.githubusercontent.com/43231870/113501877-cdb28480-956b-11eb-816f-505f17e20f52.png)
> 
> Italic usually requires a special italic version of the font, whereas oblique just distorts the characters of the normal font. It may be a temporary workaround.
It is strange
it still doesn't work for Chinese publication.

**Comment by ocouch** [comment]
I'm pretty new to Zotero's code, but it seems might this might be a bug in citeproc-js; so it may be better to open an issue on that repo.
Skimming through it, I can see that container-title is handled differently to title - whether that's a red herring or not, I don't know.

See: https://github.com/Juris-M/citeproc-js#submitting-bug-reports

**Comment by redleafnew** [comment]
> I'm pretty new to Zotero's code, but it seems might this might be a bug in citeproc-js; so it may be better to open an issue on that repo.
> Skimming through it, I can see that container-title is handled differently to title - whether that's a red herring or not, I don't know.
> 
> See: https://github.com/Juris-M/citeproc-js#submitting-bug-reports
font-style="italic" works for Author and Title field, but not for container title in the Visual CSL Editor.
<img width="765" alt="Snipaste_2021-04-04_18-49-58" src="https://user-images.githubusercontent.com/22135631/113506312-a7461680-9576-11eb-93b8-b7233b9f0a23.png">

**Comment by bwiernik** [comment]
This appears to be a citeproc-js issue. Let's keep all of the discussion in that thread.

**Comment by redleafnew** [comment]
thanks @bwiernik , the bug has also been submitted according to https://github.com/Juris-M/citeproc-js#submitting-bug-reports

**Comment by adam3smith** [comment]
Closing here as per above
