### ISSUE TITLE
Citation styles and localisation, problem with Title Case

### ISSUE THREAD

**Issue by ajnyga** [citation-style-language/styles#5324]
Hi,

I realize that this might not be an issue with the CSL files as such, but figured that I could get some answers since the developers here have worked a lot with citations.

We are using Open Journals Systems in our journal platform and OJS uses Citation Style Language for creating article citations. 

Many of our journals publish in Finnish and some citations styles like Chicago and APA apply formatting that you would never use in Finnish language. The problematic part is `Title Case` which is used in article titles and journal names. That kind of styling does not exist in Finnish language. I am fairly sure that it is the same with many other languages as well.

Here is an example citation using APA:

> Välisalo, T., & Karonen, P. (2018). Muistettu ja unohdettu musiikki: Mitä muistitieto ja äänitemyyntitilastot kertovat 1980-luvun nuorten musiikkikulttuurista. _Etnomusikologian Vuosikirja_, 30, 183–206. https://doi.org/10.23985/evk.69215

The correct name of the journal is _Etnomusikologian vuosikirja_.

What do you think would be a solution here? Is it something that could be solved in CSL styles? I am happy to contribute if you know how to solve the problem.

**Comment by adam3smith** [comment]
Hi -- this is handled in CSL by referring to the language field of an item:
https://docs.citationstyles.org/en/stable/specification.html#non-english-items 

I don't know if citeproc-php, which I believe OJS uses, handles that correctly, but that'd be a question for OJS and/or the citeproc maintainer.

**Comment by ajnyga** [comment]
Sorry for missing your answer earlier and pointing me to the right direction!
