### ISSUE TITLE
Delete journal-of-eta-maritime-science.csl

### ISSUE THREAD

**Issue by burakkundakci** [citation-style-language/styles#5346]
We are started to use different citation style and this version is not be used any longer. So I want to delete this csl file.

**Comment by POBrien333** [comment]
Better: update the style. 
Can you provide a link to the guidelines? Or do you use one of the more standard styles? We can link to that.

**Comment by burakkundakci** [comment]
Yes we started to use IEEE style and inform the authors to use the IEEE style.
