### ISSUE TITLE
MLA Style (8th edition) citations for journal articles incorrectly including publisher name

### ISSUE THREAD

**Issue by happywanderer23** [citation-style-language/styles#5352]
My library is using "modern-language-association.csl" in our Ex Libris Primo discovery system. 

Recently I noticed that journal article citations are incorrectly including the publisher name as part of the citation. Here are 2 examples:

Citation #1 (Routledge should not be included):

Billings, Linda. “Should Humans Colonize Mars? No.” Theology and Science, vol. 17, no. 3, Routledge, 2019, pp. 341–46, doi:10.1080/14746700.2019.1632524.

Permalink: https://alliance-primo.hosted.exlibrisgroup.com/permalink/f/o4maap/TN_cdi_crossref_primary_10_1080_14746700_2019_1632524

Citation #2 (Kluwer Academic Publishers should not be included):

Schenker, Paul S, et al. “Planetary Rover Developments Supporting Mars Exploration, Sample Return and Future Human-Robotic Colonization.” Autonomous Robots, vol. 14, no. 2, Kluwer Academic Publishers, 2003, pp. 103–26, doi:10.1023/A:1022271301244.

Permalink: https://alliance-primo.hosted.exlibrisgroup.com/permalink/f/o4maap/TN_cdi_gale_infotracacademiconefile_A155106390

I believe that this issue started occurring sometime after February 2021.  Is there a fix for this issue?

Stephanie

**Comment by JaniceChristopher** [comment]
This has been an ongoing problem in the MLA 8th, and I see it's also a problem in the MLA 9th .csl. Can someone please fix this so my reference librarians will quit bugging me? Thank you!

**Comment by POBrien333** [comment]
@happywanderer23  and @JaniceChristopher 

As you can see in the linked PR this has been addressed and you can update either of the styles in your documents to get the update.
