### ISSUE TITLE
#5156 Aquatic Conservation doesn't match journal and duplicates title in reference list

### ISSUE THREAD

**Issue by JensHegg** [citation-style-language/styles#5377]
I'm formatting a manuscript for Aquatic Conservation: Marine and Freshwater Ecosystems and the .csl doesn't match, as the editor has informed me. 

Below is the formatting style guide from the editor, with the errors highlighted and explained in red text by me. 

Issues to address:

1. Title is duplicated for every reference in reference list
2. In-text citations italicize "et al." and shouldn't
2. Two authors in-text citations using "and" instead of "&"
3. Three authors in-text citations includes author intitials and does not use "&" for last author in list
4. In reference list, journal articles with more than 7 authors do not include "et al."
5. DOI isn't included for all reference types

[References-Guidelines Aquatic Conservation.docx](https://github.com/citation-style-language/styles/files/6299095/References-Guidelines.Aquatic.Conservation.docx)

**Comment by JensHegg** [comment]
I'm sorry, it appears that #4 above was a mistake in my own references, not the /csl. Instead, the .csl is adding "_et al._" to three-author citations rather than listing all three with an ampersand before the last one.

**Comment by POBrien333** [comment]
Hi,

Thank you for reporting the issue.

I have now adapted the style according to their guidelines and an actual [publication](https://onlinelibrary.wiley.com/doi/epdf/10.1002/aqc.3543).

1. Not reproducible
2. done
3. done
4. not correct. their example: (Barros, Read & Verdejo, 2008)
5. Not correct. they have 6 authors + et al.
6. done

Plenty other fixes, too. ;)

You can try the style via this link: https://github.com/citation-style-language/styles/raw/3d8411a52ee6cd6f0fa60dee5f4ef07b48752126/aquatic-conservation.csl

**Comment by JensHegg** [comment]
This is closer, but not quite there. Thanks POBrian333 for working on it. 

#4 above. Yes, the example is correct, and in the publication you linked see "(King, Kuchling & Bradshaw, 1998)" which is correct. However, the style is still giving me (first author et al., date) format for three-author journals and reports when it should be (first author, second author & third author, date)

#5 above. Yes, again this is correct. In the reference list, after the 6th author there should be an et al. if there are 7 or more authors. That is still not working correctly. All the authors are being listed currently, without use of et al.

All the other issues listed above have been fixed. 

I think my way of phrasing the first post wasn't clear. I was pointing out the error rather than what the format should be. 

I'm not sure why I was getting duplicate titles, but it's fixed now so hurray!

**Comment by POBrien333** [comment]
The template style I used had the et-set within the macros directly, which I don´t do (and generally isn't the best practise if not needed). Hence I didn't see that.

https://raw.githubusercontent.com/citation-style-language/styles/3d8411a52ee6cd6f0fa60dee5f4ef07b48752126/aquatic-conservation.csl

**Comment by JensHegg** [comment]
Is this link to your most recent revision? The automated examples in the pull request look right, but on downloading this it has not changed. Three-author in-text citations are still using et al. and authors in reference list doesn't use et al. for 7+ authors. 

Re the pull request (to keep comments in one place). I do now know .csl, but I was on deadline so did as much learning as I could in a couple hours to attempt to get something that works via the visual editor. 

I'll continue to monitor here for a fix so this can be closed.

**Comment by adam3smith** [comment]
Yeah, that's the old link. The new one is 
https://github.com/citation-style-language/styles/raw/ca19ea58085c5eed8bfdc08019c85e30001cb411/aquatic-conservation.csl

**Comment by JensHegg** [comment]
This works. Thanks all.
