### ISSUE TITLE
APA generator should have italics

### ISSUE THREAD

**Issue by whitesnakeftw** [citation-style-language/styles#5382]
The journal name, the comma and space that follow it, and the volume number should all be italicized in the generated APA citation.

This also goes for book titles (not sure about other citation styles).

**Comment by rmzelle** [comment]
Where are you seeing this? As you can see for the Zotero Style Repository preview of the base APA style, the journal name, volume number, and book title are all italicized:

https://www.zotero.org/styles?q=id%3Aapa (hover over the style link to see the preview)

**Comment by adam3smith** [comment]
Happy to point you in the right direction if you want to know who to contact about this, but it's definitely not our issue, so closing here.

**Comment by whitesnakeftw** [comment]
@rmzelle @adam3smith As you probably have figured out by now, I was referring to this tool: https://citation.crosscite.org/

Sorry if this is the wrong repository. And yes, I'd like to be pointed in the right direction, thanks. :)

**Comment by adam3smith** [comment]
Crosscite's github is here: https://github.com/crosscite but the lack of italics is actually just a limitation of how the service is implemented: it only returns plain text, so no formatting like bold, italics, superscripts, indents, etc., so no use reporting this to them. If you need formatted citations, you'll need to use something else. 
For individual DOIs, zbib.org should work nicely (and will also take non-DOI identifiers).

For the response error that you reported separately, that appears to be a recurring instability issue with CrossRef's API at the moment.
