### ISSUE TITLE
Getting a "Incomplete response received from application" most of the times

### ISSUE THREAD

**Issue by whitesnakeftw** [citation-style-language/styles#5394]
I'm getting a "`<h2>Incomplete response received from application</h2>`" error more times than not.

Not sure if related, but this happens both in Chrome and Firefox. I'm trying to generate an APA citation with en-us. Not sure if this happens with different settings.

**Comment by rmzelle** [comment]
> I'm getting a "`<h2>Incomplete response received from application</h2>`" error more times than not.

What website is giving you this error?

**Comment by whitesnakeftw** [comment]
@rmzelle Sorry, I thought this was the repository for https://citation.crosscite.org/

I was linked to this repository by their documentation page: https://citation.crosscite.org/docs.html#sec-4-1

**Comment by adam3smith** [comment]
Sorry this got left lingering. Crosscite is here  
https://github.com/crosscite
