### ISSUE TITLE
Regarding advanced functional materials reference output

### ISSUE THREAD

**Issue by 3kpfamily** [citation-style-language/styles#5396]
In Mendeley reference manager, I am trying to follow the " Advanced functional materials" citation style. In this citation style, the reference format should be 1. A. B. Author 1, C. D. Author 2, Adv. Mater. 2020, 18, 2001086. But in my case, I only can get 1. A. B. Author 1, C. D. Author 2, Advanced Materials 2020, 18, 2001086. Can anybody help me to solve this issue?
 for reference : I have attached author guidelines from advanced functional materials:
https://onlinelibrary.wiley.com/page/journal/16163028/homepage/author-guidelines

**Comment by adam3smith** [comment]
You'd have to talk to Mendeley. The style is coded to abbreviate journal titles, see e.g. item [2] here: https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fadvanced-functional-materials
If the abbreviation isn't shown, that's a problem with the input data or with how they produce abbreviations
