### ISSUE TITLE
Renaming an existing style

### ISSUE THREAD

**Issue by jjrondeau** [citation-style-language/styles#5401]
Hi,
We are planning to rename our "universite-du-quebec-a-montreal" style "universite-du-quebec-a-montreal-APA". I am wondering if I should proceed as for any other change within the code.

And once this will be done, what will be the impact for users that have already added this style to their Zotero? Will they have to reload the renamed style? Or will the UQAM style be automatically replaced by the renamed UQAM-APA style?

Thank you

**Comment by rmzelle** [comment]
We try to keep changes to style IDs (and file names) to a minimum. Would it work to just change the style title?

**Comment by ocouch** [comment]
@rmzelle There's no ideal way out of this, but what about duplicating the file and renaming, and set up the old file as a dependent style? (and insert comments in the file directing style editors to modifythe new style, and recommending they update their links).

That way you maintain legacy compatibility while keeping maintenance fairly straightforward.

**Comment by rmzelle** [comment]
> @rmzelle There's no ideal way out of this, but what about duplicating the file and renaming, and set up the old file as a dependent style? (and insert comments in the file directing style editors to modifythe new style, and recommending they update their links).
> 
> That way you maintain legacy compatibility while keeping maintenance fairly straightforward.

We'd either change the style ID and include the renaming in https://github.com/citation-style-language/styles/blob/master/renamed-styles.json, or leave the style ID as is. I'd really like to avoid having duplicates in the repository.

Zotero does use https://github.com/citation-style-language/styles/blob/master/renamed-styles.json, but IIRC only updates it with new releases of Zotero. This would automatically update the installed style in a Zotero installation, but I think it would still result in permanent breakage of word processor documents generated with the old style (Zotero will likely complain to the user that it can't find the old style and ask the user to select a different one).

**Comment by jjrondeau** [comment]
My apologies for the late reply. I'm back to work on this file. 
So, if I understand correctly, I could change the style title for Université du Québec à Montréal - APA (Français - Canada)  and style ID for http://www.zotero.org/styles/universite-du-quebec-a-montreal-apa? To avoid confusion, I would prefer to avoid to have 2 styles in the repository, named Université du Québec à Montréal - APA (Français - Canada) and Université du Québec à Montréal (Français - Canada)
