### ISSUE TITLE
`gost-r-7-0-5-2008` fails to format webpages because `match="any"` is missing

### ISSUE THREAD

**Issue by Michael-tehc** [citation-style-language/styles#5405]
These lines:

https://github.com/citation-style-language/styles/blob/9876e819aff820339f7277fa7bbfea7b78dfbb21/gost-r-7-0-5-2008.csl#L137-L140

...won't be executed because they don't have `match="any"`, so the `webpage` type won't match. The change was introduced here: https://github.com/citation-style-language/styles/commit/d18d1338c122d686d4b28c8149b110df9220bce7#diff-186dc603660bf3cc7a0ff5e7f63fff2df722d90e49711834fbf49b7ea4cfb393R137.

What gets executed instead is this line:

https://github.com/citation-style-language/styles/blob/9876e819aff820339f7277fa7bbfea7b78dfbb21/gost-r-7-0-5-2008.csl#L141

...which quite bizzarely ends with `... thesis webpage" match="any">`.

Shouldn't the `webpage` type contain `[Электронный ресурс]` in the bibliography, as shown here in ГОСТ Р 7.0.5-2008: http://protect.gost.ru/v.aspx?control=8&baseC=-1&page=0&month=-1&year=-1&search=&RegNum=1&DocOnPageCount=15&id=165614&pageK=AB78A3D0-D4DC-4306-AC48-AAD7BEF2CC96?

Shouldn't the XML be like this, with `match="any"`?

```xml
<else-if type="webpage post-weblog" match="any"> 
   <text macro="title" prefix=" "/> 
   <text prefix=" " macro="access"/> 
 </else-if> 
```

**Comment by rmzelle** [comment]
@Michael-tehc, thanks for the report!
