### ISSUE TITLE
csl file for Mendeley Harvard British Standard 2010

### ISSUE THREAD

**Issue by andreas-chrysostomou** [citation-style-language/styles#5408]
Greetings all,

The referencing software I use is Mendeley, and I was looking to use the Harvard British Standard 2010 reference format. However, it is not provided by Mendeley. This style is provided by other software (like refworks) but I have to use Mendeley. I have tried myself to make it through their csl editor with their gracious help, but I do not have enough expertise on the matter to know if what I am doing is correct. I would respectfully like to ask if anyone has a csl file for Harvard British Standard 2010, or if they can make it and share it. I realise this is a tall order so any help is appreciated, in the meantime I will be working myself to make it through csl editor in the hopes of helping others such as myself.

My gratitude to all

**Comment by POBrien333** [comment]
RefWorks also accepts .csl files as can be seen here: https://citationstyles.org/

If you can find that file from RefWorks you should be able to add it in Mendeley.

**Comment by adam3smith** [comment]
RefWorks also has their old styles, though, and I suspect it's one of them, so that likely won't work.

Most UK University Harvard styles are based on the "British Standard 2010" -- the standard isn't actually well-defined enough for a citation style as I understand it, so I think RefWorks just made some judgments calls there. What do you need this for? If you just need a standard-ish Harvard style, I'd recommend Cite Them Right (10th edition) - Harvard

**Comment by andreas-chrysostomou** [comment]
> RefWorks also accepts .csl files as can be seen here: https://citationstyles.org/ or https://knowledge.exlibrisgroup.com/RefWorks/Knowledge_Articles/Citation_Style_Language_(CSL)_in_RefWorks
> 
> If you can find that file from RefWorks you should be able to add it in Mendeley.

Thank you for the  reply, i need this for essays, thesis etc for my University

**Comment by andreas-chrysostomou** [comment]
> RefWorks also has their old styles, though, and I suspect it's one of them, so that likely won't work.
> 
> Most UK University Harvard styles are based on the "British Standard 2010" -- the standard isn't actually well-defined enough for a citation style as I understand it, so I think RefWorks just made some judgments calls there. What do you need this for? If you just need a standard-ish Harvard style, I'd recommend Cite Them Right (10th edition) - Harvard

Thank you for the reply, I will try to export the style from refworks

**Comment by adam3smith** [comment]
Just to be clear -- I'm saying you almost certainly won't be able to export the British Standard 2010 style from RefWorks to Mendeley. I'm suggesting an alternative style and am also asking for which university this is a requirement.

**Comment by andreas-chrysostomou** [comment]
> Just to be clear -- I'm saying you almost certainly won't be able to export the British Standard 2010 style from RefWorks to Mendeley. I'm suggesting an alternative style and am also asking for which university this is a requirement.

> Thank you for clarifying, its the University of Cyprus

**Comment by adam3smith** [comment]
Style is documented here: http://library.ucy.ac.cy/per-page-files/services/references/harvard---british-standard-2010.pdf
Queen Margaret University - Harvard looks like a very close match; I'd work with that (it's available for Mendeley)
