### ISSUE TITLE
CSL for IOS Press Books

### ISSUE THREAD

**Issue by Monkperson** [citation-style-language/styles#5413]
Hello - I really appreciate you creating the CSL for IOS Press books for Zotero! It is invaluable for me. Unfortunately, the recent update numbers the citations in the text alphabetically instead of order of appearance. Can you please change this? @michelole - thank you so much!!

**Comment by adam3smith** [comment]
Checked with the person who updated the style: https://github.com/citation-style-language/styles/pull/5030#issuecomment-826131632

**Comment by michelole** [comment]
I can confirm the instructions I used to create the style originally (https://github.com/citation-style-language/styles/pull/2371) have *not* been changed and thus https://github.com/citation-style-language/styles/pull/5030 should be reverted.

**Comment by rmzelle** [comment]
@Monkperson, @michelole, sorry for the hiccup! The change has been rolled back.
