### ISSUE TITLE
Duplicate ISSNs aren't being reported

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#5438]
@retorquere, it looks like our test for duplicate ISSNs isn't working.

E.g. 1161-9473 is currently duplicated (https://github.com/citation-style-language/styles/search?q=1161-9473), but the commit that introduced the duplicated merged without complaint (https://github.com/citation-style-language/styles/actions/runs/826493406 from https://github.com/citation-style-language/styles/pull/5427). Could you take a look?

See also:
https://github.com/citation-style-language/styles/blob/931c057e5d1554ad10c7ab7acaa6bf55a9098d82/spec/repository_spec.rb#L17
https://github.com/citation-style-language/styles/blob/931c057e5d1554ad10c7ab7acaa6bf55a9098d82/spec/filters.yaml

(probably related to https://github.com/citation-style-language/styles/pull/5268)

**Comment by retorquere** [comment]
I don't yet know what causes it, but it seems unrelated to splitting off `filters.yaml`; if I recreate the PR environment:

* clone master into `~/github/styles`
* clone master again in `~/github/styles/pull-request`
* remove `topoi-orient-occident-classique.csl` from `~/github/styles`
* run `rake` in `~/github/styles`

I do get the "The CSL Style Repository may not contain any (non-excepted) duplicate ISSNs" error.

**Comment by retorquere** [comment]
I've also removed `topoi-orient-occident-classique.csl` on my fork, and [added it back in in a PR](https://github.com/retorquere/styles/runs/2543109435?check_suite_focus=true) and the test correctly fails there. Still no idea how the CSL repo could be different than that.

**Comment by retorquere** [comment]
Ah OK. So, what do we do here?

**Comment by rmzelle** [comment]
Would it be possible to run things like the ISSN duplicate check in PRs in a post-merge setting, so that outdated PR branches don't hide errors like this one?

**Comment by rmzelle** [comment]
> it can be ran as part of the merge test

Ideally it would be tested automatically on every PR commit.

**Comment by retorquere** [comment]
The `sheldon` workflow (which also runs the spec tests) runs when a PR is opened, synchronized (= more commits pushed), or when its labels change.

**Comment by rmzelle** [comment]
The problem here is that https://github.com/citation-style-language/styles/runs/2541604807 (the result of https://github.com/citation-style-language/styles/pull/5427/commits/c203546caf1ed3f9f1bfc96a2f75fc3839d0b9a9) should have failed, since I had merged https://github.com/citation-style-language/styles/pull/5426 a few minutes prior. So merging #5427 at that point would result in a duplicated ISSN.

Maybe the underlying issue is that #5426 and #5427 were created in parallel (instead of sequentially with the second opened only after the first one was merged), so the pull request branch of #5427 didn't include the style added in #5426.

**Comment by retorquere** [comment]
That is the cause here, and I don't see how we could get around that. Next best thing would be also running the check on merge, because that's when these files meet, but that's only going to alert the person doing the merge, not the PR submitter.

**Comment by adam3smith** [comment]
I think we can let this be. The scenario is sufficiently rare and a mistaken duplicate doesn't break functionality
