### ISSUE TITLE
Mendeley and Zotero: Error when referencing a video or film in APA 7 style

### ISSUE THREAD

**Issue by fmarit** [citation-style-language/styles#5465]
I've been directed here by Mendeley support team after contacting them about this issue. I'm not quite sure if I'm in the right place, but I will expose it here:
The issue is that I've found a mistake in Mendeley and Zotero APA 7 style when referencing a film. I wrote to them and they led me here.
I've entered a film reference manually in Mendeley library (choosing Film from the drop down menu when adding manually a reference), but when I insert the bibliography it comes out wrong. To be precise, the reference in APA 7 should show:

FUOC, & Igualada, A. (2021). Telepràctica en logopèdia: Tractament [vídeo]. Mediaproducción, SLU.

(Well, the title should be in Italics which don't seem to show in this message, but they come out right in the reference, this is not the issue) The error is with the word [video] in brackets and not in italics, after the title and before the dot; which should come out when adding bibliography from Mendeley, and it doesn't. The reference in the bibliography comes out like this instead:

FUOC, & Igualada, A. (2021). Telepràctica en logopèdia: Tractament. Mediaproducción, SLU.

Without the word [video] in brackets (it could say [film] as well (In the following link you can find examples of how to cite a video in APA 7 style Video - APA 7th referencing style - Library Guides at University of Queensland Library (uq.edu.au)).

Therefore, the word [video] (or similar, in brackets), which is mandatory in APA 7 format is missing. I've been told by my teacher to add it manually in my papers, but besides being a hassle, I don't think that's the right way to do it, the error should be fixed. Is there any way to fix this? Thank you.

Here find a document explaining the error with screenshots:
[Screenshots-Explanation-Mendeley-Error.docx](https://github.com/citation-style-language/styles/files/6528874/Screenshots-Explanation-Mendeley-Error.docx)

**Comment by adam3smith** [comment]
@bwiernik would you be willing to take a look at this, please, and respond? Will be much quicker for you.

**Comment by bwiernik** [comment]
@fmarit Enter the word video/film/documentary or whatever is appropriate in the Genre field in Mendeley or Zotero. See here for an example in Zotero https://www.zotero.org/groups/2205533/test_items_library/collections/MR2N872S/items/B77DN7UU/item-details

If Mendeley doesn't have a Genre field for the item, enter it in Note like this:
Genre: Film

**Comment by adam3smith** [comment]
You can add "genre" to any item in the Mendeley desktop app using the options. Not sure what happened with that in the web version (where the "note" workaround also doesnt' work anymore.)

**Comment by bwiernik** [comment]
We can close this.

**Comment by fmarit** [comment]
Hello,

Thank you @bwiernik and @adam3smith . It seems like Zotero has fixed the issue, and now the citation comes out fine using Zotero.

However, not the same with Mendeley. I tried what you suggest (enter Genre: Film in the Note in Mendeley Desktop (Mendeley doesn't have a Genre field), but it did not work. Any chances of fixing it in Mendeley? Or should I write back to them again?

Best regards,
Fanny

> @fmarit Enter the word video/film/documentary or whatever is appropriate in the Genre field in Mendeley or Zotero. See here for an example in Zotero https://www.zotero.org/groups/2205533/test_items_library/collections/MR2N872S/items/B77DN7UU/item-details
> 
> If Mendeley doesn't have a Genre field for the item, enter it in Note like this:
> Genre: Film

**Comment by bwiernik** [comment]
That would be a problem with how Mendeley is generating its citation data. You would need to contact them about fixing that. 

Personally, I would recommend just switching to using Zotero instead.

**Comment by fmarit** [comment]
Thanks @bwiernik. I will write back to Mendeley, and I'll follow your advice and switch to Zotero, if they can't fix it.

**Comment by bwiernik** [comment]
See here for the best method to move from Mendeley to Zotero https://www.zotero.org/support/kb/mendeley_import

**Comment by fmarit** [comment]
@bwiernik Thanks again!!!

**Comment by POBrien333** [comment]
Haven't looked at Mendeley for a while, but you can activate all kinds of fields within the options. It might not show "genre" by default, but you might be able to optionally show it. That's what adamsmith had mentioned above already.

**Comment by fmarit** [comment]
@POBrien333  Thanks! That did it. I hadn't realized that I can activate the fields within each different option, so I had activated different fields, but in the "generic" option, not in the "film" option. Now it works just fine. Thanks again.
