### ISSUE TITLE
Style request "The orthopaedic Journal of Sports Medicine"

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/styles#5474]
Requested via wiki by @Benedikter.

> Hi, I´d like to request adding the citation style of "The orthopaedic Journal of Sports Medicine" for Zotero
> 
> https://journals.sagepub.com/pb-assets/cmscontent/OJS/OJSM_Manuscript_Submission_Guidelines_April_2019-1556558906070.pdf
> 
> Here is the Endnote format https://endnote.com/style_download/the-orthopaedic-journal-of-sports-medicine/
> 
> Citation style as follows:
> 
>     Ardern, CL, Glasgow, P, Schneiders, A, et al. 2016 consensus statement on return to sport from the First World Congress in Sports Physical Therapy, Bern. Br J Sports Med. 2016;50(14):853–864.
> 
>     Bayer, ML, Magnusson, SP, Kjaer, M; Tendon Research Group Bispebjerg . Early versus delayed rehabilitation after acute muscle injury. N Engl J Med. 2017;377(13):1300–1301.

https://github.com/citation-style-language/styles/wiki/_Citation_Style_theOrthopaedicJournalofSportsMedicine/3923a4a88ac17b6ac6cc689a51b552a2903a0ac7

**Comment by rmzelle** [comment]
@Benedikter, next time, please submit style requests as either GitHub issues in this repository, or in the Zotero forums in a new thread. See also https://github.com/citation-style-language/styles/blob/master/REQUESTING.md#requesting-a-new-style

**Comment by POBrien333** [comment]
Duplication: 

https://forums.zotero.org/discussion/89974/urgent-style-request-orthopaedic-journal-of-sports-medicine#latest
