### ISSUE TITLE
import of Zotero format received

### ISSUE THREAD

**Issue by kaapoloistokorppi** [citation-style-language/styles#5496]
Hi all,

as happened with previous help requests/issues, I've been sent here by Mendeley Support.
I have received a .csl file for the citation style of my doctoral school. Apparently, it was made for Zotero. When I drag it in the import window of Mendeley I get the following message (see attachment)
![Catturan](https://user-images.githubusercontent.com/85480630/121225202-f61f6d80-c891-11eb-8552-643d63d217dc.PNG)
even though the file is indeed .csl.
What could be the issue? How to solve it?

Thanks

Kaapo

**Comment by adam3smith** [comment]
If you can link to the file or upload it here, we can confirm whether it is valid CSL, but if that's the case, this is really a Mendeley issue. We can't help with installation problems in their software, obviously, and I don't understand why they'd send you here with that.

**Comment by kaapoloistokorppi** [comment]
Hi,

thank you for your answer. I attach the file.
[Aisala_DPMLS.zip](https://github.com/citation-style-language/styles/files/6629423/Aisala_DPMLS.zip)

Kaapo

**Comment by POBrien333** [comment]
Several errors in this file.

Try this. Right click, save as, download and install as before.
https://gist.githubusercontent.com/POBrien333/596b68198ee8cf0704481c9a6ef764ad/raw/dc804167b47c0f712daa3b0ff684d2e401c9e7b2/heikki-aisala-food-chem-phd-citation-style-numeric.csl

**Comment by kaapoloistokorppi** [comment]
Hi,

thank you very much! I dragged it again on the citation style page and gave the same error. Now I am wondering if I am doing something wrong (although instructions online said "to drag" the file). I sent anyway another email to Mendeley Support.

Kaapo

**Comment by POBrien333** [comment]
My bad.
I left some of your butchered remnants in there. haha

This works:
https://gist.githubusercontent.com/POBrien333/596b68198ee8cf0704481c9a6ef764ad/raw/b7863f17bc419a63bcc281f0628efb3af6b96aec/heikki-aisala-food-chem-phd-citation-style-numeric.csl

**Comment by kaapoloistokorppi** [comment]
Hi,

yes this works. Great! Thank you!

Well, Mendely replied that they cannot provide further assistance, since they don't make the .csl files. _Very nice!_

Kaapo
