### ISSUE TITLE
Could you update HICSS citation style?

### ISSUE THREAD

**Issue by sarahsunflower** [citation-style-language/styles#5503]
Hi!

Thank you all for preparing the HICSS reference style!

Now the style on github orders the references by authors alphabetical order.
https://github.com/citation-style-language/styles/blob/master/hawaii-international-conference-on-system-sciences-proceedings.csl

For the conference HICSS this year https://hicss.hawaii.edu/
HICSS says:
“References should be organized according to the order in which they are referred to in the paper.”

Could you kindly update the style?

I think having the citation number ordered according to their appearance in the paper is similar to IEE citation style, but the bibliography format still needs to be HICSS style. So it would be great if you can update the HICSS style on github.

Sorry that I am not familiar with github. It would be great if you can help. Because the HICSS submission deadline is June 15 this year. Thank you so much!

Best,
Sarah

**Comment by POBrien333** [comment]
Hi,

I can fix that quickly _IF_ it is correct. Can you point out where you got that quote from?
I don't see it here: https://hicss.hawaii.edu/authors/

**Comment by sarahsunflower** [comment]
Thank you!
It is on the later part of the webpage you shared
6. Prepare final paper
* Please prepare the final manuscript according to the Final Word Format
Specifications
<https://docs.google.com/document/d/1c_xHLd3se_eWR-tpWpqnWMTB5xzUWU4HMk-WgsPtQZw/edit?usp=sharing>
or
And they put the template as a google document
https://docs.google.com/document/d/1c_xHLd3se_eWR-tpWpqnWMTB5xzUWU4HMk-WgsPtQZw/edit
Thank you so mcuh!

**Comment by sarahsunflower** [comment]
Thank you!
It is on the later part of the webpage you shared
6. Prepare final paper
* Please prepare the final manuscript according to the Final Word Format Specifications or 
And they put the template as a google documenthttps://docs.google.com/document/d/1c_xHLd3se_eWR-tpWpqnWMTB5xzUWU4HMk-WgsPtQZw/edit
Thank you so mcuh!

**Comment by sarahsunflower** [comment]
In the very end of the template they put on google document, it says 
"10. References 
List and number all bibliographical references in 9-point Times, single-spaced, at the end of your paper.  When referenced in the text, enclose the citation number in square brackets, for example [1]. Where appropriate, include the name(s) of editors of referenced books.
References should be organized according to the order in which they are referred to in the paper.

[1] A.B. Smith, C.D. Jones, and E.F. Roberts, “Article Title”, Journal, Publisher, Location, Date, pp. 1-10. 
[2] Jones, C.D., A.B. Smith, and E.F. Roberts, Book Title, Publisher, Location, Date.
"
https://docs.google.com/document/d/1c_xHLd3se_eWR-tpWpqnWMTB5xzUWU4HMk-WgsPtQZw/edit

So it is just about updating the citation numbers according to their appearance.
Again, many thanks!

**Comment by POBrien333** [comment]
I've edited my answer since (which is not reflected in the emails you got).
See my answer above.

**Comment by sarahsunflower** [comment]
You are super, POBrien333!
https://raw.githubusercontent.com/citation-style-language/styles/17d7dd5c126a38e119104f62a9e45ae156ddb658/hawaii-international-conference-on-system-sciences-proceedings.csl
this works!
