### ISSUE TITLE
include Abstract field in Mendeley bibliography

### ISSUE THREAD

**Issue by AnnBrower** [citation-style-language/styles#5504]
Hello, is there a style in mendeley that will include the Abstract field in a bibliography?  the only annotated bibliography styles i am finding include Notes, not Abstract field.

thank you
Ann Brower

**Comment by POBrien333** [comment]
It's fairly easy to add the abstract field for a CSL style.
Which style are you ideally using and what should it look like? Please show "current vs wanted" examples. :)

**Comment by AnnBrower** [comment]
Hi P, thanks for your response.  I am not too picky about style.  I had tried both APA 7th (annotated) and Chicago 17th (annotated).  (1) is what I get with APA 7th.  (2) is what I want, with abstract included in the reference.
(1)
Adger, W. N. (2016). Place, well-being, and fairness shape priorities for adaptation to climate change. In Global Environmental Change (Vol. 38, pp. A1–A3). Elsevier Ltd. https://doi.org/10.1016/j.gloenvcha.2016.03.009
(2)
Adger, W. N. (2016). Place, well-being, and fairness shape priorities for adaptation to climate change. In Global Environmental Change (Vol. 38, pp. A1–A3). Elsevier Ltd. 
Abstract: Issues of place, well-being, and fairness affect how decisions emerge and gain legitimacy and determine the outcome of who benefits and who pays. Who benefits and who pays for adaptation is important intrinsically. But it is also important because when the burden of adaptation is perceived to be unfair, then action will not be legitimized and interventions simply will not happen.

These issues highlighted here shape the priorities for adaptation and can transform the political economy of its implementation. They make it less about abstract beliefs in science, blame and difficult national planning processes to be more about placing climate change in local contexts and framing it as an issue of solidarity to enable action across scales. Incorporating place, well-being and fairness are analytical steps on that road.

**Comment by adam3smith** [comment]
There should be an APA with Abstract style available for Mendeley ("American Psychological Association 7th edition (with abstract)" is the full title)

**Comment by AnnBrower** [comment]
aaaaaaah! Thank you so much!  I have installed it now and it works.
