### ISSUE TITLE
removing http:// and https:// from URLs in MLA

### ISSUE THREAD

**Issue by eroux** [citation-style-language/styles#5545]
I don't have the MLA Handbook 9th edition, but the 8th edition says in `2.5.2 URLs and DOIs`:

> When giving a URL, copy it in full from your Web browser, but omit http:// or https://.

but `modern-language-association.csl` just copies the URL that is given as argument. I think it would be best if the style could remove the `http://` and `https://` prefixes

**Comment by POBrien333** [comment]
CSL only has access to the fields, but cannot edit them. Whatever is in your reference manager it will pull into the output. 
`<text variable="URL"/>` is all the style does. CSL cannot modify what it get's from the URL field. Add something yes, but not remove.

So, you'll need to edit the URLs manually in your database.

**Comment by eroux** [comment]
I'm not sure I understand, this is a style-specific feature so modifying the URLs in the database will make them invalid in other styles... CSL does midify some fields, for instance it modifies the casing, I was thinking of a feature similar to this. Wdyt?

**Comment by POBrien333** [comment]
I'm not aware this is currently possible, but would be something you could request here to be included in a future release of CSL: https://discourse.citationstyles.org/

**Comment by adam3smith** [comment]
Closing here, as it's not currently possible. Way forward would be as @POBrien333 says: discuss on the forum, then eventually turn into issue on the schema repository

**Comment by eroux** [comment]
thanks! here's the forum topic: https://discourse.citationstyles.org/t/new-way-to-specify-unprefixed-urls-in-styles/1731
