### ISSUE TITLE
Noob question: explain test error for new dependent style

### ISSUE THREAD

**Issue by Jmuccigr** [citation-style-language/styles#5549]
I've edited an existing style to create a [new one](https://github.com/Jmuccigr/styles/blob/patch-1/dependent/zeitschrift-fur-papyrologie-und-epigraphik.csl) for ZPE. I'm still getting one error over at #5548. I put a note there about my confusion, but thought an issue might get more attention.

The error is:

```expected `#<CSL::Style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text" default-locale="en-US" demote-non-dropping-particle="never" children=[5]>.has_macro?` to be falsey, got true```

which I think may mean that this should not be a dependent style, but I'm not sure.

Any help appreciated. Thanks.

**Comment by rmzelle** [comment]
Answered at https://github.com/citation-style-language/styles/pull/5548#issuecomment-877728868
