### ISSUE TITLE
Indicate consecutive page numbers in journal?

### ISSUE THREAD

**Issue by Quintus** [citation-style-language/styles#5581]
Dear all,

I am not entirely sure if this is the right place for this question, but since I already have a GitHub account I thought I just ask here. A little background to my person: I am a German jurist using Emacs to write scientific articles, currently with a hackish custom citation processor based on org's macros, next up either with pandoc or with the new org-cite functionality, which both use CSL. Currently I'm creating my own personal CSL styles based on `juristische-schulung.xml` and will see what I can contribute back to this repository during the course of this action. I would really like to have proper support for German law science in CSL and will report any difficulties I come over (Bruce d’Arcus might have noticed me on the org-mode mailing list a while ago when I participated a little in the org-cite discussions). As of now, I am pleasently surprised since I can even properly represent rather peculiar types like court cases (which are daily bread for jurists to cite).

So here's the thing. In German law science it is custom for the scientific journals to have consecutive page numbers for an entire year volume. That is, for a journal issued 12 times a year, each month's issues do not restart page numbering from page 1, but the page numbers are consecutive: if issue 1/2021 ends with page 65, then issue 2/2021 starts with page 66. That alone is not a problem. However, most German law journals in citation footnotes only include the issue number if and only if the cited journal does not use consecutive page numbers (i.e. restarts page numbering with each issue in a volume). Currently, I have my CSL styles set up to check the presence of the `issue`  variable, which works for the cases I write for German law science journals, but breaks if I want to use the same bibliography database with a style that always includes the issue number regardless of consecutive page numbers. I need a separate database for such styles with the `issue` field included. This is not the way it ought to be I think. So, is there a way to specify a journal has consecutive page numbers and check that in the CSL file, so I can just always include the `issue` field in my database entries?

Currently, the only thing I can think of is hijacking another variable I never use and checking that one in the CSL file, but I would like to do it proper so that it is universal with any CSL programme I may ever switch to at some point.

  -quintus

**Comment by Quintus** [comment]
Since the entire thing is more of a general question about CSL's facilities, I'll add a cc @bdarcus.

**Comment by adam3smith** [comment]
No, can't be done. APA used to have the same dumb rule, but thankfully finally got rid of it in the 7th edition and we're honestly not  super likely to add support for it in CSL (for a number of reasons, one being that metadata for this doesn't exist, making actual citation automation impossible)
