### ISSUE TITLE
Style Request: [wikipedia markup templates]

### ISSUE THREAD

**Issue by sallybaker** [citation-style-language/styles#5608]
Wikipedia has its own citation standards available here: https://en.wikipedia.org/wiki/Wikipedia:Citing_sources that are currently not available via CSL Styles.

**Comment by fgnievinski** [comment]
code could be borrowed from [Citer](https://github.com/5j9/citer), a citation generator tool for Wikipedia.

**Comment by fgnievinski** [comment]
code could also be borrowed from [Zotero](https://www.zotero.org/support/kb/zotero_and_wikipedia)

**Comment by adam3smith** [comment]
(we can't copy code in other programming languages. CSL has a very distinct structure - and is much more limited than full programming languages like  javascript or python - which is also cause for some of our concerns in implementing this)

**Comment by adam3smith** [comment]
Closed via the PR linked above

**Comment by fgnievinski** [comment]
in citations of book sections, chapter title and book title seem swapped.
