### ISSUE TITLE
Remove month from ACL style?

### ISSUE THREAD

**Issue by blester125** [citation-style-language/styles#5648]
Looking at papers published at the most recent ACL conference, it seems like they don't include the month in the bibliography reference. Is there anything to point to as a reason to keep it? Or should it be removed from the style?

**Comment by bwiernik** [comment]
Which style specifically is this? Can you give a link to a recent paper?

**Comment by blester125** [comment]
This is the style for ACL, the [association-for-computational-linguistics.csl](https://github.com/citation-style-language/styles/blob/master/association-for-computational-linguistics.csl)

Example from a recent conference [pdf](https://aclanthology.org/2022.acl-long.346.pdf). In the reference section one can see there is no month, they just output the year.

**Comment by bwiernik** [comment]
Okay that's updated. I saw several examples with month in older years, but none in more recent years
