### ISSUE TITLE
Need help removing comma after ed or eds.

### ISSUE THREAD

**Issue by ghost** [citation-style-language/styles#5664]
Hi,
I need to remove the comma after 'ed' or 'eds.' in: https://github.com/citation-style-language/styles/blob/master/harvard-bournemouth-university.csl

For example:
Otter, C. and Stephenson, K., eds.**,** 2008. _Chemical Ideas_. 3rd edition. Harlow: Heinemann.

should be

Otter, C. and Stephenson, K., eds. 2008. _Chemical Ideas_. 3rd edition. Harlow: Heinemann.

If anyone can help me I would appreciate it!

**Comment by adam3smith** [comment]
The style isn't done yet, but the PR is sufficient for discussion
