### ISSUE TITLE
Style Request: [AMA 9th edition]

### ISSUE THREAD

**Issue by meeshazee** [citation-style-language/styles#5680]
Aoa i want AMA 9th edition citation for this journal
https://meridian.allenpress.com/angle-orthodontist/pages/how-to-submit
eISSN 1945-7103 ISSN 0003-3219

examples:
Journal article: Campbell JL, Pedersen OK.The varieties of capitalism and hybrid success.Comp. Polit. Stud. 2007;40:307-332
Book: Mares I. Firms and the welfare state: When, why, and how does social policy matter to employers? New York. Oxford University Press; 2001.

**Comment by POBrien333** [comment]
I wouldn't call that a high-impact journal, but I had a go at the style. When it closes (it will say "merged") you'll be able to find it on the style repository.
