### ISSUE TITLE
Question about biomed central URL/DOI display

### ISSUE THREAD

**Issue by nsheff** [citation-style-language/styles#5700]
The biomed-central style displays a link to the DOI, but only if the URL variable is set. This is confusing, because entries that have a DOI but no URL will never have their DOI linked.  It's not clear to me why the url variable must be set in order for DOIs to render. 

The code in question is here:

https://github.com/citation-style-language/styles/blob/1efce81f8a8bd18d97a46f1beda41d5ca8d9e362/biomed-central.csl#L90-L95

**Comment by POBrien333** [comment]
Thank you for reporting the issue.
I have made a suggestion for a fix in #5701.
