### ISSUE TITLE
Is APA working correctly for first author?

### ISSUE THREAD

**Issue by naturefreak474** [citation-style-language/styles#5733]
I'm using apa.csl in Alma and it's not displaying the initials for the first author. Here's an example:

McGlade, & Ekins, P. (2015). The geographical distribution of fossil fuels unused when limiting global warming to 2 °C. Nature (London), 517(7533), 187–190. https://doi.org/10.1038/nature14016

It should be: McGlade, C., & Ekins, P. (2015). The geographical distribution of fossil fuels unused when limiting global warming to 2 °C. Nature (London), 517(7533), 187–190. https://doi.org/10.1038/nature14016

I'm not sure if this is something specific to our Alma configuration or if it's a general problem in the csl. 

Thanks,
Jack

**Comment by adam3smith** [comment]
That's an issue with Alma. Also reported here https://github.com/citation-style-language/styles/issues/5722

**Comment by naturefreak474** [comment]
@adam3smith Thanks for closing my issue. Did you report this to Ex Libris already?

**Comment by adam3smith** [comment]
No, we don't have a point of contact there, so please go ahead and report to them

**Comment by LilliB24** [comment]
@adam3smith Also detected this problem and will happily report to vendor, however could you provide any insight as to why APA 6th edition is displaying citation correctly, where as APA 7th edition is not (first author initial missing)?
I checked #5722 and couldnt see any explanation.
Thanks!

**Comment by adam3smith** [comment]
Sorry, no idea. The relevant code is more complex in APA 7, so likely somehow related to that, but CSL wouldn't even allow you to ommit the first name/initial of just the first author if you wanted to.

**Comment by naturefreak474** [comment]
I've reported the issue to Ex Libris, and they said they are working on the problem, but cannot give an expected date of completion.
Thanks!
