### ISSUE TITLE
Two publishers for journal in chinese-gb7714-2005-numeric if 'Publisher:' exists in Extra

### ISSUE THREAD

**Issue by redleafnew** [citation-style-language/styles#5735]
if https://github.com/citation-style-language/styles/blob/6152ccea8b7d7a472910d36524d1bf3557a83bfc/chinese-gb7714-2005-numeric.csl is applied, two publishers will display,
such as for https://pastebin.com/TLZybd0L , 
[1]	SON J-Y, KANG K-O. Effect of an oil-water fryer on quality properties of deep frying oil used for chicken[J]. **Korean Journal of Food and Cookery Science, Korean Society of Food and Cookery Science**, 2012, 28(4): 443–450.

if 
Line 122
`    <text variable="publisher"/>`
is changed to 
 ```
      <choose>
        <if type="book graphic legal_case legislation" match="any">
          <text variable="publisher"/>
        </if>
      </choose>
```
will show correctly.

**Comment by POBrien333** [comment]
Duplication of https://forums.zotero.org/discussion/93015/why-text-variable-publisher-in-journal-use-exra-field-if-there-is-publisher-in-extra

**Comment by redleafnew** [comment]
The PR has been merged.
