### ISSUE TITLE
I uploaded a sytle to github and it passes the automated reviewing... What to do now?

### ISSUE THREAD

**Issue by serbernardo** [citation-style-language/styles#5759]
I have adapted a Chicago author-date style https://github.com/citation-style-language/styles/pull/5742/ two weeks ago
 
SO I have been waiting for github collaborator review in order to have this style up and running.

Today I have closed the pull request (it was supposed to do that?).
Can anyone pls help and tell me what to do now?

P.S this is a portuguese adptation to our style  Faculty of Engineering Style.https://github.com/citation-style-language/styles/pull/4891
Thanks in advance,
Sergio Bernardo

**Comment by adam3smith** [comment]
Reopen the pull request and wait. We review as quickly as possible

**Comment by serbernardo** [comment]
Thanks @adam3smith for the feedback.... 
I have reopened the pull request.  :)

**Comment by adam3smith** [comment]
Style is being actively reviewed
