### ISSUE TITLE
harvard-newcastle-university

### ISSUE THREAD

**Issue by stephen-harding-ncl** [citation-style-language/styles#5763]
Hi there,

I'm based in the Digital Library Services team within Newcastle University and I've had a few reported style issues from our Liaison Librarians. Ex Libris support have sent me in this direction for any style/formatting related queries.

I've pasted below the information passed on from my colleague.

> This journal article is shown as (in Library Search):
> McLay, K.F. & Reyes, V.C. (2019) Identity and digital equity : Reflections on a university educational technology course. Australasian Journal of Educational Technology. 35 (6), 15–29.
> 
> When it should be:
> McLay, K.F. & Reyes, V.C. (2019) ‘Identity and digital equity : Reflections on a university educational technology course’, Australasian Journal of Educational Technology, 35 (6), pp. 15–29.
> 
> So the cite it tool is missing out the single quotation marks around the article title, commas not full stops between the different parts and the pp. for page numbers.
> 
> And for books
> 
> The Library Search citation is shown as: Bell, J. (2014) Doing your research project a guide for first-time researchers. Sixth edition..
> 
> When it should be:
> Bell, J. (2014) Doing your research project. 6th Edn. Maidenhead: Open University Press.
> 
> So it’s missing out the publisher place and name and the abbreviation for edition. It’s also showing the title of the book in italics in the Library Search platform but copies/pastes it without italics. 

What happens next in terms of getting this updated?

Many thanks in advance from the newbie,

Stephen

**Comment by POBrien333** [comment]
Hi,

Thank you for reporting the issues:

- article-journal: I can see the style indeed had some errors and corrected those.
- books: Style already is programmed correctly. E.g.: 
Borges, J.L. (1999) _Selected non-fictions_. 3rd edition. Eliot Weinberger (ed.). Vol. 1, 3 vols. New York, NY: Viking.

Note that for the edition there is a conditional built in: if it's just a numeric value, it'll take that number and add the ordinal suffix and the edition label to it. If it contains anything more than just numbers, it'll print it out like it is entered in the field. So, have two choices: 1. remove all but the number or 2. enter it correctly in the metadata.

I do not know what "library citations" is, but how a specific piece of software implements CSL is another issue, beyond CSL.

**Comment by stephen-harding-ncl** [comment]
Thank you very much for this
