### ISSUE TITLE
Long page number slightly different when rendered through CSL

### ISSUE THREAD

**Issue by wmhorne** [citation-style-language/styles#5773]
**Summary**: When rendered through CSL, a work's long page number has a different final digit.

## Problem

I'm citing a reference that includes a long page number, `23094990211003347`. The reference info looks like this in Zotero:

<img width="1081" alt="Screen Shot 2021-12-09 at 4 11 47 PM" src="https://user-images.githubusercontent.com/17973411/145490344-d005d580-d3df-47e9-b8f1-64bd48205f86.png">

When looking at the reference that's generated using csl, however, this page number ends up being slightly different.

It's 2309499021100334`8`, as opposed to 2309499021100334`7`:

<img width="1383" alt="Screen Shot 2021-12-09 at 4 10 00 PM" src="https://user-images.githubusercontent.com/17973411/145490248-ac65e37b-d1f0-4b68-b75b-2d71bd6cff92.png">

This appears to be true across styles:

<img width="1401" alt="Screen Shot 2021-12-09 at 4 10 36 PM" src="https://user-images.githubusercontent.com/17973411/145490254-2de27be0-8c2b-4ffb-8c7d-cb01c0b829a6.png">
<img width="1241" alt="Screen Shot 2021-12-09 at 4 15 17 PM" src="https://user-images.githubusercontent.com/17973411/145490630-d58c316e-95c5-41aa-b574-415703696725.png">

This also appears to be true regardless of the specific final digit:
<img width="1246" alt="Screen Shot 2021-12-09 at 4 18 44 PM" src="https://user-images.githubusercontent.com/17973411/145490957-8c04ea4c-80b5-4552-b809-b1a2bc4bfd1a.png">

<img width="1220" alt="Screen Shot 2021-12-09 at 4 19 14 PM" src="https://user-images.githubusercontent.com/17973411/145490965-9a0ed01d-6072-4600-b740-8c9afed40c55.png">

**Comment by adam3smith** [comment]
This is almost certainly a citeproc-js issue. It's definitely not a CSL issue, as we just handle the schema definition and styles.  

See https://github.com/Juris-M/citeproc-js

You can also report to Zotero, but if you do both make sure you cross-link the reports

**Comment by wmhorne** [comment]
Thanks. Posted here: https://github.com/Juris-M/citeproc-js/issues/194
