### ISSUE TITLE
Frontiers in Ecology & Environment edits to do

### ISSUE THREAD

**Issue by SimonDedman** [citation-style-language/styles#5783]
(Something of a note to self for later.)

There actually isn't a Frontiers in Ecology & Environment journal but conceptually [this entry](https://github.com/citation-style-language/styles/blob/master/frontiers-in-ecology-and-the-environment.csl) encompasses the Science, Engineering, Humanities, and Sustainability journals ([link #4.1](https://www.frontiersin.org/about/author-guidelines)). However it doesn't confirm to the author guidelines for seemingly all of their journals (given the prior link is for all journals), and for Science specifically, due to the following:

- no DOIs
- authors trimmed at 4 if there are max 4, at 3 if there are >=5 (should trim at >6)
- For web pages, no space between title & URL.
- Masters thesis: thesis not mentioned.

Similarly for [Frontiers in Bioscience](https://github.com/citation-style-language/styles/blob/master/frontiers-in-bioscience.csl) (again not an actual journal)

- citations are numbered (wrong style)
- author count not trimmed
- no DOIs
- no access date for web pages.

Conceptually it would be nice if someone from the Frontiers group tidied these entries up - there are currently 7 under Frontiers, probably most could be archived and the entry list streamlined to match their guidelines.

**Comment by SimonDedman** [comment]
Edit: however it looks like the [Frontiers generic entry](https://github.com/citation-style-language/styles/blob/master/frontiers.csl) is basically correct, which increases my feelling that the others should be archived if that's a thing in git.

It doesn't mention that a masters thesis is a masters thesis though. At some point I must have read a trick for this which is to add a "genre" field with "Masters Thesis" as the entry, since I have these for all my masters & Ph.D theses (with Ph.D Thesis for those obviously). But this trick may need to be paired with something in the CSL. Digging into my edited CSL from years ago, potentially this would solve it:

```
<else-if type="thesis">
          <group delimiter="; ">
            <group delimiter=", ">
              <text variable="genre" text-case="capitalize-first"/>
              <choose>
                <!-- In APA journals, the university of a thesis is always cited, even if another locator is given -->
                <if variable="DOI URL archive" match="any">
                  <text variable="publisher"/>
                </if>
              </choose>
            </group>
            <text macro="locators"/>
            <text macro="secondary-contributors"/>
          </group>
</else-if>
```

**Comment by POBrien333** [comment]
See https://github.com/citation-style-language/styles/issues/6008 for an issue and PR where we added DOIs.

**Comment by bwiernik** [comment]
Frontiers in Ecology & Environment is a journal by a completely different publisher. The repository has a style for Frontiers journals https://github.com/citation-style-language/styles/blob/master/frontiers.csl
