### ISSUE TITLE
Vox Sanguinis Reference Format

### ISSUE THREAD

**Issue by CVRANKIN** [citation-style-language/styles#5788]
Should use Journal title abbreviations consistent with PubMed NLM and AMA designations; title abbreviations should be aligned with current standard regardless.  Simple journal abbreviation example pasted from PubMed below.

https://onlinelibrary.wiley.com/page/journal/14230410/homepage/forauthors.html

**Comment by adam3smith** [comment]
The style uses journal abbreviations already. With which tool are you using it?
