### ISSUE TITLE
Problem with et-al-min attribute

### ISSUE THREAD

**Issue by SterArcher** [citation-style-language/styles#5794]
Hi, 

I'm having an issue I cannot seem to fix. I keep getting an error with et all attribute in my pull request #5789. The csl style validator says it is ok, the citation style works on my computer in zotero, but I cannot get past the bot. It keeps returning the error “ name nodes must have valid et-al-min and et-al-use-first attributes”. Does anyone have any ideas? 

Thanks!

**Comment by adam3smith** [comment]
Answered on the PR. Any follow up questions just as ask there
