### ISSUE TITLE
Styles in API not up to date

### ISSUE THREAD

**Issue by fussballlinguist** [citation-style-language/styles#5844]
Hi,

I did an update of our citation style "technische-universitat-dresden-linguistik" some time ago and it is available here: https://www.zotero.org/styles/technische-universitat-dresden-linguistik

However, when I call the style via the API, it still uses the older version, recognisable by the missing doi for example: https://api.zotero.org/users/4623520/publications/items?format=bib&style=deutsche-sprache&itemType=-attachment

**Comment by bwiernik** [comment]
@dstillman Do you know when the API updates with style changes?

**Comment by dstillman** [comment]
It was supposed to be within a few minutes of each style commit, with up to 15 minutes caching after that if recently requested, but it looks like that hasn't been working in over a year. Should be fixed going forward. Let me know if not.

(Note that the API URL above is for a different style that hasn't been updated.)
