### ISSUE TITLE
`<sort>` not working for APA intext citations

### ISSUE THREAD

**Issue by HossamGhorab** [citation-style-language/styles#5870]
# Context 

In short, I'm editing the [APA 7th eition](https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fapa) style to make it resemble the citation style demands of a thesis supervisor. I use BibTex, Rmarkdown and Pandoc (citeproc). The problem I couldn't fix after reviewing the [CSL specifications](https://docs.citationstyles.org/en/stable/specification.html) and the issues on this repo is: **How to chronologically sort multiple in-text citations (in descending order)?** 

# The problem
In the original CSL file,  the `citation` macro starting at line No#1733 has a `<sort>`  attribute, placed right before the `layout` attribute, that is identical to the `<sort>`  attribute of the `bibliography` macro. This doesn't make sense, like how will we sort inline citations by `author-bib` in the first place? Why use any `*-bib` under `citations`? 

The sorting is well done for `bibliography` macro. But the `<sort>` attribute under the `citation` macro is totally useless, the in-text citations appear in the order they are called and commenting the whole `<sort>` renders the same document. 

I used the following code in the , but nothing happened:

```
<!-- macro == citation, line == 1734 -->
  <sort>
      <key macro="date-intext" sort="descending" />
      <key variable="issued"/>
  </sort>
```

# The requested style

Please edit the .csl file found [HERE](https://drive.google.com/file/d/1D3gwEmC7yBplnwqRgRbTQMPsqm8-lYuL/view?usp=sharing) to sort multiple inline citations by 1. descending date-intext and then by 2. descending author-intext .

Thanks in advance

**Comment by adam3smith** [comment]
While you're welcome to use your custom CSL to sort APA in-text citations chronologically, of course, that's not actually APA style. 
The APA Manual explicitly says to sort in-text citations in the same order as they would appear in the bibliography, which is exactly what the style does (nothing nonsensical about the use of the author-bib macro: it's just a way to format authors), so we're leaving that as is.

**Comment by HossamGhorab** [comment]
I got your point. What happens using citeproc-pandoc is sorting the references in the order they are cited, totally ignoring the `<sort>` of he `citation` macro found here:

https://github.com/citation-style-language/styles/blob/c33dd240adb0419dcc26b870381832c9bd26e5c8/apa.csl#L1862

1. I understand that I should post an issue of this on the citeproc repo, correct?
2. I'm almost done with my .csl file and I'm to contribute it once confirmed that this is the APA flavour the university requires. I'm asking for your help for this sorting issue on the code in the [link](https://drive.google.com/file/d/1D3gwEmC7yBplnwqRgRbTQMPsqm8-lYuL/view?usp=sharing), which is the APA edited to fulfill the needs of my university. Of course you can -- and should-- leave the original APA source code untouched. 

I really appreciate you time. Thanks for your patience.
