### ISSUE TITLE
APA initials missing for first author

### ISSUE THREAD

**Issue by heidi-lib** [citation-style-language/styles#5902]
In apa.cls the initials of the first author are missing.

Example with 1 author:
Mortimer. (1983). Chemistry (5th [rev.] ed). Wadsworth Pub. Co.
Example with 2 authors:
Mahler, & Cordes, E. H. (1966). Biological chemistry. Harper & Row.
Example with 3 authors:
Hawkins, Taylor, G. V., & Mackin, R. (1973). Chemistry. Oxford University Press.

To compare, in apa-6th-edition this is: 
Example with 1 author:
Mortimer, C. E. (1983). Chemistry (5th [rev.] ed). Belmont, CA: Wadsworth Pub. Co.
Example with 2 authors:
Mahler, H. R., & Cordes, E. H. (1966). Biological chemistry. New York [etc: Harper & Row.
Example with 3 authors:
Hawkins, W. F., Taylor, G. V., & Mackin, R. (1973). Chemistry. London: Oxford University Press.

It's always the initials of the first author that are missing.

**Comment by bwiernik** [comment]
This is not programmed as part of the style. How are you generating these citations? With which program?

**Comment by heidi-lib** [comment]
It's not? I'm sorry, I didn't know that. 
Primo VE (Ex Libris library catalogue product) is using this Github to load the styles. Since there is no other configuration, I thought this format was in the style. 

I load them from a record in the Primo UI, for example see "Send to" > "Citation" here:
https://lib.hva.nl/permalink/31UKB_UAM2_INST/anc5jt/alma990024614170205131

I did some searching and figured out how to load the same apa.cls into Zotero. And, of course, it confirms that you are right. The output from Zotero for this example is:
Mahler, H. Ralph., & Cordes, E. Harold. (1966). Biological chemistry. Harper & Row.

Thank you very much for this information and pointing me in the right direction!
