### ISSUE TITLE
Harvard style- citing 2 works by same author in same year

### ISSUE THREAD

**Issue by giraffeekey** [citation-style-language/styles#5903]
Hi,

Harvard style rule: While citing works for the same author same year, it should be cited as xxx et al (2017a), xxx et al (2017b). However, none of the Harvard styles available now is following this rule. (or none that I care across) any help with that issue?

**Comment by POBrien333** [comment]
Cite Them Right certainly works correctly, as probably do the other styles that you tried. See:
![image](https://user-images.githubusercontent.com/954979/153072877-9594b515-85ed-4b3c-932e-48a702e18ed8.png)

This has to do something with your metadata or your citation software that you're using.

Can you export the two items that you want to have disambiguated as CSL JSON and attach them to an answer here?

**Comment by giraffeekey** [comment]
thanks for the response. Could you let me know how to export an item as CSL JSON?

might be an issue with mendeley as suggested. But since i have 200+ citations i cannot import them now in another software to solve this issue.

Elsevier -harvard csl works fine with the a and b thing that i'm looking for. may be that would be the second best choice....

**Comment by POBrien333** [comment]
Ah, so it works with Elsevier Harvard? Odd then.
Which Mendeley are you using exactly? Exact software name (Mendeley has 2 pieces of software) and the version? I can see if I can reproduce this somehow.

Export item: right click on an item?
If not a screenshot that shows all the metadata fields would be great. If you have DOIs/URLs and paste them here even better, so I don't have to type this manually.

**Comment by adam3smith** [comment]
I don't believe you can export CSL JSON from Mendeley. Only RIS, BibTeX,
and Endnote XML

**Comment by POBrien333** [comment]
Pinging @giraffeekey in case you didn't see this.

**Comment by adam3smith** [comment]
I'm going to close this -- the style is correct, and we can only do so much in debugging Mendeley issues
