### ISSUE TITLE
New style or update?

### ISSUE THREAD

**Issue by jcuenod** [citation-style-language/styles#5904]
I am a PhD student at Wheaton College. I've been using the SBL style (which was the basis for the Wheaton style when it was created some time ago). Since then, I believe the Wheaton style has been updated and the SBL style has had a number of revisions. Some students still use the Wheaton style but it is no longer in sync with Wheaton's own style guide.

I have modified the SBL style where I am aware of differences but I don't want to inflict it on the rest of my peers if they still want to use the old Wheaton style. Is it okay if I create a PR and contribute a new Wheaton PhD style?

**Comment by adam3smith** [comment]
Thanks for asking -- this is a good question. 
If there's a single up-to-date style guide at Wheaton, I'd much prefer to have a single style that best represents it, i.e. have you update the existing style rather than create a new one.

**Comment by bwiernik** [comment]
@jcuenod Please feel free to submit an updated style. Closing this issue for now.

**Comment by jcuenod** [comment]
Thanks @bwiernik. I need to get the students onboard and I need to do a deeper comparison of any other differences before I make any commits that affect them.
