### ISSUE TITLE
Space missing when multiple references are used in elsevier-with-titles.csl

### ISSUE THREAD

**Issue by aubertc** [citation-style-language/styles#5962]
@karnesky Shouldn't 

https://github.com/citation-style-language/styles/blob/6a7b708057ceab540a73b1587aafd46a7c220a94/elsevier-with-titles.csl#L86

be 

```
<layout prefix="[" suffix="]" delimiter=", ">
```

(i.e., with a space)?

**Comment by karnesky** [comment]
At the time of creation, [journal examples](https://web.archive.org/web/20150211101150/http://www.elsevier.com/journals/journal-of-hazardous-materials/0304-3894/guide-for-authors#68001) had no space between numbers.

The style for the particular journal now has Harvard-like examples.

Presumably, a different set of author instructions should be referred to. Do you have examples of author instructions that are numeric with spaces?

**Comment by aubertc** [comment]
I am not sure this is the style you are referring to / implementing, but currently Elsevier does use a space when two references are provided. In their [sample manuscript](https://www.elsevier.com/__data/assets/file/0007/56842/elsarticle-template.zip), page 2, you can see:

![image](https://user-images.githubusercontent.com/16466689/158074721-01816c62-672f-4311-9454-9aafc62b48bc.png)

**Comment by adam3smith** [comment]
Let's step back -- what journal are you actually interested in submitting to? The sample document doesn't actually claim to show a preferred citation style. It introduces a range of styles available as .bst in LaTeX.

**Comment by aubertc** [comment]
> what journal are you actually interested in submitting to

None, I'm just a LaTeX user that is used to styles with a space between references --- I actually thought it was the only custom, and just discovered that some styles did not have space after the comma, which I would consider to be an error.

**Comment by aubertc** [comment]
But, ok, apparently some styles do not require to have spaces after the comma, cf. e.g. [this guide](https://guides.lib.uw.edu/hsl/ama/intext): 

> If citing more than one reference at the same point, separate the numbers with commas and no spaces between. 

I had never heard of this practice, and guess that it solves this issue. Thanks!
