### ISSUE TITLE
Add doi to frontiers-of-biogeography.csl

### ISSUE THREAD

**Issue by ahhurlbert** [citation-style-language/styles#6008]
The journal Frontiers of Biogeography requires the DOI at the end of each citation as described here: https://escholarship.org/uc/fb/authorinformation

But this is not currently implemented in the .csl

Could someone add this please?

**Comment by POBrien333** [comment]
Hi,

It's not necessary to open a post on the Zotero forums and here. We're the same 3 people looking at that.
https://forums.zotero.org/discussion/comment/404651#Comment_404651

Closed with https://github.com/citation-style-language/styles/pull/6010

**Comment by POBrien333** [comment]
This can also be closed, @bwiernik :)
