### ISSUE TITLE
My CSL file upload issues

### ISSUE THREAD

**Issue by RajaAnanth** [citation-style-language/styles#6030]
Hi Team, 

My csl link is here, "https://github.com/citation-style-language/styles/pull/5918". When this will be showed in the styles repository, 
 Here, Im missing anything to update?  Please advice.

**Comment by adam3smith** [comment]
There were two pull requests for the same style, That one was closed and the current one, https://github.com/citation-style-language/styles/pull/6007, is awaiting fixes as described there.

**Comment by amyrolla** [comment]
@RajaAnanth please can you address the edits needed in #6007?
