### ISSUE TITLE
APA (7th Edition) first initial, first author listed

### ISSUE THREAD

**Issue by kalpal45** [citation-style-language/styles#6044]
Hi, I'm sorry I don't know how to make this change or I would try to make it on my own, but our research librarians noticed that the 7th edition APA style is missing the first letter of the first author's first name when generating a citation from our library system. We're using citation-style-language/styles/apa

Example:
**Incorrect example generated by citation button**
  Dolan, Stephens, J. D., & Moore, M. E. (2011). Living More Than Just Enough for the City: Persistence of High-Quality Vegetation in Natural Areas in an Urban Setting. Diversity (Basel), 3(4), 611–627. https://doi.org/10.3390/d3040611

**Corrected example with first listed author's first initials included**
  Dolan, R.W., Stephens, J. D., & Moore, M. E. (2011). Living More Than Just Enough for the City: Persistence of High-Quality Vegetation in Natural Areas in an Urban Setting. Diversity (Basel), 3(4), 611–627. https://doi.org/10.3390/d3040611

**Comment by bwiernik** [comment]
This is on Ex Libris correct? That is a bug caused by that platform using an outdated version of citeproc-js. Update to a version of Ex Libris with the current version of citeproc-js.

**Comment by kalpal45** [comment]
Yes, it is Ex Libris. Thank you - I will contact them!
