### ISSUE TITLE
Style Request: Journal of Neuroimaging

### ISSUE THREAD

**Issue by GB560** [citation-style-language/styles#6047]
Hi, I tried editing the Neurology CSL style (closest fit) but I have some strange aberrations (shows author affiliations in bibliography and uses year as edition). Appreciate your help.

A link to online style documentation: https://onlinelibrary.wiley.com/page/journal/15526569/homepage/forauthors.html 

For journals, the journal's ISSN (print version) and/or e-ISSN (online version): 1051-2284

Two citations, for a journal article and a book chapter, in the format of the style you're requesting:
In-text citation (superscript):
1
2

Bibliography:
1. Campbell JL, Pedersen O K. The varieties of capitalism and hybrid success. Comp Political Stud 2007; 40: 307–32. 
2. Mares I. Firms and the welfare state: When, why, and how does social policy matter to employers? In Hall PA & Soskice D, ed. Varieties of capitalism. The institutional foundations of comparative advantage. New York: Oxford University Press; 2001: 184–213

**Comment by POBrien333** [comment]
The style is now available from the repository.
