### ISSUE TITLE
Bibtex: Missing `citation-format`

### ISSUE THREAD

**Issue by tnajdek** [citation-style-language/styles#6056]
From what I can see `<category citation-format="author-date"/>` has been removed in 63a0b43c, was this intentional?

**Comment by bwiernik** [comment]
I think it was. It's not really an author-date format. Perhaps it should have the "label" format. Is it a problem to not have a citation-format tag?

Note that this CSL style isn't a great way to generate BibTeX. It's much better to use Zotero's BibTeX export translator

**Comment by tnajdek** [comment]
Thanks for the reply. My concern is that it affects https://www.zotero.org/styles (the empty button next to "format"). I hoped that maybe this is an oversight, especially given that this tag/attribute seems to be [required by the validator](https://validator.citationstyles.org/?url=https%3A%2F%2Fwww.zotero.org%2Fstyles%2Fbibtex&version=1.0.2_strict). If this is indeed intended, we will need to change how the page is built on our end.

**Comment by bwiernik** [comment]
Thanks for pointing out the issue!
