### ISSUE TITLE
Bluebook Law Review bibliography format issues

### ISSUE THREAD

**Issue by ShaunGP** [citation-style-language/styles#6077]
Good day

I am using the Bluebook Law Review style in Mendeley. Normally I would only use it for footnotes, but in this instance I need to include a bibliography. However, when I use the Insert Bibliography button, Word does not seem to recognise the formatting instructions. So I get:
span style="font-variant:small-caps;">Don Tapscott &#38; etc (I had to remove the < or it formats it correctly here)
instead of:
DON TAPSCOTT & ALEX TAPSCOTT, BLOCKCHAIN REVOLUTION (Penguin Random House Paperback) (2018)

Also, I think in the bibliography the surname should come first, unlike in the footnote where it is first name first, according to this source: https://www.ukessays.com/referencing/bluebook/#:~:text=cases%20by%20jurisdiction.-,Bibliography,formatting%20of%20the%20authors%20name.

Is it possible to fix this issue, or to provide some guidance on how to fix it on my end?

**Comment by ShaunGP** [comment]
Here is an example of what it looks like in Word.
[Bluebook bibliography issue.docx](https://github.com/citation-style-language/styles/files/8789551/Bluebook.bibliography.issue.docx)

**Comment by adam3smith** [comment]
The style just doesn't define a bibliography because, as far as I now, The Bluebook doesn't (your source isn't exactly authoritative ;). That Mendeley even allows you to insert one is arguably a bug on their end (and any errors with it are entirely outside of our control). 

You can try modifying the style & adding a bibliography, but I don't think we'll do this for the public version.

**Comment by ShaunGP** [comment]
Thanks for responding. I agree, the style wouldn't normally require a bibliography because all the info is in the footnotes anyway. I'm pretty sure the publishers want both in this instance though (it's for a book). Let me chat to them and confirm their requirements, and also exactly what style they expect for each.
