### ISSUE TITLE
Conversing this style to CLS

### ISSUE THREAD

**Issue by Halawani01** [citation-style-language/styles#6114]
Hello, good afternoon 

I'd like to convert this ens style in the following link to CLS

as my university uses this style with Endnote and I'd like to use it in Mendeley

https://endnote.com/style_download/harvard-hwu/

Please heeeeelp. 

waiting for your support 

Thank you ^_^

**Comment by adam3smith** [comment]
There's no conversion from Endnote styles. See [here for requesting styles](https://github.com/citation-style-language/styles/blob/master/REQUESTING.md#requesting-csl-styles).
