### ISSUE TITLE
Modern Humanities Research Assotiation 3rd edition (note-with biblography) - subsequent use of same reference does not display name of the file only author

### ISSUE THREAD

**Issue by h2Peteris** [citation-style-language/styles#6193]
Hi, I'm sorry for specific case, where I would like the base citation style to show longer footnote than it curently does on multiple citations of the same source in Mendeley.

I am using Modern Humanities Research Assotiation 3rd edition (note-with biblography) footnote citation style - and citing the same source does not display full citation, only the names - on second and further use of the same source publication.

How to enable full citation in subsequent footnote citations? 
Is it possible at all to set it to full citation or at least add the url in secondary citations of the same source?

Itried looking into editor and from what i can understand - I cant find the "generic-base" code explanation , to understand if subsequent notes are cited as short as possible and what would be other possible codes that I might enter there to change currently displayed footnotes.

Could you suggest where in code it is defined, that on second citing , on the same page or on different pages full citation is shortened. and where I could modify this short version to longer.

The logical solution would be that footnotes keep the same number as the first original footnote, but I feel that it is a complete rebuild of the style.. So if I could edit it at least for myself - breaking the short citation to at least the addition of URL, doi if not the publication full name it would be greatly appreciated. 

![Screenshot note - mendeley PL](https://user-images.githubusercontent.com/111865729/186144897-fa293e91-27eb-47a6-9147-c49d1481077b.png)
I'm not fluent in the coding language do decipher the second citation appearance in code editor.

**Comment by POBrien333** [comment]
That would be defined under "if subsequent" on the left. Only if it's the first time it uses the "Else" you are showing in the screenshot.

**Comment by h2Peteris** [comment]
Im curently still experiancing this:

![image](https://user-images.githubusercontent.com/111865729/187043015-0f68de56-83b3-4191-b1fd-98e6a4c6ddde.png)

The Subsequent is confusing, for this style.  Expanded list here:

![image](https://user-images.githubusercontent.com/111865729/187043142-1f52eef3-ce70-4b00-af07-d0f55c1aa4be.png)

Could you point me to a choice that shortens the note?

**Comment by POBrien333** [comment]
So, to explain what the style does:
"is it subsequent?" - Yes, then print it out like this.
If not (=else), then print it out like this.

In order to get rid of shortened subsequent citations you would basically just get rid of the conditional all together.
Move everything in the "else" out of the conditional, then delete the whole "conditional" part.

**Comment by adam3smith** [comment]
Closing this as answered
