### ISSUE TITLE
Triangle.csl gives bad location in citations

### ISSUE THREAD

**Issue by FrViPofm** [citation-style-language/styles#6249]
1. open zotero
2. open Libreoffice and create an new document writer
3. write something
4. click on "Add/Edit citation"
5. set "Zotero - document settings" with "triangle", "footnote"...
6. choose "classic view"
7. in "Add/Edit citation" window, select the book with "paragraph" set to "3". click "OK
8. got a footnote with the citation ending with "p. 3" 

(tested on a copy of triangle, see : https://forums.zotero.org/discussion/99517/ieee-paragraph-reference#latest  )

In fact, in the Zotero - Add/Edit citation" window, the citation ends with "p. 3" despite the chosen locator "volume", "figure", "paragraph"...

If someone can make the structure to solve this problem, I can translate it into french (in the <locale xml:lang="fr"> section, i guess). But I'm not very skillful in git to submit it.

**Comment by POBrien333** [comment]
Thank you for the issue, but as I said on the forum, I'd look into this.

Closed with https://github.com/citation-style-language/styles/pull/6251
