### ISSUE TITLE
ieee and ieee-with-url have more differences than just the URL

### ISSUE THREAD

**Issue by RubenVerborgh** [citation-style-language/styles#6260]
I would expect that the difference between `ieee` and `ieee-with-url` is just the absence of the URL in the former.

However, there are many more differences. I noted because `ieee` recently (?) stopped rendering the title of proceedings, whereas `ieee-with-url` does this just fine.

**Comment by RubenVerborgh** [comment]
Thanks, @POBrien333.

Here is a diff from `ieee` to `ieee-with-url`: https://gist.github.com/RubenVerborgh/1a365b50d8da8ef263ca942310f7bcb9#file-ieee-diff

My comments are:
- 68–69: This might be where `ieee` incorrectly drops the "in…" for conference proceedings
- 77–132: Seems expected when adding a URL
- 338–356: This is where `ieee` seems to be trying the "in…" instead

**Comment by RubenVerborgh** [comment]
Well that's the main one I noticed, yes.

**Comment by POBrien333** [comment]
Hi,

I just did some testing.
**Guidelines**: http://journals.ieeeauthorcenter.ieee.org/wp-content/uploads/sites/7/IEEE_Reference_Guide.pdf

**Conference Paper:**
![image](https://user-images.githubusercontent.com/954979/194506021-2418ef36-4a11-4bf0-9229-1f9a97107bb5.png)


**Conference Proceedings in Print:**
![image](https://user-images.githubusercontent.com/954979/194506112-f0b8911f-cb60-47a5-b541-7b78eee38be3.png)

**Comment by RubenVerborgh** [comment]
I have a different pipeline (BibTeX) than yours, but my issue was that

```bibtex
@inproceedings{verborgh_usewod_2015,
  author = {Verborgh, Ruben and Mannens, Erik and Van de Walle, Rik},
  title = {Initial Usage Analysis of {DBpedia's Triple Pattern Fragments}},
  booktitle = {Proceedings of the 5th USEWOD Workshop on Usage Analysis and the Web of Data},
  year = 2015,
  month = jun,
  url = {http://ceur-ws.org/Vol-1362/USEWOD_paper1.pdf},
}
```

resulted in

```
R. Verborgh, E. Mannens, and R. Van de Walle, “Initial Usage Analysis of DBpedia’s Triple Pattern Fragments,” 2015
```

because there were no details about the proceedings other than `booktitle`.

As you can see [here](https://gist.github.com/RubenVerborgh/1a365b50d8da8ef263ca942310f7bcb9#file-ieee-diff-L68-L69), `container-title` would only get activated when there is also any of `collection-editor editor editorial-director issue page volume`, whereas `ieee-with-url` shows `container-title` whenever `container-title` is available.

**Comment by POBrien333** [comment]
@adam3smith 
Any insight to what's behind that conditional in the "event" macro?
(https://github.com/citation-style-language/styles/blob/master/ieee.csl)
