### ISSUE TITLE
Request a Zotero-CSL of the Nursing Open

### ISSUE THREAD

**Issue by pender521** [citation-style-language/styles#6280]
Could anyone offer a Zotero-CSL for the publication of the Nursing Open? Many thanks!
The homepage of the Publication https://onlinelibrary.wiley.com/journal/20541058

**Comment by bwiernik** [comment]
Please see here for the additional information we need for a style request https://github.com/citation-style-language/styles/wiki/Requesting-Styles

**Comment by pender521** [comment]
> Please see here for the additional information we need for a style request https://github.com/citation-style-language/styles/wiki/Requesting-Styles

Thank you for your response, I will check it later

**Comment by POBrien333** [comment]
@pender521 
If this still of interest, we'd need the requested details for one of our volunteers to look at making this style.

**Comment by POBrien333** [comment]
"This journal uses American Psychological Association (APA) Reference Style. Review the [reference style guidelines](https://authorservices.wiley.com/asset/Author%20Guidelines%20Standard%20Reference%20Text.pdf) prior to submission. All references must be in English."
Source: https://onlinelibrary.wiley.com/page/journal/20541058/homepage/forauthors.html#1-g
