### ISSUE TITLE
CSL for Review of International Studies

### ISSUE THREAD

**Issue by franzeder** [citation-style-language/styles#6281]
I have downloaded your CLS for Review of International Studies for writing an article in LaTeX.

It works great. The only thing that does not work is the printing of the short-title for recurrent citations.

So, for example, the original footnote citation looks as follows:

Thorsten Wojczewski, ‘Populism, Hindu Nationalism, and Foreign Policy in India: The Politics of Representing “the People”’, International Studies Review, 22:3 (2020), p. 39.

But instead of printing 

Wojczewski, ‚Populism‘.

for recurrent citations, the style prints the following:

Wojczewski(2020).

How can I change this (i.e., changing the year for the short-title in recurrent citations).

**Comment by adam3smith** [comment]
@POBrien333 -- originally your style and this does indeed look incorrect for subsequent cites -- can you take a look?
