### ISSUE TITLE
Request for a new style for a journal Revue française d'histotechnologie

### ISSUE THREAD

**Issue by Sulmellen** [citation-style-language/styles#6286]
Dear community, could you help me to create a new style in zotero with this caracteristic:
1.	A link to online style documentation (e.g. for a journal, this would generally be a link to the journal's "Instructions to Authors" section).
File Recommandations aux auteurs.pdf
https://onedrive.live.com/?authkey=%21AM0Rb%2DNIGn3Sod8&id=724FADB4765CA125%211271&cid=724FADB4765CA125
2.	For journals, the journal's e-ISSN:
2679-5132
https://www.afhisto.fr/revue-afh
3.	Two citations

In text citation
[1]
[2]
Bibliography
1.	CAMPBELL J.L. & PEDERSEN O.K. The Varieties of Capitalism and Hybrid Success: Denmark in the Global Economy. Comparative Political Studies, 2007,40 (3): 307-312 https://doi.org/10.1177/0010414006286542
2.	MARES I. Firms and the welfare state: When, why, and how does social policy matter to employers?, in Varieties of capitalism. The institutional foundations of comparative advantage. Hall P.A. and Soskice D. (Ed), edited by Oxford University Press, New York, 2001: 184-213. http://www.woodheadpublishing.com/en/book.aspx?bookID=2354

3.	Freely article
https://www.afhisto.fr/revue-afh/33
Thank you very much,
Best 
[RequestingHelp.docx](https://github.com/citation-style-language/styles/files/9894205/RequestingHelp.docx)
regards,
Sulmellen

**Comment by POBrien333** [comment]
I have logged your request and will notify you here once a style has been created.

**Comment by Sulmellen** [comment]
Thank you very much, but I managed to create it. You can withdraw my request, thank you very much for your help, best regards, Sulmellen

    Le mardi 1 novembre 2022 à 12:40:46 UTC+1, POBrien333 ***@***.***> a écrit :  
 
 


I have logged your request and will notify you here once a style has been created.

**Comment by POBrien333** [comment]
If you've created it, please submit it to the repository, so other academics can also benefit from your work. 
see https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md

**Comment by Sulmellen** [comment]
OK with pleasure. I am waiting for confirmation from my client and I will submit it to the repository ;-)

    Le lundi 7 novembre 2022 à 17:01:22 UTC+1, POBrien333 ***@***.***> a écrit :  
 
 


If you've created it, please submit it to the repository, so other academics can also benefit from your work.
see https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md

**Comment by POBrien333** [comment]
Any progress with this, @Sulmellen ?
