### ISSUE TITLE
APA csl sometimes uses "et al." to replace one author, which does not follow APA style

### ISSUE THREAD

**Issue by gwwright** [citation-style-language/styles#6362]
**Summary:** In certain cases, APA csl uses "et al." in lieu of one author's name, which does not follow an APA rule

"et al." replaces the fourth and final author in a citation when:
- An article cites 2+ references that have 3+ authors AND the same first and second author AND are published in the same year
- At least one of those references has exactly four authors

## Problem

When citing multiple works that are published in the same year by the same first author, APA says to include as many author names as are necessary to avoid ambiguity between the citations. Then, "et al." should replace all other author names:

<img width="798" alt="210614054-95c9ba60-0c34-4210-ba30-9e24db388ce7" src="https://user-images.githubusercontent.com/98776088/210643986-903357f0-eadf-45a0-bcc5-4b851468b403.png">

APA's style guide says that "et al." should never be used to replace one author in a citation:

<img width="797" alt="210613758-318dc2a0-4336-475c-a4d2-feecae0bb539" src="https://user-images.githubusercontent.com/98776088/210644013-dbd18d59-4abc-401a-bcd4-979877814653.png">

However, in certain cases APA csl uses "et al." to replace one author, e.g.:

<img width="948" alt="210615341-5adf7830-1e4f-4a11-8375-06a541d2c4ea" src="https://user-images.githubusercontent.com/98776088/210644037-bcc5e551-0b59-4b5a-bd12-2da8c7aba1dd.png">

According to APA style, the in-text citations for these should be:

1. Xiao, Henderson, & Newell, 2022
2. Xiao, Henderson, Yang, & Newall, 2022

Because both works are published in 2022 and have the same first and second authors (Xiao and Henderson), the third author's name is required in both citations. Because APA says not to use "et al." to replace one author, citation no. 2 must also include the fourth author (Newall).

**Comment by adam3smith** [comment]
We're aware of this, but CSL can't currently handle this, and we have no plans to address this edge case in the specs. 

FWIW, APA is wrong on the Latin (et al. can mean both et alii and et alius/alia, i.e. be either singular or plural) and the rule isn't followed in many of their own publications, but if you do want to follow it to the letter, I'm afraid you'll have to edit the citations manually.

**Comment by bwiernik** [comment]
In my submissions to J of Applied Psychology, J of Personality and Social Psychology, and J of Counseling Psychology, I had copy editors explicitly change citations from following this rule to using "et al." in place of a single author. This misunderstanding of Latin is just not a rule that APA journals consistently follow, so I would not worry about it and just use "et al." in this niche situation.
