### ISSUE TITLE
Is there a good way to check for features (Doi/eprint/url)?

### ISSUE THREAD

**Issue by kellertuer** [citation-style-language/styles#6373]
Thanks for providing such a nice large library.

I am currently coming from BibLaTeX and making my first steps in Quarto.
In my BibLaTeX files I have `DOI=` as well as `eprint=` and `eprinttype=` (this one mainly for arXiv).

Is there a good way to check which styles would at least print the doi but maybe also the eprints? Or maybe also an url?

**Comment by bwiernik** [comment]
If you are using CSL styles, you really should use CSL JSON or CSL YAML as your data format. Converting from BibLaTeX when you build your Quarto file, most items other than journal articles and books will be incorrectly formatted to some degree. 

You can search the repository here for "DOI" to search for styles with DOI printing. The equivalents to eprint and eprinttype in CSL are "number" and "genre". But in general, I would suggest searching the CSL style repository at https://Zotero.org/styles for the journal or publisher you are submitting to. CSL has 1000s of styles for specific journals, publishing houses, university departments, style guides, etc. 

If you just need any generic style, APA and Chicago are both high quality styles with author-date, numeric, and footnote versions

**Comment by kellertuer** [comment]
Ah, thanks for the info with the YAML file, I will read about that then. 
I think as long as it shows doi (mine currently link the title which I feel is ok, unless on uses pdf) I am fine with most styles :)

I am not submnitting to a Journal, I am currently writing tutorials for a Julia package, so there is no real guideline I have to follow.
Will try CSL YAML the next days then,

**Comment by bwiernik** [comment]
I would recommend APA style for that purpose then. It should work well for any type of item

**Comment by bwiernik** [comment]
If you are using Zotero, the BetterBibTeX plugin can generate CSL YAML as well as Bib(La)TeX

**Comment by kellertuer** [comment]
Thanks :) will check zero for that, sure :)

**Comment by kellertuer** [comment]
Sorry, I have a short follow up question.

First of all Zotero and the yaml export work great :)

For my scenario I would like to add an arXiv link to a published paper – with the following idea: If you do not have access to the paper via the DOI, the arXiv (hopefully a link) would give you access to nearly-the-same-thing. 
But how would I specify that in CSL YAML?

I actually even struggle to find a good specification of fields in CSL YAML, is there some documentation somewhere? I am fine using Zotero, for sure, but also there I have to specify that somehow (the thing I do with `eprint=arXiv` and `eprrinttype=the-arxiv-number`).

**Comment by resonweb** [comment]
I have a similar problem: in the CSL style file, I could not find a suitable variable in the "Standard Variables" that pointing to the "serial number: arxiv" in the hayagriva format. Does anyone know how to render an arxiv number?

```hayagriva
ALEPH:2001hzl:
  type: article
  title: '{A Combination of preliminary electroweak measurements and constraints on the standard model}'
  author:
  - Abbaneo, D.
  - others
  date: 2001
  serial-number:
    arxiv: hep-ex/0112021
  parent:
    type: periodical
```

**Comment by bwiernik** [comment]
@kellertuer @resonweb Sorry for not seeing the follow-up. Personally I would just store the link to the arxiv paper in `URL`. Otherwise, if you are using APA style, you could store `archive: arXiv` and `archive_location:  hep-ex/0112021`.

If citing the arXiv paper directly (so CSL type `article`), enter the arxiv number in `number`.
