### ISSUE TITLE
Springer Titles that differ in styles contrary to their list

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#639]
There are, unfortunately, still a fair number, I'll start listing these here and we can decide how to proceed on that. 
One is Environmental Geochemistry and Health
https://forums.zotero.org/discussion/30855/style-error-environmental-geochemistry-and-health/#Item_2
In text citations have a comma in Springer SocPsyc, don't in EG&H (neither in the guide nor in articles)
cc @cparnot

**Comment by zuphilip** [comment]
The comma was delete in the `Springer SocPsyc` style in https://github.com/citation-style-language/styles/commit/33d1bc062790c824ebc21253e3148534683c2922 and therefore we could close the issue here.

**Comment by zuphilip** [comment]
ping @adam3smith
