### ISSUE TITLE
Update not being merged

### ISSUE THREAD

**Issue by Griever158** [citation-style-language/styles#6401]
Hi All

My sincere apologies if I've being rude. I believe I've followed the process from the guides correctly, so hopefully this is just a minor issue.

I created a PR a month ago to update my school's style: https://github.com/citation-style-language/styles/pull/6367

However, no one has been added as a reviewer and even though all the checks have succeeded it has not been merged.

Am I just being too eager and it will be merged eventually; or, has something gone wrong?

I deeply appreciate your help!

**Comment by adam3smith** [comment]
No, we're just running behind with reviews, sorry about that.
