### ISSUE TITLE
KSSTA style should not show publisher

### ISSUE THREAD

**Issue by ttrepka** [citation-style-language/styles#6405]
Hello,
we are using CSL in our product and a user had issues submitting his manuscript to "Knee Surgery, Sports Traumatology, Arthroscopy" ([see the style](https://github.com/citation-style-language/styles/blob/master/knee-surgery-sports-traumatology-arthroscopy.csl)). He was told by a KSSTA editor to remove publishers from the bibliography before his manuscript can be accepted.

I could make a PR with the `publisher` macro removed but I'm not sure it's correct. The style guide doesn't specifically mention it and I see one book example where it seems to be used (Blackwell, London):
> South J, Blass B (2001) The future of modern genomics. Blackwell, London

So perhaps it should only be used for books but not e.g. for articles?

Style guide: https://www.kssta.org/authors-homepage/references/
Some examples: https://www.kssta.org/kssta-reference-style-examples/

**Comment by icornelius** [comment]
`knee-surgery-sports-traumatology-arthroscopy.csl` is among the csl files flagged as "problematic" by @adam3smith @denismaier  in #5872.
