### ISSUE TITLE
NATURE style is broken in Mendeley

### ISSUE THREAD

**Issue by cement-head** [citation-style-language/styles#6407]
The 2022 version of the NATURE citation style is completely broken and causes Mendeley Plug-In to crash on Linux with LibreOffice.

**Comment by bwiernik** [comment]
That would be a bug with Mendeley, not an issue with the CSL style. You should report the crash to their technical support or consider moving to another reference manager such as Zotero

**Comment by cement-head** [comment]
I'm not moving to ZOTERO, it's terrible.  Mendeley seems to be the only reasonable reference manager on LINUX, it's extremely unfortunate that it got bought by Elsevier and they proceeded to slowly destroy it.

**Comment by cement-head** [comment]
And I do not think that it's a bug in Mendeley.  Mendeley has been using CSL format for a long time. Unfortunately, I can't say for sure, because I've never had to use that style until now - so if it existed in the past I can't say.  I believe it has something to do with the superscripting of the reference numbers in the word processor.
