### ISSUE TITLE
Magnetic Resonance in Medicine

### ISSUE THREAD

**Issue by DavidNorris42** [citation-style-language/styles#6422]
The style for this journal is correct. References should be numbered in superscript and without brackets. At present they are in-line and have round brackets.

**Comment by POBrien333** [comment]
The guidelines state "References should be prepared according to AMA Manual of
Style: A Guide for Authors, 10th edition (New York: American Medical
Association in cooperation with Oxford University Press, 2007)." [Source](https://onlinelibrary.wiley.com/pb-assets/assets/15222594/authorguidelinesdec22-1671206311.pdf)

Can you double check if this fits and then I'll just make the style a dependent on AMA.

You'll find the style on the repository: https://www.zotero.org/styles?q=ama

**Comment by DavidNorris42** [comment]
Thanks for getting back to me. I have checked and you are right. The current format is correct.
We can close the thread. My apologies for any inconvenience.

Best wishes,

David
