### ISSUE TITLE
Création style Zotero

### ISSUE THREAD

**Issue by M42Forez** [citation-style-language/styles#6435]
Bonjour,
Je suis incapable de créer un style pour Zotero... Quelqu'un pourrai m'aider???
Voici les prérequis :

Appels bibliographiques

Appel bibliographique dans le texte : (auteur année : page, figure) (Boucher 197 : 164, fig. 5).
Pour deux ou plusieurs auteurs correspondant à deux articles ou ouvrages distincts (Boucher 1976 : 164, fig. 5 ; Boucharlat 1987 : 1922)
Pour deux ou trois auteurs d’un même article ou ouvrage (Poupet, Simon 1979 : 15)
Pour plus de trois auteurs d’un même article ou ouvrage (Poupet et al. 1979 : 123)
Pour les ouvrages collectifs ou les catalogues, dans l'appel bibliographique, citer les premiers mots du titre (À la Fortune du Pot 1990).

Les titres (d'ouvrages et de revues) apparaîtront en italique dans le texte.

Appels de revue : lieu d’édition et éditeur
Pour les appels d’articles dans une revue courante, ne pas mettre le lieu et l’éditeur.

Bibliographie finale
Les différentes sections d’une référence bibliographique sont séparées par des virgules (titre de l’ouvrage/ville d’édition, titre de revue/ numéros des pages, etc.)

Monographies et ouvrages collectifs :
Nom + initiale + année, titre de l’ouvrage, titre de la collection + n°, ville d’édition, maison d’édition, année, nombre de pages.
Hamon C. 2006, Broyage et abrasion au Néolithique ancien : caractérisation technique et fonctionnelle des outillages en grès du Bassin parisien, BAR International series 1551, Oxford, Archaeopress, 2006, 342 p.
Dondin-Payre M., Raepsaet-Charlier M.-Th. (éd.) 1999, Cités, municipes, colonies, les processus de municipalisation en Gaule et en Germanie sous le Haut-Empire romain, Histoire ancienne et médiévale 53, Paris, Publications de la Sorbonne, 1999, 483 p.

Articles dans un ouvrage collectif :
Nom + initiale + année, « titre de l’article », in + initiale + nom + (éd., dir, etc.), titre de l’ouvrage, titre de la collection + numéro, ville d’édition, maison d’édition, année, nombre de pages.
Beeching A. 2003, « Organisation spatiale et symbolique du rituel funéraire chasséen en moyenne vallée du Rhône : première approche », in Ph. Chambon, J. Leclerc (dir.), Les pratiques funéraires néolithiques avant 3500 av. J.-C. en France et dans les régions limitrophes : table ronde SPF, Saint‑Germain‑en-Laye, 15-17 juin 2001, Mémoires de la Société préhistorique française 33, Paris, Société préhistorique française, 2003, p. 231-239.

Articles de périodiques :
Nom + initiale + année, « titre de l’article », titre de la revue + numéro, année, numéro des pages.
Gibaja J.-Fr.  2002, « Las  hoces  neolíticas  del  noreste  de  la  Península  Ibérica »,  Préhistoire  anthro-pologie méditerranéennes 10, 2002, p. 83‑96.

**Comment by adam3smith** [comment]
See https://github.com/citation-style-language/styles/blob/master/REQUESTING.md#requesting-csl-styles
