### ISSUE TITLE
Citing a chapter in a book in Turabian 8th edition

### ISSUE THREAD

**Issue by philcoul** [citation-style-language/styles#6469]
Hi
Turabian 8th edition says that when citing a chapter of a book:
N:       ##. Chapter Author’s First and Last Names, “Title of Chapter: Subtitle of Chapter,” in Title of Book: Subtitle of Book, **ed.** Editor’s First and Last Names (Place of Publication: Publisher’s Name, Date of Publication), XX–XX.

B:  Chapter Author’s Last Name, Chapter Author’s First Name. “Title of Chapter: Subtitle of Chapter.” In Title of Book: Subtitle of Book, **edited by** Editor’s First and Last Names, YY–YY. Place of Publication: Publisher’s Name, Date of Publication.

In my case instead of having "ed" for Notes and "edited by" for Bibliography, I get "by" for both cases. Is there a way to correct this, may be, in the turabian-fullnote-bibliography.csl? I am using Zotero.

Thanks

**Comment by POBrien333** [comment]
This certainly works. Have a look at the Mares chapter here in the sample output: https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fturabian-fullnote-bibliography

Switch style to APA, then back to Turabian. This should force a full re-render of the citations and hopefully correct this.

**Comment by adam3smith** [comment]
You'd get that output if you're using "Book author" instead of "Editor" for the editors in Zotero. as POBrien333 says, the style itself is fine.
