### ISSUE TITLE
Suffix formatting

### ISSUE THREAD

**Issue by ms609** [citation-style-language/styles#6497]
A style contains the citation format

```xml
<citation disambiguate-add-year-suffix="true" collapse="year-suffix" year-suffix-delimiter=", ">
  <layout prefix="(" suffix=")" delimiter="; ">
    <group delimiter=" ">
      <text macro="author-short"/>
      <text macro="year-date"/>
    </group>
    <text variable="year-suffix" font-style="italic"/>
  </layout>
</citation>
```

A pair of citations `[@Smith2020a; @Smith2020b]` is rendered as

(Smith 2020 _a_; b)

i.e. the "b" is not italicized; nor does it link to reference b, when reference a is linked.

Do I need to adjust the xml in my style – or is this a bug with the software I'm using to format the references?

**Comment by adam3smith** [comment]
We'd have to see the whole style, but I'd suspect this is an issue with the software, yes. Reference linking definitely is, that's not a feature of CSL at all.

**Comment by adam3smith** [comment]
Guessing from the PR this is paleontology.csl -- that's correct in the style and works in Zotero. You'd have to report it with the implementation.

**Comment by ms609** [comment]
Thanks – then I'll follow up there.  Glad to know I'm not missing anything at this level.
