### ISSUE TITLE
CSL capitalisations

### ISSUE THREAD

**Issue by bwychan** [citation-style-language/styles#6509]
I have found a bug in the CSLs such that some records have first letter capitalisations or all caps in the title.

I am using the following CSL in our PrimoVE instance (Murdoch University, Australia):
- apa-cv
- chicago-author-date
- chicago-note-bibliography
- modern-language-association
- australian-guide-to-legal-citation
- vancouver
- american-chemical society
- ieee

Both books and articles are affected. The examples below are in APA, but I also checked them in the other citation styles and in most of them, the capitalisation of the title seems to be consistent and inherited from the source data (especially the all caps one).

Fisher, A. D., April, M. D., Naylor, J. F., Kotwal, R. S., & Schauer, S. G. (2021). The Battalion Aid Station—The Forgotten Frontier of the Army Health System During the Global War on Terrorism. Military Medicine. [https://doi.org/10.1093/milmed/usab401](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1093%2Fmilmed%2Fusab401&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530527459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gvlOyb0eA8mY3kajje%2B4MnPs5%2FBOr798Zau7BFBZqYE%3D&reserved=0)
[https://librarysearch.murdoch.edu.au/permalink/61MUN_INST/3bciql/cdi_proquest_miscellaneous_2582809655](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flibrarysearch.murdoch.edu.au%2Fpermalink%2F61MUN_INST%2F3bciql%2Fcdi_proquest_miscellaneous_2582809655&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530527459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ghHgV3WxEV2kGNF8D%2Fztl86X0eLzJiNYsJFEU%2FUkY3E%3D&reserved=0)

Melanson, M., & Bower, M. (2011). THE ROLE OF THE ARMY NUCLEAR MEDICAL SCIENCE OFFICER IN THE GLOBAL WAR ON TERRORISM. Health Physics (1958), 101(1), S78–S78.
[https://librarysearch.murdoch.edu.au/permalink/61MUN_INST/3bciql/cdi_proquest_miscellaneous_902382635](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flibrarysearch.murdoch.edu.au%2Fpermalink%2F61MUN_INST%2F3bciql%2Fcdi_proquest_miscellaneous_902382635&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530527459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4hkLPbdlDIcD2jiyxoOM7fzvUGVFaf4nuj9G08DQjMg%3D&reserved=0)

Moore, A. (2019). Empire’s Labor The Global Army That Supports U.S. Wars. Cornell University Press. [https://doi.org/10.7591/9781501716393](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.7591%2F9781501716393&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530527459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=q8McVW%2Bzm7RlPSMhm0lTEIDf6O%2BIQP5Uqbu%2FdxoPuLs%3D&reserved=0)
[https://librarysearch.murdoch.edu.au/permalink/61MUN_INST/1r6on8i/alma991005438684007891](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flibrarysearch.murdoch.edu.au%2Fpermalink%2F61MUN_INST%2F1r6on8i%2Falma991005438684007891&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530684123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o9oM9Obyugb5abPdppazHFWLECMvav7zmwchRpGeJJc%3D&reserved=0)

Ramos, B., Miller, F. A., Brandão, T. R. S., Teixeira, P., & Silva, C. L. M. (2013). Fresh fruits and vegetables—An overview on applied methodologies to improve its quality and safety. Innovative Food Science & Emerging Technologies, 20, 1–15. [https://doi.org/10.1016/j.ifset.2013.07.002](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1016%2Fj.ifset.2013.07.002&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530684123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hy0oZ6pGtjKvna1UBX0yUZU8ZfeWJtb8k4OUB1QCo%2Fc%3D&reserved=0)

Schneid, F. C. (2012). The projection and limitations of imperial powers, 1618-1850. Brill.
[https://librarysearch.murdoch.edu.au/permalink/61MUN_INST/1r6on8i/alma991005511866207891](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flibrarysearch.murdoch.edu.au%2Fpermalink%2F61MUN_INST%2F1r6on8i%2Falma991005511866207891&data=05%7C01%7Cb.chan%40murdoch.edu.au%7C42371589e6d9427ddf2e08db35a94ea6%7Cc00d4c1bcf7b4e93b7c710113a9bc230%7C1%7C0%7C638162773530684123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3%2BqGvaoPAddoPMGLxMWSRthOpelQQruh7mnCEFVQS20%3D&reserved=0)

For example, in APA, only the first letter of a title/subtitle should be capitalised, as well as proper nouns. However, as can be seen, there is a variety of outputs which indicates that the capitalisation script does not seem to be working consistently. In particular, for the last one on the list, the APA citation has only the first word capitalise, but the other styles (Chicago etc.) have every word capitalised.

I am not sure which version of citeproc-java is being used, but was referred here by Ex Libris. But you should be able to test in our live PrimoVE environment without a login as the citation system is open to the public.

Regards,

Bryan Chan
Librarian, Digital Applications
Library and Knowledge Services
Murdoch University

**Comment by adam3smith** [comment]
See this explanation on sentence casing by Zotero: https://www.zotero.org/support/kb/sentence_casing it applies to CSL and CSL expects all titles to be present in sentence case (they're then correctly title cased in styles that require it, as you see for Chicago Manual). As noted in the linked Zotero article, automatic sentence casing isn't technically possible.

**Comment by bwychan** [comment]
Hi adam3smith,

The links above refer to ExLibris's Primo, not a citation tool that we can manipulate, Furthermore, there seems to be a code that attempts to do so, because as I mentioned in one of the examples there was a change in sentence casing - but not consistently. ExLibris has said this is not something they can control, and so to refer it here for someone to look into the CSL code itself. Can you help?

Regards,

Bryan Chan
Librarian, Digital Applications
Library and Knowledge Services
Murdoch University

**Comment by adam3smith** [comment]
No, sorry, really nothing we can do about this.
As per the [CSL specifications](https://docs.citationstyles.org/en/stable/specification.html#sentence-case-conversion)

> CSL processors don’t recognize proper nouns. As a result, strings in sentence case can be accurately converted to title case, but not vice versa. For this reason, it is generally preferable to store strings such as titles in sentence case, and only use text-case if a style desires another case.

And that's exactly what the styles listed are doing: Styles like APA that require sentence case do nothing, styles like MLA and Chicago that require title case convert sentence case (like your last two examples) to title case.

Proper capitalization in titles is a metadata quality issue just like correct spelling -- it's not something CSL styles (or any other way to generate citations) can automate.
