### ISSUE TITLE
Requesting Style: Journal of Anatomy

### ISSUE THREAD

**Issue by mdoube** [citation-style-language/styles#6516]
Could I please request a style for **Journal of Anatomy**, which uses a flavour of Harvard, with:

- in-line citations:
  - one or two authors listed in full, or only one author plus _et al._ if there are 3 or more authors
  - sorted alphabetically by first author name
  - disambiguated by Latin letter after year 
- Reference list:
  -  over 6 authors truncated to ~~3~~ **6** authors plus _et al._ 
  - Journal name in italics, volume number in bold (in web page but not in PDF!)
  - hanging indent in PDF, but not on webpage

The test citations should appear like this:

In-text citation:
(Campbell & Pedersen, 2007)
(Mares, 2001)

Bibliography:
Campbell, J.L. & Pedersen, O.K. (2007) The varieties of capitalism and hybrid success. _Comparative Political Studies_, 40, 307–332. Available from: https://doi.org/10.1177/0010414006286542

Mares, I. (2001) Firms and the welfare state: When, why, and how does social policy matter to employers? In: P.A. Hall & D. Soskice (Eds.) _Varieties of capitalism. The institutional foundations of comparative advantage_. New York: Oxford University Press, pp. 184–213.

[Guidelines:](https://onlinelibrary.wiley.com/page/journal/14697580/homepage/forauthors.html)

> References in the text should be inserted in parentheses in full for single and dual authored papers, but using the first author and et al. for multiple authored papers. Reference to personal communications, unedited and un-refereed work, and work that is unpublished should be minimal and should appear in the text only. It is the author’s responsibility to obtain permission from colleagues to include their work as a personal communication.
> 
> References in the list should follow the Harvard system. Over 6 authors will be abbreviated to 3 authors et al.  [NOTE this is not done in practice, it is truncated to 6 authors plus et al.] Refer to a recent copy of the journal for examples.
> 

Recent examples, from https://doi.org/10.1111/joa.13813 

In-line citations:
Specifically, many authors have demonstrated the influence of climate on the morphology of the internal nasal region (Bastir et al., [2011](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0002); Butaric et al., [2010](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0011); Carey & Steegmann, [1981](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0012); Cottle, [1955](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0018); Crognier, [1981a](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0020), [1981b](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0021); Davies, [1932](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0022); Evteev et al., [2014](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0035); Franciscus & Long, [1991](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0040); Harvati & Weaver, [2006](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0044); Jaskulska, [2014](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0053); Maddux & Butaric, [2017](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0063); Marks et al., [2019](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0065); Negus, [1960](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0069); Noback et al., [2011](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0070); Roseman & Weaver, [2004](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0078); Thomson & Buxton, [1923](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0088); Weiner, [1954](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0095); Wolpoff, [1968](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0100); Yokley, [2009](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0102); Zaidi et al., [2017](https://onlinelibrary.wiley.com/doi/10.1111/joa.13813#joa13813-bib-0103)), which is in direct contact with the external environment.

Bibliography:
Butaric, L.N., McCarthy, R.C. & Broadfield, D.C. (2010) A preliminary 3D computed tomography study of the human maxillary sinus and nasal cavity. _American Journal of Physical Anthropology_, **143**, 426– 436. Available from: https://doi.org/10.1002/ajpa.21331

Kushniarevich, A., Utevska, O., Chuhryaeva, M., Agdzhoyan, A., Dibirova, K., Uktveryte, I. et al. (2015) Genetic heritage of the Balto-Slavic speaking populations: a synthesis of autosomal, mitochondrial and Y-chromosomal data F. Calafell, ed. _PLoS One_, **10**, e0135820. Available from: https://doi.org/10.1371/journal.pone.0135820

Disambiguation by Latin lower-case letter, example from https://doi.org/10.1111/joa.13827
In-line:
Due to their position closer to the trunk, bones of the stylopod bear more muscular insertions with the pectoral and pelvic girdles than do bones of the zeugopod (Shindo & Mori, [1956a](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0133), [1956b](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0134)) and thus face different constraints.

Disambiguation by year:
Numerous attempts to formulate generally applicable allometric laws using body mass, bone length and bone circumference have been proposed, and have been subject to several decades of debates (Alexander, [1977](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0003); Alexander et al., [1979](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0004); Biewener, [1983](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0018), [2005](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0020); Bertram & Biewener, [1990](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0016); Christiansen, [1999](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0154), [2002](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0031), [2007](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0032), Kokshenev et al., [2003](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0083); Kokshenev, [2007](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0081); McMahon, [1973](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0098), [1975a](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0099), [1975b](https://onlinelibrary.wiley.com/doi/10.1111/joa.13827#joa13827-bib-0100)).

Bibliography (also, examples of journal articles):
Shindo, T. & Mori, M. (1956a) Musculature of Indian elephant. Part 1. Musculature of the forelimb. _Okajimas Folia Anatomica Japonica_, **28**, 89– 113. Available from: https://doi.org/10.2535/ofaj1936.28.1-6_89

Shindo, T. & Mori, M. (1956b) Musculature of Indian elephant part II. Musculature of the hindlimb. _Okajimas Folia Anatomica Japonica_, **28**, 115– 147. Available from: https://doi.org/10.2535/ofaj1936.28.1-6_115

Software:
Artec 3D. (2018) _Artec studio professional_. Santa Clara: Artec 3D. Available at: https://www.artec3d.com/

Whole book:
Bookstein, F.L. (1992) _Morphometric tools for landmark data: geometry and biology_, 1st edition. Cambridge: Cambridge University Press. Available from: https://doi.org/10.1017/CBO9780511573064

Book chapter:
Buckley, C. (2000) Captive elephant foot care: natural habitat husbandry techniques. In: B. Csuti, E.L. Sargent & U.S. Bechert (Eds.) _The Elephant's foot_. Ames, USA: Iowa State University Press, pp. 53– 55. Available from: https://doi.org/10.1002/9780470292150.ch6

**Comment by POBrien333** [comment]
Can you adapt the given example here to match the journal? That way we can work on your request faster. See https://github.com/citation-style-language/styles/blob/master/README.md#citation-style-language---style-repository

**Comment by mdoube** [comment]
> Can you adapt the given example here to match the journal? That way we can work on your request faster. See https://github.com/citation-style-language/styles/wiki/Requesting-Styles

Hi, thanks for picking this up and I'm happy to help but I'm not sure what you're asking for. Hopefully this should just be a tweak or dependent of an existing style but there are _so many_ Harvards that it will take ages for me to find a good baseline.
The example given above is a direct copy-paste from this month's _Journal of Anatomy_
It seems though that the stated style is not the same as the used style, with respect to author list truncation in the bibliography (7 and more authors are truncated to the first 6, not 3, plus et al.).
Also note that in-line citations are sorted alphabetically by first author and not by date.

**Comment by adam3smith** [comment]
This is the part missing from your request:

> Two citations, for a journal article and a book chapter, in the format of the style you're requesting. Create these citations for the two items shown below, the article by Campbell and Pedersen and book chapter by Mares. **If your request does not contain these specific citations, you will be asked to revise it.** Provide both in-text citations and bibliographic entries. For, e.g., the APA style, these citations would look like (...)

in other words, you'll need to format those two citations (details on the linked page) as they should be formatted for the journal to help us identify closely matching styles.

**Comment by mdoube** [comment]
> you'll need to format those two citations (details on the linked page) as they should be formatted for the journal to help us identify closely matching styles.

OK done, added to the initial request at the top of this Issue.

**Comment by POBrien333** [comment]
Give this a go. I don't see them giving any real examples in the guidelines, so as typical for Wiley journals, the style is completely adapted based on an example paper.

https://github.com/citation-style-language/styles/raw/5f82a27d96e598066596df6266931668e251f27c/journal-of-anatomy.csl

**Comment by mdoube** [comment]
> Give this a go.

Wow that was fast!

Looks good in general, I am just checking through a manuscript I'm working on at the moment.

Couple of bugs / improvements.
- et al. should not be italicised in the bibliography or in-line citations
- full stop (period, '.') needed between item title and journal name in bibliography
- no 'p.' or 'pp.' to indicate page numbers in the journal item type in the bibliography (but p. / pp. is needed in the book chapter item type)
- enforce sentence case (not Title Case) in the bibliography for item titles
- some of my in-line citations are weirdly formatted after changing document settings to use the new style, they are unlike all the other in-line citations which look fine (this may be a bug of Zotero itself, or of my database, rather than the style).

>  (Goldman et al., 2003, 2014; McFarlin et al., 2008; C. M. Riggs et al., 1993; C M Riggs et al., 1993) 

This one has some first initials that should be omitted and they are also not consistently abbreviated.

> (Burr, Schaffler, Yang, Lukoschek, et al., 1989; Burr, Schaffler, Yang, Wu, et al., 1989; McCarthy & Jeffcott, 1988)

This one has too many authors in the author list; should be truncated to first author plus et al.

**Comment by POBrien333** [comment]
https://github.com/citation-style-language/styles/raw/1151f0287be385b945e002c86b97b0723fe6f511/journal-of-anatomy.csl

**Comment by mdoube** [comment]
> I'm not going to make the "available at" vs "available from" change.

I did it and sent you a pull request:
https://github.com/POBrien333/styles/pull/2

Thanks for your work getting this started, it is a long time since I worked on CSL and would have taken me ages to get to this point.
