### ISSUE TITLE
Question about conditional citation and bibliography formatting

### ISSUE THREAD

**Issue by sbihorel** [citation-style-language/styles#6531]
Hi

Before I invest time into learning more about csl syntax / customization, I would like to know if it is possible with a custom csl file to format in-text citations and bibliography entries differently based upon the item type. Specifically, I'd like to format technical reports differently from articles/book/book chapters.

In the mock example below, the citation to a technical report shows as the report name/number, while the citation to an article shows "author name, year". The structure of the entries in the bibliography also differs.

- In text citation: " The concentrations of XYZ were measured using a validated assay (XYZ123) based upon the method developed by Smith, 2020."
- Bibliography:
Smith J, Doe J. A revolutionary method to measure  XYZ in thin air. Journal of awesome findings. 2020, 21(2) 100-125.
XYZ123 Validation Report : Measurement of XYZ in thin air. BigPharm, Inc. 2022.

If csl provides this type of capabilities, I would greatly appreciate if you could point me towards a relevant csl style example to complement the csl specifications website material that I would need to read.

Thanks

**Comment by POBrien333** [comment]
Yes, absolutely.
A typical style tests for the various item types or item groups and formats them differently.

I recommend you to just find a closely matching style using the following tool and use that as a base. 
https://editor.citationstyles.org/searchByExample/

Note that you can switch through the different item types there and that you need to use the meta data that is provided on the left.
You will likely find a match that is very close and then will only need to make smaller edits.

**Comment by denismaier** [comment]
What about activating the discussions feature?  I think this would better be moved out of the issues. (Also, I'd think this can be closed now.)
