### ISSUE TITLE
Needs update for new short-author style "associacao-brasileira-de-normas-tecnicas.csl" #6138

### ISSUE THREAD

**Issue by vsaroca** [citation-style-language/styles#6650]
`associacao-brasileira-de-normas-tecnicas.csl` #6138 needs to be updated for the new short-author style so in text citations only capitalize the first letter according to NBR 10520.

**Comment by POBrien333** [comment]
Hi,
There is quite some activity regarding ABNT on the Zotero forums as well as a few open PRs on here:
- https://github.com/citation-style-language/styles/pull/6608
- https://github.com/citation-style-language/styles/pull/6618
- https://github.com/citation-style-language/styles/pull/6647

**Comment by PriscilaSJUFRGS** [comment]
> `associacao-brasileira-de-normas-tecnicas.csl` #6138 needs to be updated for the new short-author style so in text citations only capitalize the first letter according to NBR 10520.

Yes. We're waiting to see if our other pull request is all right to make changes on this style.

**Comment by p3palazzo** [comment]
#6618 has now been fully integrated into #6608.
