### ISSUE TITLE
MLA In-Text Citations

### ISSUE THREAD

**Issue by AlexeyShaykov** [citation-style-language/styles#6667]
Hi. Thank for your works. 

I use https://github.com/citation-style-language/styles/blob/master/modern-language-association.csl 
to show in text Citations by MLA format, but here https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_in_text_citations_the_basics.html 

MLA format citation use author-page method of in-text citation like:

`Romantic poetry is characterized by the "spontaneous overflow of powerful feelings" (Wordsworth 263).`

Here is my example https://codesandbox.io/s/citation-js-format-sample-forked-r2l5fs?file=/src/App.js
where I try to make citations in diff formats. 

Pls help to display page numbers in MLA In-Text Citations

**Comment by bwiernik** [comment]
The MLA CSL style already implements that format. In your examples, you didn't specify a page number or other locator to the citations. Those are only shown if provided (otherwise citations are to the whole work vs a specific page)

**Comment by adam3smith** [comment]
Note that "page" for in text citation is "locator" (of type page) for CSL. I've just added a locator to the CSL JSON in your snippet, but that didn't work. Might be that citation-js is just not handling locators? Might be worth asking over there. In any case, as bwiernik says, the style on the repository does this right (you can test, e.g., in Zotero), so no issue here.

**Comment by bwiernik** [comment]
Yep that makes sense
