### ISSUE TITLE
Replace old united-nations-conference-on-trade-and-development.csl file

### ISSUE THREAD

**Issue by MirUnctad** [citation-style-language/styles#6687]
I would like to replace the file united-nations-conference-on-trade-and-development.csl with an updated version. We are working on a more advanced version to be published in the future. Could you please let me know how to proceed?

**Comment by bwiernik** [comment]
We are happy to have the update!

Please download the style CSL file and update as needed, then follow steps 1, 2, and 3b here to submit it: https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md

Please feel free to ask any questions!

**Comment by POBrien333** [comment]
Closed by https://github.com/citation-style-language/styles/pull/6696
