### ISSUE TITLE
New style curator interest

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/styles#6699]
Hi @adam3smith @bdarcus, my husband Karl @presbyope is interested in helping to curate the styles and locales repos. Could one of you add him as a contributor?

**Comment by bdarcus** [comment]
Great!

I'm a little confused on how to do that. We have teams, with permissions, but am not clear on which his role would belong to.

Perhaps @adam3smith can clarify.

**Comment by adam3smith** [comment]
I've added @presbyope to the Maintainer team, which has maintain privileges for styles and locales and write for documentation and schema. In a rush right now, but we have an open issue for review criteria, please read through those and let us know if you have any questions. And most importantly, thanks so much, Karl, we can really use the help.
