### ISSUE TITLE
Wrong in-text separator in all styles

### ISSUE THREAD

**Issue by baltzis** [citation-style-language/styles#6755]
In Greek the separator for multiple in-text citations in parenthesis (in all styles using this format) is not the same as on almost all other languages. The correct character is the sign "·" (Greek semicolon, "ano teleia", Unicode 0387, U+0387) and not ";". This should be corrected everywhere because authors are enforced to make a lot of corrections manually.

**Comment by POBrien333** [comment]
Thank you baltzis. Such issues are better placed in the locale section of this repository: https://github.com/citation-style-language/locales

@adam3smith 
Would I change this line from the locale file?
[    <term name="semicolon">;</term>](https://github.com/citation-style-language/locales/blob/3fd551ca87ea464f89b1509e4987015691f3132b/locales-el-GR.xml#L170)

**Comment by adam3smith** [comment]
I think so, yes -- I'd test that this works (with an embedded local in any given styles) but I think this should work.
