### ISSUE TITLE
ASA 7th edition?

### ISSUE THREAD

**Issue by jmcgranahan** [citation-style-language/styles#6761]
When will the American Sociological Association (ASA) citation style be updated? The CSL file currently in this repo is for the 6th edition; however the 7th edition was published a couple of months ago. Please advise. Thank you.

**Comment by POBrien333** [comment]
The more info you give us (link, changes) the easier it is for us to provide a new style.

**Comment by bwiernik** [comment]
We don't currently have a print copy of this style guide. If you can list out the changes that need to be made for 7th edition, we will be able to update the style much more quickly.

**Comment by bwiernik** [comment]
Oh, in that case, this will be an easy update! Thanks for following up with them!
