### ISSUE TITLE
really need help on how to submit a proposed change to a style sheet

### ISSUE THREAD

**Issue by annabel-mc** [citation-style-language/styles#6779]
Hello, I am very sorry, I am very new to github and literally do not have a clue, I have been asked to make some edits to this style sheet 
https://github.com/citation-style-language/styles/blob/master/harvard-limerick.csl, as a colleague in our library (University of Limerick Library) has noted a few issues, one being a problem with how the edition is displaying currently it is displaying in a citation as ...
Second edition. ed, 
but in fact should be ....
2nd ed.

I have no idea how I submit this proposed change to github, any advice would be very greatly appreciated
Kind Regards
Anne McMahon (UL Library)

**Comment by zepinglee** [comment]
See the contributing guide in <https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md>.

**Comment by annabel-mc** [comment]
Thanks will take a read of that

**Comment by POBrien333** [comment]
I've just submitted a PR. Note though that this would've been output correctly already though if the data was entered with just the number in the edition field.

**Comment by annabel-mc** [comment]
Thanks very much for the update,
