### ISSUE TITLE
Request for a Update to the "Food and Function" Citation Style in Zotero

### ISSUE THREAD

**Issue by fergusLu1998** [citation-style-language/styles#6873]
Hi,
I hope this message finds you well. I am reaching out to extend my sincere appreciation for the exceptional work your team has accomplished. It has come to my attention that the "Food and Function" citation style file (food-and-function.csl) currently available in Zotero, last updated on 2014-05-16, does not reflect the most recent citation guidelines. Notably, the latest guidelines include the integration of an article's theme within the bibliography entries, an element that is missing in the current version.

Given that, I am eagerly looking forward to an updated version of the CSL file that incorporates these changes. Your attention to this matter would greatly benefit the research community relying on Zotero for accurate and up-to-date citation management.

Thank you for your time and consideration.

**Comment by fergusLu1998** [comment]
**An old one:**
3 N. Chu, D. Wang, S. Shieh and E. Rimm, Int. J. Obes. _Relat. Metab. Disord_., 2000, **24**, 1265–1271.
**A new one:**
2 O. A. Tokede, T. A. Onabanjo, A. Yansane, J. M. Gaziano
and L. Djoussé, Soya products and serum lipids: a metaanalysis of randomised controlled trials, _Br. J. Nutr._, 2015,
**114**, 831–843

**Comment by POBrien333** [comment]
Use this style instead: https://www.zotero.org/styles?q=id%3Aroyal-society-of-chemistry-with-titles

I'll update the dependent style.

**Comment by fergusLu1998** [comment]
Thank you for the advice! The csl you recommended shares a same style to current F&F bibliorgraphy.

Hope everything goes well~
