### ISSUE TITLE
Single volume appearing as "Vols." with apa.csl

### ISSUE THREAD

**Issue by isaactpetersen** [citation-style-language/styles#6886]
I am using `apa.csl` with a LaTeX document. The volume field is formatted incorrectly in the reference for many books. In particular, a single volume appears as "Vols." instead of "Vol."

For instance, here is the BibTeX citation:

```
@InBook{Ackerman2013,
  author    = {Ackerman, Phillip L.},
  editor    = {Geisinger, Kurt F. and Carlson, Janet F. and Hansen, Jo-Ida C. and Kuncel, Nathan R. and Reise, Steven P. and Rodriguez, Michael C.},
  pages     = {119--132},
  publisher = {American Psychological Association},
  title     = {Assessment of intellectual functioning in adults},
  year      = {2013},
  address   = {Washington, DC, US},
  series    = {APA handbooks in psychology.},
  volume    = {2: Testing and Assessment in Clinical and Counseling Psychology},
  booktitle = {APA handbook of testing and assessment in psychology}
}
```

Here is the resulting reference:

Ackerman, P. L. (2013). Assessment of intellectual functioning in adults. In K. F. Geisinger, J. F. Carlson, J.-I. C. Hansen, N. R. Kuncel, S. P. Reise, & M. C. Rodriguez (Eds.), *APA handbook of testing and assessment in psychology: Vols. 2: Testing and Assessment in Clinical and Counseling Psychology* (pp. 119–132). American Psychological Association.

However, "Vols. 2: ..." should be "Vol. 2: ..."

Any help would be greatly appreciated. Thanks!

**Comment by adam3smith** [comment]
CSL volume is explicitly for the volume number, not its title (there's volume-title for that). In this particular case, I would think most convenient data entry would be to include the volume information in the book title. If you don't want to go with that, you would have to figure out how whatever tool you are using (pandoc?) let's you specify the volume title separately -- the easiest would be to use CSL Json or CSL YAML

**Comment by isaactpetersen** [comment]
Thanks for letting me know. I'll look more into this and will close this for now. Thanks!
