### ISSUE TITLE
Chicago Style - Single volume of multi-volume work

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/styles#6924]
Got this email this morning:

> Dear All,
> 
> Apologies for emailing out of the blue. I found your names in the chicago-fullnote-bibliography.csl file, and thought I might email directly about a Chicago style citation question I've been encountering.
> 
> In quick summary, it appears to me that the latest Chicago CSL does not accommodate the somewhat uncommon, but not rare, case of citing a single volume from a multivolume work. In this situation, a person is supposed to include the title of the single volume (if the individual volumes have independent titles).
> 
> My research indicates that [volume-title is an available variable](https://github.com/citation-style-language/schema/issues/180) in CSL, which could be invoked from Zotero's "extra" field, were the Chicago .csl file to use it.. Alternatively, I see that the Chicago CSL does already use container-title, but not for multi-volume works. Could either of these options be incorporated?
> 
> While I work with XML, I don't have enough know-how of CSL or of Chicago (I'm an MLA guy myself) to suggest this addition directly myself, so I thought I'd see if it's on the radar of the maintainers.
> 
> Thanks much for reading.
> 
> Best,
> Dan

@adam3smith @POBrien333

**Comment by adam3smith** [comment]
Yeah, `volume-title` is the right variable to use here. It's relatively new, so hasn't made it into many styles yet, but generally on my radar (PRs also welcome).

**Comment by bwiernik** [comment]
I directed the sender to follow up on this issue as needed

**Comment by scholarsgrotto** [comment]
Brilliant. This email was from me, thank you very much for looking into it. This kind of citation can be found in the Chicago Manual of Style online at 14.118, "Citing a particular volume in a note" (https://www.chicagomanualofstyle.org/book/ed17/part3/ch14/psec118.html) and probably elsewhere.

There are several posts on the Zotero forum covering this as well, from [2020](https://forums.zotero.org/discussion/86422/citing-one-volume-of-a-multivolume-work-in-chicago), [2019](https://forums.zotero.org/discussion/76733/entering-multivolume-works-with-individual-titles-into-zotero-standalone), and even as far back as [2012](https://forums.zotero.org/discussion/26476/help-feature-request-individual-volumes-as-parts-of-multivolume-works).

**Comment by POBrien333** [comment]
Would you be able to provide a screenshot from the CMoS manual that shows this? (I don't have access)

**Comment by denismaier** [comment]
> These examples may be beyond spec at the moment, as I don't see anything like `volume-author` or `volume-editor` in the CSL variables list, and I'm not sure if you could do an end-around with existing variables such as `collection-editor` and `container-author`.

Yes, that's tricky. There were discussions about changing the currently flat data model to a hierarchical/structured data model, which would allow for such things. But don't expect anything to happen regarding this in the short term.
