### ISSUE TITLE
Style validation?

### ISSUE THREAD

**Issue by NicolasSouchon** [citation-style-language/styles#6980]
Dear all, is there any problem with validating this [style](https://github.com/citation-style-language/styles/pull/6871)? I submitted it two months ago and no news since regarding the validation.

**Comment by bwiernik** [comment]
Just been a bit of a slow period for the volunteers that maintain this repository sorry!

**Comment by NicolasSouchon** [comment]
Hello, thank you for your reply. No problem, I thought there was a problem with the style.
