### ISSUE TITLE
Help to find a format

### ISSUE THREAD

**Issue by edmundomarques** [citation-style-language/styles#6991]
Hey everyone,

I'm new here and I need some help finding or editing a template that fits the format below.

For in-text citations:
a) One author: author's last name and publication year;
b) Two authors: both authors' last names separated by "&" and the publication year;
c) Three or more authors: first author's last name followed by "et al." and the publication year;
d) Multiple works by the same author with different dates: cite the author's last name followed by the dates in parentheses;
e) Works by the same author with the same date are identified with lowercase letters (a, b, c, etc.);
f) Citing various works by different authors: mention all authors and publication years in chronological order;
g) Citation of authors with coincident last names and dates: initials are cited.

It would be like this: (AUTHOR 1, YEAR), or (AUTHOR 1 & AUTHOR 2, YEAR), or (AUTHOR 1 et al., YEAR). If there are 3 or more authors, "et al." appears in italics.

For the reference list, the format would be:

Authorship. Article title. Journal title. Year; Volume(issue), Page range.

Example: OLIVEIRA IM, SANTANA TR, CORREIA ACC, FONTES LS, GRIZA S, FARIA-E-SILVA AL. Color heterogeneity and individual color changes in dentin and enamel bleached in the presence of a metallic orthodontic bracket. Journal of Esthetic and Restorative Dentistry. 2021; 33(2): 262-268.

I've tried locating .csl files but I can't find any. I've also tried editing and saving them, but I keep getting errors.

Thanks a lot in advance for the help.

**Comment by adam3smith** [comment]
That's what https://editor.citationstyles.org/searchByExample/ is for -- we really can't help you find individual citation styles, sorry, though if this is for a specific journal, see https://github.com/citation-style-language/styles/blob/master/REQUESTING.md#requesting-csl-styles
