### ISSUE TITLE
Request for style ISO 690 FULL NOTE SPANISH

### ISSUE THREAD

**Issue by anamulopez** [citation-style-language/styles#7059]
Hello, could you please create an style for ISO-690 in spansh full note, please?
Thank you very much in advance

**Comment by POBrien333** [comment]
We can have a look. Is that documented anywhere?

**Comment by anamulopez** [comment]
Hello, thank you very much for your kind help. I found a pdf online that explains how iso 690 is, do you still need it?

**Comment by POBrien333** [comment]
yes. Hence my question

**Comment by anamulopez** [comment]
[384-2017-10-24-ISO 690 Univ. Carlos III.pdf](https://github.com/citation-style-language/styles/files/15457465/384-2017-10-24-ISO.690.Univ.Carlos.III.pdf)
I found this pdf.
In the part "Métodos de cita: relación entre la cita en el texto y la referencia bibliográfica" where iit explains how to make the citation in the text the style will be the numeric one, so it will be the "2. Sistema numérico"
