### ISSUE TITLE
Royal Society of Chemistry style missing spaces in citation for articles

### ISSUE THREAD

**Issue by jamesrswift** [citation-style-language/styles#7070]
https://github.com/citation-style-language/styles/blob/6dd5144f52bac3c1588d52505cafc14667b23579/royal-society-of-chemistry.csl#L162-L166

Groups are not appropriately separated. Suggest:

```
              <if variable="page">
                <group delimiter=", ">
                  <text macro="issued"/>
                  <text variable="volume" font-weight="bold"/>
                  <text variable="page"/>
                  </group>
                </if>
```

**Comment by POBrien333** [comment]
You're more than happy to contribute the fix yourself. There is no need for opening an issue if you already know the solution. :)

https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md
