### ISSUE TITLE
Zotero harvard issue

### ISSUE THREAD

**Issue by nidahkaiser** [citation-style-language/styles#7082]
Hello, I am new to this, 

how do I get my Harvard in-text citation style to be in chronological format and the (a) and (b) also rearranged? 

For example my citations are: 
(Arcand and Chakraborty, 2013; D. Basu, 2021; Berenschot, 2011b, 2011a) 

How do I get them arranged as: 
(Berenschot, 2011a, 2011b; Arcand and Chakraborty, 2013; D. Basu, 2021)

**Comment by adam3smith** [comment]
which Harvard style? There are hundreds

**Comment by nidahkaiser** [comment]
Elsevier - Harvard (with titles) 1-22-2019

I looked online and found one solution. So I changed the code between "citation" and "layout" but still there isn't any change.

My edited code is: 

<citation et-al-min="3" et-al-use-first="1" disambiguate-add-givenname="true" disambiguate-add-year-suffix="true" collapse="year" cite-group-delimiter=", ">
    <sort>
      <key macro="author"/>
      <key macro="issued" sort="descending"/>
      <key macro="author"/>
      <key variable="citation-number"/>
    </sort>
    <layout prefix="(" suffix=")" delimiter="; ">

**Comment by nidahkaiser** [comment]
<citation et-al-min="3" et-al-use-first="1" disambiguate-add-givenname="true" disambiguate-add-year-suffix="true" collapse="year" cite-group-delimiter=", ">
    <sort>
      <key macro="author"/>
      <key macro="issued" sort="descending"/>
      <key macro="author"/>
      <key variable="citation-number"/>
    </sort>
    <layout prefix="(" suffix=")" delimiter="; ">

**Comment by adam3smith** [comment]
you'll want:

```
  <sort>
      <key macro="issued" />
      <key macro="author"/>
      <key variable="citation-number"/>
    </sort>
```

If you just want any Harvard style, though, I'm sure there are others that do this out of the box already.

**Comment by nidahkaiser** [comment]
Ok thank you so much. Yes, can you please tell me which Harvard style would do this??

**Comment by nidahkaiser** [comment]
Also thank you it worked!!

**Comment by adam3smith** [comment]
I'd have to look through the other Harvard styles myself, so if you have this working for your purposes, I'll close this here
