### ISSUE TITLE
G3: Genes, Genomes, Genetics: Convert to dependent style 

### ISSUE THREAD

**Issue by dstillman** [citation-style-language/styles#7116]
We received this from someone at OUP.

> My name is […] and I work with the journal G3. We recently heard from an author that the G3 citationstyles entry appears to be inconsistent with the author guidelines for citation formatting, which has broken automatic citation formatting via tools such as Paperpile and Zotero which use that database.
>
> The relevant database entry can be viewed here: [https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fg3](https://urldefense.com/v3/__https:/editor.citationstyles.org/styleInfo/?styleId=http*3A*2F*2Fwww.zotero.org*2Fstyles*2Fg3__;JSUlJSU!!CzAuKJ42GuquVTTmVmPViYEvSg!IbtngWCsufQ271h9JDAZEOgqAWkWog6L7VNUzGS1MNyXZD7vsJazeeCBPzpcqQH1EdFVHz9_k03V$).
>
> G3 points authors to use the CSE style file (https://www.zotero.org/styles/council-of-science-editors-author-date). Is it possible to make the above file a ‘dependent’ file which, instead of containing its own formatting rules, simply calls the parent style (CSE in this case) and applies these rules?
>
> Thank you for your help.

**Comment by POBrien333** [comment]
Thank you. I've provided a PR to fix the issue.
