### ISSUE TITLE
Request style update: IEEE V 11.29.2023

### ISSUE THREAD

**Issue by thelsevier** [citation-style-language/styles#7119]
Hello,

the current [IEEE style implementation](https://github.com/citation-style-language/styles/blob/0349ae4627b2b1d316aba2b3b3c7bef415e3018d/ieee.csl#L4) is correct as per the 2021 guidelines, V 01.29.2021 as it says in its summary tag.

The latest version of the IEEE style is V 11.29.2023 ([guidelines here](http://journals.ieeeauthorcenter.ieee.org/wp-content/uploads/sites/7/IEEE_Reference_Guide.pdf)), but we cannot find any matching CSL file for it. Can you please help us find one or how can we formally request for one to be created?

Thank you!

**Comment by POBrien333** [comment]
Is there a specific reason or error with the style that needs fixing?
We maintain the style very closely as it's one of the most widely used styles.
It's more likely that the summary tag is just outdated, nothing more.

**Comment by adam3smith** [comment]
(I vaguely recall something here or on the Zotero forums w details; there are some 2023 changes)

**Comment by thelsevier** [comment]
Apparently there are some changes that our user noted in this document: 
[References_IEEE_Mendeley_cite (1).docx](https://github.com/user-attachments/files/16232028/References_IEEE_Mendeley_cite.1.docx)
Is this of any help for you? Thanks!

**Comment by POBrien333** [comment]
Thank you. I've added a few more changes reviewing the mentioned item types.

However, only half are real issues. The other half are due to user errors (data entry) or potentially Mendeley which I cannot help with.

**Comment by thelsevier** [comment]
@POBrien333 it would be awesome if you could specify which ones so that we can investigate if they are indeed issues on our end and inform our user accordingly. Thank you very much for your time!

**Comment by POBrien333** [comment]
We just pushed out an update for the style. You can test the various entries of your customer using that style. If you still notice an error, let us know.

**Comment by thelsevier** [comment]
That's great! We will have our users check for correctness and will open another issue if needed. As far as this issue is concerned you have made the updates so I consider it done. Thank you, and have a nice day!
