### ISSUE TITLE
Unexpected position of translators in latest version of apa.csl

### ISSUE THREAD

**Issue by zepinglee** [citation-style-language/styles#7144]
`apa.csl` updated `2024-07-19T10:52:31-04:00`

I just find bugs of `translator` in `apa.csl`. The following items are from the [Test Items Library](https://www.zotero.org/groups/2205533/test_items_library).

Current reuslts:

> Abdel Haleem, M. A. S. (Trans.). (2004). The Qur’an. Oxford University Press.
> Heidegger, M. (2008). On the essence of truth. In D. F. Krell (Ed.)J. Sallis (Trans.), Basic writings (pp. 111–138). Harper Perennial Modern Thought. (Original work published 1961)

Expected:

> The Qur’an (M. A. S. Abdel Haleem, Trans.). (2004). Oxford University Press.
> Heidegger, M. (2008). On the essence of truth (J. Sallis, Trans.). In D. F. Krell (Ed.), Basic writings (pp. 111–138). Harper Perennial Modern Thought. (Original work published 1961)

```json
[
	{
		"id": "ouran2004a",
		"type": "book",
		"license": "35b",
		"publisher": "Oxford University Press",
		"title": "The Qur'an",
		"translator": [
			{
				"family": "Abdel Haleem",
				"given": "M. A. S."
			}
		],
		"issued": {
			"date-parts": [
				[
					"2004"
				]
			]
		}
	},
	{
		"id": "heidegger2008essence",
		"type": "chapter",
		"container-title": "Basic writings",
		"license": "42",
		"note": "original-date: 1961",
		"page": "111-138",
		"publisher": "Harper Perennial Modern Thought",
		"title": "On the essence of truth",
		"author": [
			{
				"family": "Heidegger",
				"given": "M."
			}
		],
		"editor": [
			{
				"family": "Krell",
				"given": "D. F."
			}
		],
		"translator": [
			{
				"family": "Sallis",
				"given": "J."
			}
		],
		"issued": {
			"date-parts": [
				[
					"2008"
				]
			]
		}
	}
]
```

**Comment by POBrien333** [comment]
@bwiernik In case you haven't seen this :)

**Comment by bwiernik** [comment]
Thanks @zepinglee! I had apparently introduced this bug in the update for CSL 1.0.2.

**Comment by zepinglee** [comment]
It works correctly now.
