### ISSUE TITLE
How to handle journal with name in 3 languages?

### ISSUE THREAD

**Issue by POBrien333** [citation-style-language/styles#7184]
Hi,

A while ago I produced a style for a Swiss journal that localises in 3 languages, but has the name of the style in DE.
They asked if it was possible to not only have "Schweizerische Zeitschrift für Geschichte" in the repo, but also the respective names in FR and IT.
Would be able to do so and how should I go about this, @adam3smith @bwiernik ?

Thanks for your input. :)

**Comment by denismaier** [comment]
Would a dependant style be an option?

**Comment by bwiernik** [comment]
I would be fine with dependent styles with the other language titles -- would it make sense to set the default locales in each to de/fr/it respectively? Would people searching for the French title be expecting the style to support German? Does the journal also publish in English? 

One thing I'm not sure of is if our quality checks will balk at styles with the same ISSN existing. Could you make a PR and try?

**Comment by POBrien333** [comment]
Great. Thanks both for your input. I've created the PR with dependent styles. I think it's better to leave out the language setting.
And no, they don't publish in English.

**Comment by adam3smith** [comment]
The CI will complain, yes. Please pack all changes in a single PR. One of
the .rb files has a list of ISSN exempt from the duplicate check. You can
add to that yourself or I can look

**Comment by POBrien333** [comment]
Thank you all! :)
