### ISSUE TITLE
Update style of Journal-of-applied-pharmaceutical-research

### ISSUE THREAD

**Issue by joapreditor** [citation-style-language/styles#7228]
Earlier DOI number was not included in the reference style. I have edited the file and code is ready. Can anyone help me to update the same in Mendeley and zotero.
[Mendeley reference style updated september 2024.docx](https://github.com/user-attachments/files/17173788/Mendeley.reference.style.updated.september.2024.docx)

**Comment by POBrien333** [comment]
Thank you. I have improved your code and made a PR.
Note that you can always submit this yourself and do not need to open an issue. 
see: https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md
