### ISSUE TITLE
Unexpected styles file Gemfile.lock in pull request (RuntimeError)

### ISSUE THREAD

**Issue by Archi-thecaires-POLYMTL** [citation-style-language/styles#7235]
Hello,

I made an attempt to submit the file "polytechnique-montreal-ieee-francais.csl".

However, I ran into the following error :

Run bundle exec sheldon --token=$GITHUB_TOKEN --welcome
Top level ::CompositeIO is deprecated, require 'multipart/post' and use Multipart::Post::CompositeReadIO instead!
Top level ::Parts is deprecated, require 'multipart/post' and use Multipart::Post::Parts instead!
bundler: failed to load command: sheldon (/home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/bin/sheldon)
/home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/bundler/gems/Sheldon-0fef50309f74/bin/sheldon:125:in `block in initialize': Unexpected styles file Gemfile.lock in pull request (RuntimeError)
    from /home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/bundler/gems/Sheldon-0fef50309f74/bin/sheldon:124:in `each'
    from /home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/bundler/gems/Sheldon-0fef50309f74/bin/sheldon:124:in `initialize'
    from /home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/bundler/gems/Sheldon-0fef50309f74/bin/sheldon:454:in `new'
    from /home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/bundler/gems/Sheldon-0fef50309f74/bin/sheldon:454:in `<top (required)>'
    from /home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/bin/sheldon:23:in `load'
    from /home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/bin/sheldon:23:in `<top (required)>'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `load'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `kernel_load'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:23:in `run'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli.rb:478:in `exec'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `load'
    from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `<main>'
Loading patch from https://github.com/citation-style-language/styles/pull/7234.diff
Error: Process completed with exit code 1.

Now, I don't know what to do, because I never had this kind of error.

Do you have any idea.

Thank you.

Best regards,
Anita Mazur

**Comment by bwiernik** [comment]
We will handle this in your pull request
