### ISSUE TITLE
Validation of CSL with custom variable

### ISSUE THREAD

**Issue by shallcro** [citation-style-language/styles#7294]
Greetings; my organization is working to submit a CSL style. Our data repository includes instances where two institutions may collaborate on the publication of data and our local citation style reflects this by presenting both institutions as 'publishers.'

To avoid confusion around the [standard variable](https://docs.citationstyles.org/en/stable/specification.html#standard-variables) 'original-publisher', we thought that we would use a custom variable ('second-distributor') to designate this second data publisher/distributor.

In our local texts, this approach works when using the '[cheater syntax](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cheater-syntax-for-odd-fields)' with citeproc-js (as noted in [this forum post](https://discourse.citationstyles.org/t/handling-non-standard-name-variables-in-csl-for-japanese-citations/1815)).

The drawback is that--unsurprisingly--our CSL file fails validation at https://validator.citationstyles.org/. Given that the [CSL submission guidelines](https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#2-validate-your-style-against-the-csl-schema-and-correct-any-validation-errors) state that we should "correct any validation errors" prior to submission, would you have any guidance on whether we should (a) adapt standard variables to our local needs or (b) submit and explain the use of our custom variable via a 'documentation' link or (c) just keep our CSL style local? 

Thanks in advance for your help/expertise and apologies if any of the above is unclear!

**Comment by bwiernik** [comment]
I would strongly recommend using standard CSL variables. We cannot accept styles that do not validate into the repository, and I would strongly advise against adopting a data model for your organization that renders your data incompatible with other CSL styles (which don't use your custom variable). 

Could you describe your confusion about original-publisher? What's your intended use for "second-distributor"?

**Comment by bwiernik** [comment]
For joint publishers, the current CSL approach is to enter both into the same `publisher` field. There has been some discussion of converting publisher to a "name" variable (which would allow items to have multiple distinct publishers) in a future CSL variable, but I would not expect that to happen for several years.

**Comment by shallcro** [comment]
Thank you for taking the time to make this suggestion; we really appreciate it!
