### ISSUE TITLE
Title of article should be "sentence case" in AMA style

### ISSUE THREAD

**Issue by jnugent** [citation-style-language/styles#7337]
The titles used in the American Medical Association style are not converted to "sentence case", where only the first word is capitalized.  

See e.g. 

https://owl.purdue.edu/owl/research_and_citation/ama_style/index.html

**Comment by bwiernik** [comment]
You should store item titles in sentence case in your data. It's possible to automatically covert to title case but not vice versa (because of proper nouns), so CSL styles in the repository never force sentence case. 

See https://www.zotero.org/support/kb/sentence_casing
