### ISSUE TITLE
Load personal csl styles

### ISSUE THREAD

**Issue by Doc73** [citation-style-language/styles#7367]
Dear devs,
I'm testing latest jabref 6.0 version. So far everything seems to be working fine.

I would like to suggest an improvement, if possible: is it possible to add a method to load a **custom CSL style**?

Yes, I can upload my style to your repository.
I have been using this style for a few years and it seems to work well, **but** I created it for my personal use and never uploaded it to Zotero nor did I officially create it for the journal.
I have already read [CSL Style Repository Requirements](https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md).

Let me know what you think is best to do.

Merry Christmas and many many thanks for your excellent job,
Domenico

**Comment by Doc73** [comment]
Sorry. Wrong site

**Comment by bwiernik** [comment]
If it's a style written to meet a journal's guidelines, please feel free to submit to this repo. Most of the journal styles in the repo were not officially submitted or commissioned by the journal

**Comment by Doc73** [comment]
@bwiernik Ok! Tomorrow I'll do it

**Comment by bwiernik** [comment]
Closing this issue but feel free to to submit
