### ISSUE TITLE
Book section with book author missing cap after inclusive page range in Chicago

### ISSUE THREAD

**Issue by hgvhgv** [citation-style-language/styles#986]
For book sections with book authors and translators, editors, or both, the word after the period following the inclusive page range, in a bibliography entry in Chicago style, should be capped. It is not in two different programs that use CSL, so I figure it's a CSL issue not a translator issue (the programs are pandoc-citeproc and Zotero).

Example (copied from Zotero using the stock chicago-fullnote-bibliography.csl)

> Geroulanos, Stefanos, and Todd Meyers. “Introduction: Georges Canguilhem’s Critique of Medical Reason.” In _Writings on Medicine_, by Georges Canguilhem, 1–24. translated by Stefanos Geroulanos and Todd Meyers. New York: Fordham University Press, 2012.

The JSON CSL entry for this item is as follows.

```
{
    "id": 375,
    "type": "chapter",
    "title": "Introduction: Georges Canguilhem's critique of medical reason",
    "container-title": "Writings on medicine",
    "publisher": "Fordham University Press",
    "publisher-place": "New York",
    "page": "1–24",
    "source": "Library of Congress ISBN",
    "event-place": "New York",
    "ISBN": "9780823234318",
    "call-number": "R723 .C36513 2012",
    "note": "biblatexdata[origdate=2002;origpub=Éditions du Seuil;origtitle=Écrits sur la médecine;origplace=Paris;origlang=French]",
    "container-author": [
        {
            "family": "Canguilhem",
            "given": "Georges"
        }
    ],
    "translator": [
        {
            "family": "Geroulanos",
            "given": "Stefanos"
        },
        {
            "family": "Meyers",
            "given": "Todd"
        }
    ],
    "author": [
        {
            "family": "Geroulanos",
            "given": "Stefanos"
        },
        {
            "family": "Meyers",
            "given": "Todd"
        }
    ],
    "issued": {
        "date-parts": [
            [
                "2012"
            ]
        ]
    }
}
```

**Comment by adam3smith** [comment]
@rmzelle what do you think? Do we want to consider this (probably your suggestion on text-case for groups) for the schema?
